(()=>{
  const ACTIVE='ei_active_decision',TWIN='ei_decision_twin_v1',BASELINE='ei_decision_twin_baseline_v2',SNAPS='ei_decision_twin_snapshots_v1';
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)||0);
  const signed=n=>`${n>0?'+':n<0?'−':''}${money(Math.abs(n))}`;
  const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
  const read=(k,f={})=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch(_e){return f}};
  const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch(_e){return false}};
  const active=read(ACTIVE,{}),saved=read(TWIN,{});
  const TYPES={
    property:{label:'Property purchase',base:'purchase price / offer',recurring:'HOA, tax, insurance, utilities',shock:'repair / assessment / closing surprise',exit:'resale / recoverable value',tip:'Carry HOA, tax, insurance or other recurring ownership costs only when you have them.'},
    vehicle:{label:'Vehicle purchase',base:'purchase price / out-the-door amount',recurring:'fuel, insurance, maintenance, parking',shock:'repair / deductible / unexpected fee',exit:'resale / trade-in value',tip:'Use Carry for costs you expect to repeat; keep one-time repairs or surprises in Stress.'},
    renovation:{label:'Repair / renovation',base:'quote / project budget',recurring:'service plan / added operating cost',shock:'change order / overrun / failed scope',exit:'recoverable / resale value if relevant',tip:'Treat the quoted scope as Entry, recurring upkeep as Carry, and change orders or overruns as Stress.'},
    contractor:{label:'Contractor quote',base:'quoted contract amount',recurring:'maintenance / service agreement',shock:'exclusion / change order / permit surprise',exit:'recoverable value if any',tip:'Keep exclusions and likely change orders visible instead of hiding them inside the quoted price.'},
    equipment:{label:'Business equipment',base:'purchase / installed cost',recurring:'service, consumables, energy, labor',shock:'downtime / repair / installation overrun',exit:'resale / salvage value',tip:'Model the equipment as a commitment: acquisition, recurring operation, failure exposure and recoverable value.'},
    software:{label:'Software / service contract',base:'upfront / implementation cost',recurring:'subscription / seat / usage fees',shock:'migration / termination / overage fee',exit:'refund / avoided cost if recoverable',tip:'Put the contract price in Entry, subscription burden in Carry, and lock-in or termination costs in Stress.'},
    lease:{label:'Lease / rental',base:'deposit / upfront commitment',recurring:'rent / lease payment / service fees',shock:'move-out / termination / damage cost',exit:'deposit / refundable value',tip:'Use Entry for upfront cash, Carry for the repeated payment, and Exit for anything genuinely recoverable.'},
    education:{label:'Education / tuition',base:'tuition / upfront program cost',recurring:'fees, housing, travel, materials',shock:'extra term / relocation / financing surprise',exit:'refund / recoverable value if any',tip:'Keep tuition separate from recurring living and program costs so you can see what really drives the commitment.'},
    travel:{label:'Travel / major event',base:'booked / quoted upfront cost',recurring:'ongoing trip or event spend',shock:'change / cancellation / disruption cost',exit:'refund / credit / recoverable value',tip:'Model what is already committed, what keeps accumulating, what disruption could cost, and what remains refundable.'},
    other:{label:'Other commitment',base:'known price / commitment',recurring:'repeating cost you choose to include',shock:'specific downside / fee / failure',exit:'recoverable value if any',tip:'Keep each assumption in the lane it belongs to: Entry, Carry, Stress or Exit.'}
  };
  const categoryMap={property:'property',vehicle:'vehicle',home:'renovation',equipment:'equipment','business-project':'equipment',personal:'other'};
  let baseline=null,lastCoords=null,chartRAF=0,lastChanged='entry';

  function activeTitle(){return clean(active.title||active.text||[active?.vehicle?.identity?.year,active?.vehicle?.identity?.make,active?.vehicle?.identity?.model].filter(Boolean).join(' ')||'')}
  function inferredType(){return categoryMap[active.category]||saved.type||'property'}
  function typeMeta(){return TYPES[$('#tw-type')?.value]||TYPES.other}
  function detail(){return clean($('#tw-title')?.value)}
  function scenarioTitle(){const d=detail(),a=activeTitle();return d||a||typeMeta().label}
  function values(){return{type:$('#tw-type')?.value||'other',detail:detail(),title:scenarioTitle(),base:Number($('#tw-base')?.value)||0,delta:Number($('#tw-delta')?.value)||0,recurring:Number($('#tw-recurring')?.value)||0,frequency:$('#tw-frequency')?.value||'monthly',growth:Number($('#tw-growth')?.value)||0,years:Number($('#tw-years')?.value)||5,shock:Number($('#tw-shock')?.value)||0,recovery:Number($('#tw-recovery')?.value)||0,target:Number($('#tw-target')?.value)||0}}
  const annualRecurring=v=>v.recurring*(v.frequency==='monthly'?12:1);
  function carryFor(annual,growth,years){let carry=0;for(let y=0;y<years;y++)carry+=annual*Math.pow(1+growth/100,y);return carry}
  function model(v){const annual=annualRecurring(v),entry=Math.max(0,v.base+v.delta),carry=carryFor(annual,v.growth,v.years),points=[{label:'Entry',t:0,value:entry,kind:'entry'}];let running=entry;for(let y=1;y<=v.years;y++){running+=annual*Math.pow(1+v.growth/100,y-1);points.push({label:`Yr ${y}`,t:y,value:running,kind:'carry'})}running+=v.shock;points.push({label:'Stress',t:v.years+.5,value:running,kind:'shock'});running=Math.max(0,running-v.recovery);points.push({label:'Exit',t:v.years+1,value:running,kind:'exit'});return{annual,entry,carry,total:running,points}}
  function cloneScenario(v){return{type:v.type||'other',detail:v.detail||'',title:v.title||'',base:v.base||0,delta:v.delta||0,recurring:v.recurring||0,frequency:v.frequency||'monthly',growth:v.growth||0,years:v.years||5,shock:v.shock||0,recovery:v.recovery||0,target:v.target||0}}
  function sameDecision(a,b){return (a?.type||'other')===(b?.type||'other')&&clean(a?.detail||a?.title||'')===clean(b?.detail||b?.title||'')}
  function ensureDeltaRange(base,value=0){const span=Math.max(50000,Math.min(250000,Math.round((base||200000)*.25/100)*100)),input=$('#tw-delta');input.min=String(-span);input.max=String(span);if(Math.abs(value)>span){const cap=Math.ceil(Math.abs(value)/1000)*1000;input.min=String(-cap);input.max=String(cap)}}
  function setControls(v){$('#tw-type').value=TYPES[v.type]?v.type:'other';$('#tw-title').value=v.detail||'';$('#tw-base').value=v.base||'';ensureDeltaRange(v.base,v.delta);$('#tw-delta').value=v.delta||0;$('#tw-recurring').value=v.recurring||'';$('#tw-frequency').value=v.frequency||'monthly';$('#tw-growth').value=v.growth||0;$('#tw-years').value=v.years||5;$('#tw-shock').value=v.shock||'';$('#tw-recovery').value=v.recovery||'';$('#tw-target').value=v.target||'';applyTypeContext(false)}

  function applyTypeContext(animate=true){const m=typeMeta(),label=$('#tw-scenario-label');label.textContent=scenarioTitle();$('#tw-context-tip').textContent=m.tip;$('#tw-base-hint').textContent=m.base;$('#tw-recurring-hint').textContent=m.recurring;$('#tw-shock-hint').textContent=m.shock;$('#tw-exit-hint').textContent=m.exit;$('#tw-stage-title').textContent=scenarioTitle();if(animate&&matchMedia('(prefers-reduced-motion: no-preference)').matches){label.classList.remove('type-change');void label.offsetWidth;label.classList.add('type-change')}}

  function geometry(v,m,bm){const W=900,H=320,p={l:52,r:34,t:34,b:50},maxT=Math.max(v.years,baseline?.years||0)+1,maxVal=Math.max(1,...m.points.map(x=>x.value),...bm.points.map(x=>x.value))*1.08,x=t=>p.l+(W-p.l-p.r)*(t/maxT),y=n=>H-p.b-(H-p.t-p.b)*(n/maxVal),toCoords=pts=>pts.map(q=>({x:x(q.t),y:y(q.value),label:q.label,value:q.value,kind:q.kind}));return{W,H,p,current:toCoords(m.points),ghost:toCoords(bm.points)}}
  const pathFor=pts=>pts.map((q,i)=>`${i?'L':'M'}${q.x.toFixed(1)} ${q.y.toFixed(1)}`).join(' ');
  function paintCurrent(coords,H,p,labels=true){const line=pathFor(coords),fill=`${line} L${coords[coords.length-1].x.toFixed(1)} ${(H-p.b).toFixed(1)} L${coords[0].x.toFixed(1)} ${(H-p.b).toFixed(1)} Z`;$('#tw-trace').setAttribute('d',line);$('#tw-fill').setAttribute('d',fill);if(labels){$('#tw-points').innerHTML=coords.map((q,i)=>`<circle class="point${i===coords.length-1?' end':''}" cx="${q.x.toFixed(1)}" cy="${q.y.toFixed(1)}" r="${i===coords.length-1?5:3.2}"><title>${q.label}: ${money(q.value)}</title></circle>`).join('');$('#tw-labels').innerHTML=coords.map(q=>q.label==='Entry'||q.label==='Exit'||q.label==='Stress'||/^Yr (1|5|10|15)$/.test(q.label)?`<text class="axis-label" x="${q.x.toFixed(1)}" y="${H-17}" text-anchor="middle">${q.label}</text>`:'').join('')}}
  function chart(v,m,bm){const g=geometry(v,m,bm);$('#tw-ghost').setAttribute('d',pathFor(g.ghost));cancelAnimationFrame(chartRAF);const final=g.current;if(lastCoords&&lastCoords.length===final.length&&matchMedia('(prefers-reduced-motion: no-preference)').matches){const from=lastCoords.map((q,i)=>({x:q.x,y:q.y,label:final[i].label,value:final[i].value,kind:final[i].kind})),start=performance.now(),dur=300;const frame=now=>{const t=Math.min(1,(now-start)/dur),e=1-Math.pow(1-t,3),mid=final.map((q,i)=>({...q,x:from[i].x+(q.x-from[i].x)*e,y:from[i].y+(q.y-from[i].y)*e}));paintCurrent(mid,g.H,g.p,false);if(t<1)chartRAF=requestAnimationFrame(frame);else{paintCurrent(final,g.H,g.p,true);const end=$('.point.end');end?.classList.add('pulse');setTimeout(()=>end?.classList.remove('pulse'),350)}};chartRAF=requestAnimationFrame(frame)}else paintCurrent(final,g.H,g.p,true);lastCoords=final.map(q=>({...q}))}

  function driverData(v,m,b,bm){return[['Entry',m.entry-bm.entry],['Carry',m.carry-bm.carry],['Stress',v.shock-b.shock],['Exit',-(v.recovery-b.recovery)]]}
  function renderDrivers(v,m,b,bm){const data=driverData(v,m,b,bm),max=Math.max(1,...data.map(x=>Math.abs(x[1]))),wrap=$('#tw-driver-bars');wrap.innerHTML=data.map(([name,val])=>{const width=Math.min(50,Math.abs(val)/max*50),side=val>=0?'positive':'negative';return `<div class="driver-row ${side}"><span>${name}</span><div class="driver-track"><i style="width:${width}%"></i></div><strong>${signed(val)}</strong></div>`}).join('');const dominant=[...data].sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]))[0];if(!dominant||Math.abs(dominant[1])<1){$('#tw-driver').textContent='At baseline';$('#tw-driver-note').textContent='Move any assumption to see what drives the difference.'}else{$('#tw-driver').textContent=dominant[0];$('#tw-driver-note').textContent=`${signed(dominant[1])} of the change comes from ${dominant[0].toLowerCase()}.`}}
  function renderSensitivity(v,m){const annual=m.annual,plusMonth=carryFor(annual+1200,v.growth,v.years)-m.carry,plusGrowth=annual?carryFor(annual,v.growth+1,v.years)-m.carry:0,nextYear=annual*Math.pow(1+v.growth/100,v.years);$('#sens-monthly').textContent=money(plusMonth);$('#sens-growth').textContent=annual?money(plusGrowth):'$0';$('#sens-year').textContent=annual?money(nextYear):'$0'}
  function renderTarget(v,m){const target=v.target,out=$('#tw-target-entry'),note=$('#tw-target-note');if(!target){out.textContent='—';note.textContent='Set a ceiling to solve backwards.';return}const nonEntry=m.carry+v.shock-v.recovery,maxEntry=target-nonEntry;if(maxEntry<0){out.textContent='$0';note.textContent=`Carry + Stress − Exit already equals ${money(nonEntry)}, above your ceiling.`;return}out.textContent=money(maxEntry);const gap=maxEntry-v.base;note.textContent=gap>=0?`The known amount fits with ${money(gap)} of entry headroom.`:`Entry needs to be ${money(Math.abs(gap))} below the known amount.`}
  function pulse(kind){const starts={entry:8,carry:28,shock:48,exit:68},el=$('#tw-impact-pulse'),start=starts[kind]??8;el.style.left=`${start}%`;el.style.width=`${92-start}%`;el.classList.remove('run');void el.offsetWidth;el.classList.add('run')}
  function switchStep(step,focus=false){$$('[data-step]').forEach(b=>b.classList.toggle('active',b.dataset.step===step));$$('[data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===step));if(focus){const target={entry:'#tw-delta',carry:'#tw-recurring',shock:'#tw-shock',exit:'#tw-recovery'}[step];setTimeout(()=>$(target)?.focus(),40)}}
  function summary(v,m,bm){if(!v.base)return`Choose a ${typeMeta().label.toLowerCase()} and enter the known amount to start.`;const delta=m.total-bm.total,rec=m.annual?`${money(m.annual)} a year in recurring burden over ${v.years} year${v.years===1?'':'s'}`:'no recurring burden entered',stress=v.shock?`${money(v.shock)} of explicit downside`:'no downside event entered',exit=v.recovery?`${money(v.recovery)} recovered at exit`:'no exit recovery entered';return `${v.title}: at ${money(m.entry)} entry, ${rec}, ${stress}, and ${exit}, this scenario lands at ${money(m.total)} net cash commitment — ${delta===0?'the pinned baseline':`${signed(delta)} versus the pinned baseline`}.`}
  function animateValue(el){if(!el)return;el.classList.remove('change');void el.offsetWidth;el.classList.add('change')}
  function update(changed='entry',animate=true){lastChanged=changed;applyTypeContext(false);const v=values(),m=model(v),b=baseline||cloneScenario(v),bm=model(b),delta=m.total-bm.total;$('#tw-delta-out').textContent=signed(v.delta);$('#tw-growth-out').textContent=`${v.growth.toFixed(1).replace('.0','')}%`;$('#tw-years-out').textContent=`${v.years} yr${v.years===1?'':'s'}`;$('#tw-stage-title').textContent=v.title;$('#tw-total').textContent=v.base?money(m.total):'Enter an amount';$('#tw-total-note').textContent=v.base?`${v.years} year horizon · explicit inputs only`:'Nothing modeled yet.';$('#tw-gap').textContent=v.base?signed(delta):'—';$('#tw-gap-note').textContent=delta===0?'Current scenario matches the pinned baseline.':delta>0?'Current scenario costs more than baseline.':'Current scenario costs less than baseline.';$('#tw-state-label').textContent=delta===0?'AT BASELINE':delta>0?'ABOVE BASELINE':'BELOW BASELINE';$('#tw-state-delta').textContent=v.base?`${signed(delta)} change`:'No scenario';$('#eq-entry').textContent=money(m.entry);$('#eq-carry').textContent=money(m.carry);$('#eq-shock').textContent=money(v.shock);$('#eq-exit').textContent=money(v.recovery);$('#eq-total').textContent=money(m.total);$('#tw-summary').textContent=summary(v,m,bm);renderDrivers(v,m,b,bm);renderSensitivity(v,m);renderTarget(v,m);chart(v,m,bm);write(TWIN,{...cloneScenario(v),updatedAt:new Date().toISOString()});if(animate){pulse(changed);['#tw-total','#tw-gap','#tw-driver','#tw-state-delta'].forEach(s=>animateValue($(s)))}}

  function pinBaseline(){baseline=cloneScenario(values());write(BASELINE,baseline);lastCoords=null;update(lastChanged,false);const b=$('#tw-pin'),old=b.textContent;b.textContent='Baseline pinned ✓';setTimeout(()=>b.textContent=old,1400)}
  function resetBaseline(){if(!baseline)return;setControls({...baseline,target:values().target});lastCoords=null;update('entry')}
  function snapshots(){const s=read(SNAPS,[]);return Array.isArray(s)?s:[]}
  function renderSnapshots(newId=null){const list=snapshots(),grid=$('#tw-snapshot-grid');$('#tw-snapshot-count').textContent=`${list.length} saved`;if(!list.length){grid.innerHTML='<div class="snapshot-empty">Save a scenario to compare prices, horizons, stress cases or exit assumptions without losing your current work.</div>';return}grid.innerHTML=list.map((s,i)=>{const m=model(s),meta=TYPES[s.type]||TYPES.other;return `<article class="snapshot-card${s.id===newId?' new':''}" data-snap="${s.id}"><span>${meta.label} · Snapshot ${String.fromCharCode(65+i)}</span><strong>${money(m.total)}</strong><small>${money(m.entry)} entry · ${money(m.carry)} carry · ${money(s.shock)} stress · ${money(s.recovery)} exit</small><div class="snapshot-actions"><button type="button" data-load="${s.id}">Load</button><button type="button" data-delete="${s.id}">Delete</button></div></article>`}).join('');$$('[data-load]',grid).forEach(b=>b.addEventListener('click',()=>{const s=snapshots().find(x=>String(x.id)===b.dataset.load);if(s){setControls(s);baseline=cloneScenario(s);write(BASELINE,baseline);lastCoords=null;update('entry');$('#tw-snapshots').open=false}}));$$('[data-delete]',grid).forEach(b=>b.addEventListener('click',()=>{write(SNAPS,snapshots().filter(x=>String(x.id)!==b.dataset.delete));renderSnapshots()}))}
  function saveSnapshot(){const v=cloneScenario(values()),id=Date.now(),list=[{...v,id,savedAt:new Date().toISOString()},...snapshots()].slice(0,4);write(SNAPS,list);renderSnapshots(id);$('#tw-snapshots').open=true;const b=$('#tw-save'),old=b.textContent;b.textContent='Saved ✓';setTimeout(()=>b.textContent=old,1200)}
  async function copyBrief(){const v=values(),m=model(v),bm=model(baseline||v),text=`ExpenseIntel Decision Twin — ${v.title}\nDecision type: ${(TYPES[v.type]||TYPES.other).label}\nKnown amount: ${money(v.base)}\nScenario entry: ${money(m.entry)}\nRecurring burden: ${money(m.annual)}/yr for ${v.years} years (${money(m.carry)} total carry)\nAnnual recurring growth: ${v.growth}%\nExplicit downside: ${money(v.shock)}\nRecovery / exit: ${money(v.recovery)}\nNet cash commitment: ${money(m.total)}\nChange vs pinned baseline: ${signed(m.total-bm.total)}\n\n${summary(v,m,bm)}\n\nScenario math only — assumptions are user-controlled.`;try{await navigator.clipboard.writeText(text);const b=$('#tw-copy'),old=b.textContent;b.textContent='Copied ✓';setTimeout(()=>b.textContent=old,1200)}catch(_e){}}

  function bind(){
    $$('[data-step]').forEach(b=>b.addEventListener('click',()=>switchStep(b.dataset.step)));
    $$('[data-flow]').forEach(b=>b.addEventListener('click',()=>switchStep(b.dataset.flow,true)));
    [['tw-base','entry'],['tw-delta','entry'],['tw-recurring','carry'],['tw-frequency','carry'],['tw-growth','carry'],['tw-years','carry'],['tw-shock','shock'],['tw-recovery','exit']].forEach(([id,type])=>$('#'+id)?.addEventListener('input',()=>{if(id==='tw-base')ensureDeltaRange(Number($('#tw-base').value)||0,Number($('#tw-delta').value)||0);update(type)}));
    $('#tw-target')?.addEventListener('input',()=>update(lastChanged,false));
    $('#tw-type')?.addEventListener('change',()=>{applyTypeContext(true);update(lastChanged)});
    $('#tw-title')?.addEventListener('input',()=>{applyTypeContext(true);update(lastChanged,false)});
    $$('[data-delta-pct]').forEach(b=>b.addEventListener('click',()=>{const base=Number($('#tw-base').value)||0,pct=Number(b.dataset.deltaPct)||0,delta=Math.round(base*pct/100/100)*100;ensureDeltaRange(base,delta);$('#tw-delta').value=delta;update('entry')}));
    $$('[data-shock-add]').forEach(b=>b.addEventListener('click',()=>{const n=Number(b.dataset.shockAdd)||0;$('#tw-shock').value=n?Math.max(0,(Number($('#tw-shock').value)||0)+n):'';update('shock')}));
    $('#tw-pin')?.addEventListener('click',pinBaseline);$('#tw-reset')?.addEventListener('click',resetBaseline);$('#tw-save')?.addEventListener('click',saveSnapshot);$('#tw-copy')?.addEventListener('click',copyBrief)
  }

  function prefill(){const type=inferredType(),aTitle=activeTitle(),base=Number(active.price)||Number(saved.base)||0,current={type,detail:aTitle||saved.detail||'',title:aTitle||saved.title||(TYPES[type]||TYPES.other).label,base,delta:Number(saved.delta)||0,recurring:Number(saved.recurring)||0,frequency:saved.frequency||'monthly',growth:Number(saved.growth)||0,years:Number(saved.years)||5,shock:Number(saved.shock)||0,recovery:Number(saved.recovery)||0,target:Number(saved.target)||0};setControls(current);const storedBase=read(BASELINE,null);baseline=storedBase&&sameDecision(storedBase,current)?{...current,...storedBase,type:storedBase.type||current.type,detail:storedBase.detail||current.detail}:cloneScenario(current);if(!storedBase||!sameDecision(storedBase,current))write(BASELINE,baseline);$('#tw-active-title').textContent=aTitle||'No active Check yet';$('#tw-active-meta').textContent=[active.price?money(active.price):'',active.location||'',active.category?String(active.category).replace(/-/g,' '):''].filter(Boolean).join(' · ')||'Choose a decision type, then enter only the amounts you actually know.';$('#tw-link-check').textContent=aTitle?'Open Check →':'Run a Check →';applyTypeContext(false)}
  function init(){prefill();bind();renderSnapshots();update('entry',false)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
