(()=>{
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const ACTIVE='ei_active_decision';
  const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
  const setText=(el,text)=>{if(el&&el.textContent!==text)el.textContent=text};
  function active(){try{return JSON.parse(localStorage.getItem(ACTIVE)||'null')}catch(_e){return null}}
  function friendlyStatus(raw){raw=clean(raw).toUpperCase();if(raw==='STRONG')return['Good context','Most major layers are connected, but still verify the deal-specific facts below.'];if(raw==='PARTIAL')return['Useful, some gaps','There is enough evidence to help, but at least one important fact could still change the answer.'];return['Early check','Use this as a starting point. ExpenseIntel is still missing decision-critical evidence.']}
  function questionFor(text){const t=clean(text);if(!t)return null;if(/transaction-price benchmark|comparable price|market benchmark/i.test(t))return['What would make the price answer stronger?','Paste another quote, comparable listing, or exact listing URL. That is more useful than adding more general market statistics.','Add a comparable'];if(/exact vehicle configuration|trim/i.test(t))return['What is the exact trim or VIN?','That lets ExpenseIntel match the right fuel, safety and comparable-market data instead of averaging across versions.','Add trim or VIN'];if(/insurance/i.test(t))return['Do you have an insurance quote?','A real premium can materially change the ownership cost. ExpenseIntel should use your quote rather than guess one.','Add insurance quote'];if(/property-specific|appraisal|comps|comparable sales/i.test(t))return['Do you have the exact address or a comparable sale?','Property value is specific. An address or real comparable sale is more useful than a national average.','Add property detail'];if(/contractor quotes|comparable|scope/i.test(t))return['Do you have the full quote or another quote?','Scope differences are often the reason two contractor prices look far apart. Paste the real scope rather than estimating it.','Add quote detail'];return[`Can you verify this: ${t.replace(/[.]+$/,'')}?`,'If you know it, add it. If you do not, leave it unknown—ExpenseIntel should not invent the answer.','Add this detail']}
  function focusIntake(prompt){const describe=$('[data-mode="describe"]');describe?.click();const box=$('#check-text');if(!box)return;const a=active(),base=clean(box.value||a?.text||a?.title||'');box.value=base+(base?'\n\n':'')+`Additional detail: `;box.placeholder=prompt;box.focus();box.setSelectionRange(box.value.length,box.value.length);$('#check-form')?.scrollIntoView({behavior:'smooth',block:'center'})}
  function collapseEvidence(){const ev=$('[data-result-evidence]');if(!ev||ev.dataset.eiHelpful==='1')return;ev.dataset.eiHelpful='1';const cards=$$('article',ev);if(cards.length<=3)return;cards.slice(3).forEach(x=>x.classList.add('ei-secondary-evidence'));const b=document.createElement('button');b.type='button';b.className='ei-evidence-toggle';b.textContent=`Show ${cards.length-3} more evidence signal${cards.length-3===1?'':'s'} ↓`;b.onclick=()=>{const open=ev.classList.toggle('ei-expanded');b.textContent=open?'Show fewer evidence signals ↑':`Show ${cards.length-3} more evidence signal${cards.length-3===1?'':'s'} ↓`};ev.appendChild(b)}
  function simplifyLabels(){const score=$('.check-score span');setText(score,'HOW COMPLETE IS THIS?');const raw=$('[data-result-score]');if(raw&&raw.dataset.friendlyStatus!=='1'){const [label]=friendlyStatus(raw.textContent);raw.dataset.original=raw.textContent;raw.dataset.friendlyStatus='1';raw.textContent=label}setText($('.check-card.primary .check-card-head span'),'What we know');setText($('.check-result-grid .check-card:nth-child(2) .check-card-head span'),'What we still need to know');setText($('[data-result-next] span'),'What to do next');setText($('.decision-meaning .check-card-head span'),'Why this matters to you')}
  function buildSummary(){const shell=$('[data-check-output] .shell');if(!shell||shell.querySelector('.ei-plain-summary'))return;const top=$('.check-output-top',shell),cmd=$('.decision-command',shell),call=clean($('[data-decision-call]',shell)?.textContent),reason=clean($('[data-decision-reason]',shell)?.textContent),next=clean($('[data-result-next] strong',shell)?.textContent),nextCopy=clean($('[data-result-next] p',shell)?.textContent),rawStatus=clean($('[data-result-score]',shell)?.dataset.original||$('[data-result-score]',shell)?.textContent),label=clean($('[data-result-label]',shell)?.textContent),[friendly,explain]=friendlyStatus(rawStatus);if(!top||!cmd||!call)return;const s=document.createElement('section');s.className='ei-plain-summary';s.innerHTML=`<div class="ei-plain-call"><span>The short answer</span><strong></strong><p></p></div><div><span>Do this next</span><strong></strong><p></p></div><div class="ei-complete"><span>How complete?</span><strong></strong><p></p><small></small></div>`;s.children[0].querySelector('strong').textContent=call;s.children[0].querySelector('p').textContent=reason;s.children[1].querySelector('strong').textContent=next||'Review the missing fact';s.children[1].querySelector('p').textContent=nextCopy||'Use the missing-evidence list below before committing money.';s.children[2].querySelector('strong').textContent=friendly;s.children[2].querySelector('p').textContent=explain;s.children[2].querySelector('small').textContent=label;top.insertAdjacentElement('afterend',s);const details=document.createElement('details');details.className='ei-decision-details';const summary=document.createElement('summary');summary.textContent='See the detailed decision logic';details.appendChild(summary);cmd.insertAdjacentElement('beforebegin',details);details.appendChild(cmd)}
  function addOneQuestion(){const card=$('.check-result-grid .check-card:nth-child(2)');if(!card||card.querySelector('.ei-one-question'))return;const unknown=$('.check-unknown',card);const q=questionFor(unknown?.textContent);if(!q)return;const box=document.createElement('div');box.className='ei-one-question';box.innerHTML='<span>One thing that could improve this answer</span><strong></strong><p></p><button type="button"></button>';box.querySelector('strong').textContent=q[0];box.querySelector('p').textContent=q[1];box.querySelector('button').textContent=q[2];box.querySelector('button').onclick=()=>focusIntake(q[0]);const list=$('[data-result-unknowns]',card);if(list)list.insertAdjacentElement('beforebegin',box);else card.appendChild(box)}
  function enhance(){const out=$('[data-check-output]');if(!out||out.hidden||!$('[data-decision-call]',out))return;simplifyLabels();buildSummary();addOneQuestion();collapseEvidence()}
  function watch(){const out=$('[data-check-output]');if(!out)return;let queued=false;const obs=new MutationObserver(()=>{if(queued)return;queued=true;setTimeout(()=>{queued=false;enhance()},0)});obs.observe(out,{subtree:true,childList:true,characterData:true});enhance()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch,{once:true});else watch();
})();