(()=>{
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const ACTIVE='ei_active_decision';
  const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
  const setText=(el,text)=>{if(el&&el.textContent!==text)el.textContent=text};
  function active(){try{return JSON.parse(localStorage.getItem(ACTIVE)||'null')}catch(_e){return null}}
  function friendlyStatus(raw){raw=clean(raw).toUpperCase();if(raw==='STRONG')return['Good context','Most major layers are connected, but deal-specific facts can still change the answer.'];if(raw==='PARTIAL')return['Useful, some gaps','There is enough evidence to help, but at least one important fact could still change the answer.'];return['Early check','Use this as a starting point. ExpenseIntel is still missing decision-critical evidence.']}
  function questionFor(text){const t=clean(text);if(!t)return null;if(/transaction-price benchmark|comparable price|market benchmark/i.test(t))return['Add one real comparison','Paste another quote, comparable listing, or exact listing URL. A real comparison is more useful than another general statistic.','Paste a quote, price or link'];if(/exact vehicle configuration|trim/i.test(t))return['What is the exact trim or VIN?','This lets ExpenseIntel match the right fuel, safety and market data instead of averaging across several versions.','Type the trim or VIN'];if(/insurance/i.test(t))return['Do you have an insurance quote?','A real premium can materially change ownership cost. ExpenseIntel should use your number rather than invent one.','Type the annual or monthly quote'];if(/property-specific|appraisal|comps|comparable sales/i.test(t))return['Add the exact address or a comparable sale','Property value is specific. An address or real comparable sale is more useful than a national average.','Paste the address, sale or listing'];if(/contractor quotes|comparable|scope/i.test(t))return['Add the full scope or another quote','Scope differences are often why contractor prices look far apart. Use the real quote rather than estimating what is included.','Paste the missing scope or other quote'];return[`Can you verify this? ${t.replace(/[.]+$/,'')}`,'If you know it, add it. If you do not, leave it unknown—ExpenseIntel should not invent the answer.','Type what you know']}
  function currentMetrics(){return $$('.decision-command-grid>div').map(div=>({label:clean($('span',div)?.textContent),value:clean($('strong',div)?.textContent)})).filter(x=>x.label&&x.value).slice(0,4)}
  function collapseEvidence(){const ev=$('[data-result-evidence]');if(!ev||ev.dataset.eiHelpful==='1')return;ev.dataset.eiHelpful='1';const cards=$$('article',ev);if(cards.length<=3)return;cards.slice(3).forEach(x=>x.classList.add('ei-secondary-evidence'));const b=document.createElement('button');b.type='button';b.className='ei-evidence-toggle';b.textContent=`Show ${cards.length-3} more evidence signal${cards.length-3===1?'':'s'} ↓`;b.onclick=()=>{const open=ev.classList.toggle('ei-expanded');b.textContent=open?'Show fewer evidence signals ↑':`Show ${cards.length-3} more evidence signal${cards.length-3===1?'':'s'} ↓`};ev.appendChild(b)}
  function simplifyLabels(){const score=$('.check-score span');setText(score,'HOW COMPLETE IS THIS?');const raw=$('[data-result-score]');if(raw&&raw.dataset.friendlyStatus!=='1'){const [label]=friendlyStatus(raw.textContent);raw.dataset.original=raw.textContent;raw.dataset.friendlyStatus='1';raw.textContent=label}setText($('.check-card.primary .check-card-head span'),'What we know');setText($('.check-result-grid .check-card:nth-child(2) .check-card-head span'),'What we still need to know');setText($('[data-result-next] span'),'What to do next');setText($('.decision-meaning .check-card-head span'),'Why this matters to you')}
  function buildSummary(){const shell=$('[data-check-output] .shell');if(!shell||shell.querySelector('.ei-everyday-summary'))return;const top=$('.check-output-top',shell),call=clean($('[data-decision-call]',shell)?.textContent),reason=clean($('[data-decision-reason]',shell)?.textContent),next=clean($('[data-result-next] strong',shell)?.textContent),nextCopy=clean($('[data-result-next] p',shell)?.textContent),rawStatus=clean($('[data-result-score]',shell)?.dataset.original||$('[data-result-score]',shell)?.textContent),label=clean($('[data-result-label]',shell)?.textContent),[friendly,explain]=friendlyStatus(rawStatus),metrics=currentMetrics();if(!top||!call)return;const s=document.createElement('section');s.className='ei-everyday-summary';s.innerHTML='<div class="ei-summary-head"><div><span>The short answer</span><strong></strong><p></p></div><aside><span>How complete?</span><b></b><small></small></aside></div><div class="ei-summary-lower"><div class="ei-key-numbers"><span>Key numbers</span><div></div></div><div class="ei-next-step"><span>Do this next</span><strong></strong><p></p></div></div>';
    $('.ei-summary-head>div>strong',s).textContent=call;$('.ei-summary-head>div>p',s).textContent=reason;$('.ei-summary-head aside b',s).textContent=friendly;$('.ei-summary-head aside small',s).textContent=`${explain} ${label}`.trim();const nums=$('.ei-key-numbers>div',s);nums.innerHTML=metrics.length?metrics.map(x=>`<div><span>${x.label}</span><strong>${x.value}</strong></div>`).join(''):'<p>No decision-specific number is verified yet. ExpenseIntel will keep it unknown rather than estimate it silently.</p>';$('.ei-next-step strong',s).textContent=next||'Verify the missing fact';$('.ei-next-step p',s).textContent=nextCopy||'Use the most important missing fact before committing money.';top.insertAdjacentElement('afterend',s)}
  function appendAnswer(question,answer){const describe=$('[data-mode="describe"]');describe?.click();const box=$('#check-text');const form=$('[data-check-form]');if(!box||!form)return;const a=active(),base=clean(box.value||a?.text||a?.title||'');box.value=`${base}${base?'\n\n':''}Additional detail — ${question}: ${answer}`;box.dataset.userEdited='1';form.requestSubmit?.()}
  function addInlineQuestion(){const shell=$('[data-check-output] .shell');if(!shell||shell.querySelector('.ei-inline-question'))return;const unknown=$('.check-unknown',shell),q=questionFor(unknown?.textContent);if(!q)return;const summary=$('.ei-everyday-summary',shell);if(!summary)return;const box=document.createElement('section');box.className='ei-inline-question';box.innerHTML='<div><span>One thing that would improve this answer</span><strong></strong><p></p></div><form><label class="sr-only" for="ei-followup-answer">Answer</label><input id="ei-followup-answer" type="text"><button type="submit">Update my check →</button><button type="button" class="ei-skip">I don\'t know</button></form>';box.querySelector('strong').textContent=q[0];box.querySelector('p').textContent=q[1];const input=box.querySelector('input');input.placeholder=q[2];box.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const answer=clean(input.value);if(!answer){input.focus();return}appendAnswer(q[0],answer)});box.querySelector('.ei-skip').onclick=()=>box.remove();summary.insertAdjacentElement('afterend',box)}
  function collapseAnalysis(){const shell=$('[data-check-output] .shell');if(!shell||shell.querySelector('.ei-analysis-details'))return;const targets=['.decision-command','.check-result-grid','.decision-meaning','[data-comps-section]','[data-vehicle-section]'].map(s=>$(s,shell)).filter(Boolean);if(!targets.length)return;const d=document.createElement('details');d.className='ei-analysis-details';const summary=document.createElement('summary');summary.innerHTML='<span>See evidence, risks & detailed analysis</span><small>Sources, unknowns, safety, market context and technical detail</small>';d.appendChild(summary);targets[0].insertAdjacentElement('beforebegin',d);targets.forEach(el=>d.appendChild(el))}
  function enhance(){const out=$('[data-check-output]');if(!out||out.hidden||!$('[data-decision-call]',out))return;simplifyLabels();buildSummary();addInlineQuestion();collapseEvidence();collapseAnalysis()}
  function watch(){const out=$('[data-check-output]');if(!out)return;let queued=false;const obs=new MutationObserver(()=>{if(queued)return;queued=true;setTimeout(()=>{queued=false;enhance()},0)});obs.observe(out,{subtree:true,childList:true,characterData:true});enhance()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch,{once:true});else watch();
})();