(()=>{
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const ACTIVE='ei_active_decision';
  const LEASE_BENCH={avgLease:'$619/mo',avgFinance:'$770/mo',leaseShare:'24.1%',term:'24–48 mo',miles:'10k–15k/yr',period:'Q1 2026'};
  const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
  const setText=(el,text)=>{if(el&&el.textContent!==text)el.textContent=text};
  const skipped=new Set();let unknownSignature='',summarySignature='';
  function active(){try{return JSON.parse(localStorage.getItem(ACTIVE)||'null')}catch(_e){return null}}
  function friendlyStatus(raw){raw=clean(raw).toUpperCase();if(raw==='STRONG')return['Good context','Most major layers are connected, but deal-specific facts can still change the answer.'];if(raw==='PARTIAL')return['Useful, some gaps','There is enough evidence to help, but at least one important fact could still change the answer.'];return['Early check','Use this as a starting point. ExpenseIntel is still missing decision-critical evidence.']}
  function questionFor(text){const t=clean(text);if(!t)return null;if(/lease contract: monthly payment|lease: monthly payment/i.test(t))return['What is the monthly lease payment?','ExpenseIntel already has the market baseline. Your payment lets it show how the actual lease compares and calculate the real cash commitment.','$ per month'];if(/lease contract: lease term|lease: lease term/i.test(t))return['How long is the lease?','The term converts the monthly quote into total scheduled lease cash and lets ExpenseIntel model the commitment.','Months'];if(/lease contract: due at signing|lease: due at signing/i.test(t))return['How much is due at signing?','Up-front cash can make a lease look cheaper per month than it really is.','$ due at signing'];if(/lease contract: mileage allowance|lease: mileage allowance/i.test(t))return['What is the mileage allowance?','Mileage limits are a major part of the economics and end-of-lease risk.','Miles per year'];if(/exact purchase|quote price|purchase\/quote price/i.test(t))return['What is the actual price or quote?','The exact amount is needed before ExpenseIntel can compare the economics of this decision.','$ amount'];if(/exact vehicle configuration|trim/i.test(t))return['What is the exact trim or VIN?','This lets ExpenseIntel match the right fuel, safety and market data instead of averaging across several versions.','Type the trim or VIN'];if(/property-specific|appraisal|comps|comparable sales/i.test(t))return['What is the exact address or best comparable sale?','Property value is highly specific. An address or a real comparable sale is more useful than a national average.','Paste the address, sale or listing'];if(/contractor quotes|scope/i.test(t))return['Can you paste the full scope or another quote?','Scope differences are often why contractor prices look far apart. ExpenseIntel should compare the actual work, not assume what is included.','Paste the scope or other quote'];if(/transaction-price benchmark|comparable price|market benchmark|transaction-level comparable/i.test(t))return['Do you have one real comparison?','Paste another quote, comparable listing, or exact listing URL. A real comparison is more useful than another general statistic.','Paste a quote, price or link'];if(/insurance/i.test(t))return['Do you have an insurance quote?','A real premium can materially change ownership cost. ExpenseIntel should use your number rather than invent one.','Type the annual or monthly quote'];if(/tax|hoa/i.test(t))return['Do you know the taxes or HOA?','These recurring costs can materially change a property decision, so a real number is more useful than a broad estimate.','Type the annual tax or monthly HOA'];return[`Can you verify this? ${t.replace(/[.]+$/,'')}`,'If you know it, add it. If you do not, leave it unknown—ExpenseIntel should not invent the answer.','Type what you know']}
  function questionScore(t){t=clean(t);if(/lease contract: monthly payment|lease: monthly payment/i.test(t))return150;if(/lease contract: lease term|lease: lease term/i.test(t))return145;if(/lease contract: due at signing|lease: due at signing/i.test(t))return140;if(/lease contract: mileage allowance|lease: mileage allowance/i.test(t))return135;if(/exact purchase|quote price|purchase\/quote price/i.test(t))return120;if(/exact vehicle configuration|trim/i.test(t))return115;if(/property-specific|appraisal|comps|comparable sales/i.test(t))return110;if(/contractor quotes|scope/i.test(t))return105;if(/transaction-price benchmark|comparable price|market benchmark|transaction-level comparable/i.test(t))return95;if(/tax|hoa/i.test(t))return80;if(/insurance/i.test(t))return75;return50}
  function bestQuestion(shell){const rows=$$('.check-unknown',shell).map(x=>clean(x.textContent)).filter(Boolean).filter(x=>!skipped.has(x)).sort((a,b)=>questionScore(b)-questionScore(a));if(!rows.length)return null;const raw=rows[0],q=questionFor(raw);return q?{raw,title:q[0],copy:q[1],placeholder:q[2]}:null}
  function currentMetrics(shell=document){return $$('.decision-command-grid>div',shell).map(div=>({label:clean($('span',div)?.textContent),value:clean($('strong',div)?.textContent)})).filter(x=>x.label&&x.value).slice(0,4)}
  function isLease(shell){const a=active(),text=[a?.text,a?.title,$('[data-result-title]',shell)?.textContent,$('[data-result-sub]',shell)?.textContent].filter(Boolean).join(' ');return /\bleas(?:e|ed|ing)\b/i.test(text)}
  function collapseEvidence(){const ev=$('[data-result-evidence]');if(!ev||ev.dataset.eiHelpful==='1')return;ev.dataset.eiHelpful='1';const cards=$$('article',ev);if(cards.length<=3)return;cards.slice(3).forEach(x=>x.classList.add('ei-secondary-evidence'));const b=document.createElement('button');b.type='button';b.className='ei-evidence-toggle';b.textContent=`Show ${cards.length-3} more evidence signal${cards.length-3===1?'':'s'} ↓`;b.onclick=()=>{const open=ev.classList.toggle('ei-expanded');b.textContent=open?'Show fewer evidence signals ↑':`Show ${cards.length-3} more evidence signal${cards.length-3===1?'':'s'} ↓`};ev.appendChild(b)}
  function simplifyLabels(){const score=$('.check-score span');setText(score,'HOW COMPLETE IS THIS?');const raw=$('[data-result-score]');if(raw&&raw.dataset.friendlyStatus!=='1'){const [label]=friendlyStatus(raw.textContent);raw.dataset.original=raw.textContent;raw.dataset.friendlyStatus='1';raw.textContent=label}setText($('.check-card.primary .check-card-head span'),'What we know');setText($('.check-result-grid .check-card:nth-child(2) .check-card-head span'),'What we still need to know');setText($('[data-result-next] span'),'What to do next');setText($('.decision-meaning .check-card-head span'),'Why this matters to you')}
  function summaryData(shell){
    let call=clean($('[data-decision-call]',shell)?.textContent),reason=clean($('[data-decision-reason]',shell)?.textContent),next=clean($('[data-result-next] strong',shell)?.textContent),nextCopy=clean($('[data-result-next] p',shell)?.textContent),metrics=currentMetrics(shell);
    if(isLease(shell)){
      const hasLeaseMetrics=metrics.some(x=>/LEASE|U\.S\. LEASE|TYPICAL TERM|MILE/i.test(x.label));
      if(!/LEASE/i.test(call)||/PRICE NOT VERIFIED/i.test(call))call='LEASE MARKET BASELINE';
      if(!/lease|\$619|market baseline/i.test(reason))reason=`Even with only “I want to lease a 2026 Porsche,” ExpenseIntel can give useful context now: the U.S. average lease payment is ${LEASE_BENCH.avgLease} (${LEASE_BENCH.period}), about ${LEASE_BENCH.leaseShare} of new vehicles are leased, and common lease structures run ${LEASE_BENCH.term} with roughly ${LEASE_BENCH.miles}. These are national anchors, not a Porsche-specific quote.`;
      if(!hasLeaseMetrics)metrics=[{label:'U.S. AVG LEASE',value:LEASE_BENCH.avgLease},{label:'NEW-CAR LOAN AVG',value:LEASE_BENCH.avgFinance},{label:'TYPICAL TERM',value:LEASE_BENCH.term},{label:'MILEAGE RANGE',value:LEASE_BENCH.miles}];
      if(!/lease|payment|model|term|mileage/i.test(next)||/deal price|exact price/i.test(next)){next='Add the Porsche model or monthly payment';nextCopy='ExpenseIntel has already built the general lease baseline. The model unlocks better vehicle-specific fuel and safety data; the payment, term, due-at-signing and mileage turn the baseline into your actual lease economics.'}
    }
    return{call,reason,next,nextCopy,metrics};
  }
  function buildSummary(){const shell=$('[data-check-output] .shell');if(!shell)return;const top=$('.check-output-top',shell),rawStatus=clean($('[data-result-score]',shell)?.dataset.original||$('[data-result-score]',shell)?.textContent),label=clean($('[data-result-label]',shell)?.textContent),[friendly,explain]=friendlyStatus(rawStatus),data=summaryData(shell);if(!top||!data.call)return;const sig=JSON.stringify([data.call,data.reason,data.next,data.nextCopy,data.metrics,rawStatus,label]);let s=$('.ei-everyday-summary',shell);if(!s){s=document.createElement('section');s.className='ei-everyday-summary';s.innerHTML='<div class="ei-summary-head"><div><span>The short answer</span><strong></strong><p></p></div><aside><span>How complete?</span><b></b><small></small></aside></div><div class="ei-summary-lower"><div class="ei-key-numbers"><span>Key numbers</span><div></div></div><div class="ei-next-step"><span>Do this next</span><strong></strong><p></p></div></div>';top.insertAdjacentElement('afterend',s)}if(sig===summarySignature)return;summarySignature=sig;
    $('.ei-summary-head>div>strong',s).textContent=data.call;$('.ei-summary-head>div>p',s).textContent=data.reason;$('.ei-summary-head aside b',s).textContent=friendly;$('.ei-summary-head aside small',s).textContent=`${explain} ${label}`.trim();const nums=$('.ei-key-numbers>div',s);nums.innerHTML=data.metrics.length?data.metrics.map(x=>`<div><span>${x.label}</span><strong>${x.value}</strong></div>`).join(''):'<p>No decision-specific number is verified yet. ExpenseIntel will keep it unknown rather than estimate it silently.</p>';$('.ei-next-step strong',s).textContent=data.next||'Verify the missing fact';$('.ei-next-step p',s).textContent=data.nextCopy||'Use the most important missing fact before committing money.'}
  function appendAnswer(question,answer){const describe=$('[data-mode="describe"]');describe?.click();const box=$('#check-text');const form=$('[data-check-form]');if(!box||!form)return;const a=active(),base=clean(box.value||a?.text||a?.title||'');box.value=`${base}${base?'\n\n':''}Additional detail — ${question}: ${answer}`;box.dataset.userEdited='1';form.requestSubmit?.()}
  function addInlineQuestion(){const shell=$('[data-check-output] .shell');if(!shell||shell.querySelector('.ei-inline-question'))return;const q=bestQuestion(shell);if(!q)return;const summary=$('.ei-everyday-summary',shell);if(!summary)return;const box=document.createElement('section');box.className='ei-inline-question';box.innerHTML='<div><span>One thing that would improve this answer</span><strong></strong><p></p></div><form><label class="sr-only" for="ei-followup-answer">Answer</label><input id="ei-followup-answer" type="text"><button type="submit">Update my check →</button><button type="button" class="ei-skip">I don\'t know</button></form>';box.querySelector('strong').textContent=q.title;box.querySelector('p').textContent=q.copy;const input=box.querySelector('input');input.placeholder=q.placeholder;box.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const answer=clean(input.value);if(!answer){input.focus();return}appendAnswer(q.title,answer)});box.querySelector('.ei-skip').onclick=()=>{skipped.add(q.raw);box.remove();setTimeout(addInlineQuestion,0)};summary.insertAdjacentElement('afterend',box)}
  function collapseAnalysis(){const shell=$('[data-check-output] .shell');if(!shell||shell.querySelector('.ei-analysis-details'))return;const targets=['.decision-command','.check-result-grid','.decision-meaning','[data-comps-section]','[data-vehicle-section]'].map(s=>$(s,shell)).filter(Boolean);if(!targets.length)return;const d=document.createElement('details');d.className='ei-analysis-details';const summary=document.createElement('summary');summary.innerHTML='<span>See evidence, risks & detailed analysis</span><small>Sources, unknowns, safety, market context and technical detail</small>';d.appendChild(summary);targets[0].insertAdjacentElement('beforebegin',d);targets.forEach(el=>d.appendChild(el))}
  function enhance(){const out=$('[data-check-output]');if(!out||out.hidden||!$('[data-decision-call]',out))return;const sig=$$('.check-unknown',out).map(x=>clean(x.textContent)).filter(Boolean).join('|');if(sig!==unknownSignature){unknownSignature=sig;skipped.clear()}simplifyLabels();buildSummary();addInlineQuestion();collapseEvidence();collapseAnalysis()}
  function watch(){const out=$('[data-check-output]');if(!out)return;let queued=false;const obs=new MutationObserver(()=>{if(queued)return;queued=true;setTimeout(()=>{queued=false;enhance()},0)});obs.observe(out,{subtree:true,childList:true,characterData:true});enhance()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch,{once:true});else watch();
})();