(()=>{
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const money=n=>Number.isFinite(+n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(+n):'—';
  const num=v=>{const m=String(v??'').replace(/,/g,'').match(/-?\$?\s*(-?\d+(?:\.\d+)?)/);return m?+m[1]:0};
  const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const ACTIVE='ei_active_decision';
  const active=()=>{try{return JSON.parse(localStorage.getItem(ACTIVE)||'null')}catch(_e){return null}};
  const source=root=>clean([active()?.text,active()?.title,active()?.url,$('.ei-v12-live',root)?.textContent,$('.ei-v12-call h2',root)?.textContent,document.title].filter(Boolean).join(' '));
  const amort=(p,apr,m)=>{const r=(+apr||0)/100/12;if(!p||!m)return 0;return r?p*r/(1-Math.pow(1+r,-m)):p/m};
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const controlRows=root=>$$('.ei-v12-control',root).map(c=>{const input=$('input[type="range"]',c),label=clean($('label',c)?.textContent).replace(/AUTO-FILLED/ig,''),output=clean($('output',c)?.textContent);return{el:c,input,label,output,raw:+(input?.value||num(output)||0)}}).filter(x=>x.input&&x.label);
  const rowBy=(root,rx)=>controlRows(root).find(x=>rx.test(x.label));
  const setRange=(row,value,{expand=true}={})=>{if(!row?.input||!Number.isFinite(+value))return;const input=row.input,v=+value;if(expand&&v>=+input.max*.92){const step=Math.max(+input.step||1,v>150000?2500:v>75000?1000:500);input.max=Math.ceil((v*1.45)/step)*step}if(expand&&v<=+input.min){input.min=Math.max(0,Math.floor(v*.55/(+input.step||1))*(+input.step||1))}input.value=clamp(v,+input.min,+input.max);input.dispatchEvent(new Event('input',{bubbles:true}))};
  function inferredVehiclePrice(root){
    const a=active(),t=source(root).toLowerCase(),explicit=+(a?.price||0);
    if(explicit>5000)return{value:explicit,label:'Auto-filled from the price in your decision',quality:'user'};
    const cashMatches=[...(String(a?.text||'').matchAll(/\$\s*([\d,]{5,})/g))].map(m=>+m[1].replace(/,/g,'')).filter(x=>x>5000&&x<1500000);if(cashMatches.length)return{value:cashMatches[0],label:'Auto-filled from the price in your description',quality:'user'};
    if(/2026/.test(t)&&/porsche/.test(t)&&/911/.test(t)&&/gt3/.test(t))return{value:222500,label:'Modeled starting MSRP baseline for a 2026 Porsche 911 GT3 · replace with the exact configured/listing price',quality:'public-model'};
    if(/2027/.test(t)&&/porsche/.test(t)&&/911/.test(t)&&/gt3/.test(t))return{value:235800,label:'Current Porsche published starting MSRP baseline · replace with the exact configured/listing price',quality:'public-model'};
    const benchmark=num($('[data-k2]',root)?.textContent)||num($('.ei-v13-endcap.reference .value',root)?.textContent);if(benchmark>5000)return{value:benchmark,label:'Auto-filled from the available benchmark baseline · replace with your exact negotiated price',quality:'benchmark'};
    return null;
  }
  function enhancePrice(root){
    const row=rowBy(root,/^(purchase price|price)$/i);if(!row||row.el.dataset.v16Price)return;row.el.dataset.v16Price='1';
    const hint=$('small',row.el),label=$('label',row.el),inf=inferredVehiclePrice(root),text=source(root).toLowerCase(),luxury=/porsche|ferrari|lamborghini|mclaren|aston martin|bentley|rolls[- ]?royce/i.test(text);
    if(luxury&&+row.input.max<300000)row.input.max=500000;else if(+row.input.max<100000)row.input.max=Math.max(150000,+row.input.max*2);
    if(inf&&(+row.input.value<inf.value*.55||Math.abs(+row.input.value-45000)<1200||Math.abs(+row.input.value-65000)<1200)){const step=inf.value>150000?2500:inf.value>75000?1000:500;row.input.min=Math.max(1000,Math.floor(inf.value*.5/step)*step);row.input.max=Math.ceil(inf.value*1.55/step)*step;row.input.step=step;setRange(row,inf.value,{expand:false});if(label&&!$('.ei-v16-auto-badge',label)){const badge=document.createElement('span');badge.className='ei-v16-auto-badge';badge.textContent='Auto-filled';label.appendChild(badge)}if(hint)hint.textContent=inf.label}
    const entry=document.createElement('div');entry.className='ei-v16-price-entry';entry.innerHTML=`<span>Exact purchase price</span><input type="number" min="0" step="500" aria-label="Exact purchase price" value="${Math.round(+row.input.value||0)}"><button type="button">AUTO</button><small class="ei-v16-price-source">${esc(inf?.label||'Enter the exact selling price. The slider range expands automatically for higher-value vehicles.')}</small>`;row.el.appendChild(entry);
    const exact=$('input',entry),autoBtn=$('button',entry),src=$('.ei-v16-price-source',entry);let syncing=false;
    exact.addEventListener('change',()=>{const v=+exact.value;if(v>0){syncing=true;setRange(row,v);syncing=false;if(src)src.textContent='Using your exact entered purchase price.'}});row.input.addEventListener('input',()=>{if(!syncing)exact.value=Math.round(+row.input.value||0)});
    autoBtn.addEventListener('click',()=>{const guess=inferredVehiclePrice(root);if(!guess){if(src)src.textContent='No reliable automatic price was found. Enter the listing or negotiated price directly.';return}const step=guess.value>150000?2500:guess.value>75000?1000:500;row.input.step=step;row.input.min=Math.max(1000,Math.floor(guess.value*.5/step)*step);row.input.max=Math.ceil(guess.value*1.55/step)*step;setRange(row,guess.value,{expand:false});exact.value=Math.round(guess.value);if(src)src.textContent=guess.label});
  }
  function savingsFromDom(root){const direct=num($('.ei-v12-savings strong',root)?.textContent)||num($('[data-k4]',root)?.textContent);if(direct>0)return direct;const cards=$$('.ei-v12-kpi',root);const card=cards.find(x=>/identified savings opportunity/i.test(clean(x.textContent)));return num($('strong',card)?.textContent)}
  function currentValues(root){const get=rx=>rowBy(root,rx)?.raw||0;return{price:get(/^(purchase price|price)$/i),apr:get(/financing apr/i),down:get(/down payment/i),miles:get(/annual mileage/i),payment:get(/monthly payment/i),term:get(/term length/i),due:get(/due at signing/i),mortgage:get(/mortgage rate/i),carry:get(/taxes \+ insurance/i),project:get(/quoted project cost/i),cont:get(/contingency/i),finance:get(/financing cost/i),delay:get(/delay exposure/i)}}
  function kind(root){const labels=controlRows(root).map(x=>x.label.toLowerCase()).join('|');if(labels.includes('monthly payment'))return'lease';if(labels.includes('mortgage rate'))return'property';if(labels.includes('quoted project cost'))return'project';if(labels.includes('purchase price')&&labels.includes('financing apr'))return'vehicle';return'general'}
  function optimizer(root){
    const v=currentValues(root),k=kind(root),dom=savingsFromDom(root);let targets=[],levers=[],modeled=dom;
    if(k==='vehicle'){
      const priceTarget=Math.round(v.price*.97/500)*500,aprTarget=Math.max(0,v.apr-.75),principal=v.price*(1-v.down/100),p0=amort(principal,v.apr,60),pt=priceTarget*(1-v.down/100),p1=amort(pt,v.apr,60),p2=amort(pt,aprTarget,60),priceSave=Math.max(0,(v.price-v.price*v.down/100+p0*60)-(priceTarget-priceTarget*v.down/100+p1*60)),aprSave=Math.max(0,(p1-p2)*60);modeled=Math.max(dom,priceSave+aprSave);const carrySave=Math.max(0,dom-priceSave-aprSave);
      targets=[['Purchase price',money(v.price),`≤ ${money(priceTarget)}`,'price',priceTarget],['Financing APR',`${v.apr.toFixed(2)}%`,`≤ ${aprTarget.toFixed(2)}%`,'apr',aprTarget],['Down payment',`${Math.round(v.down)}%`,'Keep liquidity intentional','down',v.down]];
      levers=[{title:'Negotiate selling price first',copy:`Move the actual selling price toward ${money(priceTarget)} before discussing monthly payment.`,save:priceSave},{title:'Separate financing from the car deal',copy:`Use outside financing to pressure APR from ${v.apr.toFixed(2)}% toward ${aprTarget.toFixed(2)}%.`,save:aprSave}];if(carrySave>250)levers.push({title:'Trim carrying cost',copy:'Quote insurance and ownership costs before signing; the current improved path assumes some carrying-cost compression.',save:carrySave});
    }else if(k==='lease'){
      const payTarget=Math.max(100,Math.round(v.payment*.95/10)*10),dueTarget=Math.min(v.due,500),paySave=Math.max(0,(v.payment-payTarget)*v.term),dueSave=Math.max(0,v.due-dueTarget);modeled=Math.max(dom,paySave+dueSave);targets=[['Monthly payment',`${money(v.payment)}/mo`,`≤ ${money(payTarget)}/mo`,'payment',payTarget],['Due at signing',money(v.due),`≤ ${money(dueTarget)}`,'due',dueTarget],['Term',`${Math.round(v.term)} mo`,v.term>48?'≤ 48 mo':`${Math.round(v.term)} mo`,'term',Math.min(v.term,48)]];levers=[{title:'Reduce the payment without hiding it in cash down',copy:`A roughly 5% payment improvement is worth about ${money(paySave)} over this term.`,save:paySave},{title:'Protect upfront cash',copy:`Keep drive-off near ${money(dueTarget)} instead of prepaying the lease economics.`,save:dueSave}];
    }else if(k==='property'){
      const rateTarget=Math.max(2,v.mortgage-.5),principal=v.price*(1-v.down/100),rateSave=Math.max(0,(amort(principal,v.mortgage,360)-amort(principal,rateTarget,360))*60),carrySave=Math.max(0,v.price*v.carry/100*5*.05);modeled=Math.max(dom,rateSave+carrySave);targets=[['Mortgage rate',`${v.mortgage.toFixed(3)}%`,`≤ ${rateTarget.toFixed(3)}%`,'mortgage',rateTarget],['Taxes + insurance',`${v.carry.toFixed(1)}%/yr`,'Replace with exact quotes','carry',v.carry]];levers=[{title:'Shop the mortgage independently',copy:'A half-point rate improvement can materially change five-year cash burden.',save:rateSave},{title:'Replace carrying-cost assumptions',copy:'Use exact tax, insurance and HOA figures before treating the modeled burden as settled.',save:carrySave}];
    }else if(k==='project'){
      const contTarget=Math.max(8,Math.round(v.cont*.65)),finTarget=Math.max(0,v.finance-1),contSave=v.project*Math.max(0,v.cont-contTarget)/100,finSave=(v.project*(1+contTarget/100))*Math.max(0,v.finance-finTarget)/100*2;modeled=Math.max(dom,contSave+finSave);targets=[['Contingency',`${Math.round(v.cont)}%`,`${contTarget}% after scope proof`,'cont',contTarget],['Financing cost',`${v.finance.toFixed(2)}%`,`≤ ${finTarget.toFixed(2)}%`,'finance',finTarget],['Delay exposure',`${Math.round(v.delay)} mo`,'0–1 mo','delay',Math.min(v.delay,1)]];levers=[{title:'Prove scope before cutting reserve',copy:'Turn exclusions and ambiguity into written scope, then reduce contingency rationally.',save:contSave},{title:'Shop financing separately',copy:'Do not let financing opacity sit inside the contractor or vendor number.',save:finSave}];
    }else{targets=[];levers=[{title:'Attack the largest modeled lever first',copy:'Use the sensitivity view to change the real term that moves the most dollars, then verify it in writing.',save:dom}];modeled=dom}
    modeled=Math.max(0,modeled);return{k,v,targets,levers,modeled};
  }
  function panelHtml(root){const o=optimizer(root),total=o.modeled||savingsFromDom(root);return `<div class="ei-v16-opt-head"><div><div class="ei-v16-opt-kicker">ExpenseIntel / Optimize</div><h3>Turn the green path into <em>actual asks.</em></h3><p>This panel explains where the modeled savings come from, gives target terms, and lets you apply the improved scenario to the live model. It does not pretend the counterparty has already agreed.</p></div><div class="ei-v16-opt-total"><span>Modeled savings opportunity</span><strong>${total?money(total):'Limited'}</strong><small>Current path versus the modeled optimized terms. Not a guaranteed discount or quote.</small></div></div><div class="ei-v16-opt-body"><div class="ei-v16-opt-levers"><div class="ei-v16-opt-title"><h4>Where the savings come from</h4><span>Dollar articulation</span></div>${o.levers.map((x,i)=>`<div class="ei-v16-lever"><div class="num">0${i+1}</div><div><b>${esc(x.title)}</b><p>${esc(x.copy)}</p></div><strong>${x.save>0?`~${money(x.save)}`:'VERIFY'}</strong></div>`).join('')}<div class="ei-v16-opt-actions"><button class="primary" data-v16-apply>Apply optimized scenario</button><button data-v16-copy>Copy negotiation plan</button><button data-v16-reset>Reset terms</button><button data-v16-close>Close</button></div><div class="ei-v16-opt-note">The optimizer changes real model inputs—price, rate, payment, drive-off, contingency or other relevant terms. It never counts a larger down payment as “savings.” Replace modeled targets with actual written offers as you get them.</div></div><aside class="ei-v16-opt-side"><div class="ei-v16-opt-title"><h4>Target terms</h4><span>Current → target</span></div><div class="ei-v16-targets">${o.targets.length?o.targets.map(x=>`<div class="ei-v16-target"><span>${esc(x[0])}</span><div><b>${esc(x[1])}</b><i>→</i><strong>${esc(x[2])}</strong></div></div>`).join(''):'<div class="ei-v16-target"><span>Next move</span><div><b>Current terms</b><i>→</i><strong>Improve the largest lever</strong></div></div>'}</div></aside></div>`}
  function toast(t){document.querySelector('.ei-v16-opt-toast')?.remove();const n=document.createElement('div');n.className='ei-v16-opt-toast';n.textContent=t;document.body.appendChild(n);setTimeout(()=>n.remove(),1800)}
  function ensurePanel(root){let p=$('#eiV16Optimizer',root);if(!p){p=document.createElement('section');p.id='eiV16Optimizer';p.className='ei-v16-optimizer';$('.ei-v12-hero',root)?.insertAdjacentElement('afterend',p)}return p}
  function openOptimizer(root){const p=ensurePanel(root);p.innerHTML=panelHtml(root);p.classList.add('open');bindPanel(root,p);p.scrollIntoView({behavior:'smooth',block:'nearest'})}
  function applyTargets(root){const o=optimizer(root);if(!root.dataset.v16Baseline)root.dataset.v16Baseline=JSON.stringify(controlRows(root).map(r=>[r.label,r.raw]));o.targets.forEach(x=>{const row=rowBy(root,new RegExp(`^${x[0].replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}$`,'i'));if(row&&Number.isFinite(+x[4]))setRange(row,+x[4])});setTimeout(()=>{const p=ensurePanel(root);if(p.classList.contains('open')){p.innerHTML=panelHtml(root);bindPanel(root,p)}toast('Optimized scenario applied')},80)}
  function reset(root){try{const rows=JSON.parse(root.dataset.v16Baseline||'[]');rows.forEach(([label,value])=>{const row=rowBy(root,new RegExp(`^${String(label).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}$`,'i'));if(row)setRange(row,+value)});setTimeout(()=>{const p=ensurePanel(root);if(p.classList.contains('open')){p.innerHTML=panelHtml(root);bindPanel(root,p)}toast('Original terms restored')},80)}catch(_e){toast('No saved baseline yet')}}
  function planText(root){const o=optimizer(root);return ['ExpenseIntel Optimizer',`Modeled savings opportunity: ${money(o.modeled||savingsFromDom(root))}`,'','Target terms:',...o.targets.map(x=>`- ${x[0]}: ${x[1]} -> ${x[2]}`),'','Savings levers:',...o.levers.map((x,i)=>`${i+1}. ${x.title} — ${x.copy}${x.save>0?` (~${money(x.save)})`:''}`),'','Planning targets only; verify actual written offers before committing.'].join('\n')}
  function bindPanel(root,p){$('[data-v16-apply]',p)?.addEventListener('click',()=>applyTargets(root));$('[data-v16-reset]',p)?.addEventListener('click',()=>reset(root));$('[data-v16-close]',p)?.addEventListener('click',()=>p.classList.remove('open'));$('[data-v16-copy]',p)?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(planText(root));toast('Negotiation plan copied')}catch(_e){toast('Copy unavailable')}})}
  function ensureButtons(root){const actions=$('.ei-v12-hero-actions',root);if(actions&&!$('[data-ei-v16-optimize]',actions)){const b=document.createElement('button');b.className='ei-v12-btn ei-v16-opt-btn';b.dataset.eiV16Optimize='1';b.innerHTML='OPTIMIZE & SAVE <span aria-hidden="true">↗</span>';b.addEventListener('click',()=>openOptimizer(root));const rec=[...actions.querySelectorAll('button')].find(x=>/recommendations/i.test(x.textContent));if(rec)rec.insertAdjacentElement('afterend',b);else actions.appendChild(b)}
    const controls=$('.ei-v12-controls',root);if(controls&&!$('.ei-v16-opt-card',controls)){const c=document.createElement('div');c.className='ei-v16-opt-card';const s=savingsFromDom(root);c.innerHTML=`<div class="eyebrow">OPTIMIZER</div><strong>${s?money(s):'Find savings'}</strong><p>See exactly which terms create the improved path, then apply the modeled scenario.</p><button type="button">OPTIMIZE THIS DEAL →</button>`;const value=$('strong',c);if(value){value.style.fontVariantNumeric='tabular-nums lining-nums';value.style.fontFeatureSettings='"tnum" 1, "lnum" 1';value.style.whiteSpace='nowrap'}c.querySelector('button').addEventListener('click',()=>openOptimizer(root));controls.appendChild(c)}}
  function refreshCard(root){const card=$('.ei-v16-opt-card',root),strong=card&&$('strong',card);if(strong){const s=savingsFromDom(root),next=s?money(s):'Find savings';if(strong.textContent!==next)strong.textContent=next}}
  function enhance(root){if(!root)return;enhancePrice(root);ensureButtons(root);refreshCard(root)}
  let queued=false;function schedule(){if(queued)return;queued=true;setTimeout(()=>{queued=false;$$('.ei-v12-dashboard').forEach(enhance)},80)}
  const host=document.querySelector('[data-check-output]')||document.body;new MutationObserver(mutations=>{const meaningful=mutations.some(m=>{const target=m.target instanceof Element?m.target:m.target.parentElement;return !target?.closest?.('.ei-v16-opt-card,.ei-v16-optimizer')});if(meaningful)schedule()}).observe(host,{childList:true,subtree:true});host.addEventListener('input',e=>{if(!e.target.matches?.('.ei-v12-control input[type="range"]'))return;const root=e.target.closest('.ei-v12-dashboard');if(!root)return;setTimeout(()=>{refreshCard(root);const p=$('#eiV16Optimizer.open',root);if(p){p.innerHTML=panelHtml(root);bindPanel(root,p)}},45)});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule();
})();