(()=>{
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const num=s=>{const m=String(s||'').replace(/,/g,'').match(/-?\$?\s*(-?\d+(?:\.\d+)?)/);return m?+m[1]:0};
  const money=n=>Number.isFinite(+n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(+n):'—';
  const pct=n=>`${n>=0?'+':''}${n.toFixed(1)}%`;
  function controlRows(root){return $$('.ei-v12-control',root).map(c=>({label:clean($('label',c)?.textContent),value:clean($('output',c)?.textContent),hint:clean($('small',c)?.textContent),raw:+($('input[type="range"]',c)?.value||0)})).filter(x=>x.label)}
  function pathValue(root,type){return num($(`.ei-v13-endcap.${type} .value`,root)?.textContent)}
  function summary(root){const current=pathValue(root,'current')||num($('[data-k2]',root)?.textContent),improved=pathValue(root,'improved')||Math.max(0,current-num($('[data-k4]',root)?.textContent)),benchmark=pathValue(root,'reference'),saving=Math.max(0,current-improved)||num($('[data-k4]',root)?.textContent),confidence=clean($('[data-v16-chip]',root)?.textContent)||'Planning baseline',gap=benchmark?((current-benchmark)/benchmark)*100:null,item=clean($('.ei-v12-live span:first-child',root)?.textContent)||'this purchase';return{current,improved,benchmark,saving,confidence,gap,item}}
  function category(rows){const labels=rows.map(x=>x.label.toLowerCase()).join('|');if(labels.includes('monthly payment')&&labels.includes('term length'))return'lease';if(labels.includes('mortgage rate'))return'property';if(labels.includes('quoted project cost')||labels.includes('contingency'))return'project';if(labels.includes('purchase price')&&labels.includes('financing apr'))return'vehicle';return'general'}
  function targetFor(x,kind){const l=x.label.toLowerCase(),v=x.raw||num(x.value),hint=x.hint||'';
    if(/monthly payment/.test(l)){const bm=num(hint)||619,target=v?Math.max(100,Math.round((v>bm?Math.min(v*.95,bm*.98):v*.98)/10)*10):Math.round(bm*.98/10)*10;return{from:x.value,to:`≤ ${money(target)}/mo`,why:'Negotiate the payment before adding cash down; payment improvements compound through the full term.'}}
    if(/term length/.test(l)){const target=v>48?48:v;return{from:x.value,to:v>48?'≤ 48 months':`${Math.round(target)} months or shorter`,why:'Avoid stretching the commitment just to make the monthly number look better.'}}
    if(/due at signing/.test(l)){return{from:x.value,to:v>500?'$0–$500':'Keep near $0',why:'Keep upfront cash reversible instead of using a large drive-off to disguise the economics.'}}
    if(/annual mileage/.test(l)){return{from:x.value,to:'Match real usage',why:'Do not underbuy mileage to manufacture a cheaper-looking plan; price the miles you will actually use.'}}
    if(/purchase price|quoted project cost|^price$/.test(l)){const target=v?Math.round(v*.97/100)*100:0;return{from:x.value,to:target?`≤ ${money(target)}`:'Beat the current quote',why:kind==='project'?'Normalize scope first, then push the total price after exclusions are comparable.':'Use the benchmark and condition evidence as the price anchor, not the monthly payment.'}}
    if(/financing apr/.test(l)){const target=Math.max(0,v-.75);return{from:x.value,to:`≤ ${target.toFixed(2)}%`,why:'Bring outside financing and make the seller compete on rate separately from price.'}}
    if(/mortgage rate/.test(l)){const target=Math.max(0,v-.5);return{from:x.value,to:`≤ ${target.toFixed(3)}%`,why:'Rate shopping can move the five-year burden materially without changing the property.'}}
    if(/down payment/.test(l)){return{from:x.value,to:'Preserve liquidity',why:'Use cash down intentionally; do not sacrifice reversibility only to improve the displayed monthly payment.'}}
    if(/taxes \+ insurance/.test(l)){return{from:x.value,to:'Replace with actual quotes',why:'The planning baseline should disappear once exact taxes, insurance and HOA information is available.'}}
    if(/contingency/.test(l)){return{from:x.value,to:'10–15% unless scope is fixed',why:'Optimize scope clarity before cutting contingency; a falsely low reserve is not a real saving.'}}
    if(/financing cost/.test(l)){const target=Math.max(0,v-1);return{from:x.value,to:`≤ ${target.toFixed(2)}%`,why:'Separate financing from the vendor quote and shop it independently.'}}
    if(/delay exposure/.test(l)){return{from:x.value,to:'0–1 month',why:'Resolve approvals, dependencies and lead times before irreversible spend begins.'}}
    if(/annual recurring cost/.test(l)){const target=v?Math.round(v*.9/50)*50:0;return{from:x.value,to:target?`≤ ${money(target)}/yr`:'Reduce recurring burden',why:'Recurring costs deserve negotiation because they compound after the headline purchase is forgotten.'}}
    if(/decision horizon/.test(l)){return{from:x.value,to:x.value,why:'Keep the horizon realistic; changing it only to improve the result would hide the commitment rather than optimize it.'}}
    return{from:x.value,to:'Improve or verify',why:x.hint||'Replace the model with a better fact when available.'}}
  }
  function bullets(root,selector,max=4){return $$(selector,root).map(x=>clean(x.textContent)).filter(Boolean).slice(0,max)}
  function largestLever(root){return clean($('[data-v15-lever]',root)?.textContent)||clean($('[data-sens] .ei-v12-sens-card strong',root)?.textContent).split('·')[0]||'the largest cost driver'}
  function unknowns(root){const rail=$$('[data-rail] .ei-v12-insight',root),u=rail.find(x=>/unknown|missing/i.test(clean($('.tag',x)?.textContent)));const items=u?$$('li',u).map(x=>clean(x.textContent)):[];if(items.length)return items.slice(0,4);return $$('.ei-v16-row .open',root).map(x=>clean(x.closest('.ei-v16-row')?.querySelector('strong')?.textContent)).filter(Boolean).slice(0,4)}
  function levers(root){const rail=$$('[data-rail] .ei-v12-insight',root),box=rail.find(x=>/levers/i.test(clean($('.tag',x)?.textContent)));return box?$$('li',box).map(x=>clean(x.textContent)).filter(Boolean).slice(0,4):[]}
  function walkAway(s){if(s.gap!=null&&s.gap>8)return`If the final terms still leave the modeled path more than about ${Math.max(5,Math.round(s.gap/2))}% above the benchmark after negotiation, pause and compare another deal.`;if(s.saving>0)return`If the seller cannot capture a meaningful share of the ${money(s.saving)} identified opportunity without hiding it in more upfront cash, a longer term, or weaker scope, keep shopping.`;return'If the economics only improve by changing assumptions instead of changing the actual terms, do not treat that as optimization.'}
  function buildPlan(root){const rows=controlRows(root),kind=category(rows),s=summary(root),targets=rows.map(x=>({label:x.label,...targetFor(x,kind)})).slice(0,6),u=unknowns(root),lev=levers(root),first=largestLever(root),benchmark=s.benchmark?money(s.benchmark):'Not yet connected';const steps=[
    {tag:'01 / First move',title:`Attack ${first} first.`,copy:lev[0]||'Start with the input that moves the most modeled dollars. Do not negotiate five small items before the biggest one.'},
    {tag:'02 / Target terms',title:'Negotiate toward the improved path.',copy:`The current modeled path is ${money(s.current)} versus an improved path near ${money(s.improved)}. Use the target terms on the right as the working brief, not as guaranteed market quotes.`},
    {tag:'03 / Verify',title:u.length?`Resolve ${u.length} high-impact unknown${u.length===1?'':'s'}.`:'Keep the model tied to the real contract.',copy:u.length?`Highest priority: ${u.slice(0,3).join('; ')}.`:'Before signing, replace any remaining planning assumptions with the actual written terms.'},
    {tag:'04 / Walk-away line',title:'Do not optimize by hiding the cost.',copy:walkAway(s)}
  ];return{s,kind,targets,u,lev,steps,benchmark}}
  function html(root){const p=buildPlan(root),s=p.s;return `<div class="ei-optimize-head"><div><div class="ei-optimize-kicker">ExpenseIntel / Optimizer</div><h3>Optimize <em>${esc(s.item)}</em></h3><p>This is the action plan behind the green Improved Path. It converts the model into negotiation targets, verification priorities and a walk-away rule. Targets are planning goals, not promised quotes.</p></div><div class="ei-optimize-summary"><div><span>Current path</span><strong>${money(s.current)}</strong></div><div><span>Improved path</span><strong>${money(s.improved)}</strong></div><div class="save"><span>Identified opportunity</span><strong>${s.saving?money(s.saving):'Limited'}</strong></div><div><span>Planning confidence</span><strong>${esc(s.confidence)}</strong></div></div></div><div class="ei-optimize-body"><div class="ei-optimize-main"><div class="ei-optimize-section-head"><h4>Your optimized purchase plan</h4><span>4-step action brief</span></div><div class="ei-optimize-steps">${p.steps.map((x,i)=>`<article class="ei-optimize-step"><div class="num">${i+1}</div><div><span>${esc(x.tag)}</span><strong>${esc(x.title)}</strong><p>${esc(x.copy)}</p></div></article>`).join('')}</div><div class="ei-optimize-actions"><button class="primary" data-opt-copy>Copy optimized plan</button><button data-opt-leverage>Open leverage view</button><button class="quiet" data-opt-close>Close</button></div></div><aside class="ei-optimize-side"><div class="ei-optimize-section-head"><h4>Target terms</h4><span>Current → target</span></div><div class="ei-optimize-targets">${p.targets.map(x=>`<div class="ei-optimize-target"><span>${esc(x.label)}</span><div class="ei-optimize-target-row"><b>${esc(x.from)}</b><i>→</i><strong>${esc(x.to)}</strong></div><div class="ei-optimize-note"><span>Why this matters</span><p>${esc(x.why)}</p></div></div>`).join('')}</div></aside></div><div class="ei-optimize-disclaimer">Benchmark path: ${esc(p.benchmark)}. ExpenseIntel's Optimizer improves the modeled terms; it does not guarantee a seller, lender, contractor, insurer or other counterparty will offer those terms.</div>`}
  function planText(root){const p=buildPlan(root),s=p.s;return [`ExpenseIntel Optimized Plan — ${s.item}`,`Current path: ${money(s.current)}`,`Improved path: ${money(s.improved)}`,`Identified opportunity: ${s.saving?money(s.saving):'Limited'}`,'',...p.steps.map((x,i)=>`${i+1}. ${x.title} ${x.copy}`),'','Target terms:',...p.targets.map(x=>`- ${x.label}: ${x.from} -> ${x.to}`)].join('\n')}
  function toast(t){document.querySelector('.ei-optimize-toast')?.remove();const x=document.createElement('div');x.className='ei-optimize-toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1700)}
  function bind(root,panel){const copy=$('[data-opt-copy]',panel),close=$('[data-opt-close]',panel),lev=$('[data-opt-leverage]',panel);if(copy)copy.onclick=async()=>{try{await navigator.clipboard.writeText(planText(root));toast('Optimized plan copied')}catch(_e){toast('Copy unavailable')}};if(close)close.onclick=()=>panel.classList.remove('open');if(lev)lev.onclick=()=>{const tab=$('[data-tab="leverage-v5"]',root);if(tab){tab.click();$('.ei-v12-workspace',root)?.scrollIntoView({behavior:'smooth',block:'start'})}}}
  function render(root,panel){panel.innerHTML=html(root);bind(root,panel)}
  function ensure(){const root=$('.ei-v12-dashboard');if(!root)return;const actions=$('.ei-v12-hero-actions',root);if(!actions)return;let btn=$('[data-ei-optimize]',root);if(!btn){btn=document.createElement('button');btn.className='ei-v12-btn ei-optimize-btn';btn.dataset.eiOptimize='';btn.innerHTML='OPTIMIZE <span aria-hidden="true">↗</span>';actions.insertAdjacentElement('afterbegin',btn)}let panel=$('.ei-optimize-panel',root);if(!panel){panel=document.createElement('section');panel.className='ei-optimize-panel';const hero=$('.ei-v12-hero',root);hero?.insertAdjacentElement('afterend',panel)}if(!btn.dataset.bound){btn.dataset.bound='1';btn.onclick=()=>{render(root,panel);panel.classList.add('open');panel.scrollIntoView({behavior:'smooth',block:'nearest'})}}}
  let q=false;function schedule(){if(q)return;q=true;setTimeout(()=>{q=false;ensure()},60)}const out=document.querySelector('[data-check-output]')||document.body;new MutationObserver(schedule).observe(out,{subtree:true,childList:true});out.addEventListener('input',e=>{if(!e.target.matches?.('.ei-v12-control input[type="range"]'))return;const root=e.target.closest('.ei-v12-dashboard'),panel=root?.querySelector('.ei-optimize-panel.open');if(panel)render(root,panel)});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule();
})();
