(()=>{
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const money=n=>Number.isFinite(Number(n))?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)):'—';
  const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  let lastData=null,queued=false,lastSignature='';

  function capture(){
    if(window.__eiVisualFetchWrapped)return;window.__eiVisualFetchWrapped=true;
    const original=window.fetch.bind(window);
    window.fetch=async(...args)=>{const response=await original(...args);try{const url=typeof args[0]==='string'?args[0]:args[0]?.url||'';if(/\/api\/check(?:\?|$)/.test(url))response.clone().json().then(d=>{if(d?.ok){lastData=d;lastSignature='';schedule()}}).catch(()=>{})}catch(_e){}return response};
  }
  function schedule(){if(queued)return;queued=true;setTimeout(()=>{queued=false;render()},45)}
  function signature(d){return [d?.detectedCategory,d?.price,d?.check?.score,d?.check?.label,d?.evidence?.sourceCount,d?.comparables?.median,(d?.check?.unknown||[]).join('|')].join('~')}
  function layerState(d){
    const cat=d.detectedCategory,unknown=(d.check?.unknown||[]).join(' ').toLowerCase(),signals=d.evidence?.signals||[],v=d.vehicle||{},c=d.comparables,has=rx=>signals.some(x=>rx.test(String(x.label||'')));
    if(cat==='vehicle')return[['Identity',v.identity?.vin?1:(v.identity?.year&&v.identity?.make&&v.identity?.model?.5:0),'VIN / exact configuration'],['Price',d.price?1:0,'Listing or quoted price'],['Market',c?.ok?1:0,'Comparable market price'],['Running cost',v.fuel?.summary?.annualFuelCost?1:(has(/gasoline|fuel|repair|maintenance/i)?.5:0),'Fuel / operating cost'],['Safety',v.safety?.ok?1:0,'Recall / complaint / rating evidence'],['Personal cost',/insurance|depreciation/.test(unknown)?0:(has(/insurance|depreciation/i)?.5:0),'Insurance / depreciation']];
    if(cat==='property')return[['Property',d.page?.ok?1:(d.input?.location?.5:0),'Exact property / location'],['Price',d.price?1:0,'Asking or purchase price'],['Market',!/appraisal|comps|comparable/.test(unknown)&&has(/house prices/i)?.5:0,'Comparable value evidence'],['Financing',has(/mortgage/i)?1:(has(/treasury/i)?.5:0),'Mortgage backdrop'],['Operating',has(/electricity|natural gas/i)?1:0,'Utilities / carrying costs'],['Property costs',has(/insurance/i)?.5:(/insurance|tax|hoa/.test(unknown)?0:.5),'Tax / insurance / HOA']];
    if(cat==='home')return[['Scope',/scope|full quote/.test(unknown)?.5:1,'What work is included'],['Price',d.price?1:0,'Quoted price'],['Benchmark',/contractor quotes|comparable/.test(unknown)?0:.5,'Comparable quote evidence'],['Inputs',signals.some(x=>x.unit==='% YoY')?1:0,'Material / equipment pressure'],['Location',d.input?.location?.5:0,'Local cost context'],['Exclusions',/permit|electrical|disposal|excluded/.test(unknown)?0:.5,'Potential missing scope']];
    return[['Item',d.input?.text||d.page?.title?1:0,'What is being bought'],['Price',d.price?1:0,'Price captured'],['Market',/benchmark|comparable/.test(unknown)?0:.5,'Market benchmark'],['Ongoing cost',signals.length?.5:0,'Operating burden'],['Risk',unknown.length?.5:1,'Known constraints'],['Exit',0,'Resale / reversibility']];
  }
  function visibilityMetric(d){const layers=layerState(d);return{score:Math.round(layers.reduce((s,x)=>s+x[1],0)/layers.length*100),layers}}
  function ring(score){const r=44,c=2*Math.PI*r,dash=c*clamp(score,0,100)/100;return `<svg class="ei-ring" viewBox="0 0 110 110" role="img" aria-label="Decision visibility ${score} percent"><circle cx="55" cy="55" r="44" class="ei-ring-bg"/><circle cx="55" cy="55" r="44" class="ei-ring-value" stroke-dasharray="${dash.toFixed(1)} ${(c-dash).toFixed(1)}"/><text x="55" y="51" text-anchor="middle" class="ei-ring-number">${score}</text><text x="55" y="68" text-anchor="middle" class="ei-ring-label">VISIBLE</text></svg>`}
  function visibility(d){const m=visibilityMetric(d);return `<div class="ei-viz-grid"><div class="ei-viz-ring-wrap">${ring(m.score)}<p><strong>Decision Visibility</strong> measures how much of the decision is evidenced now. It is not a probability the purchase is good.</p></div><div class="ei-layer-list">${m.layers.map(([name,state,note])=>`<button type="button" class="ei-layer ${state===1?'verified':state===.5?'partial':'missing'}"><span>${name}</span><i><b style="width:${state*100}%"></b></i><em>${state===1?'Verified':state===.5?'Partial':'Missing'}</em><small>${note}</small></button>`).join('')}</div></div>`}
  function pressure(d){const sig=(d.evidence?.signals||[]).filter(s=>s.unit==='% YoY'&&Number.isFinite(Number(s.value))).slice(0,6);if(!sig.length)return '<div class="ei-viz-empty"><strong>No current cost-pressure series is connected for this decision.</strong><p>ExpenseIntel will not manufacture a chart from unrelated data.</p></div>';const max=Math.max(5,...sig.map(s=>Math.abs(Number(s.value))));return `<div class="ei-pressure-chart">${sig.map(s=>{const v=Number(s.value),w=Math.min(48,Math.abs(v)/max*48),left=v>=0?50:50-w;return `<div class="ei-pressure-row"><span>${clean(s.label)}</span><div class="ei-pressure-track"><i style="left:${left}%;width:${w}%"></i><b style="left:50%"></b></div><strong>${v>=0?'+':''}${v.toFixed(1)}%</strong><small>${clean(s.period||'')} · ${clean(s.source||'')}</small></div>`}).join('')}<p class="ei-chart-note">Current year-over-year pressure from connected sources. Context only—not a forecast or quote benchmark.</p></div>`}
  function cost(d){const fuel=d.vehicle?.fuel?.summary?.annualFuelCost,price=Number(d.price)||0;if(d.detectedCategory!=='vehicle'||!fuel||!price)return '<div class="ei-viz-empty"><strong>Known Cost Path is not available yet.</strong><p>This appears only when ExpenseIntel has both a price and a connected recurring-cost series. Missing layers stay missing.</p></div>';const low=Number(fuel.min),mid=Number(fuel.median),high=Number(fuel.max),years=[0,1,2,3,4,5],vals=years.map(y=>({y,low:price+low*y,mid:price+mid*y,high:price+high*y})),min=price,max=Math.max(...vals.map(x=>x.high)),W=620,H=230,p={l:64,r:22,t:18,b:38},x=y=>p.l+(W-p.l-p.r)*(y/5),yy=v=>H-p.b-(H-p.t-p.b)*((v-min)/(max-min||1)),line=vals.map((q,i)=>`${i?'L':'M'}${x(q.y).toFixed(1)},${yy(q.mid).toFixed(1)}`).join(' ');return `<div class="ei-cost-path"><div class="ei-cost-kpis"><div><span>Purchase</span><strong>${money(price)}</strong></div><div><span>EPA/DOE fuel / yr</span><strong>${money(mid)}</strong></div><div><span>Known 5-year range</span><strong>${money(price+low*5)}–${money(price+high*5)}</strong></div></div><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Five year known vehicle cost path"><path d="${line}" class="ei-cost-line"/>${years.map(y=>`<line x1="${x(y)}" y1="${p.t}" x2="${x(y)}" y2="${H-p.b}" class="ei-cost-grid"/><text x="${x(y)}" y="${H-13}" text-anchor="middle">${y===0?'Today':`Yr ${y}`}</text>`).join('')}${vals.map(q=>`<circle cx="${x(q.y)}" cy="${yy(q.mid)}" r="5"><title>Year ${q.y}: ${money(q.mid)}</title></circle>`).join('')}</svg><p class="ei-chart-note">Purchase price + official EPA/DOE standard-use fuel only. Financing, insurance, maintenance, taxes and depreciation remain separate until known.</p></div>`}
  function market(d){const c=d.comparables,p=Number(d.price)||0;if(!c?.ok||!p||!c.median)return '<div class="ei-viz-empty"><strong>Market Distance is waiting on reliable comparable-price data.</strong><p>Macro inflation data does not count as a comparable.</p></div>';const lo=Number(c.p25||c.median*.9),hi=Number(c.p75||c.median*1.1),span=Math.max(1,hi-lo),min=lo-span*.6,max=hi+span*.6,pos=v=>clamp((v-min)/(max-min)*100,0,100),delta=(p-c.median)/c.median*100;return `<div class="ei-market-distance"><div class="ei-market-head"><div><span>Market Distance</span><strong>${delta>=0?'+':''}${delta.toFixed(1)}%</strong><small>vs reliability-cleared median</small></div><div><span>Comparable median</span><strong>${money(c.median)}</strong><small>${c.numFound||c.count||0} matched observations</small></div><div><span>Reliability</span><strong>${clean(c.confidenceLabel||'GOOD')}</strong><small>${clean(c.matchScope||'')} · ${clean(c.matchPrecision||'')}</small></div></div><div class="ei-market-rail"><i class="ei-market-band" style="left:${pos(lo)}%;width:${Math.max(2,pos(hi)-pos(lo))}%"></i><b class="ei-market-median" style="left:${pos(c.median)}%"><em>MEDIAN</em></b><b class="ei-market-you" style="left:${pos(p)}%"><em>YOU · ${money(p)}</em></b></div><div class="ei-market-labels"><span>${money(min)}</span><span>Middle market ${money(lo)}–${money(hi)}</span><span>${money(max)}</span></div></div>`}
  function mount(d){
    const shell=$('[data-check-output] .shell');if(!shell)return;let section=$('.ei-metrics-lab',shell);if(!section){section=document.createElement('section');section.className='ei-metrics-lab';const anchor=$('.decision-meaning',shell)||$('.check-result-grid',shell)||$('.decision-command',shell)||$('.check-output-top',shell);anchor?.insertAdjacentElement('afterend',section)}if(!section)return;
    section.innerHTML='<div class="ei-lab-head"><div><span>ExpenseIntel Metrics</span><h3>See the decision, not just the numbers.</h3><p>Interactive measures built only from evidence already connected to this check.</p></div><div class="ei-lab-tabs" role="tablist"><button type="button" class="active" data-viz="visibility">Visibility</button><button type="button" data-viz="cost">Cost path</button><button type="button" data-viz="pressure">Pressure</button><button type="button" data-viz="market">Market</button></div></div><div class="ei-viz-stage" data-viz-stage></div>';
    const stage=$('[data-viz-stage]',section),tabs=$$('[data-viz]',section),draw=type=>{tabs.forEach(b=>b.classList.toggle('active',b.dataset.viz===type));stage.classList.remove('is-changing');stage.innerHTML=type==='cost'?cost(d):type==='pressure'?pressure(d):type==='market'?market(d):visibility(d);requestAnimationFrame(()=>stage.classList.add('is-changing'))};tabs.forEach(b=>b.addEventListener('click',()=>draw(b.dataset.viz)));draw(d.comparables?.ok?'market':'visibility');
  }
  function render(){if(!lastData)return;const shell=$('[data-check-output] .shell');if(!shell||$('.check-loading',shell)||!$('.decision-command',shell)){setTimeout(schedule,90);return}const sig=signature(lastData);if(sig===lastSignature&&$('.ei-metrics-lab',shell))return;lastSignature=sig;mount(lastData)}
  capture();const out=$('[data-check-output]');if(out){const obs=new MutationObserver(()=>{if(lastData&&!$('.ei-metrics-lab',out)&&!$('.check-loading',out)&&$('.decision-command',out))schedule()});obs.observe(out,{subtree:true,childList:true})}
})();