'use strict';
(()=>{const $=id=>document.getElementById(id),M=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n),engine=window.ExpenseIntelBidReview;
function field(parent,id,label,value,type='number'){const div=document.createElement('div');div.className='field';const l=document.createElement('label');l.htmlFor=id;l.textContent=label;const e=document.createElement(type==='textarea'?'textarea':'input');e.id=id;if(type!=='textarea'){e.type=type;e.value=value;if(type==='number'){e.min='0';e.max='100000000';e.step='.01';}}else{e.maxLength=1500;e.value=value;}div.append(l,e);parent.append(div);}
for(const letter of ['A','B']){const root=$('bid'+letter);[['name','Bidder / option name','Quote '+letter,'text'],['bid','Quoted amount ($)','','number'],['allowance','Additional upfront allowance ($)','0','number'],['monthly','Monthly running cost ($)','0','number'],['annual','Annual service cost ($)','0','number'],['source','Quote reference / date','','text'],['scope','Included scope and uncertainties (short, non-confidential summary)','','textarea']].forEach(([key,label,v,type])=>field(root,letter+key,label,v,type));}
const get=letter=>Object.fromEntries(['name','bid','allowance','monthly','annual','source','scope'].map(key=>[key,$(letter+key).value]));
function row(parent,arr){const tr=document.createElement('tr');arr.forEach(value=>{const td=document.createElement('td');td.textContent=value;tr.append(td);});parent.append(tr);}
function render(d){$('result').classList.add('active');$('out-title').textContent=d.title;$('labelA').textContent=d.bids[0].name;$('labelB').textContent=d.bids[1].name;$('totalA').textContent=M(d.base[0].total);$('totalB').textContent=M(d.base[1].total);$('difference').textContent=M(Math.abs(d.diff));$('difference-note').textContent=d.years+'-year cost difference · assumptions only';$('interpret').textContent=d.interpretation;$('costA').textContent=d.bids[0].name;$('costB').textContent=d.bids[1].name;$('scA').textContent=d.bids[0].name;$('scB').textContent=d.bids[1].name;$('horizon').textContent=d.years+'-year modeled totals';const costs=$('cost-lines');costs.replaceChildren();[['Quoted bid',d.bids[0].bid,d.bids[1].bid],['Additional allowance',d.bids[0].allowance,d.bids[1].allowance],['Effective upfront',d.base[0].upfront,d.base[1].upfront],['Annual operating + service',d.base[0].annual,d.base[1].annual],[d.years+'-year total',d.base[0].total,d.base[1].total]].forEach(r=>row(costs,[r[0],M(r[1]),M(r[2])]));const bars=$('bars');bars.replaceChildren();const max=Math.max(...d.base.map(v=>v.total),1);d.base.forEach((v,i)=>{const el=document.createElement('div');el.className='chartrow';const label=document.createElement('strong');label.textContent=d.bids[i].name;const track=document.createElement('div');track.className='track';const fill=document.createElement('div');fill.className='fill';fill.style.width=(v.total/max*100)+'%';track.append(fill);const sum=document.createElement('b');sum.textContent=M(v.total);el.append(label,track,sum);bars.append(el);});$('crossover').textContent=d.crossover!==null?'Costs cross at approximately '+d.crossover+' year(s) if the entered annual assumptions hold.':'No positive crossover occurs under the entered constant annual costs.';const issues=$('issues');issues.replaceChildren();d.issues.forEach(text=>{const li=document.createElement('li');li.textContent=text;issues.append(li);});const scenarios=$('scenarios');scenarios.replaceChildren();d.scenarios.forEach(s=>row(scenarios,[s.name+' — '+s.detail,M(s.costs[0].total),M(s.costs[1].total),M(s.costs[0].total-s.costs[1].total)]));$('method').textContent=d.method;const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;$('result').scrollIntoView({behavior:reduce?'auto':'smooth',block:'start'});}
$('bid-form').addEventListener('submit',e=>{e.preventDefault();$('error').textContent='';try{render(engine.compare({title:$('project').value,years:$('years').value,bids:[get('A'),get('B')]}));}catch(error){$('result').classList.remove('active');$('error').textContent=error.message;}});
$('print').addEventListener('click',()=>{if($('result').classList.contains('active'))window.print();});
$('demo').addEventListener('click',()=>{for(const [l,vals] of [['A',{name:'Fictional bid A',bid:16200,allowance:800,monthly:25,annual:150,source:'Invented quotation A',scope:'Installation, permit and warranty noted'}],['B',{name:'Fictional bid B',bid:17400,allowance:0,monthly:15,annual:100,source:'Invented quotation B',scope:'Installation, electrical and warranty noted'}]])for(const [key,value] of Object.entries(vals))$(l+key).value=value;$('project').value='Fictional HVAC replacement';$('years').value='5';$('bid-form').requestSubmit();});
})();
