'use strict';
/* Works entirely in the browser: no quotes or customer details are transmitted. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ExpenseIntelBidReview=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
 const TERMS=[['Permits / inspections',/\bpermits?|inspections?\b/i],['Electrical / panel',/\belectrical|panel|wiring|disconnect\b/i],['Removal / disposal',/\bremoval|remove|disposal|haul.?away\b/i],['Equipment / model',/\bequipment|model|capacity|seer\b/i],['Parts / labor warranty',/\bwarrant|guarantee\b/i],['Commissioning / testing',/\bcommission|testing|start.?up|balanc\b/i],['Schedule / milestones',/\bschedule|milestones|completion\b/i],['Change orders',/\bchange.?orders?|extra work\b/i]];
 function number(v,name){if(v===''||v===null||v===undefined)throw Error(name+' is required.');const n=Number(v);if(!Number.isFinite(n)||n<0||n>1e8)throw Error(name+' must be between 0 and $100 million.');return Math.round((n+Number.EPSILON)*100)/100;}
 function clean(v,max=1500){return String(v||'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,max);}
 function parse(payload){if(!payload||typeof payload!=='object'||!Array.isArray(payload.bids)||payload.bids.length!==2)throw Error('Enter exactly two bids.');const years=Number(payload.years);if(!Number.isInteger(years)||years<1||years>10)throw Error('Choose a comparison period from 1 to 10 years.');const title=clean(payload.title,120)||'Contractor bid comparison';const bids=payload.bids.map((b,i)=>({name:clean(b.name,70)||'Quote '+(i?'B':'A'),bid:number(b.bid,'Bid amount'),allowance:number(b.allowance??0,'Additional allowance'),monthly:number(b.monthly??0,'Monthly cost'),annual:number(b.annual??0,'Annual cost'),source:clean(b.source,350),scope:clean(b.scope,1500)}));if(bids.some(b=>b.bid<=0))throw Error('Both bid amounts must be positive.');return{title,years,bids};}
 const round=n=>Math.round((n+Number.EPSILON)*100)/100;
 function cost(b,y,extra=0,allowanceMult=1,recurringMult=1){const upfront=b.bid+b.allowance*allowanceMult+extra;const annual=(b.monthly*12+b.annual)*recurringMult;return{upfront:round(upfront),annual:round(annual),total:round(upfront+annual*y)};}
 function compare(payload){const p=parse(payload),[a,b]=p.bids,base=p.bids.map(x=>cost(x,p.years));const diff=round(base[0].total-base[1].total),gap=Math.abs(diff);const scenarios=[{name:'Entered assumptions',detail:'Exactly the figures entered by the user.',costs:base},{name:'Cost pressure (illustrative)',detail:'Allowances +15%; recurring costs +25% for both bids; not a forecast.',costs:p.bids.map(x=>cost(x,p.years,0,1.15,1.25))},{name:'Extra fee on lower-cost bid (illustrative)',detail:'Adds $600 to the bid with lower entered total. This is hypothetical, not a known fee.',costs:p.bids.map((x,i)=>cost(x,p.years,(diff===0?0:(diff<0?0:1))===i?600:0))}];
 const issues=[];if(!a.scope||!b.scope)issues.push('One or both written scope summaries are missing. Obtain complete proposals before assessing inclusions.');TERMS.forEach(([term,re])=>{const x=re.test(a.scope),y=re.test(b.scope);if(x!==y)issues.push(term+' appears in '+(x?a.name:b.name)+' notes but not '+(x?b.name:a.name)+' notes. Ask both bidders to confirm in writing; omission from these notes is not exclusion.');});if(!issues.length)issues.push('No differences detected in the listed scope keywords. Complete contracts may still differ.');p.bids.forEach(q=>{if(!q.source)issues.push(q.name+': quote/document reference not supplied.');if(!q.scope)issues.push(q.name+': full scope, exclusions and warranty not documented.');});issues.push('Confirm equipment equivalence, permits, taxes, warranty, contractor credentials, schedule and change-order rates independently.');
 const annualDifference=round(base[0].annual-base[1].annual);const upfrontDifference=round(base[0].upfront-base[1].upfront);let crossover=null;if(annualDifference!==0&&upfrontDifference/annualDifference<0)crossover=round(-upfrontDifference/annualDifference);
 const interpretation=diff===0?'The two bids have equal modeled costs under your inputs. This is not proof of equivalent scope or quality.':(diff>0?b.name:a.name)+' has a lower entered '+p.years+'-year modeled cost by $'+gap.toFixed(2)+'. This is only an arithmetic comparison, not a contractor recommendation.';
 return{...p,base,diff,crossover,scenarios,issues,interpretation,annualDifference,upfrontDifference,yearly:Array.from({length:p.years+1},(_,y)=>({year:y,costs:p.bids.map(x=>cost(x,y).total)})),method:'Total modeled cost = bid + additional allowance + years × (12 × monthly running cost + annual servicing). Input data are user-provided. No quotes, prices, energy figures, contractor quality or contract terms are independently verified; hypothetical scenarios are not predictions.'};
 }
 return{compare,parse,cost,TERMS};
});
