(()=>{
  if(!location.pathname.startsWith('/about/'))return;
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const sections=$$('.about-section');
  const findSection=word=>sections.find(s=>(s.querySelector('.about-kicker')?.textContent||'').toLowerCase().includes(word));
  const how=findSection('how it works'),tools=findSection('the tools'),transparent=findSection('transparency'),expect=findSection('what to expect');
  if(how)how.id='how-it-works';if(tools)tools.id='tools';if(transparent)transparent.id='transparency';if(expect)expect.id='what-to-expect';

  function tightenThesis(){
    const one=$('.about-one-line p');if(one)one.innerHTML='<strong>ExpenseIntel builds a Decision Passport before commitment:</strong> price, true cost, exposure, timing, changeability, alternatives, exit and the evidence underneath all of it.';
    const lede=$('.about-lede');if(lede)lede.textContent='ExpenseIntel is pre-commitment decision intelligence. Give it a meaningful purchase, quote, property, lease, vehicle or project before you commit, and it organizes the economic consequences into one living decision record instead of scattering them across unrelated calculators.';
    if(tools){const h=$('.about-section-head h2',tools),p=$('.about-section-head p',tools),k=$('.about-kicker',tools);if(k)k.textContent='The engines';if(h)h.textContent='Specialist engines, one decision.';if(p)p.textContent='Check is the front door. Fair Price, TrueCost, Timing, X-Ray, Project Intel, Location Intelligence and Watch are deeper engines inside the same Decision Passport—not separate products a user has to understand first.'}
  }

  function addArchitecture(){if(!how||$('.about-architecture'))return;const sec=document.createElement('section');sec.className='about-section about-architecture';sec.id='decision-model';sec.innerHTML=`<div class="about-section-head"><div class="about-kicker">The decision model</div><div><h2>What are you actually committing yourself to?</h2><p>Every future ExpenseIntel feature has to earn its place by improving one of these lenses. That keeps the product broad enough to grow without turning into a pile of calculators.</p></div></div><div class="about-lens-shell"><div class="about-lens-grid">${[['01','Price','Is the amount itself supported?'],['02','True cost','What does it cost after day one?'],['03','Exposure','What can still move against you?'],['04','Timing','Does acting now beat waiting?'],['05','Changeability','Which costs can you control later?'],['06','Alternatives','What else solves the same problem?'],['07','Exit','How expensive is it to undo?'],['08','Evidence','How much of this is actually known?']].map((x,i)=>`<button type="button" class="about-lens${i===0?' active':''}" data-about-lens="${i}"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></button>`).join('')}</div><div class="about-lens-readout"><span>Decision Passport</span><strong data-about-lens-title>Price</strong><p data-about-lens-copy></p><a href="/check/">Start one decision →</a></div></div>`;how.insertAdjacentElement('afterend',sec);
    const lensCopy=[
      'A known sticker price is not the same thing as a fair price. ExpenseIntel keeps the amount, the benchmark and the verdict separate.',
      'Financing, recurring bills, taxes, maintenance, fees and recovery value belong in one future receipt—not six disconnected calculators.',
      'The fragile assumptions stay visible. Missing scope, insurance, condition, approvals, utilities and comparables become explicit work to do.',
      'Waiting is only useful when the assumptions are visible. ExpenseIntel stress-tests timing instead of pretending to know the future.',
      'Some burden is structural; some can be switched, renegotiated, reduced or redesigned. Control is part of the economics.',
      'A decision should survive a credible second option. ExpenseIntel should compare the path, not optimize one choice in isolation.',
      'Resale, cancellation, switching cost, holding period and reversibility determine how trapped you become if the assumptions change.',
      'Connected facts, user-supplied inputs, models and unknowns remain visibly different. Confidence follows evidence, not presentation.'
    ];
    const buttons=$$('[data-about-lens]',sec),title=$('[data-about-lens-title]',sec),copy=$('[data-about-lens-copy]',sec);const set=i=>{buttons.forEach((b,n)=>b.classList.toggle('active',n===i));title.textContent=$('strong',buttons[i]).textContent;copy.textContent=lensCopy[i]};buttons.forEach((b,i)=>b.addEventListener('click',()=>set(i)));set(0)
  }

  function addJump(){const hero=$('.about-hero');if(!hero||$('.about-jump'))return;const nav=document.createElement('nav');nav.className='about-jump';nav.setAttribute('aria-label','About page sections');nav.innerHTML='<span>Jump to</span><a href="#how-it-works">How it works</a><a href="#decision-model">Decision model</a><a href="#tools">Engines</a><a href="#transparency">Transparency</a><a href="#what-to-expect">What to expect</a>';hero.insertAdjacentElement('afterend',nav);const links=$$('a',nav),targets=links.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-22% 0px -68%'});targets.forEach(t=>io.observe(t))}}

  const choices={
    general:{label:'ExpenseIntel Check',match:'ExpenseIntel Check',href:'/check/',copy:'Start with the commitment itself. ExpenseIntel builds the Decision Passport and decides which deeper engine is worth opening.'},
    price:{label:'Fair Price',match:'Fair Price',href:'/fairprice/',copy:'Use the price engine when the important question is whether an asking price or quote is actually supported by comparable evidence.'},
    total:{label:'TrueCost',match:'TrueCost',href:'/truecost/',copy:'Use the cost engine when financing, recurring burden, fees, holding period or recovery value can change the decision.'},
    timing:{label:'Wait or Buy',match:'Wait or Buy',href:'/timing/',copy:'Use the timing engine when acting now versus later depends on rates, incentives or explicit assumptions about the future.'},
    property:{label:'Location Intelligence',match:'Location Intelligence',href:'/screen/',copy:'Use the location engine when property facts, utilities, systems, recurring costs, hazard context or controllable expense matter.'},
    project:{label:'Project Intel + X-Ray',match:'Project Intel + X-Ray',href:'/project/',copy:'Use the diligence engine when a project has documents, dependencies, utility constraints, irreversible spend or expensive failure points.'}
  };
  function addChooser(){if(!tools||$('.about-chooser'))return;const grid=$('.tools-grid',tools);if(!grid)return;const box=document.createElement('div');box.className='about-chooser';box.innerHTML='<div class="about-chooser-copy"><span>Same decision, deeper lens</span><h3>What part of the commitment needs more work?</h3></div><div class="about-choice-buttons" role="group" aria-label="Choose a decision question"><button type="button" data-choice="general">I am not sure yet</button><button type="button" data-choice="price">Price</button><button type="button" data-choice="total">True cost</button><button type="button" data-choice="timing">Timing</button><button type="button" data-choice="property">Location costs</button><button type="button" data-choice="project">Project risk</button></div><div class="about-choice-result" aria-live="polite"><div><span>Recommended engine</span><strong>ExpenseIntel Check</strong><p>Start with the decision and let ExpenseIntel decide which deeper engine is useful.</p></div><a class="solidbtn" href="/check/">Open Check →</a></div>';grid.insertAdjacentElement('beforebegin',box);
    const result=$('.about-choice-result',box),title=$('strong',result),copy=$('p',result),cta=$('a',result),buttons=$$('button[data-choice]',box);
    const activate=key=>{const c=choices[key]||choices.general;buttons.forEach(b=>{const on=b.dataset.choice===key;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on?'true':'false')});title.textContent=c.label;copy.textContent=c.copy;cta.href=c.href;cta.textContent=`Open ${c.label.replace('ExpenseIntel ','')} →`;$$('.tool-card',tools).forEach(card=>{const match=(card.querySelector('h3')?.textContent||'').trim()===c.match;card.classList.toggle('recommended',match)});result.classList.remove('pulse');void result.offsetWidth;result.classList.add('pulse')};buttons.forEach(b=>b.addEventListener('click',()=>activate(b.dataset.choice)));activate('general')}

  function makeCardsWorkBetter(){$$('.tool-card').forEach(card=>{const a=$('a',card);if(!a)return;a.setAttribute('aria-label',`${card.querySelector('h3')?.textContent||'ExpenseIntel engine'} — open engine`)});const company=$$('.footer-col').find(c=>(c.querySelector('h4')?.textContent||'').trim()==='Company');if(company&&!company.querySelector('a[href="/about/"]')){const a=document.createElement('a');a.href='/about/';a.textContent='About ExpenseIntel';company.insertBefore(a,company.firstElementChild?.nextSibling||null)}}

  function smoothAnchors(){document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a)return;const target=document.querySelector(a.getAttribute('href'));if(!target)return;e.preventDefault();target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});history.replaceState(null,'',a.getAttribute('href'))})}

  tightenThesis();addArchitecture();addJump();addChooser();makeCardsWorkBetter();smoothAnchors();
})();