(()=>{
  if(!location.pathname.startsWith('/watch/'))return;
  const $=(s,r=document)=>r.querySelector(s);
  const PASSPORT='ei_decision_passport_v1';
  const read=()=>{try{return JSON.parse(localStorage.getItem(PASSPORT)||'null')}catch(_e){return null}};
  const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
  function reshape(){const hero=$('.watch-hero');if(hero){const k=$('.kicker',hero),h=$('h1',hero),p=$('h1+p',hero);if(k)k.textContent='A serious decision should leave a memory.';if(h)h.innerHTML='Save the passport. See what <em>changed.</em>';if(p)p.textContent='ExpenseIntel keeps the original decision baseline so a future answer can be compared with what you knew, assumed and worried about at the time. The current beta stays browser-local and does not pretend to monitor prices in the background.'}const first=$('.watch-section-title .section-no');if(first)first.textContent='Decision Passports'}
  function render(){const p=read(),work=$('.watch-work .shell');if(!p||!work||$('.ei-memory-card'))return;const local=$('.watch-local',work),card=document.createElement('section');card.className='ei-memory-card';const updated=p.updatedAt?new Date(p.updatedAt):null,when=updated&&!Number.isNaN(updated.valueOf())?updated.toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Saved locally';card.innerHTML=`<div class="ei-memory-head"><div><span>Most recent Decision Passport</span><strong></strong></div><div><span>Local decision ID</span><b></b></div></div><div class="ei-memory-grid"><div class="ei-memory-cell"><span>ExpenseIntel call</span><strong data-memory-call></strong></div><div class="ei-memory-cell"><span>Evidence</span><strong data-memory-evidence></strong></div><div class="ei-memory-cell"><span>Open exposure</span><strong data-memory-open></strong></div><div class="ei-memory-cell"><span>Updated</span><strong data-memory-updated></strong></div></div><div class="ei-memory-foot"><p>This is a local decision record, not proof that ExpenseIntel is continuously monitoring the market.</p><div class="ei-memory-actions"><a href="/check/">Re-open decision →</a><a href="/truecost/">TrueCost</a><a href="/data/">Evidence</a></div></div>`;card.querySelector('.ei-memory-head strong').textContent=clean(p.title)||'Recent decision';card.querySelector('.ei-memory-head b').textContent=clean(p.id)||'LOCAL';card.querySelector('[data-memory-call]').textContent=clean(p.call)||'No call saved';card.querySelector('[data-memory-evidence]').textContent=clean(p.evidenceStatus)||'Not recorded';card.querySelector('[data-memory-open]').textContent=Number.isFinite(Number(p.unknownCount))?`${Number(p.unknownCount)} unresolved`:'Not recorded';card.querySelector('[data-memory-updated]').textContent=when;(local||work.firstElementChild)?.insertAdjacentElement('afterend',card)}
  function init(){reshape();render()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();