(()=>{
  if(!(location.pathname==='/'||location.pathname.startsWith('/check/')))return;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const ACTIVE='ei_active_decision';
  const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
  const money=n=>Number(n)>0?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)):'—';
  const readActive=()=>{try{return JSON.parse(localStorage.getItem(ACTIVE)||'null')}catch(_e){return null}};
  const escapeHtml=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const modes=[['graph','01','Commitment Graph'],['switch','02','Switchboard'],['elastic','03','Cost Elasticity'],['regret','04','Regret Surface'],['half','05','Decision Half-Life'],['reverse','06','Reverse Search'],['deps','07','Hidden Dependencies'],['failure','08','Failure Budget']];

  function context(root){
    const a=readActive()||{};
    const unknowns=$$('.check-unknown',root).map(x=>clean(x.textContent)).filter(Boolean);
    const evidence=$$('[data-result-evidence] article',root).map(x=>clean(x.textContent)).filter(Boolean);
    const actions=$$('a[href]',root).map(a=>({label:clean(a.textContent),href:a.getAttribute('href')})).filter(x=>/truecost|timing|watch|screen|fair/i.test(x.href||''));
    const call=clean($('[data-decision-call]',root)?.textContent);
    const score=clean($('[data-result-score]',root)?.textContent);
    const label=clean($('[data-result-label]',root)?.textContent);
    const title=clean(a.title||a.text||$('[data-result-title]',root)?.textContent||'Active decision');
    const price=Number(a.price)||Number(String(title).replace(/[^0-9.]/g,'').match(/\d+(?:\.\d+)?/)?.[0])||0;
    const category=String(a.category||'').toLowerCase();
    return {a,unknowns,evidence,actions,call,score,label,title,price,category};
  }

  const categorySets={
    vehicle:{switches:[['Financing','Negotiable','APR, term and down payment can change independently of vehicle price.'],['Insurance','Switchable','Compare equivalent coverage and deductibles; do not optimize premium alone.'],['Fuel / charging','Partly controllable','Driving pattern, fuel type and charging access affect operating burden.'],['Trim + options','Design choice','Removing low-value options can reduce both price and depreciation exposure.'],['Service plan','Negotiable','Separate actual maintenance coverage from dealer add-ons.'],['Seller / dealer','Switchable','The same configuration may be available through another seller.']],elastic:{fixed:['Taxes / registration','Vehicle identity'],adjustable:['Financing','Insurance','Seller / dealer','Trim + options','Service plan'],unknown:['Depreciation','Repair burden','Future resale']},deps:[['Insurance eligibility','A purchase can be affordable but expensive to insure.','Get an actual premium for the VIN/configuration.'],['Configuration identity','Pricing and fuel evidence can be wrong if trim/drivetrain are unresolved.','Confirm VIN or exact trim.'],['Resale market','Exit economics depend on future demand for this configuration.','Use resale evidence rather than an assumed recovery rate.'],['Recall completion','A model-level recall does not prove a specific VIN is repaired.','Check VIN-level recall status before closing.']]},
    property:{switches:[['Mortgage / lender','Negotiable','Rate, points, term and closing costs can materially alter carrying cost.'],['Insurance','Switchable','Compare equivalent coverage, exclusions and deductibles.'],['Electric supply','Eligibility dependent','Some markets allow supplier choice; verify local tariff rules before assuming savings.'],['Heating system','Structural choice','Fuel and system choice can change long-run cost but requires building-specific feasibility.'],['Water heating','Structural choice','System efficiency and fuel type affect recurring burden.'],['Recurring services','Switchable','Internet, waste, maintenance and service vendors may be rebid.']],elastic:{fixed:['Property tax base','Location / parcel','HOA obligations if applicable'],adjustable:['Insurance','Financing','Utility usage','Service vendors','System efficiency'],unknown:['Major repairs','Assessment changes','Future resale','Special assessments']},deps:[['Property identity','Square footage, use and parcel facts drive several cost layers.','Confirm assessor/property facts before relying on modeled cost.'],['Insurance market','Hazard exposure can become an insurance-cost problem.','Get a real property-specific premium and exclusions.'],['Building systems','Age and condition can create concentrated future costs.','Verify HVAC, roof, electrical, plumbing and water-heating condition.'],['Local tax / assessment','Taxes can diverge from purchase price and change after sale.','Verify current bill, assessment rules and exemptions.']]},
    home:{switches:[['Scope','Negotiable','Reduce ambiguity before negotiating price; exclusions often matter more than headline discount.'],['Contractor','Switchable','Compare like-for-like scope, schedule, warranty and allowances.'],['Materials','Design choice','Substitutions can change cost without changing the underlying job.'],['Sequence','Design choice','Bundling or reordering work can reduce duplicate mobilization.'],['Financing','Negotiable','Financing cost belongs beside project cost.'],['Warranty / service','Negotiable','Value depends on actual coverage and who bears failure risk.']],elastic:{fixed:['Permit requirements','Site constraints'],adjustable:['Scope','Materials','Contractor','Sequence','Financing'],unknown:['Change orders','Hidden conditions','Schedule delay','Rework']},deps:[['Scope completeness','Missing work becomes change-order exposure.','Require inclusions, exclusions, quantities and allowances in writing.'],['Existing conditions','Walls, utilities or equipment can hide costly conditions.','Inspect before final price where feasible.'],['Permit / approval path','Approval delays can create carrying and schedule cost.','Verify authority, permit and inspection requirements.'],['Sequence dependencies','One trade can make another redo work.','Map predecessor work before mobilization.']]},
    equipment:{switches:[['Vendor','Switchable','Compare delivered scope, commissioning and service—not unit price alone.'],['Financing','Negotiable','Term and rate can change effective acquisition cost.'],['Maintenance contract','Switchable','Service coverage and response time can be rebid.'],['Energy source','Structural choice','Operating cost may depend heavily on fuel/electricity assumptions.'],['Specification','Design choice','Oversizing or unnecessary options can add capital and operating cost.'],['Warranty','Negotiable','Failure allocation matters when downtime is expensive.']],elastic:{fixed:['Site constraints','Core required capacity'],adjustable:['Vendor','Financing','Specification','Service contract','Operating schedule'],unknown:['Downtime','Repair parts','Residual value','Installation overruns']},deps:[['Site readiness','Power, fuel, space or structural limits can invalidate the equipment choice.','Verify utilities and installation requirements first.'],['Service access','Cheap equipment can be expensive if qualified service is scarce.','Verify local service coverage and parts lead time.'],['Downtime cost','Failure cost may exceed repair cost.','Estimate operational loss from outage duration.'],['Residual value','Exit economics depend on a real secondary market.','Verify resale/liquidation evidence rather than assuming recovery.']]},
    personal:{switches:[['Seller','Switchable','Compare exact product and included service before committing.'],['Financing','Negotiable','Payment structure can materially change total cost.'],['Warranty','Negotiable','Extended coverage should be priced separately from the item.'],['Subscription / service','Switchable','Recurring service can outgrow the purchase price over time.'],['Configuration','Design choice','Choose only the features that materially solve the need.'],['Timing','Decision choice','Waiting can be tested when price or financing is likely to matter.']],elastic:{fixed:['Required taxes / fees'],adjustable:['Seller','Financing','Warranty','Configuration','Service plan'],unknown:['Resale','Repair burden','Future price']},deps:[['Exact configuration','Price comparisons fail when products are not actually equivalent.','Confirm model/specification and included items.'],['Recurring service','A low purchase price can hide required subscriptions or consumables.','List recurring obligations explicitly.'],['Return / cancellation','Exit rights determine how reversible the commitment is.','Verify return, cancellation and restocking terms.'],['Warranty / support','Failure cost depends on service quality and coverage.','Confirm actual warranty and service path.']]}
  };
  function setFor(c){if(/property/.test(c))return categorySets.property;if(/home/.test(c))return categorySets.home;if(/vehicle/.test(c))return categorySets.vehicle;if(/equipment|business-project|project/.test(c))return categorySets.equipment;return categorySets.personal}

  function graph(ctx){
    const nodes=[['Price',ctx.price?money(ctx.price):'amount'],['True cost','future receipt'],['Exposure',ctx.unknowns.length?`${ctx.unknowns.length} open`:'review'],['Timing','scenario'],['Alternatives','not compared'],['Exit','reversibility'],['Evidence',[ctx.score,ctx.label].filter(Boolean).join(' ')||'status']];
    const pos=[[19,23],[50,13],[81,24],[86,66],[64,86],[35,86],[13,63]];
    return `<div class="ei-lab-note">This map shows the parts of the current commitment that are connected versus still unresolved. It is a decision map, not a portfolio graphic.</div><div class="ei-graph-wrap"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${pos.map((p,i)=>`<path class="ei-graph-edge${(i===2&&ctx.unknowns.length)?' hot':''}" d="M50 50 L${p[0]} ${p[1]}"/>`).join('')}</svg><div class="ei-graph-node root">${escapeHtml(ctx.title.slice(0,48))}<small>commitment</small></div>${nodes.map((n,i)=>`<div class="ei-graph-node${i===2&&ctx.unknowns.length?' open':''}" style="left:${pos[i][0]}%;top:${pos[i][1]}%">${n[0]}<small>${escapeHtml(n[1])}</small></div>`).join('')}</div>`
  }
  function switchboard(ctx){const set=setFor(ctx.category);return `<div class="ei-lab-note">A switchable cost is not automatically a cheap cost. This screen identifies levers; it does not claim a provider, quote or saving exists until one is verified.</div><div class="ei-switch-grid">${set.switches.map(x=>`<article class="ei-switch"><span>Control lever <b>${x[1]}</b></span><strong>${x[0]}</strong><p>${x[2]}</p></article>`).join('')}</div>`}
  function elasticity(ctx){const e=setFor(ctx.category).elastic;return `<div class="ei-lab-note">Cost Elasticity classifies what is structurally fixed, meaningfully adjustable or still unknown. It deliberately avoids inventing dollar shares when ExpenseIntel does not have the underlying bill data.</div><div class="ei-elastic"><div><span>Structural</span><strong>Harder to move</strong><ul>${e.fixed.map(x=>`<li>${x}</li>`).join('')}</ul></div><div><span>Adjustable</span><strong>Worth testing</strong><ul>${e.adjustable.map(x=>`<li>${x}</li>`).join('')}</ul></div><div><span>Unknown</span><strong>Needs evidence</strong><ul>${e.unknown.map(x=>`<li>${x}</li>`).join('')}</ul></div></div>`}
  function regret(ctx){return `<div class="ei-lab-note">Regret Surface is a user-controlled stress test, not a forecast. All shock sliders start at zero. The math simply asks how much extra burden your selected downside assumptions would create relative to the entered commitment amount.</div><div class="ei-stress-grid"><div class="ei-lab-field"><label>Base commitment amount <output data-r-baseout>${ctx.price?money(ctx.price):'enter amount'}</output></label><input data-r-base type="number" min="0" step="100" value="${ctx.price||''}" placeholder="0"></div><div class="ei-lab-field"><label>Unexpected first-year cost <output data-r-aout>0%</output></label><input data-r-a type="range" min="0" max="25" value="0"></div><div class="ei-lab-field"><label>Recovery / value shortfall <output data-r-bout>0%</output></label><input data-r-b type="range" min="0" max="30" value="0"></div><div class="ei-lab-field"><label>Exit friction <output data-r-cout>0%</output></label><input data-r-c type="range" min="0" max="15" value="0"></div></div><div class="ei-lab-result"><div><span>Selected downside burden</span><strong data-r-total>Set a scenario</strong></div><p data-r-note>No negative assumptions are preloaded. Move a slider to test your own case.</p></div>`}
  function halfLife(ctx){
    const all=ctx.evidence.join(' ').toLowerCase();const hasRate=/treasury|rate|gasoline|price|market|ppi|cpi/.test(all),hasIdentity=/nhtsa|assessor|parcel|property|vehicle identity|recall/.test(all),hasAnnual=/annual|2026|2025|eia|bls/.test(all);
    const short=hasRate?'Live or market-sensitive evidence is present. Re-check it before commitment if time passes.':'No clearly market-sensitive evidence was detected in the displayed result.';
    const medium=hasAnnual?'Public benchmark context is present. It can remain useful while still aging behind live prices.':'No medium-horizon benchmark was clearly detected.';
    const durable=hasIdentity?'Identity, safety or property facts are present. These often age more slowly than market prices but still require source-specific review.':'No durable identity layer was clearly detected.';
    return `<div class="ei-lab-note">“Half-Life” is an ExpenseIntel freshness discipline, not a statistical claim. It separates evidence that can go stale quickly from facts that tend to remain useful longer.</div><div class="ei-half-grid"><article class="ei-half-card"><span>Short-lived</span><strong>${hasRate?'Re-check first':'Not detected'}</strong><p>${short}</p></article><article class="ei-half-card"><span>Medium-lived</span><strong>${hasAnnual?'Context layer':'Not detected'}</strong><p>${medium}</p></article><article class="ei-half-card"><span>Durable</span><strong>${hasIdentity?'Identity layer':'Not detected'}</strong><p>${durable}</p></article></div><div class="ei-lab-result"><div><span>Freshness priority</span><strong>${ctx.unknowns.length?'Resolve unknowns first':hasRate?'Refresh market-sensitive inputs':'Review source dates'}</strong></div><p>${ctx.unknowns[0]?escapeHtml(ctx.unknowns[0]):'The most important refresh depends on which fact can materially change the decision.'}</p></div>`
  }
  function reverse(ctx){return `<div class="ei-lab-note">Reverse Search is a constraint builder today—not an inventory search pretending to have listings it cannot access. Define what a better alternative must satisfy, then carry the brief into a fresh Check.</div><div class="ei-reverse-grid"><div class="ei-lab-field"><label>Maximum upfront amount</label><input data-v-max type="number" min="0" step="100" placeholder="Optional"></div><div class="ei-lab-field"><label>Priority</label><select data-v-priority><option value="lowest all-in cost">Lowest all-in cost</option><option value="strongest evidence">Strongest evidence</option><option value="easiest exit">Easiest exit</option><option value="lowest recurring burden">Lowest recurring burden</option></select></div><div class="ei-lab-field"><label>Maximum unresolved facts</label><input data-v-unknown type="number" min="0" max="20" value="3"></div><div class="ei-lab-field"><label>Required condition</label><label class="ei-lab-check"><input data-v-exit type="checkbox"> Must have a meaningfully reversible exit</label></div></div><div class="ei-lab-actions"><button type="button" data-v-build>Build alternative brief</button><a href="/check/">Start fresh Check →</a></div><div class="ei-brief" data-v-brief>Set constraints, then build the brief.</div>`}
  function deps(ctx){const d=setFor(ctx.category).deps;const extra=ctx.unknowns.slice(0,2).map((u,i)=>[`Open evidence gap ${i+1}`,'The current check explicitly says this fact is unresolved.',u]);return `<div class="ei-lab-note">Hidden Dependencies focuses on what the commitment relies on—not just what it costs. Current unresolved Check items are promoted into the dependency map instead of being buried.</div><div class="ei-dep-grid">${[...extra,...d].map((x,i)=>`<article class="ei-dep"><span>Dependency ${String(i+1).padStart(2,'0')} <b>${i<extra.length?'OPEN':'CHECK'}</b></span><strong>${escapeHtml(x[0])}</strong><p>${escapeHtml(x[1])}<br><br><b>Verify:</b> ${escapeHtml(x[2])}</p></article>`).join('')}</div>`}
  function failure(ctx){const labels=/property/.test(ctx.category)?['Major system / repair','Insurance or tax shock','Early exit / transaction friction']:/vehicle/.test(ctx.category)?['Repair / downtime','Insurance / operating shock','Resale shortfall']:/home|project|equipment/.test(ctx.category)?['Change order / overrun','Delay / downtime','Rework / failure'] : ['Unexpected cost','Recurring burden','Exit / recovery loss'];return `<div class="ei-lab-note">Failure Budget makes the bad-year reserve explicit. ExpenseIntel does not populate costs it cannot know; enter only figures you are willing to stress-test.</div><div class="ei-failure-grid"><div class="ei-lab-field"><label>Base commitment</label><input data-f-base type="number" min="0" step="100" value="${ctx.price||''}" placeholder="Optional"></div><div class="ei-lab-field"><label>Available reserve</label><input data-f-reserve type="number" min="0" step="100" placeholder="Enter your cushion"></div></div><div class="ei-failure-rows">${labels.map((l,i)=>`<div class="ei-failure-row"><input value="${escapeHtml(l)}" aria-label="Failure scenario label ${i+1}"><input data-f-cost type="number" min="0" step="100" placeholder="$0" aria-label="Failure scenario cost ${i+1}"></div>`).join('')}</div><div class="ei-lab-result"><div><span>Failure stack</span><strong data-f-total>$0</strong></div><p data-f-note>Enter one or more downside costs. The reserve comparison will update automatically.</p></div>`}

  const builders={graph,switch:switchboard,elastic:elasticity,regret,half:halfLife,reverse,deps,failure};
  function bindInteractive(panel,mode,ctx){
    if(mode==='regret'){const base=$('[data-r-base]',panel),a=$('[data-r-a]',panel),b=$('[data-r-b]',panel),c=$('[data-r-c]',panel);const update=()=>{const bv=Number(base.value)||0,av=Number(a.value)||0,bv2=Number(b.value)||0,cv=Number(c.value)||0;$('[data-r-baseout]',panel).textContent=bv?money(bv):'enter amount';$('[data-r-aout]',panel).textContent=av+'%';$('[data-r-bout]',panel).textContent=bv2+'%';$('[data-r-cout]',panel).textContent=cv+'%';const total=bv*(av+bv2+cv)/100;$('[data-r-total]',panel).textContent=(av+bv2+cv)&&bv?money(total):'Set a scenario';$('[data-r-note]',panel).textContent=(av+bv2+cv)&&bv?`Transparent scenario: ${av}% first-year cost + ${bv2}% recovery shortfall + ${cv}% exit friction, all applied to the entered base. This is not a probability or forecast.`:'No negative assumptions are preloaded. Move a slider to test your own case.'};[base,a,b,c].forEach(x=>x.addEventListener('input',update));update()}
    if(mode==='reverse'){$('[data-v-build]',panel)?.addEventListener('click',()=>{const max=Number($('[data-v-max]',panel).value)||0,priority=$('[data-v-priority]',panel).value,unk=Number($('[data-v-unknown]',panel).value),exit=$('[data-v-exit]',panel).checked;const brief=`ALTERNATIVE BRIEF\nCurrent decision: ${ctx.title}\nFind a credible alternative that prioritizes ${priority}.${max?`\nUpfront amount: no more than ${money(max)}.`:''}\nEvidence requirement: no more than ${unk} unresolved decision-critical facts.${exit?'\nExit requirement: meaningfully reversible if assumptions change.':''}\nCompare price, true cost, exposure, timing, changeability, alternatives, exit and evidence. Do not fill missing facts with estimates unless they are explicitly labeled as modeled.`;$('[data-v-brief]',panel).textContent=brief;navigator.clipboard?.writeText(brief).catch(()=>{})})}
    if(mode==='failure'){const costs=$$('[data-f-cost]',panel),reserve=$('[data-f-reserve]',panel);const update=()=>{const total=costs.reduce((s,x)=>s+(Number(x.value)||0),0),r=Number(reserve.value)||0;$('[data-f-total]',panel).textContent=money(total||0).replace('—','$0');$('[data-f-note]',panel).textContent=total?r?`${money(r)} reserve would ${r>=total?'cover':'leave a gap against'} this ${money(total)} user-entered failure stack${r>=total?'.':` by ${money(total-r)}.`}`:`This stack is ${money(total)}. Enter an available reserve to test coverage.`:'Enter one or more downside costs. The reserve comparison will update automatically.'};[...costs,reserve].forEach(x=>x.addEventListener('input',update));update()}
  }
  function renderMode(box,mode,ctx){const title=Object.fromEntries(modes.map(x=>[x[0],x[2]]))[mode],descs={graph:'See the whole commitment as one connected system.',switch:'Find the parts you may be able to change later.',elastic:'Separate structural burden from controllable burden.',regret:'Choose your own downside assumptions and see the burden.',half:'See which evidence deserves to be refreshed first.',reverse:'Define what a better alternative must satisfy.',deps:'Expose what the decision quietly depends on.',failure:'Put a number on the bad-year cushion you want.'};$$('[data-lab-mode]',box).forEach(b=>b.classList.toggle('active',b.dataset.labMode===mode));$('[data-lab-title]',box).textContent=title;$('[data-lab-desc]',box).textContent=descs[mode];const panel=$('[data-lab-content]',box);panel.innerHTML=builders[mode](ctx);bindInteractive(panel,mode,ctx)}
  function build(){const root=$('[data-check-output] .shell');if(!root||!$('[data-decision-call]',root))return;if($('.ei-decision-lab',root))return;const pass=$('.ei-live-passport',root);if(!pass)return;const ctx=context(root),box=document.createElement('details');box.className='ei-decision-lab';box.innerHTML=`<summary><span class="ei-lab-badge">Optional</span><strong>Decision Lab — advanced decision physics</strong><small>8 contained diagnostics · nothing runs as a hidden verdict</small></summary><div class="ei-lab-shell"><nav class="ei-lab-nav" aria-label="Decision Lab diagnostics"><span>Explore</span>${modes.map((x,i)=>`<button type="button" class="${i===0?'active':''}" data-lab-mode="${x[0]}"><b>${x[1]}</b><strong>${x[2]}</strong></button>`).join('')}</nav><section class="ei-lab-panel"><div class="ei-lab-panel-head"><div><span>Decision Lab</span><h3 data-lab-title>Commitment Graph</h3></div><p data-lab-desc></p></div><div class="ei-lab-content" data-lab-content></div></section></div>`;pass.insertAdjacentElement('afterend',box);$$('[data-lab-mode]',box).forEach(b=>b.addEventListener('click',()=>{if(!box.open)box.open=true;renderMode(box,b.dataset.labMode,ctx)}));box.addEventListener('toggle',()=>{if(box.open&&!$('[data-lab-content]',box).children.length)renderMode(box,'graph',ctx)});renderMode(box,'graph',ctx)}
  function watch(){const out=$('[data-check-output]');if(!out)return;let t;const run=()=>{clearTimeout(t);t=setTimeout(build,100)};new MutationObserver(ms=>{if(ms.some(m=>{const el=m.target.nodeType===3?m.target.parentElement:m.target;return !el?.closest?.('.ei-decision-lab')}))run()}).observe(out,{subtree:true,childList:true});run()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch,{once:true});else watch();
})();