(()=>{
  const ACTIVE='ei_active_decision';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const money=n=>Number(n)>0?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)):'';
  function loadCss(){if(document.querySelector('link[data-ei-motion]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='/motion.css';l.dataset.eiMotion='';document.head.appendChild(l)}
  function loadExperience(){if(!document.querySelector('link[data-ei-experience-css]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/experience.css';l.dataset.eiExperienceCss='';document.head.appendChild(l)}if(!document.querySelector('script[data-ei-experience-js]')){const s=document.createElement('script');s.src='/experience.js';s.defer=true;s.dataset.eiExperienceJs='';document.head.appendChild(s)}}
  function loadSavings(){if(!location.pathname.startsWith('/screen/'))return;if(!document.querySelector('link[data-ei-savings-css]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/savings.css';l.dataset.eiSavingsCss='';document.head.appendChild(l)}if(!document.querySelector('script[data-ei-savings-js]')){const s=document.createElement('script');s.src='/savings.js';s.defer=true;s.dataset.eiSavingsJs='';document.head.appendChild(s)}if(!document.querySelector('link[data-ei-target-css]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/target-plan.css';l.dataset.eiTargetCss='';document.head.appendChild(l)}if(!document.querySelector('script[data-ei-target-js]')){const s=document.createElement('script');s.src='/target-plan.js';s.defer=true;s.dataset.eiTargetJs='';document.head.appendChild(s)}}
  function read(){try{return JSON.parse(localStorage.getItem(ACTIVE)||'null')}catch(_e){return null}}
  function title(a){return String(a?.title||a?.text||[a?.vehicle?.identity?.year,a?.vehicle?.identity?.make,a?.vehicle?.identity?.model,a?.vehicle?.identity?.trim].filter(Boolean).join(' ')||'Active decision').replace(/\s+/g,' ').trim().slice(0,150)}
  function setIf(id,value,force=false){const el=$(`#${id}`);if(!el||value==null||value==='')return false;const params=new URLSearchParams(location.search);const hasQuery=params.size>0;if(!force&&hasQuery)return false;el.value=String(value);el.dataset.autoFilled='1';return true}
  function addContext(a,anchor){if(!a||!anchor||document.querySelector('.ei-context-note'))return;const note=document.createElement('div');note.className='ei-context-note';note.innerHTML='<div><span>Carried from ExpenseIntel Check</span><br><strong></strong></div><small></small>';note.querySelector('strong').textContent=title(a);note.querySelector('small').textContent=[a.price?money(a.price):'',a.location||'',a.vehicle?.identity?.vin?'VIN-confirmed':''].filter(Boolean).join(' · ')+' · review any assumptions that ExpenseIntel cannot verify';anchor.parentNode.insertBefore(note,anchor)}
  function prefill(a){if(!a)return;const p=new URLSearchParams(location.search);if(p.size)return;let used=false;
    if(document.body.dataset.eiTool==='truecost'||$('#tc-price')){used=setIf('tc-label',title(a))||used;used=setIf('tc-price',a.price)||used;const down=$('#tc-down');if(down&&a.price&&Number(down.value)===8000){down.value=String(Math.round(Number(a.price)*.2/100)*100);down.dataset.autoFilled='1'}addContext(a,$('[data-truecost-form]')||$('.si-panel'))}
    if(document.body.dataset.eiTool==='fairprice'||$('#fp-quote')){used=setIf('fp-label',title(a))||used;used=setIf('fp-quote',a.price)||used;addContext(a,$('[data-fairprice-form]')||$('.si-panel'))}
    if(document.body.dataset.eiTool==='timing'||$('#tm-price')){used=setIf('tm-label',title(a))||used;used=setIf('tm-price',a.price)||used;addContext(a,$('[data-timing-form]')||$('.si-panel'))}
    if(document.body.dataset.eiTool==='shock'||$('#sh-price')){used=setIf('sh-label',title(a))||used;used=setIf('sh-price',a.price)||used;addContext(a,$('[data-shock-form]')||$('.si-panel'))}
    if(used){const form=$('form[data-truecost-form],form[data-fairprice-form],form[data-timing-form],form[data-shock-form]');setTimeout(()=>form?.requestSubmit?.(),80)}
  }
  function dock(a){if(!a||location.pathname==='/'||location.pathname.startsWith('/check/')||document.querySelector('.active-decision-dock'))return;const d=document.createElement('aside');d.className='active-decision-dock';d.setAttribute('aria-label','Active ExpenseIntel decision');d.innerHTML='<div class="ead-copy"><div class="ead-mark">EI</div><div><strong></strong><small></small></div></div><div class="ead-actions"><a class="primary" href="/check/">Check</a><a href="/fairprice/">Fair Price</a><a href="/truecost/">TrueCost</a><a href="/watch/">Watch</a><button type="button" title="Clear active decision">×</button></div>';d.querySelector('strong').textContent=title(a);d.querySelector('small').textContent=[a.price?money(a.price):'',a.location||'',a.category?String(a.category).replace(/-/g,' '):''].filter(Boolean).join(' · ');d.querySelector('button').onclick=()=>{try{localStorage.removeItem(ACTIVE)}catch(_e){}d.remove()};document.body.appendChild(d)}
  function reveal(){if(!('IntersectionObserver'in window))return;const selectors=['main>section','.module','.check-card','.si-panel','.si-results','.check-how-grid article','.check-engine-row a','.price-card','.answer-card','.si-discipline>div'];const els=[...new Set(selectors.flatMap(s=>$$(s)))].filter(el=>!el.closest('[hidden]'));const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('ei-in');io.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -30px'});els.forEach((el,i)=>{el.classList.add('ei-reveal');if(i<2)requestAnimationFrame(()=>el.classList.add('ei-in'));else io.observe(el)})}
  function navMotion(){const nav=$('.site-nav');if(!nav)return;const sync=()=>nav.classList.toggle('ei-scrolled',scrollY>14);sync();addEventListener('scroll',sync,{passive:true})}
  function navTouch(){if(location.pathname!=='/'&&!location.pathname.startsWith('/check/'))return;const c=$('.navright .solidbtn');if(c&&$('#check-form')){c.href='#check-form';c.textContent='Run a check'}}
  function metricMotion(){const target=document.body;const obs=new MutationObserver(ms=>{for(const m of ms){if(m.type!=='childList'&&m.type!=='characterData')continue;const el=m.target.nodeType===3?m.target.parentElement:m.target;if(!el?.matches?.('strong,[data-result-score],#tc-total,#sh-total,#tm-verdict,#fp-verdict'))continue;if(!/[0-9$%]|STRONG|PARTIAL|LIMITED|BUY|WAIT|NEUTRAL/i.test(el.textContent||''))continue;el.classList.remove('ei-metric-pop');void el.offsetWidth;el.classList.add('ei-metric-pop')}});obs.observe(target,{subtree:true,childList:true,characterData:true})}
  function labelAuto(){$$('[data-auto-filled="1"]').forEach(el=>{const label=el.closest('.field')?.querySelector('label');if(label&&!label.querySelector('.ei-source-chip')){const c=document.createElement('span');c.className='ei-source-chip';c.textContent='From Check';label.append(' ',c)}})}
  function keyboard(){addEventListener('keydown',e=>{if(e.key!=='/'||e.metaKey||e.ctrlKey||e.altKey)return;const tag=document.activeElement?.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag))return;const target=$('#check-text,#check-url,#fp-label,#tc-label,#tm-label,#xr-text,#pj-brief-text');if(!target)return;e.preventDefault();target.focus()})}
  function init(){if(document.documentElement.dataset.eiPolishReady==='1')return;document.documentElement.dataset.eiPolishReady='1';loadCss();loadExperience();loadSavings();navTouch();const a=read();prefill(a);dock(a);reveal();navMotion();metricMotion();keyboard();setTimeout(labelAuto,120)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();