(()=>{
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const KEY='ei_property_latest_v2';let latest=null,inflight=null,lastAddress='',useTouched=false,sqftTouched=false;
  const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
  const num=v=>Number.isFinite(Number(v))?Number(v):null;
  const money=n=>num(n)!=null?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(num(n)):'—';
  const pct=n=>num(n)!=null?`${(num(n)*100).toFixed(0)}%`:'—';
  const fmt=n=>num(n)!=null?Math.round(num(n)).toLocaleString():'—';
  const sourceFor=(d,k)=>d?.fieldSources?.[k]?.sourceLabel||'';
  function safeSave(v){try{sessionStorage.setItem(KEY,JSON.stringify(v))}catch(_e){}}
  function safeRead(){try{return JSON.parse(sessionStorage.getItem(KEY)||'null')}catch(_e){return null}}
  function field(form,name){return form.querySelector(`[name="${name}"]`)}
  function showError(form,msg=''){let el=form.querySelector('.screen-error');if(!el){el=document.createElement('div');el.className='screen-error';el.role='alert';form.appendChild(el)}el.textContent=msg;el.classList.toggle('show',!!msg)}
  function freshStart(form){const q=new URLSearchParams(location.search),saved=(()=>{try{return JSON.parse(sessionStorage.getItem('ei_last')||'null')}catch(_e){return null}})(),sq=field(form,'sqft'),use=field(form,'use');if(use&&!use.querySelector('option[value=""]')){const o=document.createElement('option');o.value='';o.textContent='Auto-detect current use';use.prepend(o)}if(!q.has('use')&&!saved?.use&&use)use.value='';if(!q.has('sqft')&&!saved?.sqft&&sq&&String(sq.value)==='7500'){sq.value='';sq.placeholder='Auto-filled after address when records exist'}if(use)use.addEventListener('change',()=>useTouched=true);if(sq)sq.addEventListener('input',()=>{if(!sq.dataset.eiApplying)sqftTouched=true})}
  async function json(url){const r=await fetch(url,{headers:{Accept:'application/json'}}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Property data unavailable');return d}
  async function resolvedLocation(address){const u=new URL('/api/address',location.origin);u.searchParams.set('q',address);const d=await json(u),list=d.suggestions||[];let m=list.find(x=>clean(x.label).toLowerCase()===clean(address).toLowerCase())||(list.length===1?list[0]:list[0]);if(m?.needsDetails&&m.placeId){const d2=await json(`/api/address?placeId=${encodeURIComponent(m.placeId)}`);m=d2.suggestions?.[0]}return m||null}
  async function fetchProperty(address,loc){const u=new URL('/api/property',location.origin),c=loc?.components||{};u.searchParams.set('address',loc?.label||address);[['street',c.street],['city',c.city],['state',c.state],['zip',c.zip],['tract',c.tract],['lat',loc?.coordinates?.lat],['lon',loc?.coordinates?.lon]].forEach(([k,v])=>{if(v!==null&&v!==undefined&&v!=='')u.searchParams.set(k,String(v))});return json(u)}
  function ensurePanel(form){let p=$('.ei-property-intel',form);if(p)return p;p=document.createElement('section');p.className='ei-property-intel';p.innerHTML='<div class="ei-property-head"><div><span>Property facts / auto-fill</span><strong data-pi-title>Waiting for a verified address</strong></div><b data-pi-grade>AUTO</b></div><div class="ei-property-grid" data-pi-grid></div><div class="ei-property-context" data-pi-context hidden></div><details class="ei-property-review"><summary><span>Review / correct property facts</span><b>Optional ↓</b></summary><div class="ei-property-review-grid" data-pi-review></div></details><div class="ei-property-foot"><span data-pi-source>Public record facts stay separate from estimates.</span><strong data-pi-status>ADDRESS FIRST</strong></div>';const sqft=field(form,'sqft')?.closest('.field');(sqft||field(form,'use')?.closest('.field'))?.insertAdjacentElement('afterend',p);return p}
  const fieldDefs=[['squareFootage','Living area',v=>`${fmt(v)} ft²`],['bedrooms','Bedrooms',v=>fmt(v)],['bathrooms','Bathrooms',v=>num(v)?.toFixed(num(v)%1?1:0)||'—'],['yearBuilt','Year built',v=>fmt(v)],['lotSize','Lot size',v=>num(v)>=43560?`${(num(v)/43560).toFixed(2)} ac`:`${fmt(v)} ft²`],['stories','Stories',v=>num(v)?.toFixed(num(v)%1?1:0)||'—'],['roomCount','Rooms',v=>fmt(v)],['style','Style',v=>clean(v)||'—']];
  function renderPanel(form,d){const p=ensurePanel(form),facts=d?.facts||{},grid=$('[data-pi-grid]',p);p.classList.remove('loading');$('[data-pi-title]',p).textContent=d.propertyFound?'Found property-specific facts':'No connected property record yet';$('[data-pi-grade]',p).textContent=`${d.coverage||0}% COVERAGE`;grid.innerHTML='';fieldDefs.forEach(([k,label,format])=>{const v=facts[k],conf=(d.conflicts||[]).some(x=>x.field===k),est=!v&&k==='squareFootage'&&facts.estimatedGrossFloorArea;const card=document.createElement('div');card.className=`ei-property-fact${conf?' conflict':''}${est?' estimate':''}`;const shown=v!=null&&v!==''?format(v):est?`~${fmt(facts.estimatedGrossFloorArea)} gross ft²`:'—',src=v!=null&&v!==''?sourceFor(d,k):est?'OpenStreetMap geometry':'Not in connected record';card.innerHTML='<span></span><strong></strong><small></small>';card.querySelector('span').textContent=label;card.querySelector('strong').textContent=shown;card.querySelector('small').textContent=conf?`Source conflict · ${src}`:src;grid.appendChild(card)});
    const ctx=$('[data-pi-context]',p),c=d.context;if(c){ctx.hidden=false;ctx.innerHTML='<span>Neighborhood context / Census tract — context, not this property</span><div class="ei-property-context-grid"><div><b></b><small>Median home value</small></div><div><b></b><small>Median structure year</small></div><div><b></b><small>Owner occupied</small></div><div><b></b><small>Vacancy</small></div><div><b></b><small>Median household income</small></div><div><b></b><small>Median gross rent</small></div></div>';const vals=[money(c.medianHomeValue),fmt(c.medianYearBuilt),pct(c.ownerOccupancyRate),pct(c.vacancyRate),money(c.medianHouseholdIncome),money(c.medianGrossRent)];$$('.ei-property-context-grid b',ctx).forEach((e,i)=>e.textContent=vals[i])}else ctx.hidden=true;
    const review=$('[data-pi-review]',p);review.innerHTML='';[['bedrooms','Bedrooms'],['bathrooms','Bathrooms'],['yearBuilt','Year built'],['lotSize','Lot size / ft²']].forEach(([k,label])=>{const l=document.createElement('label');l.textContent=label;const i=document.createElement('input');i.type='number';i.step=k==='bathrooms'?'.5':'1';i.min='0';i.name=`property_${k}`;i.value=facts[k]??'';i.placeholder='Unknown';i.addEventListener('input',()=>{latest=latest||d;latest.userCorrections=latest.userCorrections||{};latest.userCorrections[k]=i.value===''?null:Number(i.value);safeSave(latest)});l.appendChild(i);review.appendChild(l)});
    const srcs=(d.sources||[]).map(x=>x.label).join(' + ');$('[data-pi-source]',p).textContent=srcs||'No property-specific source returned; ExpenseIntel did not guess.';$('[data-pi-status]',p).textContent=(d.conflicts||[]).length?`${d.conflicts.length} FIELD${d.conflicts.length===1?'':'S'} TO REVIEW`:d.propertyFound?'AUTO-FILLED WHERE SAFE':'MANUAL FACTS MAY BE NEEDED'}
  function apply(form,d){const facts=d.facts||{},sq=field(form,'sqft'),use=field(form,'use');if(sq&&d.autoFillSafe?.squareFootage&&num(facts.squareFootage)>=300&&!sqftTouched){sq.dataset.eiApplying='1';sq.value=String(Math.round(num(facts.squareFootage)));sq.dataset.autoFilled='1';sq.dataset.propertySource=sourceFor(d,'squareFootage');delete sq.dataset.eiApplying}if(use&&d.suggestedUse&&!useTouched){use.value=d.suggestedUse;use.dataset.autoFilled='1'}renderPanel(form,d)}
  async function enrich(form,force=false){const ai=field(form,'address'),address=clean(ai?.value);if(!address)return null;if(!force&&latest&&lastAddress===address)return latest;if(inflight)return inflight;const p=ensurePanel(form);p.classList.add('loading');$('[data-pi-title]',p).textContent='Reading assessor + property sources…';$('[data-pi-status]',p).textContent='CONNECTING';inflight=(async()=>{try{const loc=await resolvedLocation(address);if(!loc)throw new Error('Choose a verified address first.');const d=await fetchProperty(address,loc);d.location=loc;latest=d;lastAddress=address;safeSave(d);apply(form,d);document.dispatchEvent(new CustomEvent('ei:property-enriched',{detail:d}));return d}catch(e){p.classList.remove('loading');$('[data-pi-title]',p).textContent='Property facts could not be auto-filled';$('[data-pi-source]',p).textContent=e.message||'Property source unavailable';$('[data-pi-status]',p).textContent='NO GUESS USED';return null}finally{inflight=null}})();return inflight}
  function renderResult(d){const full=$('[data-full-result]');if(!full||!d)return;full.querySelector('.ei-property-card')?.remove();const facts={...(d.facts||{}),...(d.userCorrections||{})},card=document.createElement('section');card.className='ei-property-card';const items=[['Living area',facts.squareFootage?`${fmt(facts.squareFootage)} ft²`:'—','squareFootage'],['Bedrooms',facts.bedrooms??'—','bedrooms'],['Bathrooms',facts.bathrooms??'—','bathrooms'],['Year built',facts.yearBuilt??'—','yearBuilt'],['Lot',facts.lotSize?(num(facts.lotSize)>=43560?`${(num(facts.lotSize)/43560).toFixed(2)} ac`:`${fmt(facts.lotSize)} ft²`):'—','lotSize'],['Stories',facts.stories??'—','stories'],['Assessed value',facts.assessedValue?money(facts.assessedValue):'—','assessedValue'],['Last sale',facts.lastSalePrice?money(facts.lastSalePrice):'—','lastSalePrice']];card.innerHTML='<div class="ei-property-card-head"><div><span>Property DNA / verified where available</span><h3>The building behind the cost model.</h3></div><b></b></div><div class="ei-property-card-grid"></div><div class="ei-property-card-note"></div>';card.querySelector('b').textContent=`${d.coverage||0}% FACT COVERAGE`;const grid=$('.ei-property-card-grid',card);items.forEach(([label,value,key])=>{const x=document.createElement('div');x.innerHTML='<span></span><strong></strong><small></small>';x.querySelector('span').textContent=label;x.querySelector('strong').textContent=String(value);x.querySelector('small').textContent=sourceFor(d,key)||((d.userCorrections||{})[key]!=null?'User correction':'Not connected');grid.appendChild(x)});$('.ei-property-card-note',card).textContent='Property-specific records improve the inputs ExpenseIntel knows. Bedrooms, baths, vintage and other facts are not converted into arbitrary cost penalties; they guide diligence and future system-level models unless an authoritative cost relationship is connected.';const banner=$('.result-banner',full);banner?.insertAdjacentElement('afterend',card);const trust=$('[data-trust-building]',full),pill=trust?.parentElement?.querySelector('.source-pill');if(trust){const source=sourceFor(d,'squareFootage')||d.sources?.[0]?.label||'User supplied';trust.textContent=[facts.squareFootage?`${fmt(facts.squareFootage)} ft²`:'',facts.yearBuilt?`built ${facts.yearBuilt}`:'',source].filter(Boolean).join(' · ')}if(pill&&d.propertyFound){pill.textContent='Property record';pill.className='source-pill verified'}}
  function observe(form){const status=form.querySelector('.address-status');if(!status)return;const check=()=>{if(status.classList.contains('verified')&&clean(field(form,'address')?.value)!==lastAddress)enrich(form)};new MutationObserver(check).observe(status,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});check()}
  function bind(){const form=$('[data-screen-form]');if(!form)return;freshStart(form);ensurePanel(form);setTimeout(()=>observe(form),80);const cached=safeRead();if(cached&&clean(cached.address)===clean(field(form,'address')?.value)){latest=cached;lastAddress=clean(field(form,'address')?.value);apply(form,cached)}form.addEventListener('submit',async e=>{if(form.dataset.eiPropertyResubmit==='1'){delete form.dataset.eiPropertyResubmit;return}const sq=num(field(form,'sqft')?.value),use=field(form,'use')?.value;if(sq>=300&&use)return;e.preventDefault();e.stopImmediatePropagation();showError(form,'');const d=await enrich(form,true),sq2=num(field(form,'sqft')?.value),use2=field(form,'use')?.value;if(!(sq2>=300)){showError(form,d?.facts?.estimatedGrossFloorArea?'Verified living area was not available. ExpenseIntel found only a mapped building-area estimate, so confirm the square footage before running the cost model.':'Square footage was not available from the connected property records. Enter the best known living/building area before running the model.');field(form,'sqft')?.focus();return}if(!use2){showError(form,'Property use could not be identified reliably. Choose how the property is used, then run the screen.');field(form,'use')?.focus();return}form.dataset.eiPropertyResubmit='1';form.requestSubmit()},true);document.addEventListener('ei:screen-complete',e=>{if(latest){e.detail.property=latest;renderResult(latest)}})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();