(()=>{
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const KEY='ei_refinement_profile',ACTIVE='ei_active_decision';
  const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const norm=s=>clean(s).toLowerCase().replace(/[^a-z0-9]+/g,'');
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')||{}}catch(_e){return{}}};
  const save=p=>{try{localStorage.setItem(KEY,JSON.stringify({...p,updatedAt:Date.now()}))}catch(_e){}};
  const active=()=>{try{return JSON.parse(localStorage.getItem(ACTIVE)||'null')||{}}catch(_e){return{}}};
  const schemas={
    property:[['propertyType','Property type',['Single-family','Condo','Townhouse','Multi-family','Land','Commercial']],['condition','Condition',['New / recently built','Turnkey','Average','Needs renovation','Major rehab']],['occupancy','Use',['Primary residence','Second home','Investment / rental']],['horizon','Expected hold',['< 3 years','3–7 years','7–15 years','15+ years']]],
    home:[['projectType','Project',['HVAC','Roof','Kitchen','Bathroom','Electrical','Plumbing','Windows / siding','Addition','Foundation','Landscaping','Other']],['scope','Scope',['Repair','Partial replacement','Full replacement','Full renovation']],['quality','Finish level',['Budget','Standard','Premium','Luxury']],['timing','Timing',['Flexible','Within 3 months','Within 30 days','Urgent / emergency']]],
    renovation:[['projectType','Project',['HVAC','Roof','Kitchen','Bathroom','Electrical','Plumbing','Windows / siding','Addition','Foundation','Landscaping','Other']],['scope','Scope',['Repair','Partial replacement','Full replacement','Full renovation']],['quality','Finish level',['Budget','Standard','Premium','Luxury']],['timing','Timing',['Flexible','Within 3 months','Within 30 days','Urgent / emergency']]],
    contractor:[['projectType','Work type',['General construction','HVAC','Electrical','Plumbing','Roofing','Concrete','Excavation','Finish work','Other']],['scope','Scope clarity',['Detailed written scope','Partial scope','Concept / allowance-heavy']],['quality','Spec level',['Basic','Standard','Premium','Custom']],['timing','Schedule',['Flexible','Normal','Accelerated','Emergency']]],
    equipment:[['equipmentType','Equipment class',['Construction','Industrial / manufacturing','HVAC / mechanical','Fleet / vehicle','IT / computing','Medical','Restaurant / hospitality','Other']],['condition','Condition',['New','Used','Refurbished','Lease / rental']],['usage','Expected use',['Light','Moderate','Heavy','Continuous / mission critical']],['horizon','Expected hold',['< 2 years','2–5 years','5–10 years','10+ years']]],
    'business-project':[['projectType','Project type',['Buildout','Expansion','New facility','Relocation','Technology / systems','Equipment installation','Other']],['stage','Stage',['Early concept','Budgeting','Bidding','Contract negotiation','Ready to start']],['scale','Scale',['Small','Medium','Large','Enterprise / multi-site']],['timing','Schedule',['Flexible','Normal','Accelerated','Deadline-critical']]],
    software:[['scale','Users / seats',['1–10','11–50','51–250','251–1,000','1,000+']],['term','Contract term',['Monthly','1 year','2 years','3+ years']],['migration','Migration effort',['None','Light','Moderate','Heavy']],['criticality','Business criticality',['Low','Moderate','High','Mission critical']]],
    education:[['program','Program type',['Undergraduate','Graduate','Professional','Certificate / bootcamp','Other']],['duration','Duration',['< 1 year','1–2 years','3–4 years','5+ years']],['housing','Housing',['Included / known','Separate cost','Living at home']],['funding','Funding',['Cash / family','Loans','Scholarship + cash','Mixed']]],
    travel:[['tripType','Trip type',['Vacation','Business','Wedding / event','International study','Other']],['party','Party size',['1','2','3–4','5+']],['duration','Duration',['1–3 days','4–7 days','1–2 weeks','2+ weeks']],['flexibility','Flexibility',['Fixed dates','Some flexibility','Highly flexible']]],
    other:[['condition','Condition',['New','Used','Refurbished','Not applicable']],['funding','Payment',['Cash','Financed','Subscription / recurring','Mixed']],['horizon','Expected use',['< 1 year','1–3 years','3–7 years','7+ years']]]
  };
  function detectCategory(){const c=$('#check-category')?.value;if(c&&c!=='auto')return c;const t=clean([$('#check-text')?.value,$('#check-url')?.value,active().text,active().title].filter(Boolean).join(' ')).toLowerCase();if(/\b(car|vehicle|truck|suv|sedan|porsche|bmw|mercedes|audi|ford|toyota|honda|lease.*car)\b/.test(t))return'vehicle';if(/\b(condo|house|home purchase|property|real estate|mortgage)\b/.test(t))return'property';if(/\b(renovation|repair|hvac|roof|kitchen|bathroom|plumbing|electrical)\b/.test(t))return'home';if(/\b(equipment|machine|forklift|generator|compressor)\b/.test(t))return'equipment';return'other'}
  async function options(mode,params={}){const u=new URL('/api/refine-options',location.origin);u.searchParams.set('mode',mode);Object.entries(params).forEach(([k,v])=>v&&u.searchParams.set(k,v));const r=await fetch(u,{headers:{Accept:'application/json'}}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Options unavailable');return d.options||[]}
  function selectField(key,label,vals=[],placeholder='Choose…'){return`<div class="ei-refine-field"><label for="ei-ref-${key}">${esc(label)}</label><select id="ei-ref-${key}" data-ref-key="${esc(key)}"><option value="">${esc(placeholder)}</option>${vals.map(v=>`<option value="${esc(typeof v==='string'?v:v.value)}">${esc(typeof v==='string'?v:(v.label||v.value))}</option>`).join('')}</select></div>`}
  function genericFields(cat,p){return(schemas[cat]||schemas.other).map(([key,label,vals])=>selectField(key,label,vals)).join('')}
  function vehicleFields(){return`${selectField('year','Year',[],'Choose year…')}${selectField('make','Make',[],'Choose make…')}${selectField('model','Model / trim',[],'Choose model / trim…')}${selectField('config','Exact configuration',[],'Optional configuration…')}<div class="ei-refine-field"><label for="ei-ref-condition">Condition</label><select id="ei-ref-condition" data-ref-key="condition"><option value="">Choose…</option><option>New</option><option>Certified pre-owned</option><option>Used</option></select></div>`}
  function chips(p,root){const box=$('.ei-refine-summary',root);if(!box)return;const vals=Object.entries(p||{}).filter(([k,v])=>!['category','updatedAt','source'].includes(k)&&v).map(([,v])=>typeof v==='object'?(v.label||v.value||''):v).filter(Boolean);box.innerHTML=vals.slice(0,6).map((v,i)=>`<span class="ei-refine-chip${i===0?' strong':''}">${esc(v)}</span>`).join('')}
  function setOptions(sel,vals,placeholder,selected=''){if(!sel)return;sel.disabled=false;sel.innerHTML=`<option value="">${esc(placeholder)}</option>`+vals.map(v=>`<option value="${esc(typeof v==='string'?v:v.value)}">${esc(typeof v==='string'?v:(v.label||v.value))}</option>`).join('');if(selected&&[...sel.options].some(o=>o.value===selected))sel.value=selected}
  function bestMatch(vals,text){const n=norm(text);let best=null,score=0;for(const v of vals){const label=typeof v==='string'?v:(v.label||v.value),x=norm(label);let s=0;if(n.includes(x)&&x.length>2)s=90+x.length;else if(x.includes(n)&&n.length>2)s=70+n.length;if(s>score){score=s;best=typeof v==='string'?v:v.value}}return best}
  async function hydrateVehicle(root,p){const text=clean([$('#check-text')?.value,$('#tw-title')?.value,active().text,active().title].filter(Boolean).join(' '));const yearSel=$('[data-ref-key="year"]',root),makeSel=$('[data-ref-key="make"]',root),modelSel=$('[data-ref-key="model"]',root),configSel=$('[data-ref-key="config"]',root);const years=await options('years');setOptions(yearSel,years,'Choose year…',p.year||'');if(!yearSel.value){const ym=text.match(/\b(19\d{2}|20\d{2})\b/);if(ym&&[...yearSel.options].some(o=>o.value===ym[1]))yearSel.value=ym[1]}if(!yearSel.value)return;makeSel.disabled=true;const makes=await options('makes',{year:yearSel.value});setOptions(makeSel,makes,'Choose make…',p.make||'');if(!makeSel.value){const m=bestMatch(makes,text);if(m)makeSel.value=m}if(!makeSel.value)return;modelSel.disabled=true;const models=await options('models',{year:yearSel.value,make:makeSel.value});setOptions(modelSel,models,'Choose model / trim…',p.model||'');if(!modelSel.value){const m=bestMatch(models,text);if(m)modelSel.value=m}if(!modelSel.value)return;configSel.disabled=true;const configs=await options('configs',{year:yearSel.value,make:makeSel.value,model:modelSel.value});setOptions(configSel,configs,'Optional configuration…',p.config||'')}
  function currentProfile(root,cat){const p={category:cat,source:'optional refinement'};$$('[data-ref-key]',root).forEach(el=>{if(el.value)p[el.dataset.refKey]=el.value});return p}
  function canonicalVehicle(p){return clean([p.year,p.make,p.model,p.config].filter(Boolean).join(' '))}
  function saveFrom(root,cat){const p=currentProfile(root,cat);save(p);chips(p,root);if(location.pathname.startsWith('/twin/')&&cat==='vehicle'){const title=$('#tw-title'),label=canonicalVehicle(p);if(title&&label){title.value=label;title.dispatchEvent(new Event('input',{bubbles:true}));title.dispatchEvent(new Event('change',{bubbles:true}))}}return p}
  function bindGeneric(root,cat){$$('[data-ref-key]',root).forEach(el=>el.addEventListener('change',()=>saveFrom(root,cat)))}
  function bindVehicle(root){const year=$('[data-ref-key="year"]',root),make=$('[data-ref-key="make"]',root),model=$('[data-ref-key="model"]',root);const refresh=async(level)=>{root.classList.add('ei-v9-loading');try{const p=saveFrom(root,'vehicle');if(level==='year'){setOptions(make,[],'Loading makes…');make.disabled=true;setOptions(model,[],'Choose make first');model.disabled=true;setOptions($('[data-ref-key="config"]',root),[],'Choose model first');$('[data-ref-key="config"]',root).disabled=true;if(year.value){const vals=await options('makes',{year:year.value});setOptions(make,vals,'Choose make…')}}if(level==='make'){setOptions(model,[],'Loading models…');model.disabled=true;setOptions($('[data-ref-key="config"]',root),[],'Choose model first');$('[data-ref-key="config"]',root).disabled=true;if(year.value&&make.value){const vals=await options('models',{year:year.value,make:make.value});setOptions(model,vals,'Choose model / trim…')}}if(level==='model'){const cfg=$('[data-ref-key="config"]',root);setOptions(cfg,[],'Loading configurations…');cfg.disabled=true;if(year.value&&make.value&&model.value){const vals=await options('configs',{year:year.value,make:make.value,model:model.value});setOptions(cfg,vals,'Optional configuration…')}}saveFrom(root,'vehicle')}catch(_e){}finally{root.classList.remove('ei-v9-loading')}};year?.addEventListener('change',()=>refresh('year'));make?.addEventListener('change',()=>refresh('make'));model?.addEventListener('change',()=>refresh('model'));$$('[data-ref-key]',root).filter(x=>![year,make,model].includes(x)).forEach(el=>el.addEventListener('change',()=>saveFrom(root,'vehicle')))}
  async function renderInto(details,cat){const body=$('.ei-refine-body',details),p=read();body.innerHTML=`<div class="ei-refine-intro"><div><strong>${cat==='vehicle'?'Narrow the exact vehicle':'Narrow the assumptions'}</strong><p>${cat==='vehicle'?'Optional. Choose as much as you know; year, make and model/trim materially improve fuel, safety, market and lease assumptions.':'Optional. These fields are added to the decision context so ExpenseIntel can use narrower assumptions without blocking the first answer.'}</p></div><span class="ei-refine-source">${cat==='vehicle'?'EPA / DOE options':'ExpenseIntel context'}</span></div><div class="ei-refine-grid">${cat==='vehicle'?vehicleFields():genericFields(cat,p)}</div><div class="ei-refine-summary"></div>`;if(cat==='vehicle'){try{await hydrateVehicle(details,p)}catch(_e){}bindVehicle(details)}else{bindGeneric(details,cat)}const saved=read();$$('[data-ref-key]',details).forEach(el=>{if(saved.category===cat&&saved[el.dataset.refKey]&&[...el.options].some(o=>o.value===saved[el.dataset.refKey]))el.value=saved[el.dataset.refKey]});chips(read(),details)}
  function makeDetails(cls=''){const d=document.createElement('details');d.className=`ei-refine ${cls}`.trim();d.innerHTML='<summary><div><i></i><b>Refine this decision</b><span>Optional · improves accuracy</span></div></summary><div class="ei-refine-body"></div>';return d}
  function checkRefinement(){const form=$('[data-check-form]');if(!form||$('.ei-refine',form))return;const d=makeDetails();const run=$('.check-run',form);run?.insertAdjacentElement('beforebegin',d);let cat=detectCategory();renderInto(d,cat);const rerender=()=>{const n=detectCategory();if(n!==cat){cat=n;renderInto(d,cat)}};$('#check-category')?.addEventListener('change',rerender);$('#check-text')?.addEventListener('input',()=>setTimeout(rerender,100));$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>setTimeout(rerender,60)))}
  function twinCategory(){const type=$('#tw-type')?.value||'';if(type==='vehicle')return'vehicle';if(type==='lease'){const t=clean([$('#tw-title')?.value,active().title,active().text].join(' ')).toLowerCase();if(/car|vehicle|porsche|bmw|mercedes|audi|ford|toyota|honda/.test(t))return'vehicle';return'other'}return type||'other'}
  function twinRefinement(){const toolbar=$('.twin-toolbar');if(!toolbar||$('.ei-refine-twin'))return;const d=makeDetails('ei-refine-twin');toolbar.insertAdjacentElement('afterend',d);let cat=twinCategory();renderInto(d,cat);const rerender=()=>{const n=twinCategory();if(n!==cat){cat=n;renderInto(d,cat)}};$('#tw-type')?.addEventListener('change',()=>setTimeout(rerender,50));$('#tw-title')?.addEventListener('input',()=>setTimeout(rerender,120))}
  function carried(){if(location.pathname==='/'||location.pathname.startsWith('/check/')||location.pathname.startsWith('/twin/'))return;const p=read(),vals=Object.entries(p).filter(([k,v])=>!['category','updatedAt','source'].includes(k)&&v).map(([,v])=>v);if(!vals.length||$('.ei-refine-carried'))return;const form=$('form,.si-panel,[data-truecost-form],[data-fairprice-form],[data-timing-form],[data-shock-form]');if(!form)return;const x=document.createElement('div');x.className='ei-refine-carried';x.innerHTML=`<div><span>Refinement carried from Check</span><strong>${esc(vals.slice(0,5).join(' · '))}</strong></div><a href="/check/">Edit refinement →</a>`;form.insertAdjacentElement('beforebegin',x)}
  function addRefinementToCheckRequest(){const native=window.fetch.bind(window);if(window.__eiV9Fetch)return;window.__eiV9Fetch=true;window.fetch=async(input,init={})=>{try{const url=typeof input==='string'?input:input?.url||'';if(/\/api\/check(?:\?|$)/.test(url)&&init?.body&&typeof init.body==='string'){const body=JSON.parse(init.body),p=read(),bits=Object.entries(p).filter(([k,v])=>!['category','updatedAt','source'].includes(k)&&v).map(([k,v])=>`${k}: ${v}`);if(bits.length){body.text=clean([body.text,`Optional refinement selections — ${bits.join('; ')}`].filter(Boolean).join('\n'));if((!body.category||body.category==='auto')&&p.category)body.category=p.category;init={...init,body:JSON.stringify(body)}}}}catch(_e){}return native(input,init)}}
  function visualCleanup(){const selectors=['.check-card','.si-panel','.twin-kpi','.price-card','.answer-card','.ei-v12-kpi'];selectors.forEach(s=>$$(s).forEach(x=>x.classList.add('ei-v9-clean-card')));$$('button').forEach(b=>{if(!b.type)b.type='button'});$$('img').forEach(img=>{if(!img.loading)img.loading='lazy'})}
  function init(){addRefinementToCheckRequest();checkRefinement();twinRefinement();carried();visualCleanup();const out=$('[data-check-output]');if(out)new MutationObserver(()=>visualCleanup()).observe(out,{subtree:true,childList:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();