(()=>{
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const KEY='ei_location_actuals_v1';
  const money=n=>Number.isFinite(Number(n))?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)):'—';
  const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
  const num=v=>Number.isFinite(Number(v))?Number(v):0;
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(_e){return{}}};
  const write=v=>{try{localStorage.setItem(KEY,JSON.stringify(v))}catch(_e){}};
  const idFor=r=>[r.address,r.use,r.sqft].map(x=>clean(x).toLowerCase()).join('|');
  const categories=['electric','gas','water','tax','insurance','other'];
  const labels={electric:'Electricity',gas:'Natural gas',water:'Water + sewer',tax:'Property tax',insurance:'Insurance',other:'Waste + other'};

  function savedActuals(r){return read()[idFor(r)]||{}}
  function mergedCosts(r,actual){const out={};categories.forEach(k=>out[k]=num(actual[k])>0?num(actual[k]):num(r.categories?.[k]));return out}
  function total(c){return categories.reduce((s,k)=>s+num(c[k]),0)}
  function controllable(c){return num(c.electric)+num(c.gas)+num(c.water)+num(c.insurance)+num(c.other)}
  function affected(c,keys){return keys.reduce((s,k)=>s+num(c[k]),0)}
  function saveActual(r,k,v){const all=read(),id=idFor(r),row=all[id]||{};if(num(v)>0)row[k]=num(v);else delete row[k];row.updatedAt=new Date().toISOString();all[id]=row;write(all)}

  function useSystems(use){
    const common=[
      {title:'HVAC scheduling + controls',copy:'Tighten occupied hours, setbacks and simultaneous heating/cooling before replacing equipment.',keys:['electric','gas'],low:.05,high:.12},
      {title:'Lighting + controls',copy:'LEDs, occupancy sensing and daylight controls are easiest to screen when lighting hours are long.',keys:['electric'],low:.03,high:.08}
    ];
    const map={
      restaurant:[{title:'Kitchen hood + make-up air controls',copy:'Reduce unnecessary exhaust and conditioned make-up air when cooking load is low.',keys:['electric','gas'],low:.05,high:.14},{title:'Refrigeration tune-up',copy:'Door seals, condenser cleaning, setpoints and anti-sweat controls can target a heavy electric load.',keys:['electric'],low:.05,high:.12},...common],
      retail:[...common,{title:'Envelope + door-loss reduction',copy:'Air curtains, door closers and sealing can reduce heating/cooling loss at high-traffic entrances.',keys:['electric','gas'],low:.03,high:.08}],
      office:[...common,{title:'Plug-load shutdown',copy:'Timers and power-management policies target after-hours computer and equipment loads.',keys:['electric'],low:.02,high:.06}],
      warehouse:[{title:'High-bay lighting + occupancy',copy:'Target long lighting hours and empty aisles before broad equipment replacement.',keys:['electric'],low:.05,high:.14},{title:'Dock-door infiltration control',copy:'Seals, door timing and destratification can reduce heating/cooling leakage.',keys:['electric','gas'],low:.04,high:.10},...common],
      industrial:[{title:'Compressed-air leak program',copy:'Find leaks, lower pressure where feasible and shut idle compressors off.',keys:['electric'],low:.05,high:.15},{title:'Motors + variable-speed drives',copy:'Screen continuously throttled pumps, fans and process motors for speed control.',keys:['electric'],low:.04,high:.12},{title:'Process-heat recovery',copy:'Screen exhaust and hot process streams for reusable heat before adding capacity.',keys:['gas','electric'],low:.04,high:.12}],
      multifamily:[{title:'Common-area HVAC + controls',copy:'Scheduling, reset controls and balancing can target common-area and central-system waste.',keys:['electric','gas'],low:.04,high:.10},{title:'Water-heating efficiency',copy:'Insulation, recirculation controls and fixture flow can reduce both water and heating burden.',keys:['gas','electric','water'],low:.04,high:.10},{title:'Air sealing + weatherization',copy:'Target infiltration before sizing replacement heating or cooling equipment.',keys:['electric','gas'],low:.04,high:.10}],
      residential:[{title:'Air sealing + weatherization',copy:'Reduce infiltration before buying larger HVAC equipment.',keys:['electric','gas'],low:.04,high:.10},{title:'Heat-pump feasibility screen',copy:'Compare actual gas use, electric rate, climate and equipment quotes before switching systems. ExpenseIntel does not assume a heat pump automatically saves money.',keys:['electric','gas'],low:.03,high:.12},{title:'Water-heating upgrade',copy:'Use actual water-heater fuel and hot-water load before choosing heat-pump, gas or resistance equipment.',keys:['gas','electric','water'],low:.03,high:.09}],
      other:common
    };
    return (map[use]||common).slice(0,4)
  }

  function actionIdeas(r,c){
    const actions=[];
    if(c.electric>0)actions.push({key:'electric',title:'Cut electricity use',copy:'Start with schedules, controls and the largest electric end-use. A 10% reduction in this cost layer is shown as a screening target—not a promised efficiency gain.',save:c.electric*.10,tag:'10% usage scenario'});
    if(c.gas>0)actions.push({key:'gas',title:'Cut natural-gas use',copy:'Screen heating schedules, envelope loss, hot-water load and combustion efficiency before changing fuel systems.',save:c.gas*.10,tag:'10% usage scenario'});
    if(c.water>0)actions.push({key:'water',title:'Reduce water + sewer',copy:'Check leaks, fixture flow, irrigation/process use and the actual local tariff. Water savings often reduce sewer charges too, but tariff structure must be verified.',save:c.water*.10,tag:'10% usage scenario'});
    if(c.insurance>0)actions.push({key:'insurance',title:'Re-shop insurance',copy:'Replace the modeled layer with a real premium, then compare equivalent deductibles, limits and exclusions. Do not compare headline premium alone.',save:c.insurance*.10,tag:'10% lower-premium scenario'});
    if(c.other>0)actions.push({key:'other',title:'Rebid waste + recurring service',copy:'Pull recurring vendor charges out of “other,” normalize service frequency and rebid only the like-for-like scope.',save:c.other*.10,tag:'10% lower-service scenario'});
    return actions.sort((a,b)=>b.save-a.save).slice(0,5)
  }

  function render(r){
    const host=$('[data-full-result]');if(!host||!host.classList.contains('show'))return;
    host.querySelector('.ei-savings')?.remove();
    const actual=savedActuals(r),c=mergedCosts(r,actual),cont=controllable(c),t=total(c),share=t?cont/t:0,actions=actionIdeas(r,c),systems=useSystems(r.use);
    const section=document.createElement('section');section.className='ei-savings';
    section.innerHTML=`
      <div class="ei-savings-head"><div><div class="mini-label">ExpenseIntel / Cost Reduction Lab</div><h3>Where can you actually cut this?</h3><p>The cost stack is only useful if it tells you what to do. ExpenseIntel now separates controllable layers from harder-to-change costs, lets you replace modeled values with real bills, and tests provider/system scenarios without pretending a quote exists.</p></div><aside><div><span>Controllable share</span><strong data-save-share>${Math.round(share*100)}%</strong></div><div><span>10% controllable scenario</span><strong data-save-ten>${money(cont*.10)}/yr</strong></div></aside></div>
      <div class="ei-savings-tabs" role="tablist"><button type="button" class="active" data-save-tab="actions">Best moves</button><button type="button" data-save-tab="systems">System changes</button><button type="button" data-save-tab="switch">Test a switch</button></div>
      <div class="ei-savings-panel active" data-save-panel="actions">
        <div class="ei-save-overview"><div class="ei-save-metric"><span>Modeled controllable spend</span><strong data-save-cont>${money(cont)}</strong><p>Electricity, gas, water, insurance and other recurring operating layers. Property tax is excluded from this number because it is not normally an operating lever.</p></div><div class="ei-target"><div class="ei-target-top"><div><span class="mini-label">What-if target</span><strong><span data-target-pct>10</span>% cut</strong></div><small>Scenario only · not a forecast</small></div><input type="range" min="5" max="25" step="1" value="10" data-save-slider><div class="ei-target-scale"><span>5%</span><span>15%</span><span>25%</span></div><div class="ei-target-output"><div><span>Annual savings</span><strong data-target-year>${money(cont*.10)}</strong></div><div><span>3-year run-rate impact</span><strong data-target-three>${money(cont*.10*3)}</strong></div></div></div></div>
        <div class="ei-action-list" data-action-list></div>
      </div>
      <div class="ei-savings-panel" data-save-panel="systems"><div class="ei-system-head"><div><span>System-level ideas</span><h4>Change the load before changing the building.</h4></div><p>These are screening scenarios tied to the cost layers already on this property. The dollar ranges show what a stated reduction in the affected layer would be worth; they are not engineering-audit savings claims.</p></div><div class="ei-system-grid" data-system-grid></div></div>
      <div class="ei-savings-panel" data-save-panel="switch"><div class="ei-switch-grid"><div class="ei-switch-card"><span>Electric provider / tariff test</span><h4>Would a lower electric rate matter?</h4><p>${r.energy?.electricity?.centsKwh?`EIA state end-use benchmark: ${num(r.energy.electricity.centsKwh).toFixed(2)}¢/kWh. `:''}Enter the all-in rate on your actual bill and a real competing all-in offer. Delivery/supply structure can differ, so ExpenseIntel compares the rates you enter rather than naming a provider it cannot verify.</p><div class="ei-switch-fields"><label>Current all-in ¢/kWh<input inputmode="decimal" data-elec-current placeholder="Current bill rate"></label><label>New all-in ¢/kWh<input inputmode="decimal" data-elec-offer placeholder="Verified offer"></label></div><div class="ei-switch-result" data-elec-result><strong>Enter two real rates</strong><small>Uses ${r.electricUsage?Math.round(r.electricUsage).toLocaleString()+' modeled kWh/year':'the modeled electricity spend'} to estimate the difference.</small></div></div><div class="ei-switch-card"><span>Natural-gas provider / tariff test</span><h4>Would a lower gas rate matter?</h4><p>${r.energy?.gas?.dollarsMcf?`EIA state end-use benchmark: $${num(r.energy.gas.dollarsMcf).toFixed(2)}/Mcf. `:''}Enter your real all-in gas rate and a real competing rate. ExpenseIntel will show the math but will not claim a supplier or tariff is available without a verified offer.</p><div class="ei-switch-fields"><label>Current $/Mcf<input inputmode="decimal" data-gas-current placeholder="Current bill rate"></label><label>New $/Mcf<input inputmode="decimal" data-gas-offer placeholder="Verified offer"></label></div><div class="ei-switch-result" data-gas-result><strong>Enter two real rates</strong><small>Uses ${r.gasUsage?Math.round(r.gasUsage).toLocaleString()+' modeled Mcf/year':'the modeled gas spend'} to estimate the difference.</small></div></div></div></div>
      <details class="ei-actuals"><summary><span>Make this more accurate with your real bills</span><b>Optional · replaces modeled layers only where you enter data ↓</b></summary><div class="ei-actuals-grid"></div><div class="ei-adjusted"><div><span>Adjusted annual cost</span><strong data-adjusted-total>${money(t)}</strong></div><div><span>Real layers supplied</span><strong data-actual-count>${Object.keys(actual).filter(k=>num(actual[k])>0).length} / 6</strong></div></div></details>
      <div class="ei-savings-foot"><strong>HOW TO READ THIS:</strong> “Modeled” means ExpenseIntel is applying the existing building/use model. “Scenario” means a transparent what-if percentage. “Real” means you entered the bill, premium or provider offer yourself. System-switch ideas are screening prompts until actual equipment, load, climate, tariff and installation data are known.</div>`;
    const anchor=$('.forecast-strip',host)||$('.cost-stack',host);anchor?.insertAdjacentElement('afterend',section);

    const list=$('[data-action-list]',section);actions.forEach((a,i)=>{const card=document.createElement('article');card.className=`ei-action-card${i===0?' best':''}`;card.innerHTML=`<span>${i===0?'Highest modeled opportunity':labels[a.key]}</span><h4>${a.title}</h4><strong>${money(a.save)}/yr</strong><p>${a.copy}</p><small>${a.tag} · based on the current ${labels[a.key].toLowerCase()} layer</small>`;list.appendChild(card)});
    if(c.tax>0){const card=document.createElement('article');card.className='ei-action-card';card.innerHTML=`<span>Property tax</span><h4>Verify assessment + exemptions</h4><strong>No fake savings estimate</strong><p>ExpenseIntel should not assume a successful appeal or exemption. Replace the modeled tax layer with the parcel bill, then verify assessed value, classification and eligible exemptions.</p><small>Verification action · savings withheld until parcel data exists</small>`;list.appendChild(card)}

    const sg=$('[data-system-grid]',section);systems.forEach(s=>{const base=affected(c,s.keys),lo=base*s.low,hi=base*s.high,card=document.createElement('article');card.className='ei-system-card';card.innerHTML=`<h5>${s.title}</h5><p>${s.copy}</p><div class="impact"><strong>${money(lo)}–${money(hi)}/yr</strong><span>if the affected modeled layer falls ${Math.round(s.low*100)}–${Math.round(s.high*100)}%</span></div>`;sg.appendChild(card)});

    const slider=$('[data-save-slider]',section),syncSlider=()=>{const p=num(slider.value)/100;$('[data-target-pct]',section).textContent=String(Math.round(p*100));$('[data-target-year]',section).textContent=money(controllable(mergedCosts(r,savedActuals(r)))*p);$('[data-target-three]',section).textContent=money(controllable(mergedCosts(r,savedActuals(r)))*p*3)};slider.addEventListener('input',syncSlider);
    $$('[data-save-tab]',section).forEach(b=>b.onclick=()=>{$$('[data-save-tab]',section).forEach(x=>x.classList.toggle('active',x===b));$$('[data-save-panel]',section).forEach(p=>p.classList.toggle('active',p.dataset.savePanel===b.dataset.saveTab))});

    const ag=$('.ei-actuals-grid',section);categories.forEach(k=>{const lab=document.createElement('label');lab.textContent=`Annual ${labels[k]}`;const input=document.createElement('input');input.type='number';input.min='0';input.step='1';input.placeholder=`Model ${money(r.categories?.[k])}`;input.value=num(actual[k])>0?String(actual[k]):'';input.addEventListener('input',()=>{saveActual(r,k,input.value);refresh()});lab.appendChild(input);ag.appendChild(lab)});

    function refresh(){const a=savedActuals(r),m=mergedCosts(r,a),ct=controllable(m),tt=total(m);$('[data-save-share]',section).textContent=`${Math.round((tt?ct/tt:0)*100)}%`;$('[data-save-ten]',section).textContent=`${money(ct*.10)}/yr`;$('[data-save-cont]',section).textContent=money(ct);$('[data-adjusted-total]',section).textContent=money(tt);$('[data-actual-count]',section).textContent=`${Object.keys(a).filter(k=>num(a[k])>0).length} / 6`;syncSlider();const newActions=actionIdeas(r,m);list.innerHTML='';newActions.forEach((x,i)=>{const card=document.createElement('article');card.className=`ei-action-card${i===0?' best':''}`;card.innerHTML=`<span>${i===0?'Highest modeled opportunity':labels[x.key]}</span><h4>${x.title}</h4><strong>${money(x.save)}/yr</strong><p>${x.copy}</p><small>${x.tag} · ${num(a[x.key])>0?'uses your real annual cost':'uses the current modeled layer'}</small>`;list.appendChild(card)});if(m.tax>0){const card=document.createElement('article');card.className='ei-action-card';card.innerHTML='<span>Property tax</span><h4>Verify assessment + exemptions</h4><strong>No fake savings estimate</strong><p>ExpenseIntel does not assume an appeal succeeds. Verify the parcel bill, assessment and eligible exemptions first.</p><small>Verification action</small>';list.appendChild(card)};sg.innerHTML='';useSystems(r.use).forEach(s=>{const base=affected(m,s.keys),card=document.createElement('article');card.className='ei-system-card';card.innerHTML=`<h5>${s.title}</h5><p>${s.copy}</p><div class="impact"><strong>${money(base*s.low)}–${money(base*s.high)}/yr</strong><span>if affected layer falls ${Math.round(s.low*100)}–${Math.round(s.high*100)}%</span></div>`;sg.appendChild(card)})}

    const eCur=$('[data-elec-current]',section),eOff=$('[data-elec-offer]',section),eRes=$('[data-elec-result]',section);function electricTest(){const cur=num(eCur.value),off=num(eOff.value);if(!(cur>0&&off>0)){eRes.innerHTML=`<strong>Enter two real rates</strong><small>${r.energy?.electricity?.centsKwh?`EIA benchmark ${num(r.energy.electricity.centsKwh).toFixed(2)}¢/kWh is reference only.`:'No current benchmark is available.'}</small>`;return}let usage=num(r.electricUsage);if(!usage&&num(r.categories?.electric)>0&&num(r.energy?.electricity?.centsKwh)>0)usage=num(r.categories.electric)/(num(r.energy.electricity.centsKwh)/100);if(!usage){eRes.innerHTML='<strong>Usage still needed</strong><small>ExpenseIntel cannot convert the rate difference into annual dollars without a kWh estimate or bill history.</small>';return}const diff=usage*(cur-off)/100;eRes.innerHTML=`<strong>${diff>=0?money(diff)+' / yr lower':money(Math.abs(diff))+' / yr higher'}</strong><small>${Math.round(usage).toLocaleString()} kWh modeled annual use × ${Math.abs(cur-off).toFixed(2)}¢/kWh rate difference. Confirm all-in bill components before switching.</small>`}eCur.addEventListener('input',electricTest);eOff.addEventListener('input',electricTest);
    const gCur=$('[data-gas-current]',section),gOff=$('[data-gas-offer]',section),gRes=$('[data-gas-result]',section);function gasTest(){const cur=num(gCur.value),off=num(gOff.value);if(!(cur>0&&off>0)){gRes.innerHTML=`<strong>Enter two real rates</strong><small>${r.energy?.gas?.dollarsMcf?`EIA benchmark $${num(r.energy.gas.dollarsMcf).toFixed(2)}/Mcf is reference only.`:'No current benchmark is available.'}</small>`;return}let usage=num(r.gasUsage);if(!usage&&num(r.categories?.gas)>0&&num(r.energy?.gas?.dollarsMcf)>0)usage=num(r.categories.gas)/num(r.energy.gas.dollarsMcf);if(!usage){gRes.innerHTML='<strong>Usage still needed</strong><small>ExpenseIntel cannot convert the rate difference into annual dollars without a gas-use estimate or bill history.</small>';return}const diff=usage*(cur-off);gRes.innerHTML=`<strong>${diff>=0?money(diff)+' / yr lower':money(Math.abs(diff))+' / yr higher'}</strong><small>${Math.round(usage).toLocaleString()} Mcf modeled annual use × $${Math.abs(cur-off).toFixed(2)}/Mcf rate difference. Confirm fixed charges and tariff structure before switching.</small>`}gCur.addEventListener('input',gasTest);gOff.addEventListener('input',gasTest);
  }

  document.addEventListener('ei:screen-complete',e=>render(e.detail));
})();