(()=>{
 const $=(s,r=document)=>r.querySelector(s), money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)||0), pct=n=>Number.isFinite(Number(n))?`${Number(n)>=0?'+':''}${(Number(n)*100).toFixed(1)}%`:'—';
 function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
 async function json(url){const r=await fetch(url,{headers:{Accept:'application/json'}}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||d.errors?.[0]||'Connected data unavailable');return d}
 function signalValue(s){if(s.type==='rate')return s.value==null?'—':`${Number(s.value).toFixed(2)}%`;if(s.type==='percent_change')return s.value==null?'—':`${Number(s.value)>=0?'+':''}${Number(s.value).toFixed(2)}%`;if(s.type==='fuel_price')return s.value==null?'—':s.unit==='$/kWh'?`$${Number(s.value).toFixed(3)}/kWh`:`$${Number(s.value).toFixed(2)}/gal`;if(s.type==='state_energy')return s.value==null?'—':`${Number(s.value).toFixed(2)}¢/kWh`;return s.value==null?'—':Number(s.value).toFixed(2)}
 function signalNote(s){if(s.type==='price_index')return `${s.period||''}${s.yoy!=null?` · ${pct(s.yoy)} YoY`:''}`;if(s.type==='percent_change')return `${s.period||''}${s.quarterChange!=null?` · ${Number(s.quarterChange)>=0?'+':''}${Number(s.quarterChange).toFixed(2)}% q/q`:''}`;return s.period||''}
 function ensureContext(after){let el=$('[data-live-context]');if(el)return el;el=document.createElement('section');el.className='si-live-context';el.dataset.liveContext='1';el.innerHTML='<div class="si-live-head"><div><span>Connected evidence</span><strong>Loading public signals…</strong></div><b>LIVE</b></div><div class="si-live-grid" data-live-grid></div><div class="si-live-foot" data-live-foot>Observed evidence only. No forecast or fair-price claim is implied.</div>';after?.insertAdjacentElement('afterend',el);return el}
 function renderContext(d,after){const el=ensureContext(after),grid=$('[data-live-grid]',el),head=$('.si-live-head strong',el),foot=$('[data-live-foot]',el);if(head)head.textContent=`${d.sourceCount||0} authoritative source${d.sourceCount===1?'':'s'} · ${d.coverageScore||0}% connected coverage`;const sig=(d.signals||[]).filter(s=>s.value!=null).slice(0,10);if(grid)grid.innerHTML=sig.length?sig.map(s=>`<article><span>${esc(s.label)}</span><strong>${esc(signalValue(s))}</strong><small>${esc(signalNote(s))}</small><em>${esc(s.source||'Public source')}</em></article>`).join(''):'<article class="wide"><span>Coverage</span><strong>No connected signal returned</strong><small>The model will continue using explicit user inputs rather than inventing data.</small></article>';if(foot)foot.textContent=`Observed public evidence only · ${d.methodology?.rule||'signals remain separate from modeled assumptions.'}`;return el}
 async function loadDecisionContext({q='',category='other',location=''}={},after){const el=ensureContext(after);try{return renderContext(await json(`/api/decision-context?${new URLSearchParams({q,category,location})}`),after)}catch(e){const h=$('.si-live-head strong',el),g=$('[data-live-grid]',el);if(h)h.textContent='Connected evidence temporarily unavailable';if(g)g.innerHTML=`<article class="wide"><span>Fallback</span><strong>User-input model remains available</strong><small>${esc(e.message)}</small></article>`;return el}}
 function bindAsk(){const form=$('[data-spend-search]');if(!form)return;form.addEventListener('submit',()=>{const q=$('#spend-query')?.value||'',category=$('#spend-category')?.value||'other',location=$('#spend-location')?.value||'',brief=$('[data-spend-brief]');setTimeout(()=>loadDecisionContext({q,category,location},brief),0)})}
 function pageParams(){const p=new URLSearchParams(location.search);return{q:p.get('q')||'',category:p.get('category')||'other',location:p.get('location')||''}}
 function bindToolContext(){if($('[data-spend-search]'))return;const anchor=$('.si-panel')||$('.si-results')||$('.platform-hero');if(!anchor)return;const p=pageParams();loadDecisionContext(p,anchor)}
 function vehiclePanel(){const form=$('[data-truecost-form]');if(!form)return;const p=pageParams();if(p.category!=='vehicle'&&!/\b(19|20)\d{2}\b/.test(p.q))return;const body=$('.si-panel-body',form);if(!body)return;const panel=document.createElement('div');panel.className='si-vehicle-panel';panel.innerHTML=`<div class="si-vehicle-title"><div><span>Vehicle intelligence</span><strong>NHTSA + FuelEconomy.gov</strong></div><b>OFFICIAL DATA</b></div><div class="si-grid2"><div class="field"><label>Model year</label><input class="input" data-v-year type="number" min="1984" max="2030" placeholder="2026"></div><div class="field"><label>Make</label><input class="input" data-v-make placeholder="Ford"></div><div class="field"><label>Model</label><input class="input" data-v-model placeholder="F-150"></div><div class="field"><label>VIN (optional)</label><input class="input" data-v-vin maxlength="17" placeholder="Decode exact vehicle"></div><div class="field"><label>Annual miles</label><input class="input" data-v-miles type="number" min="0" step="500" value="12000"></div></div><button class="si-data-btn" type="button" data-v-load><span>Load official vehicle data</span><span>→</span></button><div class="si-vehicle-result" data-v-result></div>`;
  body.insertBefore(panel,body.firstChild);const yearMatch=p.q.match(/\b((?:19|20)\d{2})\b/);if(yearMatch)$('[data-v-year]',panel).value=yearMatch[1];
  $('[data-v-load]',panel).addEventListener('click',async()=>{const btn=$('[data-v-load]',panel),out=$('[data-v-result]',panel),year=$('[data-v-year]',panel).value,make=$('[data-v-make]',panel).value.trim(),model=$('[data-v-model]',panel).value.trim(),vin=$('[data-v-vin]',panel).value.trim(),miles=Math.max(0,Number($('[data-v-miles]',panel).value)||12000);btn.disabled=true;btn.firstElementChild.textContent='Loading NHTSA + EPA data…';try{const d=await json(`/api/vehicle-context?${new URLSearchParams({year,make,model,vin})}`),sum=d.vehicleFuel?.summary,decoded=d.decoded&&!d.decoded.error?d.decoded:null,opts=d.vehicleFuel?.options||[],fuelRange=sum?.annualFuelCost;let scaled=null;if(fuelRange?.median!=null)scaled=fuelRange.median*(miles/15000);const mpg=sum?.combinedMpg;out.classList.add('show');out.innerHTML=`<div class="si-v-facts"><div><span>Vehicle</span><strong>${esc(decoded?`${decoded.year} ${decoded.make} ${decoded.model}`:`${year} ${make} ${model}`)}</strong><small>${decoded?esc([decoded.trim,decoded.bodyClass,decoded.driveType].filter(Boolean).join(' · ')):`${opts.length} EPA configuration${opts.length===1?'':'s'} found`}</small></div><div><span>Combined MPG range</span><strong>${mpg?`${mpg.min}–${mpg.max}`:'—'}</strong><small>EPA / DOE configurations</small></div><div><span>Annual fuel estimate</span><strong>${scaled!=null?money(scaled):fuelRange?`${money(fuelRange.min)}–${money(fuelRange.max)}`:'—'}</strong><small>${scaled!=null?`${miles.toLocaleString()} mi/yr scaled from EPA annual estimate`:'EPA standard-use estimate'}</small></div><div><span>Connected vehicle layers</span><strong>${Object.values(d.coverage||{}).filter(Boolean).length}/4</strong><small>VIN identity · EPA economy · fuel price · BLS</small></div></div><div class="si-v-actions">${scaled!=null?'<button type="button" data-use-fuel>Use fuel estimate in TrueCost</button>':''}<span>Purchase price, insurance and depreciation are not invented where no verified feed exists.</span></div>`;if(scaled!=null)$('[data-use-fuel]',out)?.addEventListener('click',()=>{const annual=$('#tc-annual');if(annual){annual.value=String(Math.round(scaled));form.requestSubmit()}})}catch(e){out.classList.add('show');out.innerHTML=`<div class="si-data-error">${esc(e.message)}</div>`}finally{btn.disabled=false;btn.firstElementChild.textContent='Load official vehicle data'}})
 }
 function timingTrendAssist(){const form=$('[data-timing-form]');if(!form)return;const p=pageParams(),anchor=$('.si-panel',form)||form;json(`/api/decision-context?${new URLSearchParams(p)}`).then(d=>{let target;if(p.category==='vehicle')target=(d.signals||[]).find(s=>s.type==='price_index'&&/new vehicles|used cars/i.test(s.label));else if(p.category==='home'||p.category==='property')target=(d.signals||[]).find(s=>s.type==='percent_change');else target=(d.signals||[]).find(s=>s.type==='price_index');if(!target)return;const observed=target.type==='percent_change'?Number(target.value):target.yoy!=null?Number(target.yoy)*100:null;if(!Number.isFinite(observed))return;const box=document.createElement('div');box.className='si-trend-assist';box.innerHTML=`<div><span>Observed market trend</span><strong>${esc(target.label)} ${observed>=0?'+':''}${observed.toFixed(1)}%</strong><small>${esc(target.period||'')} · ${esc(target.source||'public source')}</small></div><button type="button">Use as scenario assumption</button>`;anchor.insertAdjacentElement('afterend',box);box.querySelector('button').addEventListener('click',()=>{const input=$('#tm-change');if(input){input.value=observed.toFixed(1);form.requestSubmit();box.querySelector('button').textContent='Copied as scenario ✓'}})}).catch(()=>{})}
 document.addEventListener('DOMContentLoaded',()=>{bindAsk();bindToolContext();vehiclePanel();timingTrendAssist()});
})();