(()=>{
  const $=(s,r=document)=>r.querySelector(s);
  const WATCH='ei_spend_watch';
  const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)||0);
  const read=()=>{try{return JSON.parse(localStorage.getItem(WATCH)||'[]')}catch(_e){return[]}};
  const write=v=>{try{localStorage.setItem(WATCH,JSON.stringify(v))}catch(_e){}};
  function render(){const list=$('[data-spend-watch-list]'),empty=$('[data-spend-watch-empty]'),count=$('[data-spend-watch-count]');if(!list)return;const items=read();list.innerHTML='';if(count)count.textContent=String(items.length);if(empty)empty.style.display=items.length?'none':'grid';items.forEach(item=>{const base=Number(item.baseline)||0,current=Number(item.current)||0,delta=current&&base?current-base:null,pct=delta!=null&&base?delta/base*100:null,card=document.createElement('article');card.className='watch-card';card.innerHTML=`<div class="watch-head"><div><span>${item.type||'Decision'} · ${item.id||'Saved'}</span><strong></strong></div><div><span>Saved</span><b></b></div></div><div class="watch-grid" style="grid-template-columns:1.4fr 1fr 1fr 1fr"><div class="watch-cell"><span>Saved baseline</span><strong>${base?money(base):'—'}</strong></div><div class="watch-cell"><span>Reference</span><strong>${item.reference?money(item.reference):item.sticker?money(item.sticker):'—'}</strong></div><div class="watch-cell"><span>Current observed price</span><strong>${current?money(current):'Not updated'}</strong></div><div class="watch-cell"><span>Change vs baseline</span><strong class="${delta>0?'signal-up':delta<0?'signal-down':'signal-flat'}">${delta==null?'—':`${delta>=0?'+':''}${money(delta)} (${pct>=0?'+':''}${pct.toFixed(1)}%)`}</strong></div></div><div class="watch-change"><span>${delta==null?'Awaiting an updated observation':Math.abs(pct||0)>=2?'Meaningful change entered':'Small change entered'}</span><p>${item.note||'Saved decision baseline.'} Enter a current observed price when you revisit the decision. ExpenseIntel compares it with the saved baseline; this browser-local beta does not claim background monitoring for unsupported markets.</p></div><div class="watch-actions"><small>${item.type||'Decision'} · browser-local baseline</small><div class="watch-buttons"><input aria-label="Current observed price" type="number" min="0" step="10" placeholder="Current price" value="${current||''}" style="width:150px;border:1px solid var(--ink);background:var(--white);padding:9px;font:800 9px var(--mono)"><button type="button" data-update>Update</button><button type="button" data-remove>Remove</button></div></div>`;card.querySelector('.watch-head strong').textContent=item.label||'Saved decision';card.querySelector('.watch-head b').textContent=item.savedAt?new Date(item.savedAt).toLocaleDateString():'—';card.querySelector('[data-update]').onclick=()=>{const value=Number(card.querySelector('input').value)||0;const arr=read();const hit=arr.find(x=>x.id===item.id);if(hit){hit.current=value;hit.currentUpdatedAt=new Date().toISOString();write(arr);render()}};card.querySelector('[data-remove]').onclick=()=>{write(read().filter(x=>x.id!==item.id));render()};list.appendChild(card)});
  }
  document.addEventListener('DOMContentLoaded',()=>{$('[data-spend-watch-clear]')?.addEventListener('click',()=>{if(confirm('Clear saved spending-decision baselines from this browser?')){write([]);render()}});render()});
})();