(()=>{
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const num=(id,def=0)=>{const el=$(`#${id}`);const n=Number(el?.value);return Number.isFinite(n)?n:def};
  const text=id=>String($(`#${id}`)?.value||'').trim();
  const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)||0);
  const pct=n=>`${(Number(n)||0).toFixed(1)}%`;
  const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
  const WATCH='ei_spend_watch';
  const readWatch=()=>{try{return JSON.parse(localStorage.getItem(WATCH)||'[]')}catch(_e){return[]}};
  const writeWatch=v=>{try{localStorage.setItem(WATCH,JSON.stringify(v))}catch(_e){}};
  const id=()=>`EI-${Date.now().toString(36).toUpperCase()}`;
  function payment(principal,apr,years){const months=Math.max(1,Math.round(years*12)),r=Math.max(0,apr)/100/12;if(!r)return principal/months;return principal*r*Math.pow(1+r,months)/(Math.pow(1+r,months)-1)}
  function interestPaid(principal,apr,termYears,horizonYears){principal=Math.max(0,principal);if(!principal||!termYears)return 0;const months=Math.min(Math.round(termYears*12),Math.round(horizonYears*12)),r=Math.max(0,apr)/100/12,p=payment(principal,apr,termYears);let balance=principal,interest=0;for(let i=0;i<months;i++){const part=balance*r;interest+=part;balance=Math.max(0,balance-(p-part))}return interest}
  function set(id,value){const el=$(`#${id}`);if(el)el.textContent=value}
  function receipt(rows,total){const box=$('[data-receipt]');if(!box)return;box.innerHTML=`<h3>Future Receipt</h3>${rows.map(([k,v])=>`<div class="si-receipt-row"><span>${k}</span><b>${money(v)}</b></div>`).join('')}<div class="si-receipt-row total"><span>True expense</span><b>${money(total)}</b></div>`}
  function watchButton(payload){const btn=$('[data-save-watch]');if(!btn)return;btn.onclick=()=>{const arr=readWatch();arr.unshift({id:id(),savedAt:new Date().toISOString(),...payload()});writeWatch(arr.slice(0,40));btn.textContent='Saved to Change Watch ✓';setTimeout(()=>btn.textContent='Save to Change Watch',1800)}
  function initSearch(){const form=$('[data-spend-search]');if(!form)return;const routes={truecost:'/truecost/',fairprice:'/fairprice/',timing:'/timing/',shock:'/shock/',map:'/expense-map/',project:'/project/',xray:'/xray/'};
    function classify(q,category){q=q.toLowerCase();if(/quote|bid|estimate|contractor|proposal|invoice|price fair|overpay/.test(q))return['fairprice','Fair Price'];if(/wait|buy now|timing|sale|discount|rate drop|incentive/.test(q))return['timing','Wait or Buy'];if(/move|city|zip|where|location|market|relocat/.test(q))return['map','Expense Map'];if(/build|lease|warehouse|restaurant|site|property|permit|utility|project/.test(q))return['project','Project Lab'];if(/bill|lease sheet|document|budget|upload/.test(q))return['xray','X-Ray'];if(/hidden|surprise|shock|underestimate/.test(q))return['shock','Cost Shock'];if(category==='property'||category==='business-project')return['project','Project Lab'];return['truecost','TrueCost']}
    form.addEventListener('submit',e=>{e.preventDefault();const q=text('spend-query'),cat=text('spend-category'),amount=num('spend-amount'),location=text('spend-location'),horizon=num('spend-horizon',5),[key,label]=classify(q,cat);const brief=$('[data-spend-brief]');brief?.classList.add('show');set('brief-title',q||'Your spending decision');set('brief-route',label);set('brief-amount',amount?money(amount):'Add price in next step');set('brief-location',location||'No location supplied');set('brief-horizon',`${horizon} year${horizon===1?'':'s'}`);const link=$('[data-brief-link]');if(link){const params=new URLSearchParams({q,category:cat,amount:String(amount||''),location,horizon:String(horizon)});link.href=`${routes[key]}?${params}`;link.textContent=`Open ${label} →`}try{sessionStorage.setItem('ei_last_spend_query',JSON.stringify({q,cat,amount,location,horizon,key}))}catch(_e){}})
  }
  function initTrueCost(){const form=$('[data-truecost-form]');if(!form)return;let last=null;const q=new URLSearchParams(location.search);if(q.get('amount'))$('#tc-price').value=q.get('amount');if(q.get('horizon'))$('#tc-years').value=q.get('horizon');if(q.get('q'))$('#tc-label').value=q.get('q');
    const run=e=>{e?.preventDefault();const label=text('tc-label')||'Purchase',price=num('tc-price'),down=clamp(num('tc-down'),0,price),apr=num('tc-apr'),term=num('tc-term',5),upfront=num('tc-upfront'),monthly=num('tc-monthly'),annual=num('tc-annual'),years=Math.max(.25,num('tc-years',5)),resale=num('tc-resale');const financed=Math.max(0,price-down),interest=interestPaid(financed,apr,term,years),recurring=monthly*12*years+annual*years,trueCost=Math.max(0,price-resale+interest+upfront+recurring),burden=trueCost-price;last={label,price,trueCost,burden};set('tc-total',money(trueCost));set('tc-burden',`${burden>=0?'+':''}${money(burden)}`);set('tc-yearly',money(trueCost/years));set('tc-interest',money(interest));set('tc-verdict',burden>price*.5?'The sticker price hides a large ownership burden.':burden>0?'The all-in cost is meaningfully above the purchase price.':'Resale value offsets much of the carrying cost.');receipt([['Purchase price',price],['Financing interest',interest],['Upfront fees',upfront],['Recurring costs',recurring],['Expected resale / recovery',-resale]],trueCost)};form.addEventListener('submit',run);watchButton(()=>({type:'TrueCost',label:last?.label||text('tc-label')||'Purchase',baseline:last?.trueCost||0,sticker:last?.price||num('tc-price'),note:'Saved all-in cost baseline'}));run()}
  function initFairPrice(){const form=$('[data-fairprice-form]');if(!form)return;let last=null;const q=new URLSearchParams(location.search);if(q.get('amount'))$('#fp-quote').value=q.get('amount');if(q.get('q'))$('#fp-label').value=q.get('q');const run=e=>{e?.preventDefault();const label=text('fp-label')||'Quote',quote=num('fp-quote'),low=num('fp-low'),high=num('fp-high'),comp1=num('fp-comp1'),comp2=num('fp-comp2'),comp3=num('fp-comp3'),scope=clamp(num('fp-scope',100),1,100);const comps=[comp1,comp2,comp3].filter(x=>x>0);let center=low>0&&high>=low?(low+high)/2:(comps.length?comps.reduce((a,b)=>a+b,0)/comps.length:quote);let lo=low>0?low:(comps.length?Math.min(...comps):center*.9),hi=high>0?high:(comps.length?Math.max(...comps):center*1.1);if(hi<lo)[lo,hi]=[hi,lo];const adjusted=quote/(scope/100),position=center?((adjusted-center)/center)*100:0;let verdict='Within supplied benchmark';if(adjusted<lo)verdict='Below supplied benchmark';if(adjusted>hi)verdict='Above supplied benchmark';const confidence=(low&&high?45:0)+(comps.length*15)+(scope>=80?10:0);last={label,quote,center,verdict};set('fp-verdict',verdict);set('fp-adjusted',money(adjusted));set('fp-center',money(center));set('fp-position',`${position>=0?'+':''}${pct(position)}`);set('fp-confidence',`${Math.min(95,confidence)} / 100`);set('fp-copy',`ExpenseIntel is comparing this quote against the benchmark information you supplied. It is not claiming a live market price where no connected benchmark exists.`);const rows=[['Quoted price',quote],['Scope-adjusted price',adjusted],['Benchmark low',lo],['Benchmark midpoint',center],['Benchmark high',hi]];const table=$('[data-fp-table]');if(table)table.innerHTML=rows.map(([k,v])=>`<tr><td>${k}</td><td class="num">${money(v)}</td></tr>`).join('')};form.addEventListener('submit',run);watchButton(()=>({type:'Fair Price',label:last?.label||'Quote',baseline:last?.quote||num('fp-quote'),reference:last?.center||0,note:last?.verdict||'Saved quote benchmark'}));run()}
  function totalLoanInterest(price,share,apr,term){const p=Math.max(0,price*clamp(share,0,100)/100);return payment(p,apr,term)*term*12-p}
  function initTiming(){const form=$('[data-timing-form]');if(!form)return;let last=null;const q=new URLSearchParams(location.search);if(q.get('amount'))$('#tm-price').value=q.get('amount');if(q.get('q'))$('#tm-label').value=q.get('q');const run=e=>{e?.preventDefault();const label=text('tm-label')||'Purchase',price=num('tm-price'),change=num('tm-change'),months=Math.max(1,num('tm-months',6)),aprNow=num('tm-apr-now'),aprLater=num('tm-apr-later'),share=num('tm-financed',80),term=Math.max(1,num('tm-term',5)),urgency=num('tm-urgency'),incentiveNow=num('tm-incentive-now'),incentiveLater=num('tm-incentive-later');const laterPrice=price*(1+change/100),now=price+totalLoanInterest(price,share,aprNow,term)-incentiveNow,later=laterPrice+totalLoanInterest(laterPrice,share,aprLater,term)-incentiveLater+urgency*months,diff=later-now;let verdict='NEUTRAL';if(diff>Math.max(250,price*.01))verdict='BUY NOW';if(diff<-Math.max(250,price*.01))verdict='WAIT';last={label,price,verdict,now,later};set('tm-verdict',verdict);set('tm-now',money(now));set('tm-later',money(later));set('tm-diff',`${diff>=0?'+':''}${money(diff)}`);set('tm-copy',verdict==='BUY NOW'?`Under your assumptions, waiting adds about ${money(Math.abs(diff))} to the decision burden.`:verdict==='WAIT'?`Under your assumptions, waiting saves about ${money(Math.abs(diff))}.`:'The modeled difference is small enough that non-price factors may matter more.');receipt([['Price if bought now',price],['Modeled price after wait',laterPrice],['Waiting / urgency cost',urgency*months],['Incentive now',-incentiveNow],['Incentive later',-incentiveLater]],Math.min(now,later))};form.addEventListener('submit',run);watchButton(()=>({type:'Wait or Buy',label:last?.label||'Purchase',baseline:last?.price||num('tm-price'),note:`Timing verdict: ${last?.verdict||'NEUTRAL'}`}));run()}
  function initShock(){const form=$('[data-shock-form]');if(!form)return;let last=null;const q=new URLSearchParams(location.search);if(q.get('amount'))$('#sh-price').value=q.get('amount');if(q.get('horizon'))$('#sh-years').value=q.get('horizon');if(q.get('q'))$('#sh-label').value=q.get('q');const run=e=>{e?.preventDefault();const label=text('sh-label')||'Expense',price=num('sh-price'),monthly=num('sh-monthly'),annual=num('sh-annual'),oneTime=num('sh-onetime'),years=Math.max(.25,num('sh-years',5)),resale=num('sh-resale'),hidden=monthly*12*years+annual*years+oneTime-resale,total=Math.max(0,price+hidden),ratio=price?hidden/price*100:0;last={label,price,total};set('sh-total',money(total));set('sh-hidden',`${hidden>=0?'+':''}${money(hidden)}`);set('sh-ratio',`${ratio>=0?'+':''}${pct(ratio)}`);set('sh-copy',hidden>price*.75?'The secondary costs are almost as important as the sticker price.':hidden>price*.25?'This decision carries a material cost layer beyond the sticker price.':'The modeled secondary burden is relatively contained.');receipt([['Sticker price',price],['Monthly layers',monthly*12*years],['Annual layers',annual*years],['One-time extras',oneTime],['Expected resale / recovery',-resale]],total)};form.addEventListener('submit',run);watchButton(()=>({type:'Cost Shock',label:last?.label||'Expense',baseline:last?.total||0,sticker:last?.price||num('sh-price'),note:'Saved cost-shock baseline'}));run()}
  async function initMap(){const form=$('[data-map-form]');if(!form)return;const q=new URLSearchParams(location.search);if(q.get('category'))$('#map-use').value=q.get('category')==='property'?'residential':q.get('category');const run=async e=>{e?.preventDefault();const use=text('map-use')||'industrial',sqft=Math.max(300,num('map-sqft',5000)),status=$('[data-map-status]'),body=$('[data-map-body]');if(status)status.textContent='Loading connected public market signals…';if(body)body.innerHTML='';try{const r=await fetch(`/api/market?use=${encodeURIComponent(use)}`,{headers:{Accept:'application/json'}}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Market data unavailable');const intensity=Number(d.intensity?.kwhSqft)||0;const rows=d.markets.map(m=>{const rate=Number(m.electricity?.centsKwh)||0;return {...m,annual:rate/100*intensity*sqft,rate}}).sort((a,b)=>a.annual-b.annual);if(status)status.textContent=`Live connected layer: state electricity prices · ${d.methodology?.scope||''}`;if(body)body.innerHTML=rows.map((m,i)=>`<tr class="${i===0?'best':''}"><td><span class="si-rank">${i+1}</span></td><td><strong>${m.city}, ${m.state}</strong><br><small>${m.region}</small></td><td class="num">${m.rate.toFixed(2)}¢/kWh</td><td class="num">${money(m.annual)}/yr</td><td>${m.electricity?.yoy!=null?`${m.electricity.yoy>=0?'+':''}${(m.electricity.yoy*100).toFixed(1)}% YoY`:'—'}</td></tr>`).join('');set('map-count',`${rows.length} markets`);set('map-low',rows[0]?`${rows[0].city}, ${rows[0].state}`:'—');set('map-high',rows.at(-1)?`${rows.at(-1).city}, ${rows.at(-1).state}`:'—')}catch(err){if(status)status.textContent=err.message||'Market data unavailable';if(body)body.innerHTML='<tr><td colspan="5">Connected market data is temporarily unavailable.</td></tr>'}};form.addEventListener('submit',run);run()}
  function init(){initSearch();initTrueCost();initFairPrice();initTiming();initShock();initMap()}
  document.addEventListener('DOMContentLoaded',init);
})();