(()=>{
 const $=(s,r=document)=>r.querySelector(s), money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)||0), pct=n=>Number.isFinite(Number(n))?`${Number(n)>=0?'+':''}${(Number(n)*100).toFixed(1)}%`:'—';
 const ACTIVE='ei_active_decision';
 function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
 function active(){try{return JSON.parse(localStorage.getItem(ACTIVE)||'null')}catch(_e){return null}}
 async function json(url){const r=await fetch(url,{headers:{Accept:'application/json'}}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||d.errors?.[0]||'Connected data unavailable');return d}
 function signalValue(s){if(s.type==='rate')return s.value==null?'—':`${Number(s.value).toFixed(2)}%`;if(s.type==='percent_change')return s.value==null?'—':`${Number(s.value)>=0?'+':''}${Number(s.value).toFixed(2)}%`;if(s.type==='fuel_price')return s.value==null?'—':s.unit==='$/kWh'?`$${Number(s.value).toFixed(3)}/kWh`:`$${Number(s.value).toFixed(2)}/gal`;if(s.type==='state_energy')return s.value==null?'—':`${Number(s.value).toFixed(2)}¢/kWh`;return s.value==null?'—':Number(s.value).toFixed(2)}
 function signalNote(s){if(s.type==='price_index')return `${s.period||''}${s.yoy!=null?` · ${pct(s.yoy)} YoY`:''}`;if(s.type==='percent_change')return `${s.period||''}${s.quarterChange!=null?` · ${Number(s.quarterChange)>=0?'+':''}${Number(s.quarterChange).toFixed(2)}% q/q`:''}`;return s.period||''}
 function ensureContext(after){let el=$('[data-live-context]');if(el)return el;el=document.createElement('section');el.className='si-live-context';el.dataset.liveContext='1';el.innerHTML='<div class="si-live-head"><div><span>Connected evidence</span><strong>Loading public signals…</strong></div><b>LIVE</b></div><div class="si-live-grid" data-live-grid></div><div class="si-live-foot" data-live-foot>Observed evidence only. No forecast or fair-price claim is implied.</div>';after?.insertAdjacentElement('afterend',el);return el}
 function renderContext(d,after){const el=ensureContext(after),grid=$('[data-live-grid]',el),head=$('.si-live-head strong',el),foot=$('[data-live-foot]',el);if(head)head.textContent=`${d.sourceCount||0} authoritative source${d.sourceCount===1?'':'s'} · ${d.coverageScore||0}% connected coverage`;const sig=(d.signals||[]).filter(s=>s.value!=null).slice(0,10);if(grid)grid.innerHTML=sig.length?sig.map(s=>`<article><span>${esc(s.label)}</span><strong>${esc(signalValue(s))}</strong><small>${esc(signalNote(s))}</small><em>${esc(s.source||'Public source')}</em></article>`).join(''):'<article class="wide"><span>Coverage</span><strong>No connected signal returned</strong><small>The model will continue using explicit user inputs rather than inventing data.</small></article>';if(foot)foot.textContent=`Observed public evidence only · ${d.methodology?.rule||'signals remain separate from modeled assumptions.'}`;return el}
 async function loadDecisionContext({q='',category='other',location=''}={},after){const el=ensureContext(after);try{return renderContext(await json(`/api/decision-context?${new URLSearchParams({q,category,location})}`),after)}catch(e){const h=$('.si-live-head strong',el),g=$('[data-live-grid]',el);if(h)h.textContent='Connected evidence temporarily unavailable';if(g)g.innerHTML=`<article class="wide"><span>Fallback</span><strong>User-input model remains available</strong><small>${esc(e.message)}</small></article>`;return el}}
 function bindAsk(){const form=$('[data-spend-search]');if(!form)return;form.addEventListener('submit',()=>{const q=$('#spend-query')?.value||'',category=$('#spend-category')?.value||'other',location=$('#spend-location')?.value||'',brief=$('[data-spend-brief]');setTimeout(()=>loadDecisionContext({q,category,location},brief),0)})}
 function pageParams(){const p=new URLSearchParams(location.search),a=active();return{q:p.get('q')||a?.title||a?.text||'',category:p.get('category')||a?.category||'other',location:p.get('location')||a?.location||''}}
 function bindToolContext(){if($('[data-spend-search]'))return;const anchor=$('.si-panel')||$('.si-results')||$('.platform-hero');if(!anchor)return;loadDecisionContext(pageParams(),anchor)}
 function importedNote(anchor,headline,copy){if(!anchor||document.querySelector('[data-import-note]'))return;const n=document.createElement('div');n.className='ei-context-note';n.dataset.importNote='';n.innerHTML='<div><span>AUTOMATICALLY CARRIED FROM CHECK</span><br><strong></strong></div><small></small>';n.querySelector('strong').textContent=headline;n.querySelector('small').textContent=copy;anchor.parentNode.insertBefore(n,anchor)}
 function prepareTrueCost(){const form=$('[data-truecost-form]');if(!form)return;const a=active(),p=new URLSearchParams(location.search),imported=!!(a||p.get('amount')||p.get('q'));if(!imported)return;const set=(id,v)=>{const el=$(`#${id}`);if(el)el.value=String(v)};set('tc-down',0);set('tc-apr',0);set('tc-upfront',0);set('tc-monthly',0);set('tc-resale',0);let annual=0,note='Only the price/item identity is carried forward. Financing, insurance, maintenance, taxes, fees and resale remain unset until you add or verify them.';const fuel=a?.vehicle?.fuel?.summary?.annualFuelCost?.median;if(Number.isFinite(Number(fuel))){annual=Math.round(Number(fuel));note=`Price plus ${money(annual)}/yr of EPA/DOE standard-use fuel is loaded. Financing, insurance, maintenance, taxes, fees and resale are still intentionally unset.`}set('tc-annual',annual);importedNote(form,a?.title||p.get('q')||'Imported decision',note);setTimeout(()=>form.requestSubmit?.(),60)}
 function vehiclePanel(){const form=$('[data-truecost-form]');if(!form)return;const p=pageParams(),a=active(),id=a?.vehicle?.identity||{},known=a?.vehicle?.fuel;if(p.category!=='vehicle'&&!id.year&&!/\b(19|20)\d{2}\b/.test(p.q))return;const body=$('.si-panel-body',form);if(!body)return;const panel=document.createElement('div');panel.className='si-vehicle-panel';panel.innerHTML=`<div class="si-vehicle-title"><div><span>Vehicle intelligence</span><strong>${known?.ok?'Loaded from ExpenseIntel Check':'NHTSA + FuelEconomy.gov'}</strong></div><b>OFFICIAL DATA</b></div><div class="si-vehicle-result" data-v-result></div><details class="si-vehicle-refine"><summary>Refine / correct vehicle details</summary><div class="si-grid2" style="margin-top:12px"><div class="field"><label>Model year</label><input class="input" data-v-year type="number" min="1984" max="2030" placeholder="2026"></div><div class="field"><label>Make</label><input class="input" data-v-make placeholder="Ford"></div><div class="field"><label>Model</label><input class="input" data-v-model placeholder="F-150"></div><div class="field"><label>VIN (optional)</label><input class="input" data-v-vin maxlength="17" placeholder="Decode exact vehicle"></div><div class="field"><label>Annual miles</label><input class="input" data-v-miles type="number" min="0" step="500" value="12000"></div></div><button class="si-data-btn" type="button" data-v-load><span>Refresh official vehicle data</span><span>→</span></button></details>`;body.insertBefore(panel,body.firstChild);
  const yearMatch=p.q.match(/\b((?:19|20)\d{2})\b/);$('[data-v-year]',panel).value=id.year||yearMatch?.[1]||'';$('[data-v-make]',panel).value=id.make||'';$('[data-v-model]',panel).value=id.model||'';$('[data-v-vin]',panel).value=id.vin||'';
  function show(d,miles=12000){const out=$('[data-v-result]',panel),fuelData=d?.vehicleFuel||d?.fuel||known,decoded=d?.decoded&&!d.decoded.error?d.decoded:id,opts=fuelData?.options||[],sum=fuelData?.summary,fuelRange=sum?.annualFuelCost,mpg=sum?.combinedMpg;let scaled=null;if(fuelRange?.median!=null)scaled=fuelRange.median*(miles/15000);out.classList.add('show');out.innerHTML=`<div class="si-v-facts"><div><span>Vehicle</span><strong>${esc([decoded?.year,decoded?.make,decoded?.model,decoded?.trim].filter(Boolean).join(' ')||p.q)}</strong><small>${decoded?.vin?'VIN-confirmed through NHTSA':`${opts.length} EPA configuration${opts.length===1?'':'s'} found`}</small></div><div><span>Combined MPG range</span><strong>${mpg?`${mpg.min}–${mpg.max}`:'—'}</strong><small>EPA / DOE configurations</small></div><div><span>Annual fuel estimate</span><strong>${scaled!=null?money(scaled):fuelRange?`${money(fuelRange.min)}–${money(fuelRange.max)}`:'—'}</strong><small>${scaled!=null?`${miles.toLocaleString()} mi/yr scaled from EPA standard-use estimate`:'EPA standard-use estimate'}</small></div><div><span>What is still missing</span><strong>Insurance + resale</strong><small>ExpenseIntel does not silently invent these inputs.</small></div></div><div class="si-v-actions">${scaled!=null?'<button type="button" data-use-fuel>Use fuel in TrueCost</button>':''}<span>Exact price is carried from Check. Add only the unknown ownership layers that matter to you.</span></div>`;if(scaled!=null)$('[data-use-fuel]',out)?.addEventListener('click',()=>{const annual=$('#tc-annual');if(annual){annual.value=String(Math.round(scaled));form.requestSubmit();out.querySelector('[data-use-fuel]').textContent='Fuel applied ✓'}})}
  if(known?.ok)show({fuel:known},12000);
  $('[data-v-load]',panel).addEventListener('click',async()=>{const btn=$('[data-v-load]',panel),out=$('[data-v-result]',panel),year=$('[data-v-year]',panel).value,make=$('[data-v-make]',panel).value.trim(),model=$('[data-v-model]',panel).value.trim(),vin=$('[data-v-vin]',panel).value.trim(),miles=Math.max(0,Number($('[data-v-miles]',panel).value)||12000);btn.disabled=true;btn.firstElementChild.textContent='Loading NHTSA + EPA data…';try{show(await json(`/api/vehicle-context?${new URLSearchParams({year,make,model,vin})}`),miles)}catch(e){out.classList.add('show');out.innerHTML=`<div class="si-data-error">${esc(e.message)}</div>`}finally{btn.disabled=false;btn.firstElementChild.textContent='Refresh official vehicle data'}})
 }
 function fairPriceFromActive(){const form=$('[data-fairprice-form]'),a=active(),c=a?.comparables;if(!form||!c?.ok||!c.median)return;const p=new URLSearchParams(location.search);if(p.get('amount')||p.get('q'))return;const set=(id,v)=>{const el=$(`#${id}`);if(el&&v!=null)el.value=String(Math.round(Number(v)))};set('fp-quote',a.price);set('fp-low',c.p25);set('fp-high',c.p75);const list=(c.listings||[]).filter(x=>x.price).slice(0,3);list.forEach((x,i)=>set(`fp-comp${i+1}`,x.price));importedNote(form,a.title||'Active listing',`Fair Price imported the active comparable market from Check: ${money(c.p25)}–${money(c.p75)} middle range, ${money(c.median)} median across ${c.numFound||'matched'} active listings. Review trim, mileage and fees before treating this as transaction value.`);setTimeout(()=>form.requestSubmit?.(),70)}
 function timingTrendAssist(){const form=$('[data-timing-form]');if(!form)return;const p=pageParams(),anchor=$('.si-panel',form)||form;json(`/api/decision-context?${new URLSearchParams(p)}`).then(d=>{let target;if(p.category==='vehicle')target=(d.signals||[]).find(s=>s.type==='price_index'&&/new vehicles|used cars/i.test(s.label));else if(p.category==='home'||p.category==='property')target=(d.signals||[]).find(s=>s.type==='percent_change');else target=(d.signals||[]).find(s=>s.type==='price_index');if(!target)return;const observed=target.type==='percent_change'?Number(target.value):target.yoy!=null?Number(target.yoy)*100:null;if(!Number.isFinite(observed))return;const box=document.createElement('div');box.className='si-trend-assist';box.innerHTML=`<div><span>Observed market trend</span><strong>${esc(target.label)} ${observed>=0?'+':''}${observed.toFixed(1)}%</strong><small>${esc(target.period||'')} · ${esc(target.source||'public source')} · observed history, not a forecast</small></div><button type="button">Use as scenario assumption</button>`;anchor.insertAdjacentElement('afterend',box);box.querySelector('button').addEventListener('click',()=>{const input=$('#tm-change');if(input){input.value=observed.toFixed(1);form.requestSubmit();box.querySelector('button').textContent='Copied as scenario ✓'}})}).catch(()=>{})}
 document.addEventListener('DOMContentLoaded',()=>{bindAsk();prepareTrueCost();bindToolContext();vehiclePanel();fairPriceFromActive();timingTrendAssist()});
})();