(()=>{
  const ready=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn,{once:true}):fn();
  ready(()=>{
    const status=document.querySelector('.topline .status');let flag=document.querySelector('[data-network-flag]');if(!flag&&status){flag=document.createElement('span');flag.dataset.networkFlag='true';status.appendChild(flag)}
    const sync=()=>{document.documentElement.dataset.network=navigator.onLine?'online':'offline';if(flag)flag.textContent=navigator.onLine?'Live web available':'Offline · connected evidence may be limited'};sync();addEventListener('online',sync);addEventListener('offline',sync);
    const draftIds=['check-url','check-text','check-category','check-price','check-location'];
    try{const saved=JSON.parse(localStorage.getItem('expenseintel-home-draft-v1')||'null');if(saved?.draft&&Date.now()-Number(saved.savedAt||0)<1000*60*60*24*14)draftIds.forEach(id=>{const el=document.getElementById(id);if(el&&saved.draft[id])el.value=saved.draft[id]})}catch{}
    const saveDraft=()=>{const draft=Object.fromEntries(draftIds.map(id=>[id,document.getElementById(id)?.value??'']));localStorage.setItem('expenseintel-home-draft-v1',JSON.stringify({savedAt:Date.now(),draft}))};draftIds.forEach(id=>{const el=document.getElementById(id);el?.addEventListener('input',saveDraft);el?.addEventListener('change',saveDraft)});
    const advanced=document.querySelector('.check-advanced');if(advanced){advanced.open=localStorage.getItem('expenseintel-advanced-open')==='1';advanced.addEventListener('toggle',()=>localStorage.setItem('expenseintel-advanced-open',advanced.open?'1':'0'))}
    const price=document.getElementById('check-price');if(price){const syncPrice=()=>price.setAttribute('aria-invalid',price.checkValidity()?'false':'true');price.addEventListener('input',syncPrice);syncPrice()}
    const tabs=[...document.querySelectorAll('.check-tabs [data-mode]')];tabs.forEach(tab=>{tab.setAttribute('role','tab');const syncTab=()=>tab.setAttribute('aria-selected',tab.classList.contains('active')?'true':'false');syncTab();new MutationObserver(syncTab).observe(tab,{attributes:true,attributeFilter:['class']});tab.addEventListener('click',()=>localStorage.setItem('expenseintel-check-mode',tab.dataset.mode||'link'))});
    const sharedMode=new URL(location.href).searchParams.get('mode');const preferred=sharedMode||localStorage.getItem('expenseintel-check-mode');const preferredTab=tabs.find(tab=>tab.dataset.mode===preferred);if(preferredTab&&!preferredTab.classList.contains('active'))preferredTab.click();
    const form=document.querySelector('[data-check-form]');addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key==='Enter'){event.preventDefault();form?.requestSubmit()}});
    form?.addEventListener('submit',()=>{const run=form.querySelector('.check-run');if(!run)return;const original=run.innerHTML;run.disabled=true;run.setAttribute('aria-busy','true');run.innerHTML='<span>Building Decision Passport…</span><span>→</span>';setTimeout(()=>{run.disabled=false;run.removeAttribute('aria-busy');run.innerHTML=original},1600)});
    const category=document.getElementById('check-category');const sharedCategory=new URL(location.href).searchParams.get('category');if(category&&sharedCategory&&[...category.options].some(o=>o.value===sharedCategory))category.value=sharedCategory;category?.addEventListener('change',()=>{const url=new URL(location.href);url.searchParams.set('category',category.value);history.replaceState(null,'',url)});
    const examples=document.querySelector('.check-examples');if(examples&&!document.querySelector('[data-copy-decision-link]')){const copy=document.createElement('button');copy.type='button';copy.dataset.copyDecisionLink='true';copy.textContent='Copy setup link';copy.addEventListener('click',async()=>{const url=new URL(location.href);if(category?.value)url.searchParams.set('category',category.value);const mode=tabs.find(tab=>tab.classList.contains('active'))?.dataset.mode;if(mode)url.searchParams.set('mode',mode);try{await navigator.clipboard.writeText(url.toString());copy.textContent='Link copied';setTimeout(()=>copy.textContent='Copy setup link',1200)}catch{copy.textContent='Copy unavailable'}});examples.appendChild(copy)}

    if(!document.getElementById('eiWorkedPassport')){
      const hero=document.querySelector('.check-hero');
      if(hero){
        const proof=document.createElement('section');proof.id='eiWorkedPassport';proof.className='ei-worked';proof.innerHTML=`<div class="shell"><div class="ei-worked-head"><div><span>WORKED PASSPORTS</span><h2>Don’t read about the product. Run a decision.</h2><p>These use the same Decision Passport flow as a normal check. They are examples, not canned result screenshots: the output is built when you run them and connected evidence is labeled separately from modeled or missing facts.</p></div></div><div class="ei-worked-grid"><article><span>VEHICLE</span><h3>2026 F-150 · $48,400</h3><p>See price alignment, ownership burden, safety evidence and what still needs verification before the purchase.</p><button type="button" data-worked-example="vehicle">RUN VEHICLE PASSPORT →</button></article><article><span>PROJECT / QUOTE</span><h3>HVAC proposal · $17,800</h3><p>See why scope, exclusions, permits, electrical work and unresolved assumptions can matter more than the headline quote.</p><button type="button" data-worked-example="quote">RUN QUOTE PASSPORT →</button></article><article class="ei-worked-principle"><span>DECISION RULE</span><h3>Unknown is a valid output.</h3><p>ExpenseIntel should never turn a missing benchmark into fake precision. A strong Passport tells you what is known, what is modeled and what fact is worth verifying next.</p></article></div></div>`;
        hero.insertAdjacentElement('afterend',proof);
        const style=document.createElement('style');style.id='ei-worked-style';style.textContent=`.ei-worked{border-top:1px solid #d4cec2;border-bottom:1px solid #d4cec2;background:#ebe7dd;padding:34px 0}.ei-worked-head{max-width:820px}.ei-worked-head>div>span,.ei-worked-grid article>span{font:800 10px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.1em;text-transform:uppercase;color:#8d2f22}.ei-worked-head h2{font-size:clamp(28px,4vw,54px);line-height:.98;margin:8px 0 12px;color:#151515}.ei-worked-head p{max-width:760px;margin:0;color:#5f5a52;line-height:1.6}.ei-worked-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:22px}.ei-worked-grid article{display:flex;flex-direction:column;min-height:220px;padding:20px;border:1px solid #cfc8bb;background:#f7f4ed}.ei-worked-grid h3{margin:12px 0 8px;font-size:21px;line-height:1.05;color:#1c1b19}.ei-worked-grid p{margin:0 0 18px;color:#686158;line-height:1.5}.ei-worked-grid button{margin-top:auto;border:1px solid #1c1b19;background:#1c1b19;color:#fff;padding:12px 14px;text-align:left;font-weight:800;cursor:pointer}.ei-worked-grid button:hover{background:#8d2f22;border-color:#8d2f22}.ei-worked-principle{background:#1c1b19!important;border-color:#1c1b19!important}.ei-worked-principle span{color:#e6a89f!important}.ei-worked-principle h3{color:#fff}.ei-worked-principle p{color:#cbc4b8}@media(max-width:820px){.ei-worked-grid{grid-template-columns:1fr}.ei-worked-grid article{min-height:0}}`;
        document.head.appendChild(style);
        proof.querySelectorAll('[data-worked-example]').forEach(button=>button.addEventListener('click',()=>{
          const key=button.dataset.workedExample;
          const source=document.querySelector(`.check-examples [data-example="${key}"]`);
          source?.click();
          document.getElementById('check-form')?.scrollIntoView({behavior:'smooth',block:'center'});
          setTimeout(()=>form?.requestSubmit(),120);
        }));
      }
    }
  });
})();
