(()=>{
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const KEY='ei_location_actuals_v1';
  const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
  const num=v=>Number.isFinite(Number(v))?Number(v):0;
  const money=n=>Number.isFinite(Number(n))?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)):'—';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const labels={electric:'Electricity',gas:'Natural gas',water:'Water + sewer',insurance:'Insurance',other:'Waste + other',tax:'Property tax'};
  const cats=['electric','gas','water','insurance','other'];
  let latest=null;

  function readActuals(r){try{const all=JSON.parse(localStorage.getItem(KEY)||'{}'),id=[r.address,r.use,r.sqft].map(x=>clean(x).toLowerCase()).join('|');return all[id]||{}}catch(_e){return{}}}
  function costs(r){const a=readActuals(r),c={};['electric','gas','water','tax','insurance','other'].forEach(k=>c[k]=num(a[k])>0?num(a[k]):num(r.categories?.[k]));return c}
  function controllable(c){return cats.reduce((s,k)=>s+num(c[k]),0)}
  function region(state){state=String(state||'').toUpperCase();if(['ME','NH','VT','MA','RI','CT','NY','NJ','PA'].includes(state))return'Northeast';if(['OH','IN','IL','MI','WI','IA','MN','MO','KS','NE','SD','ND'].includes(state))return'Midwest';if(['DE','MD','DC','VA','WV','NC','SC','GA','FL','KY','TN','MS','AL','OK','TX','AR','LA'].includes(state))return'South';if(state)return'West';return'U.S.'}
  function climateAdvice(state){const r=region(state);if(r==='Northeast')return'Because this is a Northeast location, start with infiltration, heating schedules and envelope losses before forcing deeper temperature setbacks.';if(r==='Midwest')return'For this Midwest location, prioritize heating/cooling scheduling, envelope leakage and peak-season runtime before comfort cuts.';if(r==='South')return'For this Southern location, cooling runtime, humidity control and solar/air-infiltration load deserve first attention before thermostat extremes.';return'For this Western location, screen cooling, ventilation, envelope and rate-plan effects around the actual local climate before equipment replacement.'}
  function detailFor(use,key,r){const state=r.location?.components?.state||'',rateE=num(r.energy?.electricity?.centsKwh),rateG=num(r.energy?.gas?.dollarsMcf),place=clean(r.location?.components?.city||r.address||'this location');
    const common={
      electric:[`At ${place}, electricity is one of the controllable layers${rateE?` and the connected EIA state benchmark is ${rateE.toFixed(2)}¢/kWh`:''}. Start by identifying what runs longest, not what has the highest nameplate rating.`,`Use schedule changes first: shorten unnecessary HVAC/lighting runtime, remove simultaneous heating and cooling, and shut off idle loads after occupancy. Keep comfort setpoints within a normal band rather than creating large temperature swings.`,`Measure one billing cycle before replacing equipment. If the load barely changes, the problem is probably equipment efficiency, controls, ventilation or envelope—not user behavior.`],
      gas:[`Natural gas is worth targeting${rateG?` with the current connected state benchmark at $${rateG.toFixed(2)}/Mcf`:''}. Focus first on heating runtime, envelope leakage and hot-water load.`,`Reduce waste before temperature: weather-seal obvious leakage, verify boiler/furnace scheduling, insulate accessible hot-water piping and make sure heating is not running during long unoccupied periods.`,`Do not switch fuels based on the gas bill alone. A heat-pump or electrification decision needs actual gas use, electric rate, climate, equipment performance and installed quote.`],
      water:[`Treat water and sewer together because many tariffs bill sewer from metered water use. Start with leaks and waste that do not affect comfort.`,`Check toilets, irrigation, continuous-flow fixtures and process/cleaning schedules. Low-flow fixtures should preserve usable pressure; avoid reducing service where it affects sanitation or operations.`,`Compare the next bill after fixes before spending on larger plumbing upgrades.`],
      insurance:[`Re-shop insurance without weakening the coverage you actually need. Ask each carrier or broker to quote the same limits, deductibles and major exclusions.`,`First test pricing changes that do not reduce protection: bundling, payment method, verified alarms/sprinklers, roof or system updates, and corrected property information.`,`A cheaper premium is not a saving if the deductible, exclusions or replacement-cost basis got materially worse.`],
      other:[`Break “other” into named recurring vendors before cutting it. Waste, landscaping, pest control, monitoring and service contracts can usually be rebid more safely than simply canceled.`,`Normalize frequency and scope, then ask for like-for-like bids. Reduce duplicate visits or unused service tiers before removing service entirely.`,`Keep safety, sanitation and legally required services outside the first round of cuts.`]
    };
    const useExtra={
      residential:{electric:'For a home, prioritize HVAC runtime, standby loads, laundry/dishwashing behavior and lighting before anything that reduces comfort.',gas:'For a home, air sealing and heating controls usually deserve review before a full heating-system replacement.',water:'For a home, silent toilet leaks, shower flow and irrigation are high-value low-friction checks.'},
      restaurant:{electric:'For a restaurant, refrigeration, hood/make-up air, HVAC and lighting schedules are the first large loads to profile.',gas:'For a restaurant, cooking equipment, make-up air and hot-water schedules can dominate gas use; protect food safety and ventilation requirements.',water:'For a restaurant, pre-rinse spray valves, leaks, ice equipment and cleaning flow are common places to inspect without reducing sanitation.'},
      office:{electric:'For an office, after-hours HVAC, lighting and plug loads are usually easier to change than occupied comfort.',gas:'For an office, unoccupied heating and morning warm-up schedules deserve attention before temperature reductions during work hours.'},
      retail:{electric:'For retail, lighting, entrance infiltration and after-hours HVAC are practical first checks without changing the customer experience.',gas:'For retail, door loss and unoccupied heating often matter more than aggressive occupied setpoint changes.'},
      warehouse:{electric:'For a warehouse, high-bay lighting, dock equipment and long HVAC runtimes are better targets than occupied comfort.',gas:'For a warehouse, dock leakage, destratification and unoccupied heating can matter more than lowering worker comfort.'},
      industrial:{electric:'For industrial space, compressed air, motors, pumps and idle process loads should be measured before broad shutdown rules.',gas:'For industrial space, process heat and exhaust losses need process-specific review; do not cut temperatures or ventilation blindly.'},
      multifamily:{electric:'For multifamily, common-area lighting/HVAC and central equipment should be separated from tenant-controlled loads.',gas:'For multifamily, central heating balance, recirculation and envelope losses should be reviewed before resident comfort changes.'}
    };
    const base=common[key]||[];const extra=useExtra[r.use]?.[key];return extra?[extra,...base]:base
  }
  function metaFor(use,key){
    const base={electric:{easy:.12,deep:.24,hardship:1},gas:{easy:.10,deep:.20,hardship:1},water:{easy:.10,deep:.18,hardship:1},insurance:{easy:.12,deep:.18,hardship:1},other:{easy:.12,deep:.22,hardship:1}};
    const m={...base[key]};
    if(use==='restaurant'&&key==='electric'){m.easy=.15;m.deep=.28}if(use==='warehouse'&&key==='electric'){m.easy=.16;m.deep=.28}if(use==='industrial'&&key==='electric'){m.easy=.14;m.deep=.26}if(use==='residential'&&key==='other'){m.easy=.08;m.deep=.14}return m
  }
  function plan(r,pct){
    const c=costs(r),goal=controllable(c)*pct,rows=cats.map(k=>{const m=metaFor(r.use,k);return{key:k,cost:c[k],easyCap:c[k]*m.easy,deepCap:c[k]*m.deep,hardship:m.hardship}}).filter(x=>x.cost>0).sort((a,b)=>b.easyCap-a.easyCap),alloc={};let left=goal;
    rows.forEach(x=>{const v=Math.min(left,x.easyCap);if(v>0){alloc[x.key]=(alloc[x.key]||0)+v;left-=v}});
    if(left>1)rows.forEach(x=>{const extra=Math.max(0,x.deepCap-(alloc[x.key]||0)),v=Math.min(left,extra);if(v>0){alloc[x.key]=(alloc[x.key]||0)+v;left-=v}});
    return{c,goal,alloc,left:Math.max(0,left),achieved:goal-Math.max(0,left)}
  }
  function patchCards(r,p){
    const section=$('.ei-savings');if(!section)return;const slider=$('[data-save-slider]',section),pct=num(slider?.value)/100||.10,pl=plan(r,pct),label=$('.ei-savings-head aside div:nth-child(2) span',section),headline=$('[data-save-ten]',section);if(label)label.textContent=`${Math.round(pct*100)}% target scenario`;if(headline)headline.textContent=`${money(pl.goal)}/yr`;
    $$('.ei-action-card',section).forEach(card=>{const h=clean($('h4',card)?.textContent).toLowerCase();let key=h.includes('electric')?'electric':h.includes('natural-gas')||h.includes('gas use')?'gas':h.includes('water')?'water':h.includes('insurance')?'insurance':h.includes('waste')||h.includes('service')?'other':null;if(!key)return;const val=pl.alloc[key]||0,st=$('strong',card),sm=$('small',card);if(st)st.textContent=val>1?`${money(val)}/yr toward target`:'Not needed for this target';if(sm)sm.textContent=`Target allocation · about ${pl.c[key]?((val/pl.c[key])*100).toFixed(1):0}% of this cost layer · scenario, not a promised saving`})
  }
  function renderPlaybook(r){
    const section=$('.ei-savings');if(!section)return;let box=$('.ei-target-playbook',section);if(!box){box=document.createElement('section');box.className='ei-target-playbook';const list=$('[data-action-list]',section);list?.insertAdjacentElement('afterend',box)}if(!box)return;
    const slider=$('[data-save-slider]',section),pct=num(slider?.value)/100||.10,pl=plan(r,pct),state=r.location?.components?.state||'',city=r.location?.components?.city||'',dominant=Object.entries(pl.c).filter(([k])=>cats.includes(k)).sort((a,b)=>b[1]-a[1])[0],steps=Object.entries(pl.alloc).filter(([,v])=>v>1).sort((a,b)=>b[1]-a[1]);
    const locationLine=[clean(r.address),city&&state?`${city}, ${state}`:state,region(state)].filter(Boolean).join(' · '),target=Math.round(pct*100);
    box.innerHTML=`<div class="ei-play-head"><div><span>Target playbook / ${esc(locationLine)}</span><h4>How to reach a ${target}% cut without making the place miserable.</h4><p>${esc(climateAdvice(state))} ${dominant?`${labels[dominant[0]]} is currently the largest controllable modeled layer, so ExpenseIntel puts it first instead of spreading cuts evenly.`:''}</p></div><aside><span>Target</span><strong>${money(pl.goal)}/yr</strong><small>${pl.left<1?'Plan fully allocated':'Some target remains unallocated'}</small></aside></div><div class="ei-play-progress"><div style="width:${Math.min(100,pl.goal?pl.achieved/pl.goal*100:0)}%"></div></div><div class="ei-play-steps"></div><div class="ei-guardrails"><div><span>Comfort guardrail</span><strong>Cut waste before comfort.</strong><p>Do not start with extreme thermostat changes, reduced ventilation, skipped maintenance or removing needed services. Schedule, leaks, controls, tariffs and duplicate service come first.</p></div><div><span>Verification guardrail</span><strong>Measure after each round.</strong><p>Make one group of changes, compare the next normalized bill, then decide whether the next step is still worth doing. ExpenseIntel keeps the target as a scenario until real bills prove it.</p></div></div><details class="ei-90day" open><summary>90-day low-hardship plan <b>specific to this target ↓</b></summary><div class="ei-90-grid"><article><span>Days 1–7</span><strong>Replace guesses with bills.</strong><p>Enter actual electricity, gas, water, insurance and service spend below. Photograph or export 12 months where possible so weather and seasonality do not fool the comparison.</p></article><article><span>Days 8–30</span><strong>Do the no-regret changes.</strong><p>Fix obvious leaks, trim unnecessary operating hours, correct controls and schedules, and re-shop equivalent insurance/service contracts. Avoid equipment purchases until the easy layer is measured.</p></article><article><span>Days 31–60</span><strong>Measure the gap.</strong><p>Compare actual usage and bills with the baseline. If the target is not closing, identify the single load responsible for most of the remaining gap rather than making broad comfort cuts.</p></article><article><span>Days 61–90</span><strong>Price the deeper move.</strong><p>Only then get like-for-like quotes for controls, envelope work, HVAC, lighting, water heating or other system changes. Compare installed cost and verified annual savings before committing capital.</p></article></div></details>`;
    const wrap=$('.ei-play-steps',box);steps.forEach(([key,save],i)=>{const cost=pl.c[key],layerPct=cost?save/cost:0,advice=detailFor(r.use,key,r),art=document.createElement('article');art.className='ei-play-step';art.innerHTML=`<div class="ei-step-no">${String(i+1).padStart(2,'0')}</div><div><span>${esc(labels[key])} · contribution to ${target}% target</span><h5>${money(save)}/yr from this layer</h5><p><strong>Scenario intensity:</strong> about ${(layerPct*100).toFixed(1)}% of the current ${labels[key].toLowerCase()} layer.</p><ul>${advice.slice(0,4).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`;wrap.appendChild(art)});
    if(pl.left>1){const art=document.createElement('article');art.className='ei-play-step warning';art.innerHTML=`<div class="ei-step-no">!</div><div><span>Target gap</span><h5>${money(pl.left)}/yr still needs a deeper lever</h5><p>The requested ${target}% cut is larger than the low-to-moderate disruption screening capacity ExpenseIntel assigned to the current layers. Do not fake the rest with harsher behavior. Use real bills and quotes to test a system upgrade, tariff change or structural cost change.</p></div>`;wrap.appendChild(art)}
  }
  function sync(r){if(!r)return;patchCards(r);renderPlaybook(r)}
  function bind(r){latest=r;const wait=()=>{const section=$('.ei-savings'),slider=$('[data-save-slider]');if(!section||!slider){setTimeout(wait,60);return}if(section.dataset.eiTargetPlan==='1'){sync(r);return}section.dataset.eiTargetPlan='1';slider.addEventListener('input',()=>sync(r));$$('.ei-actuals-grid input',section).forEach(i=>i.addEventListener('input',()=>setTimeout(()=>sync(r),30)));sync(r)};wait()}
  document.addEventListener('ei:screen-complete',e=>bind(e.detail));
})();