(()=>{
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)||0);
  const n=sel=>Number($(sel)?.value)||0;
  let currentCase=null,currentCalc=null;

  function payment(loan,ratePct,years){const months=Math.max(1,Math.round(years*12)),r=ratePct/100/12;if(loan<=0)return 0;if(r===0)return loan/months;return loan*r/(1-Math.pow(1+r,-months))}
  function balance(loan,ratePct,years,monthsPaid){const months=Math.max(1,Math.round(years*12)),k=Math.min(months,Math.max(0,monthsPaid)),r=ratePct/100/12,p=payment(loan,ratePct,years);if(r===0)return Math.max(0,loan-p*k);return Math.max(0,loan*Math.pow(1+r,k)-p*((Math.pow(1+r,k)-1)/r))}
  function fiveYearRent(monthly,growthPct){let total=0,rent=Math.max(0,monthly),g=growthPct/100;for(let y=0;y<5;y++){total+=rent*12;rent*=1+g}return total}
  async function buildCase(address,sqft){const u=new URL('/api/case',location.origin);u.searchParams.set('address',address);u.searchParams.set('use','residential');u.searchParams.set('sqft',sqft);const r=await fetch(u,{headers:{Accept:'application/json'}}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Could not build home location case.');return d.case}
  function inputs(c){
    const price=Math.max(1,n('[data-price]')),sqft=Math.max(300,n('[data-sqft]')),downPct=Math.min(100,Math.max(0,n('[data-down]'))),rate=Math.max(0,n('[data-rate]')),term=Math.max(1,n('[data-term]'));
    const modeledTax=c?.categories?.tax||0,modeledIns=c?.categories?.insurance||0;
    const tax=n('[data-tax]')>0?n('[data-tax]'):modeledTax,insurance=n('[data-insurance]')>0?n('[data-insurance]'):modeledIns;
    const taxSource=n('[data-tax]')>0?'user supplied':'ExpenseIntel modeled fallback',insuranceSource=n('[data-insurance]')>0?'user supplied':'ExpenseIntel modeled fallback';
    const hoa=Math.max(0,n('[data-hoa]')),maintPct=Math.max(0,n('[data-maint]'))/100,closingPct=Math.max(0,n('[data-closing]'))/100,app=Math.max(-.2,Math.min(.3,n('[data-app]')/100)),salePct=Math.max(0,n('[data-sale]'))/100,budget=Math.max(0,n('[data-budget]')),rent=Math.max(0,n('[data-rent]')),rentGrowth=n('[data-rent-growth]');
    const locationAnnual=(c?.categories?.electric||0)+(c?.categories?.gas||0)+(c?.categories?.water||0)+(c?.categories?.other||0);
    return{price,sqft,downPct,rate,term,tax,insurance,taxSource,insuranceSource,hoa,maintPct,closingPct,app,salePct,budget,rent,rentGrowth,locationAnnual};
  }
  function ownershipNet(i,appRate){
    const downCash=i.price*i.downPct/100,loan=i.price-downCash,pi=payment(loan,i.rate,i.term),maintAnnual=i.price*i.maintPct,monthly=pi+i.tax/12+i.insurance/12+i.hoa+maintAnnual/12+i.locationAnnual/12,closingCash=i.price*i.closingPct;
    const bal5=balance(loan,i.rate,i.term,60),value5=i.price*Math.pow(1+appRate,5),saleCosts=value5*i.salePct,proceeds=Math.max(0,value5-saleCosts-bal5),cash5=downCash+closingCash+monthly*60,net=cash5-proceeds;
    return{downCash,loan,pi,maintAnnual,monthly,closingCash,bal5,value5,saleCosts,proceeds,cash5,net,principal:loan-bal5};
  }
  function maxPriceForBudget(i){if(!i.budget)return null;const taxRatio=i.tax/i.price,insRatio=i.insurance/i.price;const monthlyAt=p=>{const loan=p*(1-i.downPct/100),pi=payment(loan,i.rate,i.term);return pi+(p*taxRatio)/12+(p*insRatio)/12+i.hoa+(p*i.maintPct)/12+i.locationAnnual/12};let lo=0,hi=Math.max(i.price*5,3000000);for(let j=0;j<70;j++){const mid=(lo+hi)/2;if(monthlyAt(mid)<=i.budget)lo=mid;else hi=mid}return lo}
  function breakEvenApp(i,rentFive){if(!i.rent)return null;const f=a=>ownershipNet(i,a).net-rentFive;let lo=-.15,hi=.25;if(f(lo)<=0)return'< -15%';if(f(hi)>0)return'> 25%';for(let j=0;j<70;j++){const mid=(lo+hi)/2;if(f(mid)>0)lo=mid;else hi=mid}return((lo+hi)/2*100).toFixed(1)+'% / yr'}
  function calc(c){const i=inputs(c),o=ownershipNet(i,i.app),rentFive=fiveYearRent(i.rent,i.rentGrowth),maxPrice=maxPriceForBudget(i),breakEven=breakEvenApp(i,rentFive),stress=o.pi+(i.tax*1.10)/12+(i.insurance*1.25)/12+i.hoa+(o.maintAnnual*1.25)/12+(i.locationAnnual*1.15)/12;return{i,o,rentFive,maxPrice,breakEven,stress}}
  function render(c){currentCase=c;currentCalc=calc(c);const {i,o,rentFive,maxPrice,breakEven,stress}=currentCalc;
    $('[data-monthly]').textContent=money(o.monthly);$('[data-monthly-copy]').textContent=`All-in modeled monthly carry for ${c.address}, including financing, taxes, insurance, HOA, maintenance reserve and the current location-cost layer.`;
    $('[data-pi]').textContent=money(o.pi);$('[data-location-monthly]').textContent=money(i.locationAnnual/12);$('[data-down-cash]').textContent=money(o.downCash);$('[data-closing-cash]').textContent=money(o.closingCash);
    const stack=[['Principal + interest',o.pi,'financing'],['Property tax',i.tax/12,i.taxSource],['Home insurance',i.insurance/12,i.insuranceSource],['HOA',i.hoa,'user supplied'],['Maintenance reserve',o.maintAnnual/12,`${(i.maintPct*100).toFixed(1)}% of price / year`],['Utilities + location services',i.locationAnnual/12,'ExpenseIntel location case']];const zone=$('[data-home-stack]');zone.innerHTML='';stack.forEach(([label,val,src])=>{const d=document.createElement('div');d.className='cost-row';d.innerHTML='<div><strong></strong><small></small></div><b></b>';d.querySelector('strong').textContent=label;d.querySelector('small').textContent=src;d.querySelector('b').textContent=money(val);zone.appendChild(d)});
    const box=$('[data-budget-box]');box.classList.remove('breach');if(i.budget){const gap=i.budget-o.monthly;if(gap>=0){$('[data-budget-status]').textContent=`${money(gap)} / month of headroom.`;$('[data-budget-copy]').textContent=`The modeled carry is below your ${money(i.budget)} monthly ceiling.`}else{box.classList.add('breach');$('[data-budget-status]').textContent=`Ceiling breached by ${money(Math.abs(gap))} / month.`;$('[data-budget-copy]').textContent=`The modeled carry is above your ${money(i.budget)} monthly limit before any unmodeled repairs or lifestyle costs.`}}else{$('[data-budget-status]').textContent='Enter a monthly ceiling.';$('[data-budget-copy]').textContent='ExpenseIntel will show headroom or the size of the breach.'}
    $('[data-five-cash]').textContent=money(o.cash5);$('[data-principal]').textContent=money(o.principal);$('[data-proceeds]').textContent=money(o.proceeds);$('[data-net-cost]').textContent=money(o.net);$('[data-net-monthly]').textContent=money(o.net/60);$('[data-stress]').textContent=money(stress);$('[data-max-price]').textContent=maxPrice!=null?money(maxPrice):'Set a ceiling';$('[data-breakeven]').textContent=breakEven||'Enter rent';
    $('[data-rent-five]').textContent=i.rent?money(rentFive):'Enter comparable rent';$('[data-rent-copy]').textContent=i.rent?`${money(i.rent)}/month starting rent with ${i.rentGrowth.toFixed(1)}% annual growth.`:'Add comparable monthly rent to measure five-year ownership against renting.';
    if(i.rent){const diff=o.net-rentFive;$('[data-own-vs-rent]').textContent=(diff<=0?money(Math.abs(diff))+' lower':money(diff)+' higher');$('[data-own-vs-rent-copy]').textContent=diff<=0?'Under your assumptions, modeled five-year ownership cost is lower than five years of rent.':'Under your assumptions, modeled five-year ownership cost is higher than five years of rent.'}else{$('[data-own-vs-rent]').textContent='—';$('[data-own-vs-rent-copy]').textContent='Enter comparable rent to calculate the difference.'}
    $('[data-home-evidence]').textContent=`${c.evidence.grade} · ${c.evidence.score}/100`;$('[data-home-hazard]').textContent=c.risk?.composite?.rating||'Unavailable';$('[data-home-electric]').textContent=c.energy?.electricity?.centsKwh?`${c.energy.electricity.centsKwh.toFixed(2)}¢/kWh`:'Modeled fallback';$('[data-home-model]').textContent=c.modelVersion;
    $('[data-home-result]').classList.add('show');
  }
  function refresh(){if(currentCase)render(currentCase)}
  async function submit(e){e.preventDefault();const err=$('[data-home-error]');err.classList.remove('show');err.textContent='';const address=$('[name="address"]').value.trim(),sqft=Math.max(300,n('[data-sqft]'));if(!address){err.textContent='Enter and verify a home address.';err.classList.add('show');return}const btn=e.currentTarget.querySelector('button[type="submit"]');btn.disabled=true;try{render(await buildCase(address,sqft));$('[data-home-result]').scrollIntoView({behavior:'smooth',block:'start'})}catch(ex){err.textContent=ex.message;err.classList.add('show')}finally{btn.disabled=false}}
  async function copy(){if(!currentCase||!currentCalc)return;const c=currentCase,{i,o,rentFive,maxPrice,breakEven,stress}=currentCalc;const text=`ExpenseIntel Homebuyer Ownership Case\n${c.address}\nModel: ${c.modelVersion}\n\nPurchase price: ${money(i.price)}\nTrue monthly carry: ${money(o.monthly)}\nPrincipal + interest: ${money(o.pi)}\n5-year cash outlay: ${money(o.cash5)}\nPrincipal repaid in 5 years: ${money(o.principal)}\nModeled net sale proceeds: ${money(o.proceeds)}\nNet 5-year ownership cost: ${money(o.net)}\nEquivalent net monthly cost: ${money(o.net/60)}\nStress monthly carry: ${money(stress)}\n${i.budget?`Purchase price at monthly ceiling: ${money(maxPrice)}\n`:''}${i.rent?`5-year rent cost: ${money(rentFive)}\nBreak-even appreciation vs rent: ${breakEven}\n`:''}\nEvidence grade: ${c.evidence.grade} (${c.evidence.score}/100)\n\nDecision support only. Confirm financing, taxes, insurance, HOA and property condition independently.`;try{await navigator.clipboard.writeText(text);const b=$('[data-copy-home]'),old=b.textContent;b.textContent='Copied ✓';setTimeout(()=>b.textContent=old,1400)}catch(_e){}}
  document.addEventListener('DOMContentLoaded',()=>{$('[data-home-form]')?.addEventListener('submit',submit);$$('[data-price],[data-down],[data-rate],[data-term],[data-tax],[data-insurance],[data-hoa],[data-maint],[data-closing],[data-app],[data-sale],[data-budget],[data-rent],[data-rent-growth]').forEach(el=>el.addEventListener('input',refresh));$('[data-copy-home]')?.addEventListener('click',copy);$('[data-print-home]')?.addEventListener('click',()=>window.print())});
})();