(()=>{
  const $=(s,r=document)=>r.querySelector(s);
  const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)||0);
  const compact=n=>Math.abs(Number(n)||0)>=1000000?'$'+((Number(n)||0)/1000000).toFixed(2)+'M':Math.abs(Number(n)||0)>=1000?'$'+((Number(n)||0)/1000).toFixed(1)+'k':money(n);
  let base=null,scenarios=[];
  function err(msg=''){const e=$('[data-twin-error]');e.textContent=msg;e.classList.toggle('show',!!msg)}
  async function json(url){const r=await fetch(url,{headers:{Accept:'application/json'}});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Data unavailable.');return d}
  function calc(){
    if(!base)return null;
    const planned=Math.max(300,Number($('#tw-planned-sqft').value)||base.sqft),intensity=Math.max(.25,Math.min(3,(Number($('#tw-intensity').value)||100)/100)),eff=Math.max(0,Math.min(.6,(Number($('#tw-efficiency').value)||0)/100)),non=Math.max(-.5,Math.min(1,(Number($('#tw-nonenergy').value)||0)/100)),scale=planned/base.sqft;
    const b=base.categories;
    const electric=b.electric*scale*intensity*(1-eff),gas=b.gas*scale*intensity*(1-eff),water=b.water*scale*intensity*(1+non*.35),tax=b.tax*scale*(1+non),insurance=b.insurance*scale*(1+non),other=b.other*scale*(1+non);
    const cats={electric,gas,water,tax,insurance,other};const total=Object.values(cats).reduce((a,b)=>a+b,0),delta=total-base.total,psf=total/planned,five=Array.from({length:5},(_,i)=>total*Math.pow(1+base.growth,i)).reduce((a,b)=>a+b,0);const impacts=Object.entries(cats).map(([k,v])=>({k,v,delta:v-(base.categories[k]||0)})).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta));return{planned,intensity,eff,non,cats,total,delta,psf,five,driver:impacts[0]};
  }
  function render(){const s=calc();if(!s)return;$('[data-twin-total]').textContent=money(s.total);$('[data-twin-delta]').textContent=(s.delta>=0?'+':'')+money(s.delta);$('[data-twin-psf]').textContent='$'+s.psf.toFixed(2);$('[data-twin-five]').textContent=compact(s.five);$('[data-twin-base]').textContent=money(base.total);$('[data-twin-base-copy]').textContent=`${base.address} · ${base.use} · ${base.sqft.toLocaleString()} ft² · modeled growth ${(base.growth*100).toFixed(1)}%/yr.`;const label={electric:'Electricity',gas:'Natural gas',water:'Water / sewer',tax:'Property tax',insurance:'Insurance',other:'Other recurring cost'}[s.driver?.k]||'Cost stack';$('[data-twin-driver]').textContent=s.driver?`${label} ${s.driver.delta>=0?'+':''}${money(s.driver.delta)}`:'—';$('[data-twin-copy]').textContent=`Scenario area ${s.planned.toLocaleString()} ft² · operating intensity ${Math.round(s.intensity*100)}% of base · energy efficiency improvement ${Math.round(s.eff*100)}% · non-energy adjustment ${s.non>=0?'+':''}${Math.round(s.non*100)}%. These are user-controlled assumptions, not predicted changes.`}
  function renderScenarios(){const zone=$('[data-scenarios]');zone.innerHTML='';scenarios.forEach((s,i)=>{const row=document.createElement('div');row.className='file-row';row.innerHTML='<span></span><button type="button" style="border:0;background:none;font:800 8px var(--mono);cursor:pointer">RESTORE</button>';row.querySelector('span').textContent=`Scenario ${i+1} · ${s.planned.toLocaleString()} ft² · ${money(s.total)}/yr · ${s.delta>=0?'+':''}${money(s.delta)} vs base`;row.querySelector('button').addEventListener('click',()=>{$('#tw-planned-sqft').value=s.planned;$('#tw-intensity').value=Math.round(s.intensity*100);$('#tw-efficiency').value=Math.round(s.eff*100);$('#tw-nonenergy').value=Math.round(s.non*100);render()});zone.appendChild(row)})}
  async function run(e){e.preventDefault();err('');const ai=$('#tw-address'),use=$('#tw-use').value,sqft=Number($('#tw-sqft').value);if(!sqft||sqft<300){err('Enter a valid floor area.');return}const btn=e.currentTarget.querySelector('button[type="submit"]');btn.disabled=true;try{const loc=await EI.requireResolvedAddress(ai);if(!loc)return;let energy=null;try{energy=await json(`/api/energy?state=${encodeURIComponent(loc.components?.state||'')}&use=${encodeURIComponent(use)}`)}catch(_e){}base=EI.estimate(loc.label,use,sqft,loc,energy);$('#tw-planned-sqft').value=String(base.sqft);$('#tw-intensity').value='100';$('#tw-efficiency').value='0';$('#tw-nonenergy').value='0';scenarios=[];$('[data-twin-result]').classList.add('show');render();renderScenarios();$('[data-twin-result]').scrollIntoView({behavior:'smooth',block:'start'})}catch(ex){err(ex.message||'Unable to build digital twin.')}finally{btn.disabled=false}}
  function prefill(){try{const s=JSON.parse(sessionStorage.getItem('ei_last')||'null');if(s){$('#tw-address').value=s.address||'';$('#tw-use').value=s.use||'industrial';$('#tw-sqft').value=s.sqft||'50000'}}catch(_e){}}
  document.addEventListener('DOMContentLoaded',()=>{prefill();$('[data-twin-form]')?.addEventListener('submit',run);['#tw-planned-sqft','#tw-intensity','#tw-efficiency','#tw-nonenergy'].forEach(s=>$(s)?.addEventListener('input',render));$('[data-save-scenario]')?.addEventListener('click',()=>{const s=calc();if(!s)return;scenarios.push({...s});scenarios=scenarios.slice(-6);renderScenarios()});$('[data-reset-twin]')?.addEventListener('click',()=>{if(!base)return;$('#tw-planned-sqft').value=base.sqft;$('#tw-intensity').value=100;$('#tw-efficiency').value=0;$('#tw-nonenergy').value=0;render()})});
})();