(()=>{
  'use strict';
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const clamp=(n,min=0,max=100)=>Math.max(min,Math.min(max,Number(n)||0));
  const round=n=>Math.round(Number(n)||0);
  const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)||0);
  const STORE_KEY='ei_project_watch_v2';
  const EVIDENCE_WEIGHTS={zoning:12,utility:14,permit:12,site:10,scope:12,quote:10};
  const PROFILES={
    restaurant:{hours:5000,load:.45,kwh:43.8,water:88,sewer:88,gas:82,data:48},retail:{hours:4000,load:.38,kwh:13.2,water:32,sewer:32,gas:38,data:58},office:{hours:3000,load:.36,kwh:13.6,water:38,sewer:38,gas:35,data:82},warehouse:{hours:3500,load:.38,kwh:5.5,water:18,sewer:18,gas:44,data:42},industrial:{hours:5200,load:.55,kwh:18,water:66,sewer:61,gas:70,data:52},multifamily:{hours:8760,load:.45,kwh:8.5,water:76,sewer:76,gas:62,data:68},residential:{hours:8760,load:.32,kwh:7.2,water:58,sewer:58,gas:55,data:54},other:{hours:4000,load:.4,kwh:12.6,water:44,sewer:42,gas:46,data:50}
  };
  const LOCK={electrical:82,plumbing:78,structural:96,hvac:72,fire:86,site:92,equipment:69,finishes:36};
  const BOTTLE={zoning:'Zoning / use',utilities:'Utilities',life:'Life safety',schedule:'Schedule / procurement',site:'Site / environment',health:'Health / occupancy'};
  let mode='builder',failureDB=[],lastSnapshot=null;

  function numText(sel){const t=$(sel)?.textContent||'';const m=t.replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):null}
  function set(sel,v){const el=$(sel);if(el)el.textContent=v}
  function safeLoad(){try{return JSON.parse(localStorage.getItem(STORE_KEY)||'[]')}catch(_e){return[]}}
  function safeSave(v){try{localStorage.setItem(STORE_KEY,JSON.stringify(v));return true}catch(_e){return false}}
  function getMode(){return mode}
  function setMode(next){mode=next==='buyer'?'buyer':'builder';$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));set('[data-mode-title]',mode==='builder'?'Builder lens: sequence the work before the work sequences you.':'Buyer lens: prove the property can carry the plan before the deal carries you.');set('[data-mode-copy]',mode==='builder'?'The engine stays the same. Builder mode emphasizes scope ownership, utilities, approvals, long-lead dependencies and release gates.':'The engine stays the same. Buyer mode emphasizes feasibility, unknown obligations, downside exposure, seller diligence and walk-away conditions.');set('[data-action-mode]',mode==='builder'?'Builder action orders':'Buyer action orders');const textarea=$('#pj-brief-text');if(textarea)textarea.placeholder=mode==='builder'?'Example: Convert a 22,000 sq ft warehouse into a food-production plant within 9 months. Heavy power, process water, new HVAC and electrical service are likely.':'Example: I am considering buying a 12,000 sq ft former retail building for a restaurant. I need to know what could block the use, what the seller has not proven, and what I should verify before closing.';renderActionOrders();renderEvidence()}

  function identifyUse(text){
    const rules=[['restaurant',/restaurant|commercial kitchen|cafe|bar\b|food service/i],['warehouse',/warehouse|distribution|fulfillment/i],['industrial',/industrial|manufactur|production plant|factory|fabrication/i],['office',/office|workspace/i],['retail',/retail|storefront|shop\b/i],['multifamily',/multifamily|apartments?|multi[- ]family/i],['residential',/single[- ]family|house\b|residential/i]];
    return rules.find(([,r])=>r.test(text))?.[0]||null;
  }
  function useFromToken(s=''){return identifyUse(s)||null}
  function parseBrief(){
    const text=($('#pj-brief-text')?.value||'').trim();if(text.length<12){set('[data-brief-status]','Add a little more detail so the intake can detect useful project conditions.');return}
    const found=[];
    if(/\b(buy|buying|purchase|purchasing|acquire|acquisition|lease|leasing|closing|seller)\b/i.test(text))setMode('buyer');
    else if(/\b(build|builder|construct|construction|renovate|renovation|fit[- ]?out|contractor|preconstruction|precon)\b/i.test(text))setMode('builder');
    const conversion=text.match(/(?:convert|turn|change|repurpose)\s+(?:an?\s+|the\s+)?([a-z -]{3,30}?)\s+(?:into|to)\s+(?:an?\s+|the\s+)?([a-z -]{3,30})(?:[,.]|\s+with|\s+for|$)/i);
    if(conversion){const a=useFromToken(conversion[1]),b=useFromToken(conversion[2]);if(a){$('#pj-current').value=a;found.push(`current: ${a}`)}if(b){$('#pj-use').value=b;found.push(`proposed: ${b}`)}}
    else{const u=identifyUse(text);if(u){$('#pj-use').value=u;found.push(`use: ${u}`)}}
    const area=text.match(/([0-9][0-9,]*(?:\.\d+)?)\s*(?:sq\.?\s*ft|sqft|square\s*feet|ft²)/i);if(area){$('#pj-sqft').value=String(Math.round(Number(area[1].replace(/,/g,''))));found.push(`${Number(area[1].replace(/,/g,'')).toLocaleString()} ft²`)}
    const months=text.match(/(?:within|in|over|about|roughly)?\s*(\d{1,2})\s*(?:months?|mos?\b)/i);if(months){$('#pj-months').value=months[1];found.push(`${months[1]} months`)}
    const contingency=text.match(/(\d+(?:\.\d+)?)\s*%\s*(?:contingency|contingent)/i);if(contingency){$('#pj-contingency').value=contingency[1];found.push(`${contingency[1]}% contingency`)}
    const amps=text.match(/(\d{2,5})\s*(?:amps?|a)\b/i);if(amps){$('#pj-electric').value=amps[1];found.push(`${amps[1]}A service`)}
    const triggerRules={food:/commercial kitchen|restaurant|food production|food service|grease|hood/i,heavyPower:/heavy power|high power|large electrical|3[- ]?phase|three[- ]?phase|transformer|high electrical|manufactur/i,processWater:/process water|process wastewater|floor drain|washdown|high water|drainage/i,highOccupancy:/high occupancy|assembly|event|public occupancy|many customers|seating/i,hazmat:/hazmat|hazardous|chemical|emission|solvent|flammable|spray booth/i,exterior:/site work|parking lot|curb cut|exterior|loading dock|paving|access road/i,utilityUpgrade:/utility upgrade|service upgrade|new service|transformer upgrade|meter upgrade/i,specialEquipment:/long[- ]lead|fixed equipment|special equipment|process equipment|generator|chiller|boiler/i};
    const interventionRules={electrical:/electrical service|service upgrade|transformer|switchgear|panel upgrade/i,plumbing:/process plumbing|new plumbing|floor drain|grease trap|wastewater/i,structural:/structural|column|beam|foundation|load[- ]bearing/i,hvac:/hvac|ventilation|make[- ]up air|hood|chiller|air handling/i,fire:/sprinkler|fire suppression|fire alarm/i,site:/paving|curb cut|site work|loading dock|parking lot|access/i,equipment:/fixed equipment|process equipment|generator|machinery/i,finishes:/partition|interior finish|drywall|millwork/i};
    Object.entries(triggerRules).forEach(([k,r])=>{if(r.test(text)){const el=$(`.chip-grid input[value="${k}"]`);if(el){el.checked=true;found.push(k)}}});
    Object.entries(interventionRules).forEach(([k,r])=>{if(r.test(text)){const el=$(`[data-interventions] input[value="${k}"]`);if(el){el.checked=true;found.push(k)}}});
    const zone=$('[data-detected-row]');if(zone){zone.innerHTML='';[...new Set(found)].slice(0,14).forEach(x=>{const s=document.createElement('span');s.className='detected-chip';s.textContent=x;zone.appendChild(s)})}
    set('[data-brief-status]',found.length?`Detected ${[...new Set(found)].length} project signals. They were applied as editable suggestions—confirm them before running the model.`:'No strong structured signals were detected. Keep the narrative; set the project controls manually before running.');
  }

  function getPlan(){
    const triggers=new Set($$('.chip-grid input:checked').filter(x=>!x.closest('[data-interventions]')).map(x=>x.value));
    const interventions=new Set($$('[data-interventions] input:checked').map(x=>x.value));
    return{mode,current:$('#pj-current')?.value||'vacant',use:$('#pj-use')?.value||'other',sqft:Number($('#pj-sqft')?.value)||0,months:Number($('#pj-months')?.value)||12,contingency:Number($('#pj-contingency')?.value)||0,serviceAmps:Number($('#pj-electric')?.value)||0,triggers,interventions,brief:$('#pj-brief-text')?.value||'',evidence:Object.fromEntries($$('[data-evidence-key]').map(x=>[x.dataset.evidenceKey,!!x.checked]))};
  }
  async function getEnergy(state,use){if(!state)return null;try{const r=await fetch(`/api/energy?state=${encodeURIComponent(state)}&use=${encodeURIComponent(use)}`,{headers:{Accept:'application/json'}}),d=await r.json().catch(()=>null);return r.ok&&d?.ok?d:null}catch(_e){return null}}
  function utilityMetrics(plan,energy,serviceAmps){
    const p=PROFILES[plan.use]||PROFILES.other,intensity=Number(energy?.intensity?.kwhSqft)||p.kwh,annualKwh=intensity*plan.sqft,peakKw=annualKwh/Math.max(1,p.hours)/Math.max(.2,p.load),res=plan.use==='residential',kwPerAmp=res?.24:(Math.sqrt(3)*.208*.9),serviceKw=serviceAmps?serviceAmps*kwPerAmp:0,headroom=serviceAmps?((serviceKw-peakKw)/serviceKw)*100:null;
    const pressure={electric:clamp((intensity/45)*72+(plan.triggers.has('heavyPower')?24:0)+(plan.triggers.has('utilityUpgrade')?12:0)),water:clamp(p.water+(plan.triggers.has('processWater')?24:0)+(plan.triggers.has('food')?8:0)),sewer:clamp(p.sewer+(plan.triggers.has('processWater')?28:0)+(plan.triggers.has('food')?8:0)),gas:clamp(p.gas+(plan.triggers.has('food')?16:0)+(plan.triggers.has('heavyPower')?4:0)),data:clamp(p.data+(plan.triggers.has('specialEquipment')?8:0))};
    return{pressure,headroom,unknown:serviceAmps?4:5,peakKw};
  }
  function fragilityMetrics(plan,utility,model){const change=plan.current!=='vacant'&&plan.current!==plan.use,utilityUnknown=utility.unknown/5*100,approval=clamp(plan.triggers.size*13+(change?28:0)+(plan.triggers.has('hazmat')?18:0)),schedule=plan.months<=4?100:plan.months<=7?82:plan.months<=10?62:plan.months<=15?38:20,contingency=plan.contingency<3?100:plan.contingency<5?86:plan.contingency<8?66:plan.contingency<12?42:22,locks=[...plan.interventions].map(k=>LOCK[k]).filter(Number.isFinite),lock=locks.length?locks.reduce((a,b)=>a+b,0)/locks.length:18,operating=Number(model?.risk)||45,score=clamp(utilityUnknown*.24+approval*.24+schedule*.18+contingency*.14+lock*.10+operating*.10);return{score,lock,change}}
  function bottleneckMetrics(plan,utility){const t=plan.triggers,change=plan.current!=='vacant'&&plan.current!==plan.use,scheduleBase=plan.months<=5?92:plan.months<=8?72:plan.months<=12?52:30,scores={zoning:clamp(22+(change?54:0)+(plan.current==='vacant'?18:0)+(t.has('exterior')?10:0)+(t.has('hazmat')?12:0)),utilities:clamp(22+(utility.unknown/5)*34+(t.has('heavyPower')?34:0)+(t.has('processWater')?18:0)+(t.has('utilityUpgrade')?30:0)),life:clamp(18+(t.has('highOccupancy')?42:0)+(t.has('food')?24:0)+(t.has('specialEquipment')?12:0)+(change?8:0)),schedule:clamp(scheduleBase+(t.has('specialEquipment')?18:0)+(t.has('utilityUpgrade')?16:0)),site:clamp(16+(t.has('exterior')?54:0)+(t.has('hazmat')?48:0)+(t.has('processWater')?12:0)),health:clamp(12+(t.has('food')?64:0)+(t.has('highOccupancy')?34:0)+(change?10:0))};const ranked=Object.entries(scores).sort((a,b)=>b[1]-a[1]);return{scores,ranked,top:BOTTLE[ranked[0][0]],topScore:ranked[0][1]}}
  async function computeSite(loc,plan,serviceAmps){const energy=await getEnergy(loc?.components?.state,plan.use),model=EI.estimate(loc.label,plan.use,plan.sqft,loc,energy),utility=utilityMetrics(plan,energy,serviceAmps),frag=fragilityMetrics(plan,utility,model),bot=bottleneckMetrics(plan,utility);return{loc,energy,model,utility,frag,bot}}

  function evidenceScore(){
    const addr=($('[data-ledger-address]')?.textContent||'').trim(),energy=($('[data-ledger-energy]')?.textContent||'').trim(),plan=getPlan();let score=0;
    const addressOK=addr&& !/not yet|not run/i.test(addr);if(addressOK)score+=18;
    const publicOK=energy&&!/no public|not yet|not run/i.test(energy);if(publicOK)score+=14;
    if(plan.serviceAmps)score+=10;
    Object.entries(plan.evidence).forEach(([k,v])=>{if(v)score+=EVIDENCE_WEIGHTS[k]||0});
    return{score:clamp(score),addressOK,publicOK,plan};
  }
  function gradeFor(s){return s>=85?'A':s>=70?'B':s>=52?'C':s>=34?'D':'E'}
  function renderEvidence(){
    const box=$('[data-evidence-gauge]');if(!box)return;const e=evidenceScore(),grade=gradeFor(e.score);box.style.background=`conic-gradient(var(--lime) 0deg ${e.score*3.6}deg,#ded8cc ${e.score*3.6}deg 360deg)`;set('[data-evidence-score]',`${round(e.score)}`);set('[data-evidence-grade]',`Evidence depth ${grade}`);
    const buyer=mode==='buyer';set('[data-evidence-copy]',e.score>=80?'The project has a comparatively deep screening record. Remaining unknowns should be narrow and explicit.':e.score>=55?'The project has useful evidence, but several conclusions still depend on assumptions or user-entered facts.':'The project is still assumption-heavy. Treat scores as triage until the missing evidence is closed.');
    set('[data-e-layer-verified]',e.addressOK?'ADDRESS VERIFIED':'ADDRESS OPEN');set('[data-e-layer-public]',e.publicOK?'PUBLIC SIGNAL RETURNED':'PUBLIC SIGNAL LIMITED');set('[data-e-layer-user]',`${Object.values(e.plan.evidence).filter(Boolean).length} diligence items + ${e.plan.serviceAmps?'service input':'no service input'}`);set('[data-e-layer-model]',`${buyer?'Buyer':'Builder'} lens · screening model`);
    const missing=[];if(!e.plan.evidence.zoning)missing.push(buyer?'Written use / zoning confirmation':'Zoning or use-path confirmation');if(!e.plan.evidence.utility)missing.push('Utility capacity / service evidence');if(!e.plan.evidence.permit)missing.push('Permit / approval path');if(!e.plan.evidence.site)missing.push('Site / environmental diligence');if(!e.plan.evidence.scope)missing.push(buyer?'Inspection / condition scope':'Trade responsibility / scope matrix');if(!e.plan.evidence.quote)missing.push(buyer?'Seller cost records / real quotes':'Real quote / budget evidence');
    const zone=$('[data-evidence-next-list]');if(zone){zone.innerHTML='';missing.slice(0,5).forEach(x=>{const s=document.createElement('span');s.textContent=x;zone.appendChild(s)})}
    set('[data-evidence-next-label]',missing.length?`Best next evidence to raise depth (${grade} → higher)`:'Core evidence checklist is filled. Keep source documents current as the project changes.');
  }

  function projectPatternKeys(){const p=getPlan(),keys=new Set(['approval_dependency']);if(p.current!=='vacant'&&p.current!==p.use)keys.add('change_of_use_cascade');if(!p.serviceAmps||p.triggers.has('utilityUpgrade')||p.triggers.has('heavyPower')){keys.add('approval_critical_path');keys.add('schedule_dependency')}if([...p.interventions].some(k=>(LOCK[k]||0)>=80))keys.add('irreversible_before_entitlement');if(p.months<10)keys.add('entitlement_expiry');return keys}
  async function loadFailureDB(){try{const r=await fetch('/data/failure-library.json',{headers:{Accept:'application/json'}}),d=await r.json();if(r.ok&&Array.isArray(d.records))failureDB=d.records;renderFailureEvidence()}catch(_e){set('[data-failure-source-status]','Primary-source evidence library unavailable in this session. Pattern matching still runs, but source records are not shown.')}}
  function renderFailureEvidence(){const zone=$('[data-failure-evidence]');if(!zone)return;if(!failureDB.length){zone.innerHTML='<div class="status-note">Loading primary-source project records…</div>';return}const keys=projectPatternKeys(),ranked=failureDB.map(r=>({...r,match:(r.patterns||[]).filter(p=>keys.has(p)).length})).sort((a,b)=>b.match-a.match||b.year-a.year).filter(r=>r.match>0).slice(0,6);zone.innerHTML='';ranked.forEach(r=>{const a=document.createElement('article');a.className='source-card';a.innerHTML='<span class="source-tag"></span><h4></h4><p></p><footer><span></span><a target="_blank" rel="noopener">Open source ↗</a></footer>';a.querySelector('.source-tag').textContent=`${r.agency} · ${r.status}`;a.querySelector('h4').textContent=`${r.case} · ${r.premises}`;a.querySelector('p').textContent=r.lesson;a.querySelector('footer span').textContent=`${r.match} matched pattern${r.match===1?'':'s'} · ${r.year}`;a.querySelector('a').href=r.sourceUrl;zone.appendChild(a)});set('[data-failure-source-status]',ranked.length?`${ranked.length} relevant public primary-source records shown. These are examples, not statistical probabilities.`:'No source record in the current seed library maps closely to this project fingerprint yet.');upgradeFailureCards()}
  function upgradeFailureCards(){const map={'Capacity discovered after design':'Get a written service/capacity answer before design freeze.','Change-of-use cascade':'Get the proposed use classification and approval path in writing.','Approval on the critical path':'Put each external approval on the schedule with an owner and expiry date.','Trade-boundary scope gap':'Issue a responsibility matrix that assigns every interface to one party.','Irreversible spend before entitlement':'Do not release high-lock work until its upstream gate is closed.','Long-lead dependency trap':'Get confirmed lead time, release date and substitute path.','Contingency squeeze':'Tie contingency to unresolved scope and dependency, not a habitual percentage.'};$$('.failure-card').forEach(card=>{if(card.querySelector('.failure-nextline'))return;const title=card.querySelector('h3')?.textContent||'',next=map[title]||'Assign an owner and evidence requirement to close this pattern.';const d=document.createElement('div');d.className='failure-nextline';d.style.cssText='margin-top:10px;padding-top:9px;border-top:1px dashed var(--line);font:800 8px/1.45 var(--mono);text-transform:uppercase';d.textContent=`NEXT → ${next}`;card.appendChild(d)})}

  function actionOrders(){
    const p=getPlan(),top=($('[data-r-bottleneck]')?.textContent||'').trim(),items=[];
    const push=(title,who,ask,close)=>items.push({title,who,ask,close});
    if(p.current!=='vacant'&&p.current!==p.use||/zoning/i.test(top))push('Lock the use path','Municipal zoning / planning staff',`For ${p.use} at this exact parcel, is the use by-right, conditional, special, prohibited, or treated as a change of use? What approvals expire or depend on later milestones?`,'Written zoning/use determination, permit applicability note, or cited code section tied to the parcel.');
    if(!p.serviceAmps||p.triggers.has('heavyPower')||p.triggers.has('utilityUpgrade')||/utilit/i.test(top))push('Prove electrical capacity','Serving electric utility + electrical engineer','What voltage, phase and amperage serve the site today; what capacity is actually available for the proposed load; and what upgrade, study, transformer or lead time would be required?','Utility service/capacity letter or service record plus engineer load calculation.');
    if(p.triggers.has('processWater'))push('Prove water + discharge path','Water/sewer utility or public works','What meter/service size exists, what flow is available, what sewer/discharge limits apply, and does the proposed process require pretreatment or a special discharge approval?','Utility record plus written discharge/connection requirements.');
    if(p.triggers.has('food')||p.triggers.has('highOccupancy')||/life safety|health/i.test(top))push('Freeze the occupancy path before the layout','Building official + fire marshal + health authority','What occupancy/use classification, egress, suppression, hood/ventilation, restroom and health-review requirements are triggered by this exact use and occupant load?','Written code/plan-review comments or pre-application meeting record.');
    if(p.triggers.has('hazmat')||/site/i.test(top))push('Clear the environmental gate','Environmental reviewer + fire authority','What storage, emissions, spill, discharge, hazardous-material or site-history requirements apply, and which one must be resolved before permits or equipment release?','Environmental/site diligence memo and agency/fire requirements.');
    if(mode==='builder'){push('Close the scope interfaces','GC / preconstruction lead + major trades','Who owns trenching, utility-company coordination, controls, penetrations, temporary services, testing, startup, patching and permit fees? Where do two scopes overlap or neither scope carry the work?','Signed responsibility matrix cross-referenced to bids and scope sheets.');if(p.triggers.has('specialEquipment')||p.months<9)push('Protect the critical path','Scheduler + procurement lead','Which equipment, utility action or approval has the longest uncontrollable lead time; what is the last responsible release date; and what substitute path exists?','Procurement log with confirmed vendor lead times and schedule logic.');}
    else{push('Make the seller prove the property history','Seller / broker / landlord','Provide recent utility bills, tax history, insurance information, certificates of occupancy, open permits/violations, major repair records and known service capacities.','Source documents—not a marketing summary or verbal representation.');push('Define the walk-away condition','Buyer + counsel + lender / advisor',`Which unresolved finding would make this ${p.use} plan unacceptable before closing: prohibited use, inadequate utility service, environmental issue, major capital requirement, or approval timing?`,'Written diligence condition, contingency, price adjustment or termination right tied to the finding.');}
    const locks=[...p.interventions].filter(k=>(LOCK[k]||0)>=80);if(locks.length)push('Gate irreversible spend','Owner + design / construction lead',`Do not release ${locks.join(', ')} until the approvals and utility dependencies upstream of that work are verified.`,'Release gate in the project schedule tied to named evidence.');
    return items.slice(0,7);
  }
  function renderActionOrders(){const zone=$('[data-action-orders]');if(!zone)return;zone.innerHTML='';actionOrders().forEach((a,i)=>{const el=document.createElement('article');el.className='action-order';el.innerHTML='<strong></strong><div><b>Action</b><p></p></div><div><b>Who + what to ask</b><p></p></div><div><b>Close with evidence</b><p></p></div>';el.querySelector('strong').textContent=String(i+1).padStart(2,'0');el.children[1].querySelector('p').textContent=a.title;el.children[2].querySelector('p').textContent=`${a.who} — ${a.ask}`;el.children[3].querySelector('p').textContent=a.close;zone.appendChild(el)});renderFailureEvidence()}

  function planForStorage(){const p=getPlan();return{mode:p.mode,current:p.current,use:p.use,sqft:p.sqft,months:p.months,contingency:p.contingency,serviceAmps:p.serviceAmps,triggers:[...p.triggers],interventions:[...p.interventions],brief:p.brief,evidence:p.evidence,address:$('#pj-address')?.value||''}}
  function readDisplayedMetrics(){return{fragility:numText('[data-r-fragility]'),bottleneck:($('[data-r-bottleneck]')?.textContent||'—').trim(),utilityUnknown:numText('[data-r-utility]'),lock:($('[data-r-lock]')?.textContent||'—').trim(),evidence:evidenceScore().score}}
  async function fullCurrentSnapshot(){const inputs=planForStorage(),saved=JSON.parse(sessionStorage.getItem('ei_last')||'null');let cost=null,energyPeriod=null;if(saved?.location&&saved.address===inputs.address){const energy=await getEnergy(saved.location.components?.state,inputs.use),model=EI.estimate(saved.location.label,inputs.use,inputs.sqft,saved.location,energy);cost=round(model.total);energyPeriod=energy?.electricity?.period||null}return{at:new Date().toISOString(),inputs,metrics:{...readDisplayedMetrics(),cost,energyPeriod}}}
  function idFor(inputs){return btoa(unescape(encodeURIComponent(`${inputs.address}|${inputs.use}|${inputs.mode}`))).replace(/[^a-z0-9]/gi,'').slice(0,48)}
  async function saveCurrentProject(){const result=$('[data-project-results]');if(!result?.classList.contains('show')){set('[data-watch-status]','Run Project Intelligence first, then save the scored project.');return}const snap=await fullCurrentSnapshot(),projects=safeLoad(),id=idFor(snap.inputs),idx=projects.findIndex(p=>p.id===id);if(idx>=0){projects[idx].inputs=snap.inputs;projects[idx].snapshots=(projects[idx].snapshots||[]).concat(snap).slice(-20);projects[idx].updated=snap.at}else projects.unshift({id,name:snap.inputs.address||`${snap.inputs.use} project`,inputs:snap.inputs,created:snap.at,updated:snap.at,snapshots:[snap]});if(safeSave(projects)){lastSnapshot=snap;set('[data-watch-status]',idx>=0?'Project updated. The new snapshot is compared with the prior saved run below.':'Project saved to this browser. Re-run after adding evidence or when public signals change, then save again to track the delta.');renderWatch()}else set('[data-watch-status]','Could not save in this browser storage context.')}
  function deltaText(now,prev,suffix=''){if(now==null||prev==null)return'—';const d=now-prev;return`${d>0?'+':''}${round(d)}${suffix}`}
  function renderWatch(){const zone=$('[data-watch-grid]');if(!zone)return;const projects=safeLoad();zone.innerHTML='';if(!projects.length){zone.innerHTML='<div class="status-note">No watched projects yet. Run Project Intelligence and choose “Save / update project.”</div>';return}projects.slice(0,8).forEach(p=>{const snaps=p.snapshots||[],now=snaps[snaps.length-1],prev=snaps[snaps.length-2],card=document.createElement('article');card.className='watch-card';card.innerHTML='<header><div><span></span><h3></h3></div><span class="watch-age"></span></header><div class="watch-deltas"><div><span>Fragility Δ</span><b></b></div><div><span>Evidence Δ</span><b></b></div><div><span>Cost Δ</span><b></b></div><div><span>Bottleneck</span><b></b></div></div><footer><button data-load>Load project</button><button data-delete>Remove</button></footer>';card.querySelector('header>div>span').textContent=`${p.inputs.mode||'builder'} · ${p.inputs.use||'project'}`;card.querySelector('h3').textContent=p.name;card.querySelector('.watch-age').textContent=new Date(p.updated).toLocaleDateString();const bs=card.querySelectorAll('.watch-deltas b');bs[0].textContent=prev?deltaText(now?.metrics?.fragility,prev?.metrics?.fragility):'BASE';bs[1].textContent=prev?deltaText(now?.metrics?.evidence,prev?.metrics?.evidence):'BASE';bs[2].textContent=prev&&now?.metrics?.cost!=null&&prev?.metrics?.cost!=null?`${(now.metrics.cost-prev.metrics.cost)>0?'+':''}${money(now.metrics.cost-prev.metrics.cost)}`:'BASE';bs[3].textContent=prev&&prev?.metrics?.bottleneck!==now?.metrics?.bottleneck?`${prev.metrics.bottleneck} → ${now.metrics.bottleneck}`:(now?.metrics?.bottleneck||'—');card.querySelector('[data-load]').addEventListener('click',()=>loadProject(p));card.querySelector('[data-delete]').addEventListener('click',()=>{const next=safeLoad().filter(x=>x.id!==p.id);safeSave(next);renderWatch()});zone.appendChild(card)})}
  function loadProject(p){const x=p.inputs||{};setMode(x.mode);if($('#pj-address'))$('#pj-address').value=x.address||'';if($('#pj-current'))$('#pj-current').value=x.current||'vacant';if($('#pj-use'))$('#pj-use').value=x.use||'other';if($('#pj-sqft'))$('#pj-sqft').value=x.sqft||12000;if($('#pj-months'))$('#pj-months').value=x.months||12;if($('#pj-contingency'))$('#pj-contingency').value=x.contingency??10;if($('#pj-electric'))$('#pj-electric').value=x.serviceAmps||'';if($('#pj-brief-text'))$('#pj-brief-text').value=x.brief||'';$$('.chip-grid input').forEach(el=>{const vals=el.closest('[data-interventions]')?(x.interventions||[]):(x.triggers||[]);el.checked=vals.includes(el.value)});$$('[data-evidence-key]').forEach(el=>el.checked=!!x.evidence?.[el.dataset.evidenceKey]);renderEvidence();renderActionOrders();set('[data-watch-status]','Saved inputs loaded. Run Project Intelligence to refresh the address/public evidence and produce a new comparable snapshot.');window.scrollTo({top:$('.project-input')?.offsetTop||0,behavior:'smooth'})}

  async function runCompare(){const out=$('[data-compare-result]'),err=$('[data-compare-error]');if(err)err.textContent='';const saved=JSON.parse(sessionStorage.getItem('ei_last')||'null');if(!saved?.location||!$('[data-project-results]')?.classList.contains('show')){if(err)err.textContent='Run the primary project first so Site A has a verified address and current score.';return}const plan=getPlan(),bInput=$('#pj-b-address'),bAmps=Number($('#pj-b-electric')?.value)||0,btn=$('[data-run-project-compare]');if(!bInput?.value.trim()){if(err)err.textContent='Enter a second site address.';return}btn.disabled=true;try{const bLoc=await EI.requireResolvedAddress(bInput);if(!bLoc)return;const [a,b]=await Promise.all([computeSite(saved.location,plan,plan.serviceAmps),computeSite(bLoc,plan,bAmps)]),aScore=round(a.frag.score),bScore=round(b.frag.score),aCost=round(a.model.total),bCost=round(b.model.total);set('[data-cmp-a-address]',saved.location.label);set('[data-cmp-b-address]',bLoc.label);set('[data-cmp-a-frag]',`${aScore}/100`);set('[data-cmp-b-frag]',`${bScore}/100`);set('[data-cmp-a-util]',`${a.utility.unknown}/5`);set('[data-cmp-b-util]',`${b.utility.unknown}/5`);set('[data-cmp-a-bot]',a.bot.top);set('[data-cmp-b-bot]',b.bot.top);set('[data-cmp-a-lock]',`${round(a.frag.lock)}/100`);set('[data-cmp-b-lock]',`${round(b.frag.lock)}/100`);set('[data-cmp-a-cost]',money(aCost));set('[data-cmp-b-cost]',money(bCost));const aPoints=(100-aScore)*.32+(5-a.utility.unknown)*6+(100-a.bot.topScore)*.22+(100-a.frag.lock)*.12+(Math.min(aCost,bCost)/aCost)*28,bPoints=(100-bScore)*.32+(5-b.utility.unknown)*6+(100-b.bot.topScore)*.22+(100-b.frag.lock)*.12+(Math.min(aCost,bCost)/bCost)*28,aWin=aPoints>=bPoints;$$('.compare-site').forEach(x=>x.classList.remove('winner'));$(`[data-cmp-${aWin?'a':'b'}-site]`)?.classList.add('winner');set('[data-compare-verdict]',`${aWin?'Site A':'Site B'} is the stronger current screen for the same plan because the combined burden of fragility, unresolved utility evidence, bottleneck pressure, capital lock-in and modeled operating cost is lower. This is a screening comparison—not a site-selection conclusion.`);out?.classList.add('show')}catch(ex){if(err)err.textContent=ex.message||'Unable to compare the second site.'}finally{btn.disabled=false}}

  function afterCoreRun(){renderEvidence();renderActionOrders();upgradeFailureCards();renderFailureEvidence();const p=getPlan();set('[data-mode-result]',mode==='builder'?'BUILDER':'BUYER');set('[data-mode-result-copy]',mode==='builder'?'Sequence approvals, utilities, scope and irreversible releases before construction hardens.':'Prove feasibility, seller claims and walk-away conditions before closing hardens.');}
  function observeCore(){const target=$('[data-r-fragility]');if(!target)return;new MutationObserver(()=>setTimeout(afterCoreRun,40)).observe(target,{childList:true,characterData:true,subtree:true})}
  function bind(){
    $$('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
    $('[data-parse-brief]')?.addEventListener('click',parseBrief);
    $$('[data-evidence-key]').forEach(x=>x.addEventListener('change',()=>{renderEvidence();renderActionOrders()}));
    $('[data-save-project]')?.addEventListener('click',saveCurrentProject);
    $('[data-run-project-compare]')?.addEventListener('click',runCompare);
    $('[data-rescore-project]')?.addEventListener('click',()=>{const f=$('[data-project-form]');if(f?.requestSubmit)f.requestSubmit()});
    setMode('builder');renderWatch();renderEvidence();renderActionOrders();observeCore();loadFailureDB();
  }
  document.addEventListener('DOMContentLoaded',bind);
})();
