(()=>{
  'use strict';
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const clamp=(n,min=0,max=100)=>Math.max(min,Math.min(max,Number(n)||0));
  const fmt=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(Number(n)||0);
  const VAULT_KEY='ei_project_evidence_v4';
  const STRENGTH_RANK={verbal:1,document:2,professional:3,authority:4};
  const QUALITY_VALUE={none:0,verbal:.25,document:.65,professional:.85,authority:1};
  const KEY_LABEL={serviceAmps:'Electrical service',voltage:'Service voltage',phase:'Electrical phase',peakKw:'Project peak demand',waterDemand:'Water demand',waterCapacity:'Water capacity',sewerDemand:'Sewer flow',sewerCapacity:'Sewer allowance',gasDemand:'Gas demand',gasCapacity:'Gas capacity',occupantLoad:'Occupant load',zoningDisposition:'Use / zoning status',approvalDisposition:'Approval status',leadTime:'Lead time',permitRef:'Permit / case',projectAmount:'Project amount'};
  let selectedFile=null,lastContradictions=[],depState=null,refreshTimer=null;

  function set(sel,v){const el=$(sel);if(el)el.textContent=v}
  function safeLoad(){try{const v=JSON.parse(localStorage.getItem(VAULT_KEY)||'[]');return Array.isArray(v)?v:[]}catch(_e){return[]}}
  function safeSave(v){try{localStorage.setItem(VAULT_KEY,JSON.stringify(v));return true}catch(_e){return false}}
  function norm(s){return String(s||'').trim().toLowerCase().replace(/\s+/g,' ')}
  function projectKey(){const address=norm($('#pj-address')?.value),use=$('#pj-use')?.value||'other';return `${address||'draft'}|${use}`}
  function hashText(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
  function debounceRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(refreshAll,120)}
  function ageDays(date){if(!date)return null;const d=new Date(`${date}T12:00:00Z`);if(Number.isNaN(d.getTime()))return null;return Math.floor((Date.now()-d.getTime())/86400000)}
  function staleLimit(categories){if(categories.some(x=>['utility','permit','quote'].includes(x)))return 365;if(categories.includes('zoning'))return 730;if(categories.includes('site'))return 1095;return 730}
  function isStale(record){const age=ageDays(record.sourceDate);return age!=null&&age>staleLimit(record.categories||[])}
  function effectiveStrength(record){if(!isStale(record))return record.strength;const r=STRENGTH_RANK[record.strength]||1;return r>STRENGTH_RANK.document?'document':record.strength}
  function activeRecords(){const key=projectKey(),rows=safeLoad();return rows.filter(r=>r.projectKey===key)}
  function migrateDraft(){const address=norm($('#pj-address')?.value),use=$('#pj-use')?.value||'other';if(!address)return;const rows=safeLoad(),draft=`draft|${use}`,target=`${address}|${use}`,draftRows=rows.filter(r=>r.projectKey===draft),targetRows=rows.filter(r=>r.projectKey===target);if(draftRows.length&&!targetRows.length){draftRows.forEach(r=>r.projectKey=target);safeSave(rows)}}
  function q(key){const sel=$(`[data-quality-key="${key}"]`);return QUALITY_VALUE[sel?.value||'none']||0}
  function trigger(name){return !!$(`.chip-grid input[value="${name}"]:checked`)}
  function intervention(name){return !!$(`[data-interventions] input[value="${name}"]:checked`)}
  function num(sel){return Number($(sel)?.value)||0}
  function currentTech(){return{amps:num('#pj-electric'),voltage:num('#pj-voltage')||208,phase:num('#pj-phase')||3,pf:num('#pj-pf')||.9,peakKw:num('#pj-known-peak-kw'),waterDemand:num('#pj-water-demand'),waterCapacity:num('#pj-water-cap'),sewerDemand:num('#pj-sewer-demand'),sewerCapacity:num('#pj-sewer-cap'),gasDemand:num('#pj-gas-demand'),gasCapacity:num('#pj-gas-cap'),occupants:num('#pj-occupants')}}
  function electricCapacity(t){return t.amps?t.amps*t.voltage*t.pf*(t.phase===3?Math.sqrt(3):1)/1000:0}
  function directStatus(demand,capacity){if(!(demand>0&&capacity>0))return{known:false,over:false,headroom:null};const h=(capacity-demand)/capacity*100;return{known:true,over:h<0,headroom:h}}
  function currentCapacity(){const t=currentTech();return{electric:directStatus(t.peakKw,electricCapacity(t)),water:directStatus(t.waterDemand,t.waterCapacity),sewer:directStatus(t.sewerDemand,t.sewerCapacity),gas:directStatus(t.gasDemand,t.gasCapacity)}}

  function injectUI(){
    const brief=$('.project-brief');
    if(brief&&!$('.evidence-inbox'))brief.insertAdjacentHTML('afterend',`
      <section class="evidence-inbox" aria-label="Project evidence inbox">
        <div class="ei4-head"><div><span>00B / Evidence Inbox</span><h2>Bring the actual record into the project.</h2></div><p>Paste copied text or load a text-based project file. ExpenseIntel extracts concrete claims—service size, load, capacity, approvals, use status, lead times and project amounts—then keeps the extracted record in this browser. Detected claims are not treated as verified until source strength is assigned.</p></div>
        <div class="evidence-ingest-grid">
          <div class="evidence-drop" data-evidence-drop tabindex="0"><input id="ei-evidence-file" type="file" accept=".txt,.md,.csv,.json,text/plain,text/csv,application/json" hidden><div class="drop-orbit"><i></i><b>DROP</b></div><h3>Text evidence file</h3><p>TXT · CSV · JSON · MD, or paste copied text from a PDF/email below.</p><button type="button" data-pick-evidence>Choose file</button><small data-file-name>No file selected</small></div>
          <div class="evidence-compose">
            <div class="evidence-meta-grid"><label>Evidence name<input id="ei-evidence-name" placeholder="Utility capacity letter"></label><label>Source type<select id="ei-evidence-type"><option value="agency">Agency / utility record</option><option value="professional">Engineer / architect / professional report</option><option value="inspection">Inspection / diligence report</option><option value="contract">Contract / bid / scope document</option><option value="seller">Seller / landlord document</option><option value="marketing">Broker / marketing claim</option><option value="project">Internal project record</option><option value="other">Other</option></select></label><label>Source strength<select id="ei-evidence-strength"><option value="authority">Written agency / utility confirmation</option><option value="professional">Professional report / calculation</option><option value="document">Project / transaction document</option><option value="verbal">Verbal / marketing claim</option></select></label><label>Document date<input id="ei-evidence-date" type="date"></label></div>
            <textarea id="ei-evidence-text" placeholder="Paste the relevant text here. Example: Existing service is 800A, 480V, 3-phase. Utility can support 1,000 kW subject to final engineering review..."></textarea>
            <div class="evidence-compose-actions"><button type="button" data-parse-evidence><span class="scan-dot"></span>Parse + add evidence</button><span data-evidence-status>Nothing is uploaded until you choose Parse + add evidence.</span></div>
          </div>
        </div>
        <div class="evidence-vault-head"><div><span>PROJECT RECORD</span><b data-evidence-vault-count>0 evidence items</b></div><p>Source age and strength are visible. Stale authority records are automatically capped before they influence Evidence Depth.</p></div>
        <div class="evidence-vault" data-evidence-vault></div>
      </section>`);

    const evidence=$('.evidence-module');
    if(evidence&&!$('.contradiction-module'))evidence.insertAdjacentHTML('afterend',`
      <section class="lab-module contradiction-module">
        <div class="lab-head"><div><span>05B / Contradiction Engine</span><h2>Find the facts that cannot all be true.</h2></div><p>ExpenseIntel compares extracted document claims with each other and with the live project inputs. It surfaces direct numeric conflicts, opposing approval/use statements and stale evidence instead of silently choosing a preferred answer.</p></div>
        <div class="contradiction-summary"><div><span>Direct conflicts</span><strong data-conflict-count>0</strong></div><div><span>Critical</span><strong data-conflict-critical>0</strong></div><div><span>Stale records</span><strong data-stale-count>0</strong></div><div class="conflict-posture"><span>Record posture</span><strong data-conflict-posture>CLEAN / EMPTY</strong></div></div>
        <div class="contradiction-grid" data-contradiction-grid></div>
      </section>
      <section class="lab-module dependency-module">
        <div class="lab-head"><div><span>05C / Dependency Graph</span><h2>See what must happen before something else can happen.</h2></div><p>Project risk is often a dependency problem, not a score problem. This graph maps the current gates from use and utilities through design, permits, release, construction and opening. Blocked nodes pulse; moving lines show active dependency paths.</p></div>
        <div class="dependency-layout"><div class="dependency-stage"><svg viewBox="0 0 980 470" data-dependency-svg role="img" aria-label="Project dependency graph"></svg></div><aside class="dependency-readout"><span>SELECTED NODE</span><h3 data-dep-title>Project dependency map</h3><p data-dep-copy>Run the project and add evidence. Select a node to see what it depends on and what it blocks downstream.</p><div data-dep-meta></div></aside></div>
      </section>
      <section class="lab-module gatekeeper-module">
        <div class="lab-head"><div><span>05D / Project Gatekeeper</span><h2>Turn diligence into release gates.</h2></div><p>Gatekeeper converts uncertainty into operating controls: what cannot close, freeze, release or start until a named fact is proven. It is a sequencing screen—not legal, engineering or permit approval.</p></div>
        <div class="gate-posture"><div><span>CURRENT POSTURE</span><strong data-gate-posture>HOLD FOR EVIDENCE</strong><p data-gate-posture-copy>Build the record before irreversible commitments.</p></div><div class="gate-meter"><i data-gate-meter></i></div><div class="gate-counts"><span><b data-gate-cleared>0</b> cleared</span><span><b data-gate-open>0</b> open</span><span><b data-gate-blocked>0</b> blocked</span></div></div>
        <div class="gate-list" data-gate-list></div>
      </section>`);
  }

  function defaultStrength(type){return type==='agency'?'authority':type==='professional'||type==='inspection'?'professional':type==='marketing'?'verbal':'document'}
  function bindTypeStrength(){const type=$('#ei-evidence-type'),strength=$('#ei-evidence-strength');type?.addEventListener('change',()=>{if(strength)strength.value=defaultStrength(type.value)})}
  async function readFile(file){if(!file)return'';if(file.size>1500000)throw new Error('Keep evidence text files under 1.5 MB for this beta.');return await file.text()}
  function strengthLabel(v){return{authority:'AUTHORITY',professional:'PROFESSIONAL',document:'DOCUMENT',verbal:'CLAIM'}[v]||'SOURCE'}
  function claimValue(c){if(c.unit==='USD')return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(c.value)||0);if(c.unit==='phase')return `${c.value}-phase`;return `${typeof c.value==='number'?fmt(c.value):c.value}${c.unit?` ${c.unit}`:''}`}
  function sourceEffectiveLabel(r){const eff=effectiveStrength(r);return isStale(r)&&eff!==r.strength?`${strengthLabel(r.strength)} → ${strengthLabel(eff)} (STALE)`:strengthLabel(r.strength)}
  function applyEvidenceStrength(record){const eff=effectiveStrength(record);for(const cat of record.categories||[]){const sel=$(`[data-quality-key="${cat}"]`);if(!sel)continue;const current=sel.value||'none';if((STRENGTH_RANK[eff]||0)>(STRENGTH_RANK[current]||0)){sel.value=eff;sel.dispatchEvent(new Event('change',{bubbles:true}))}}}
  async function parseEvidence(){
    const btn=$('[data-parse-evidence]'),status=$('[data-evidence-status]');if(btn)btn.disabled=true;
    try{
      let text=($('#ei-evidence-text')?.value||'').trim();if(selectedFile){const fileText=await readFile(selectedFile);if(fileText.trim())text=text?`${text}\n\n${fileText}`:fileText}
      if(text.length<20)throw new Error('Paste some evidence text or choose a text-based file first.');
      if(status)status.textContent='Scanning claims, units and approval language…';
      const response=await fetch('/api/project-evidence',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({text})});const data=await response.json().catch(()=>null);if(!response.ok||!data?.ok)throw new Error(data?.error||'Could not parse this evidence.');
      migrateDraft();const rows=safeLoad(),type=$('#ei-evidence-type')?.value||'other',strength=$('#ei-evidence-strength')?.value||defaultStrength(type),name=($('#ei-evidence-name')?.value||selectedFile?.name||`${type} evidence`).trim(),sourceDate=$('#ei-evidence-date')?.value||data.detectedDate||null,record={id:`ev_${Date.now().toString(36)}_${hashText(text).slice(0,6)}`,projectKey:projectKey(),addedAt:new Date().toISOString(),name,type,strength,sourceDate,categories:data.categories||[],claims:data.claims||[],parserVersion:data.parserVersion,excerpt:text.slice(0,520),hash:hashText(text)};
      if(rows.some(r=>r.projectKey===record.projectKey&&r.hash===record.hash))throw new Error('That exact evidence text is already in this project record.');rows.unshift(record);safeSave(rows.slice(0,160));applyEvidenceStrength(record);
      if($('#ei-evidence-name'))$('#ei-evidence-name').value='';if($('#ei-evidence-text'))$('#ei-evidence-text').value='';if($('#ei-evidence-date'))$('#ei-evidence-date').value='';selectedFile=null;set('[data-file-name]','No file selected');if(status)status.textContent=`Added ${record.claims.length} extracted claim${record.claims.length===1?'':'s'} across ${record.categories.length||0} evidence categor${record.categories.length===1?'y':'ies'}. Review the record below.`;renderVault();refreshAll();
    }catch(error){if(status)status.textContent=error?.message||'Could not parse evidence.'}finally{if(btn)btn.disabled=false}
  }
  function removeEvidence(id){const rows=safeLoad().filter(r=>r.id!==id);safeSave(rows);renderVault();refreshAll()}
  function renderVault(){migrateDraft();const rows=activeRecords(),zone=$('[data-evidence-vault]');set('[data-evidence-vault-count]',`${rows.length} evidence item${rows.length===1?'':'s'}`);if(!zone)return;zone.innerHTML='';if(!rows.length){zone.innerHTML='<div class="vault-empty"><b>No project evidence yet.</b><span>Add one real document or copied source excerpt. The contradiction and gate systems become more useful as independent records accumulate.</span></div>';return}rows.forEach((r,i)=>{const card=document.createElement('article');card.className=`evidence-record ${isStale(r)?'stale':''}`;const date=r.sourceDate||'undated',age=ageDays(r.sourceDate),claims=(r.claims||[]).slice(0,5);card.innerHTML='<header><div><span class="record-index"></span><h3></h3></div><button type="button" aria-label="Remove evidence">×</button></header><div class="record-meta"></div><div class="record-claims"></div><footer><span></span><b></b></footer>';card.querySelector('.record-index').textContent=`EV-${String(rows.length-i).padStart(2,'0')}`;card.querySelector('h3').textContent=r.name;card.querySelector('header button').addEventListener('click',()=>removeEvidence(r.id));const meta=card.querySelector('.record-meta');[sourceEffectiveLabel(r),date,...(r.categories||[]).map(x=>x.toUpperCase())].forEach(x=>{const s=document.createElement('span');s.textContent=x;meta.appendChild(s)});const cz=card.querySelector('.record-claims');if(!claims.length)cz.innerHTML='<span class="claim-none">No structured numeric/status claim detected; source still retained as evidence context.</span>';else claims.forEach(c=>{const d=document.createElement('div');d.className='claim-chip';d.innerHTML='<span></span><strong></strong>';d.querySelector('span').textContent=KEY_LABEL[c.key]||c.label||c.key;d.querySelector('strong').textContent=claimValue(c);d.title=c.excerpt||'';cz.appendChild(d)});card.querySelector('footer span').textContent=`${r.claims?.length||0} extracted claims · ${r.parserVersion||'parser'}`;card.querySelector('footer b').textContent=age==null?'AGE UNKNOWN':isStale(r)?`${age} DAYS · STALE`:`${age} DAYS OLD`;zone.appendChild(card)})}

  function currentInputClaims(){const t=currentTech(),src={id:'current-input',name:'Current project inputs',strength:'document',sourceDate:new Date().toISOString().slice(0,10),categories:['utility'],claims:[]};const add=(key,value,unit)=>{if(value>0)src.claims.push({key,label:KEY_LABEL[key],value,unit,excerpt:'Current Project Lab input'})};add('serviceAmps',t.amps,'A');add('voltage',t.voltage,'V');add('phase',t.phase,'phase');add('peakKw',t.peakKw,'kW');add('waterDemand',t.waterDemand,'gpm');add('waterCapacity',t.waterCapacity,'gpm');add('sewerDemand',t.sewerDemand,'gpd');add('sewerCapacity',t.sewerCapacity,'gpd');add('gasDemand',t.gasDemand,'MBH');add('gasCapacity',t.gasCapacity,'MBH');add('occupantLoad',t.occupants,'people');return src}
  function relDiff(a,b){const m=Math.max(Math.abs(a),Math.abs(b),1);return Math.abs(a-b)/m}
  function contradictionThreshold(key){return{serviceAmps:.1,peakKw:.15,waterDemand:.15,waterCapacity:.15,sewerDemand:.15,sewerCapacity:.15,gasDemand:.15,gasCapacity:.15,occupantLoad:.12,projectAmount:.18}[key]??0}
  function buildContradictions(){const sources=[...activeRecords(),currentInputClaims()],byKey={};sources.forEach(s=>(s.claims||[]).forEach(c=>{(byKey[c.key]??=[]).push({claim:c,source:s})}));const out=[];
    for(const [key,items] of Object.entries(byKey)){
      for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++){
        const a=items[i],b=items[j];if(a.source.id===b.source.id)continue;let conflict=false,severity='medium',why='';
        if(['voltage','phase'].includes(key)){conflict=String(a.claim.value)!==String(b.claim.value);severity='high';why='Direct electrical configuration mismatch.'}
        else if(typeof a.claim.value==='number'&&typeof b.claim.value==='number'&&contradictionThreshold(key)>0){const d=relDiff(a.claim.value,b.claim.value);conflict=d>contradictionThreshold(key);severity=d>.3?'high':'medium';why=`Values differ by about ${Math.round(d*100)}%.`}
        else if(key==='zoningDisposition'||key==='approvalDisposition'){const av=a.claim.value,bv=b.claim.value,opposite=(av==='positive'&&['negative','expired'].includes(bv))||(bv==='positive'&&['negative','expired'].includes(av));conflict=opposite||(av==='negative'&&bv==='conditional')||(bv==='negative'&&av==='conditional');severity=opposite?'high':'medium';why='The records describe incompatible approval/use states.'}
        if(conflict)out.push({id:`${key}_${i}_${j}`,key,label:KEY_LABEL[key]||a.claim.label||key,severity,a,b,why});
      }
    }
    const proposed=$('#pj-use')?.value||'other';for(const r of activeRecords())for(const c of r.claims||[]){if(c.key==='zoningDisposition'&&c.value==='negative'&&(!c.subjectUse||c.subjectUse===proposed))out.push({id:`use_${r.id}`,key:'zoningDisposition',label:'Proposed use conflict',severity:'high',a:{source:r,claim:c},b:{source:{name:'Current project plan'},claim:{value:proposed,excerpt:`Proposed use: ${proposed}`}},why:`Evidence contains a negative zoning/use statement that may apply to the proposed ${proposed} use.`})}
    const unique=[];const seen=new Set();for(const x of out){const k=[x.key,x.a.source.name,x.b.source.name,String(x.a.claim.value),String(x.b.claim.value)].sort().join('|');if(!seen.has(k)){seen.add(k);unique.push(x)}}return unique}
  function renderContradictions(){const conflicts=buildContradictions();lastContradictions=conflicts;const stale=activeRecords().filter(isStale);set('[data-conflict-count]',String(conflicts.length));set('[data-conflict-critical]',String(conflicts.filter(x=>x.severity==='high').length));set('[data-stale-count]',String(stale.length));set('[data-conflict-posture]',conflicts.some(x=>x.severity==='high')?'CONFLICTED':conflicts.length?'REVIEW REQUIRED':stale.length?'STALE EVIDENCE':'NO DIRECT CONFLICT');const zone=$('[data-contradiction-grid]');if(!zone)return;zone.innerHTML='';if(!conflicts.length&&!stale.length){zone.innerHTML='<div class="conflict-empty"><i></i><div><b>No direct contradiction detected.</b><span>This does not prove the project facts are correct; it means the current sources are not directly fighting each other on extracted claims.</span></div></div>';return}conflicts.slice(0,10).forEach(c=>{const el=document.createElement('article');el.className=`conflict-card ${c.severity}`;el.innerHTML='<header><span></span><b></b></header><h3></h3><div class="conflict-pair"><div><span></span><strong></strong><small></small></div><i>≠</i><div><span></span><strong></strong><small></small></div></div><p></p>';el.querySelector('header span').textContent=c.severity==='high'?'CRITICAL CONFLICT':'REVIEW CONFLICT';el.querySelector('header b').textContent=c.label;el.querySelector('h3').textContent=c.why;const sides=el.querySelectorAll('.conflict-pair>div');[[c.a,sides[0]],[c.b,sides[1]]].forEach(([x,d])=>{d.querySelector('span').textContent=x.source.name||'Source';d.querySelector('strong').textContent=claimValue(x.claim);d.querySelector('small').textContent=x.claim.excerpt||'No excerpt'});el.querySelector('p').textContent='NEXT → Resolve against the highest-quality current source and update the project input; do not average conflicting facts.';zone.appendChild(el)});stale.slice(0,4).forEach(r=>{const el=document.createElement('article');el.className='conflict-card stale-card';el.innerHTML='<header><span>STALE SOURCE</span><b></b></header><h3></h3><p></p>';el.querySelector('header b').textContent=r.name;el.querySelector('h3').textContent=`${ageDays(r.sourceDate)} days old · authority weight capped for screening`;el.querySelector('p').textContent='NEXT → Refresh the underlying agency, utility, permit or transaction record before relying on it for a current release gate.';zone.appendChild(el)})}

  function gateStatus(rank,need=.85){if(rank>=need)return'cleared';if(rank>=.65)return'conditional';return'open'}
  function highConflict(keys){return lastContradictions.some(c=>c.severity==='high'&&keys.includes(c.key))}
  function gates(){const mode=($('[data-mode].active')?.dataset.mode)||'builder',cap=currentCapacity(),t=currentTech(),out=[],push=(id,stage,title,status,owner,close,copy)=>out.push({id,stage,title,status,owner,close,copy});
    let zoning=gateStatus(q('zoning'));if(highConflict(['zoningDisposition']))zoning='blocked';push('zoning','BEFORE COMMIT','Use path',zoning,'Zoning / planning','Written parcel-specific use determination or cited approval path.',zoning==='blocked'?'Current records conflict on whether the proposed use is allowed.':'Do not price or design the project as by-right until the use path is source-backed.');
    let util='open',utilWhy='Capacity remains materially unresolved.';const needsElec=trigger('heavyPower')||trigger('utilityUpgrade'),needsWater=trigger('processWater');const directElec=cap.electric.known,waterOK=!needsWater||(cap.water.known&&cap.sewer.known);if(cap.electric.over||cap.water.over||cap.sewer.over||cap.gas.over){util='blocked';utilWhy='A supplied demand value exceeds a supplied capacity value.'}else if(highConflict(['serviceAmps','voltage','phase','peakKw','waterCapacity','sewerCapacity','gasCapacity'])){util='blocked';utilWhy='Capacity evidence conflicts across the current record.'}else if(q('utility')>=.85&&(!needsElec||directElec)&&waterOK){util='cleared';utilWhy='Current screen has strong source quality and the required direct demand/capacity pairs.'}else if(q('utility')>=.65||directElec||cap.water.known||cap.sewer.known){util='conditional';utilWhy='Useful utility evidence exists, but one or more direct capacity pairs remain unresolved.'}push('utilities','BEFORE COMMIT','Utility viability',util,'Serving utilities + engineer','Current service/capacity record paired with project demand calculation.',utilWhy);
    const siteNeeded=trigger('hazmat')||trigger('exterior');const site=siteNeeded?gateStatus(q('site')):'cleared';push('site','BEFORE COMMIT','Site / environmental path',site,'Environmental / site diligence','Current site, access, environmental or title diligence tied to the plan.',siteNeeded?'Site work or hazardous-process conditions make this an active upstream gate.':'No selected trigger currently makes this a primary gate; keep site diligence current.');
    const conflictStatus=lastContradictions.some(x=>x.severity==='high')?'blocked':lastContradictions.length?'conditional':'cleared';push('conflicts','BEFORE COMMIT','Contradiction closure',conflictStatus,'Project lead / diligence owner','One accepted current fact for every critical disputed claim.',lastContradictions.length?'Do not average conflicting facts. Resolve them to a named controlling source.':'No direct extracted-claim conflict currently blocks the record.');
    const occNeeded=trigger('food')||trigger('highOccupancy')||t.occupants>=50;const occ=occNeeded?gateStatus(q('permit')):'cleared';push('life','BEFORE DESIGN FREEZE','Occupancy + life-safety basis',occ,'Building / fire / health authorities','Project-specific occupancy, egress, suppression and health-review basis.',occNeeded?'The selected use/occupancy conditions can change layout and downstream approvals.':'No current trigger elevates this above the normal permit path.');
    const permit=gateStatus(q('permit'));push('permit','BEFORE CONSTRUCTION','Permit / approval path',permit,'Design team + authority','Written permit and review sequence tied to this project.','Construction should not be treated as schedule-ready while the approval path is assumption-only.');
    const scope=gateStatus(q('scope'));push('scope',mode==='buyer'?'BEFORE CLOSE':'BEFORE RELEASE',mode==='buyer'?'Condition / responsibility record':'Trade responsibility matrix',scope,mode==='buyer'?'Buyer + inspector / counsel':'GC / preconstruction + trades',mode==='buyer'?'Inspection/condition record plus assigned responsibility for material findings.':'Signed responsibility matrix cross-referenced to scopes and bids.',mode==='buyer'?'Translate physical findings into seller obligations, price protection or walk-away rights.':'Close the interface gaps before procurement and field work create change orders.');
    const quote=gateStatus(q('quote'));push('budget',mode==='buyer'?'BEFORE CLOSE':'BEFORE RELEASE','Real cost basis',quote,mode==='buyer'?'Buyer / lender / advisor':'Estimator / owner / GC','Current quote, budget, lease schedule or documented cost basis.','A modeled cost layer should not be the only number supporting an irreversible decision.');
    const highLock=['electrical','structural','fire','site'].filter(intervention);let release=highLock.length?'conditional':'cleared';if(highLock.length&&['blocked','open'].includes(zoning)||highLock.length&&['blocked','open'].includes(util)||highLock.length&&['blocked','open'].includes(permit))release='blocked';else if(highLock.length&&zoning==='cleared'&&util==='cleared'&&permit==='cleared')release='cleared';push('release','BEFORE RELEASE','Irreversible spend release',release,'Owner / project executive',`Release gate tied to zoning, utilities and approval evidence${highLock.length?` before ${highLock.join(', ')}`:''}.`,highLock.length?'High-lock interventions are selected; upstream facts should control release timing.':'No selected high-lock intervention is currently waiting behind this gate.');
    const stale=activeRecords().filter(isStale);push('freshness','CONTINUOUS','Evidence freshness',stale.length?'conditional':'cleared','Diligence owner','Refresh records that can expire, drift or become superseded.',stale.length?`${stale.length} evidence item${stale.length===1?' is':'s are'} old enough to warrant refresh.`:'No dated evidence currently exceeds the screening freshness window.');return out}
  function renderGatekeeper(){const rows=gates(),zone=$('[data-gate-list]');if(!zone)return;const cleared=rows.filter(x=>x.status==='cleared').length,blocked=rows.filter(x=>x.status==='blocked').length,open=rows.filter(x=>x.status==='open'||x.status==='conditional').length;set('[data-gate-cleared]',cleared);set('[data-gate-open]',open);set('[data-gate-blocked]',blocked);const early=rows.filter(x=>['BEFORE COMMIT','BEFORE CLOSE','BEFORE DESIGN FREEZE'].includes(x.stage)),earlyBlocked=early.some(x=>x.status==='blocked'),earlyOpen=early.some(x=>x.status==='open'),earlyConditional=early.some(x=>x.status==='conditional');let posture='READY FOR NEXT GATE',copy='Current early-stage gates are source-backed enough to advance the screen.';if(earlyBlocked){posture='HOLD / RESOLVE';copy='At least one early-stage gate is actively blocked by conflicting or adverse evidence.'}else if(earlyOpen){posture='HOLD FOR EVIDENCE';copy='A critical early-stage fact is still assumption-only.'}else if(earlyConditional){posture='ADVANCE WITH CONTROLS';copy='The project can advance as a screen, but named conditions still need stronger evidence.'}set('[data-gate-posture]',posture);set('[data-gate-posture-copy]',copy);const meter=$('[data-gate-meter]');if(meter)meter.style.width=`${Math.round(cleared/rows.length*100)}%`;zone.innerHTML='';rows.forEach((g,i)=>{const el=document.createElement('article');el.className=`gate-row ${g.status}`;el.innerHTML='<div class="gate-no"></div><div class="gate-main"><span></span><h3></h3><p></p></div><div class="gate-owner"><span>OWNER</span><b></b></div><div class="gate-close"><span>CLOSE WITH</span><b></b></div><div class="gate-state"></div>';el.querySelector('.gate-no').textContent=String(i+1).padStart(2,'0');el.querySelector('.gate-main span').textContent=g.stage;el.querySelector('.gate-main h3').textContent=g.title;el.querySelector('.gate-main p').textContent=g.copy;el.querySelector('.gate-owner b').textContent=g.owner;el.querySelector('.gate-close b').textContent=g.close;el.querySelector('.gate-state').textContent=g.status.toUpperCase();zone.appendChild(el)})}

  function dependencyModel(){const gs=gates(),by=Object.fromEntries(gs.map(g=>[g.id,g]));const status=id=>by[id]?.status||'open';const nodes=[
    {id:'commit',label:($('[data-mode].active')?.dataset.mode)==='buyer'?'CLOSE / COMMIT':'PROJECT COMMIT',x:80,y:235,status:status('conflicts')},
    {id:'zoning',label:'USE / ZONING',x:250,y:85,status:status('zoning')},
    {id:'utilities',label:'UTILITIES',x:250,y:205,status:status('utilities')},
    {id:'site',label:'SITE / ENV',x:250,y:325,status:status('site')},
    {id:'life',label:'LIFE SAFETY',x:445,y:85,status:status('life')},
    {id:'design',label:'DESIGN FREEZE',x:445,y:205,status:['blocked'].includes(status('zoning'))||['blocked'].includes(status('utilities'))?'blocked':(['open'].includes(status('zoning'))||['open'].includes(status('utilities'))?'open':'conditional')},
    {id:'permit',label:'PERMIT PATH',x:445,y:325,status:status('permit')},
    {id:'release',label:'RELEASE',x:650,y:145,status:status('release')},
    {id:'construct',label:'CONSTRUCTION',x:650,y:285,status:status('permit')==='blocked'||status('release')==='blocked'?'blocked':status('permit')==='cleared'&&status('release')==='cleared'?'cleared':'open'},
    {id:'open',label:'OPEN / OCCUPY',x:865,y:235,status:status('permit')==='cleared'&&status('life')==='cleared'?'conditional':'open'}
  ];const edges=[['commit','zoning'],['commit','utilities'],['commit','site'],['zoning','design'],['utilities','design'],['site','permit'],['life','design'],['design','permit'],['utilities','release'],['zoning','release'],['permit','construct'],['release','construct'],['construct','open'],['life','open'],['permit','open']];return{nodes,edges,gates:by}}
  function renderDependency(){const svg=$('[data-dependency-svg]');if(!svg)return;const m=dependencyModel();depState=m;svg.innerHTML='';const NS='http://www.w3.org/2000/svg',nodeMap=Object.fromEntries(m.nodes.map(n=>[n.id,n]));const defs=document.createElementNS(NS,'defs');defs.innerHTML='<marker id="ei4-arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z"></path></marker>';svg.appendChild(defs);const edgeGroup=document.createElementNS(NS,'g');edgeGroup.setAttribute('class','dep-edges');m.edges.forEach(([a,b])=>{const A=nodeMap[a],B=nodeMap[b],path=document.createElementNS(NS,'path'),mx=(A.x+B.x)/2;path.setAttribute('d',`M ${A.x+54} ${A.y} C ${mx} ${A.y}, ${mx} ${B.y}, ${B.x-54} ${B.y}`);path.setAttribute('class',`dep-edge ${B.status}`);path.setAttribute('marker-end','url(#ei4-arrow)');edgeGroup.appendChild(path)});svg.appendChild(edgeGroup);const nodeGroup=document.createElementNS(NS,'g');nodeGroup.setAttribute('class','dep-nodes');m.nodes.forEach(n=>{const g=document.createElementNS(NS,'g');g.setAttribute('class',`dep-node ${n.status}`);g.setAttribute('transform',`translate(${n.x},${n.y})`);g.setAttribute('tabindex','0');g.setAttribute('role','button');g.innerHTML='<circle r="46"></circle><circle class="dep-pulse" r="52"></circle><text y="-4" text-anchor="middle"></text><text class="dep-status" y="13" text-anchor="middle"></text>';g.querySelector('text').textContent=n.label;g.querySelector('.dep-status').textContent=n.status.toUpperCase();const select=()=>selectDependency(n.id);g.addEventListener('click',select);g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select()}});nodeGroup.appendChild(g)});svg.appendChild(nodeGroup);const first=m.nodes.find(n=>n.status==='blocked')||m.nodes.find(n=>n.status==='open')||m.nodes[0];selectDependency(first.id)}
  function selectDependency(id){if(!depState)return;const n=depState.nodes.find(x=>x.id===id);if(!n)return;$$('.dep-node',$('[data-dependency-svg]')).forEach(x=>x.classList.remove('selected'));const index=depState.nodes.findIndex(x=>x.id===id);$$('.dep-node',$('[data-dependency-svg]'))[index]?.classList.add('selected');const incoming=depState.edges.filter(([,b])=>b===id).map(([a])=>depState.nodes.find(n=>n.id===a)?.label).filter(Boolean),outgoing=depState.edges.filter(([a])=>a===id).map(([,b])=>depState.nodes.find(n=>n.id===b)?.label).filter(Boolean),gate=depState.gates[id]||Object.values(depState.gates).find(g=>g.id===id);set('[data-dep-title]',n.label);set('[data-dep-copy]',gate?.copy||`${n.label} is ${n.status}. Select an upstream or downstream node to trace the current project sequence.`);const z=$('[data-dep-meta]');if(z)z.innerHTML=`<div><span>STATUS</span><b>${n.status.toUpperCase()}</b></div><div><span>DEPENDS ON</span><b>${incoming.join(' · ')||'PROJECT INPUTS'}</b></div><div><span>BLOCKS</span><b>${outgoing.join(' · ')||'FINAL DECISION'}</b></div>`}

  function refreshAll(){migrateDraft();renderVault();renderContradictions();renderGatekeeper();renderDependency()}
  function bindEvidence(){const pick=$('[data-pick-evidence]'),file=$('#ei-evidence-file'),drop=$('[data-evidence-drop]');pick?.addEventListener('click',()=>file?.click());file?.addEventListener('change',()=>{selectedFile=file.files?.[0]||null;set('[data-file-name]',selectedFile?`${selectedFile.name} · ${fmt(selectedFile.size)} bytes`:'No file selected')});drop?.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag')});drop?.addEventListener('dragleave',()=>drop.classList.remove('drag'));drop?.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag');selectedFile=e.dataTransfer?.files?.[0]||null;set('[data-file-name]',selectedFile?`${selectedFile.name} · ${fmt(selectedFile.size)} bytes`:'No file selected')});drop?.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();file?.click()}});$('[data-parse-evidence]')?.addEventListener('click',parseEvidence);bindTypeStrength()}
  function bindRefresh(){['#pj-address','#pj-use','#pj-current','#pj-electric','#pj-known-peak-kw','#pj-voltage','#pj-phase','#pj-pf','#pj-water-demand','#pj-water-cap','#pj-sewer-demand','#pj-sewer-cap','#pj-gas-demand','#pj-gas-cap','#pj-occupants'].forEach(sel=>{const el=$(sel);el?.addEventListener('input',debounceRefresh);el?.addEventListener('change',debounceRefresh)});$$('.chip-grid input').forEach(x=>x.addEventListener('change',debounceRefresh));$$('[data-quality-key]').forEach(x=>x.addEventListener('change',debounceRefresh));$$('[data-mode]').forEach(x=>x.addEventListener('click',()=>setTimeout(debounceRefresh,30)));const watch=$('[data-watch-status]');if(watch)new MutationObserver(()=>setTimeout(refreshAll,80)).observe(watch,{childList:true,characterData:true,subtree:true});const frag=$('[data-r-fragility]');if(frag)new MutationObserver(()=>setTimeout(refreshAll,100)).observe(frag,{childList:true,characterData:true,subtree:true});window.addEventListener('storage',e=>{if(e.key===VAULT_KEY)refreshAll()})}
  function init(){injectUI();bindEvidence();bindRefresh();refreshAll()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
