(()=>{
  'use strict';
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const TIMELINE_KEY='ei_project_timeline_v5';
  const BASELINE_KEY='ei_project_baseline_v5';
  const VAULT_KEY='ei_project_evidence_v4';
  let docFile=null,docText='',lastPublicSources=[];

  function set(sel,v){const el=$(sel);if(el)el.textContent=v}
  function numText(sel){const t=$(sel)?.textContent||'';const m=t.replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):null}
  function norm(s){return String(s||'').trim().toLowerCase().replace(/\s+/g,' ')}
  function projectKey(){return `${norm($('#pj-address')?.value)||'draft'}|${$('#pj-use')?.value||'other'}`}
  function loadJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch(_e){return fallback}}
  function saveJSON(key,v){try{localStorage.setItem(key,JSON.stringify(v));return true}catch(_e){return false}}
  function nowLabel(iso){try{return new Date(iso).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}catch(_e){return iso}}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)||0)}

  function logEvent(type,title,detail='',major=false){
    const all=loadJSON(TIMELINE_KEY,{}),key=projectKey(),rows=Array.isArray(all[key])?all[key]:[];
    const next={id:`tl_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,at:new Date().toISOString(),type,title,detail,major};
    const last=rows[0];if(last&&last.title===title&&last.detail===detail&&Date.now()-new Date(last.at).getTime()<2500)return;
    all[key]=[next,...rows].slice(0,80);saveJSON(TIMELINE_KEY,all);renderTimeline();
  }

  function injectUI(){
    const evidenceInbox=$('.evidence-inbox');
    if(evidenceInbox&&!$('.auto-evidence-module'))evidenceInbox.insertAdjacentHTML('afterend',`
      <section class="v5-panel auto-evidence-module">
        <div class="v5-head"><div><span>00C / Auto Evidence Pull</span><h2>Make the address start the diligence file.</h2></div><p>ExpenseIntel now pulls the authoritative signals it can resolve automatically, labels coverage honestly, and exposes the gaps it cannot yet prove. National coverage starts with Census geography, FEMA risk and EIA energy. Chicago adds live Department of Buildings permit history.</p></div>
        <div class="public-pull-control"><div><strong>Build the public evidence file.</strong><p>Uses the verified project address. Results remain source-separated; an official dataset signal is not the same thing as a parcel-specific zoning determination.</p></div><button class="v5-primary" type="button" data-public-pull>Pull public evidence →</button></div>
        <div class="pull-status" data-public-status>Run the project address, then pull. Coverage is shown source by source.</div>
        <div class="public-source-grid" data-public-grid></div>
      </section>
      <section class="v5-panel document-intel-module">
        <div class="v5-head"><div><span>00D / Document Intelligence</span><h2>Read the file instead of retyping it.</h2></div><p>Text PDFs are extracted in-browser. Images are OCR'd in-browser. Scanned PDFs fall back to OCR on the first pages when text extraction returns almost nothing. Extracted text is then routed into the existing Evidence Inbox, where claims remain source-labeled and reviewable.</p></div>
        <div class="doc-intel-grid"><div class="doc-drop" data-doc-drop tabindex="0"><input type="file" data-doc-file accept="application/pdf,image/png,image/jpeg,image/webp" hidden><div class="doc-icon">EVIDENCE</div><h3>PDF or image</h3><p>Drop a utility letter, permit, plan excerpt, inspection page, bid or photographed document.</p><button class="v5-primary" type="button" data-doc-pick>Choose document</button></div><div class="doc-workbench"><div class="doc-file-row"><div><strong data-doc-name>No document loaded</strong><span data-doc-meta>PDF text + image OCR beta</span></div><span class="doc-badge" data-doc-mode>WAITING</span></div><div class="doc-progress"><i data-doc-progress></i></div><div class="doc-preview" data-doc-preview>Extracted text will appear here. Files are processed in the browser; only extracted text is sent to the existing evidence parser when you choose “Add to Evidence Inbox.”</div><div class="doc-actions"><button class="v5-primary" type="button" data-doc-extract disabled>Extract intelligence</button><button class="v5-secondary" type="button" data-doc-send disabled>Add to Evidence Inbox →</button></div><p class="doc-note" data-doc-note>OCR can be slow on large images or scanned PDFs. The beta limits scanned-PDF OCR to the first three pages to avoid pretending a partial scan is a complete document review.</p></div></div>
      </section>`);

    const gatekeeper=$('.gatekeeper-module');
    if(gatekeeper&&!$('.impact-module'))gatekeeper.insertAdjacentHTML('afterend',`
      <section class="v5-panel impact-module">
        <div class="v5-head"><div><span>05E / Change Impact Engine</span><h2>When one fact changes, show what else moved.</h2></div><p>A project is not a static score. Set a baseline, change the plan or add evidence, and ExpenseIntel compares fragility, evidence depth, bottleneck, gate posture, conflicts and utility uncertainty against that baseline.</p></div>
        <div class="impact-top"><div class="impact-hero"><span>CURRENT CHANGE POSTURE</span><strong data-impact-posture>NO BASELINE</strong><p data-impact-copy>Set a baseline after a meaningful project run. Future changes will be evaluated against it instead of disappearing into a new score.</p></div><div class="impact-control"><button class="v5-primary" type="button" data-set-baseline>Set current state as baseline</button><button class="v5-secondary" type="button" data-clear-baseline>Clear baseline</button><p data-baseline-meta>No saved baseline for this project.</p></div></div>
        <div class="impact-grid"><div class="impact-kpi" data-impact-frag-wrap><span>Fragility Δ</span><b data-impact-frag>—</b></div><div class="impact-kpi" data-impact-evidence-wrap><span>Evidence Δ</span><b data-impact-evidence>—</b></div><div class="impact-kpi"><span>Gate changes</span><b data-impact-gates>—</b></div><div class="impact-kpi"><span>Conflict Δ</span><b data-impact-conflicts>—</b></div></div><div class="impact-changes" data-impact-changes></div>
      </section>
      <section class="v5-panel decision-brief-module">
        <div class="v5-head"><div><span>05F / Decision Brief</span><h2>Turn the project into a decision someone can sign off on.</h2></div><p>One page: posture, evidence depth, fragility, dominant bottleneck, blocked/open gates and the conditions required to move forward. It is a screening memo, not legal, engineering or investment advice.</p></div>
        <div class="decision-console"><div class="decision-posture"><div><span>CURRENT SCREEN</span><strong data-decision-posture>HOLD FOR EVIDENCE</strong><p data-decision-copy>Run the project and build the record.</p></div><div class="decision-stamp" data-decision-stamp>CONDITIONAL<br>SCREEN</div></div><div class="decision-detail"><div class="decision-kpis"><div><span>Evidence</span><b data-decision-evidence>—</b></div><div><span>Fragility</span><b data-decision-frag>—</b></div><div><span>Bottleneck</span><b data-decision-bot>—</b></div><div><span>Conflicts</span><b data-decision-conflicts>—</b></div></div><div class="decision-conditions" data-decision-conditions></div><div class="decision-actions"><button class="v5-primary" type="button" data-print-brief>Open printable decision brief</button><button class="v5-secondary" type="button" data-copy-brief>Copy brief summary</button></div></div></div>
      </section>`);

    const watch=$('[data-watch-grid]')?.closest('section');
    if(watch&&!$('.timeline-module'))watch.insertAdjacentHTML('afterend',`
      <section class="v5-panel timeline-module">
        <div class="v5-head"><div><span>11 / Project Timeline</span><h2>See how the decision got here.</h2></div><p>Evidence scans, document extraction, baseline changes and material project-state changes become a chronological record. This is browser-local until cloud projects are activated.</p></div><div class="timeline-toolbar"><p>Newest events first · project-specific browser record</p><button class="v5-secondary" type="button" data-clear-timeline>Clear timeline</button></div><div class="timeline-list" data-timeline-list></div>
      </section>
      <section class="cloud-module"><div class="cloud-card"><div><span>12 / Cloud Projects</span><h3>Account + team layer prepared.</h3><p>The interface is ready to move project snapshots, evidence and timeline events out of browser storage. It will not pretend to be cloud-synced until a dedicated ExpenseIntel backend and auth project are provisioned.</p></div><div class="cloud-state"><b><i class="cloud-dot" data-cloud-dot></i><span data-cloud-title>Checking cloud configuration…</span></b><small data-cloud-copy>Browser-local data remains authoritative for this session.</small></div></div></section>`);
  }

  async function fetchJSON(url){const r=await fetch(url,{headers:{Accept:'application/json'}}),d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw new Error(d.error||`Request failed (${r.status})`);return d}
  function sourceCard(source){
    const card=document.createElement('article');card.className=`public-source ${source.coverageOnly?'coverage':''}`;card.innerHTML='<header><span></span><b></b></header><h3></h3><p></p><div class="public-facts"></div><footer><button type="button">Add to evidence</button><a target="_blank" rel="noopener">Open source ↗</a></footer>';
    card.querySelector('header span').textContent=source.kind;card.querySelector('header b').textContent=source.grade||'PUBLIC';card.querySelector('h3').textContent=source.title;card.querySelector('p').textContent=source.copy;
    const facts=card.querySelector('.public-facts');(source.facts||[]).slice(0,6).forEach(([k,v])=>{const d=document.createElement('div');d.innerHTML='<span></span><b></b>';d.querySelector('span').textContent=k;d.querySelector('b').textContent=v==null?'—':String(v);facts.appendChild(d)});
    const add=card.querySelector('button');if(source.coverageOnly){add.disabled=true;add.textContent='Coverage only'}else add.addEventListener('click',()=>sendSourceToEvidence(source));const link=card.querySelector('a');link.href=source.url||'#';if(!source.url)link.style.display='none';return card
  }
  function renderPublicSources(){const z=$('[data-public-grid]');if(!z)return;z.innerHTML='';if(!lastPublicSources.length){z.innerHTML='<div class="timeline-empty" style="grid-column:1/-1">No public scan yet.</div>';return}lastPublicSources.forEach(s=>z.appendChild(sourceCard(s)))}
  function sendSourceToEvidence(source){
    const name=$('#ei-evidence-name'),type=$('#ei-evidence-type'),strength=$('#ei-evidence-strength'),date=$('#ei-evidence-date'),text=$('#ei-evidence-text');if(!text){set('[data-public-status]','Evidence Inbox is not ready yet. Reload the page and try again.');return}
    name.value=source.title;type.value='agency';type.dispatchEvent(new Event('change',{bubbles:true}));strength.value='authority';date.value=new Date().toISOString().slice(0,10);text.value=source.evidenceText||`${source.title}\n${source.copy}\n${(source.facts||[]).map(x=>`${x[0]}: ${x[1]}`).join('\n')}`;text.scrollIntoView({behavior:'smooth',block:'center'});set('[data-evidence-status]','Public evidence loaded. Review the extracted source text, then choose Parse + add evidence.');logEvent('public','Public source loaded into Evidence Inbox',source.title,false)
  }
  async function pullPublicEvidence(){
    const btn=$('[data-public-pull]'),status=$('[data-public-status]'),input=$('#pj-address');if(!input)return;if(btn)btn.disabled=true;lastPublicSources=[];renderPublicSources();
    try{
      if(status)status.textContent='Resolving the project address and querying authoritative sources…';
      const loc=await EI.requireResolvedAddress(input);if(!loc)throw new Error('Choose a verified project address first.');
      const c=loc.components||{},use=$('#pj-use')?.value||'other',jobs=[];
      jobs.push(fetchJSON(`/api/energy?state=${encodeURIComponent(c.state||'')}&use=${encodeURIComponent(use)}`).then(d=>({type:'energy',data:d})).catch(e=>({type:'energy',error:e})));
      if(c.tract)jobs.push(fetchJSON(`/api/risk?tract=${encodeURIComponent(c.tract)}`).then(d=>({type:'risk',data:d})).catch(e=>({type:'risk',error:e})));
      if((c.city||'').toLowerCase()==='chicago'&&c.state==='IL')jobs.push(fetchJSON(`/api/chicago-permits?street=${encodeURIComponent(c.street||'')}&city=Chicago&state=IL`).then(d=>({type:'permits',data:d})).catch(e=>({type:'permits',error:e})));
      const results=await Promise.all(jobs);
      lastPublicSources.push({kind:'VERIFIED GEOGRAPHY',grade:'A',title:'U.S. Census address + geography',copy:'Authoritative address resolution and geographic identifiers used as the backbone for other public-source lookups.',facts:[['Address',loc.label],['County',c.county||'—'],['Tract',c.tract||'—'],['ZIP',c.zip||'—']],url:'https://geocoding.geo.census.gov/geocoder/',evidenceText:`Verified address: ${loc.label}\nCounty: ${c.county||'unknown'}\nCensus tract: ${c.tract||'unknown'}\nState: ${c.state||'unknown'}\nZIP: ${c.zip||'unknown'}\nSource: U.S. Census Bureau address geocoder.`});
      const energy=results.find(x=>x.type==='energy')?.data;if(energy){lastPublicSources.push({kind:'ENERGY MARKET',grade:'A/B',title:'EIA state energy layer',copy:'Current state retail energy pricing plus the building-use intensity benchmark already used by ExpenseIntel. This is market evidence, not a property meter bill or tariff quote.',facts:[['Electric',energy.electricity?`${energy.electricity.centsKwh}¢/kWh`:'not returned'],['Gas',energy.gas?`${energy.gas.dollarsMcf}/Mcf`:'not returned'],['Intensity',energy.intensity?`${energy.intensity.kwhSqft} kWh/ft²`:'—'],['Sector',energy.sector||'—']],url:'https://www.eia.gov/',evidenceText:`State energy evidence for ${c.state}.\nElectricity: ${energy.electricity?.centsKwh??'not returned'} cents/kWh.\nGas: ${energy.gas?.dollarsMcf??'not returned'} dollars/Mcf.\nBuilding-use intensity benchmark: ${energy.intensity?.kwhSqft??'unknown'} kWh/ft2.\nSource: U.S. Energy Information Administration. State averages are not property-specific capacity or tariff evidence.`})}
      const risk=results.find(x=>x.type==='risk')?.data;if(risk?.available){lastPublicSources.push({kind:'HAZARD / SITE',grade:'A',title:'FEMA National Risk Index',copy:'Census-tract risk context from FEMA NRI. Useful for diligence prioritization, but not a parcel flood determination or insurance quote.',facts:[['Composite',risk.composite?.score??'—'],['Rating',risk.composite?.rating||'—'],['State percentile',risk.composite?.statePercentile??'—'],['Top hazard',risk.topHazards?.[0]?.name||'—']],url:'https://hazards.fema.gov/nri/',evidenceText:`FEMA National Risk Index for Census tract ${c.tract}.\nComposite risk score: ${risk.composite?.score??'not returned'}.\nRating: ${risk.composite?.rating||'not returned'}.\nState percentile: ${risk.composite?.statePercentile??'not returned'}.\nTop hazards: ${(risk.topHazards||[]).map(h=>`${h.name} (${h.rating||h.score||'n/a'})`).join(', ')}.\nThis is tract-level FEMA NRI context, not parcel flood-zone proof.`})}
      const permits=results.find(x=>x.type==='permits')?.data;if(permits?.available){const rec=permits.records||[];lastPublicSources.push({kind:'PERMIT HISTORY',grade:'A',title:'Chicago building permit history',copy:`The Chicago Department of Buildings dataset returned ${rec.length} recent/address-matched permit record${rec.length===1?'':'s'} from the current query. History can reveal prior work, permit conditions and project lineage; it does not prove current zoning or code compliance.`,facts:[['Records',rec.length],['Latest issue',permits.summary?.latestIssueDate?.slice(0,10)||'—'],['Conditions',permits.summary?.withConditions??0],['Coverage','2006-present']],url:permits.sourceUrl,evidenceText:`City of Chicago building permit history for ${loc.label}.\nMatched records returned: ${rec.length}.\nLatest issue date: ${permits.summary?.latestIssueDate||'not returned'}.\nRecords with permit conditions: ${permits.summary?.withConditions??0}.\nRecent permits:\n${rec.slice(0,8).map(x=>`${x.permit||'permit'} | ${x.status||'status unknown'} | ${x.issueDate||'no issue date'} | ${x.type||x.workType||'type unknown'} | ${x.description||''}`).join('\n')}\nSource: City of Chicago Data Portal Building Permits ydr8-5enu.`})}
      if((c.city||'').toLowerCase()==='chicago'&&c.state==='IL')lastPublicSources.push({kind:'ZONING COVERAGE',grade:'PORTAL',title:'Chicago zoning map / ordinance',copy:'ExpenseIntel found the official zoning coverage channel, but this scan does not yet convert the map polygon into a parcel-specific legal use determination. Keep this as an explicit open gate.',facts:[['Jurisdiction','Chicago'],['Status','manual parcel verification'],['Use','not determined'],['Confidence','open']],url:'https://gisapps.cityofchicago.org/zoning/',coverageOnly:true});
      else lastPublicSources.push({kind:'LOCAL COVERAGE GAP',grade:'OPEN',title:'Parcel zoning + local permit coverage',copy:'National zoning and municipal permit systems are fragmented. ExpenseIntel is not inventing a local result where a verified connector does not exist yet.',facts:[['Jurisdiction',`${c.city||'—'}, ${c.state||'—'}`],['Zoning','not auto-resolved'],['Permits','connector unavailable'],['Next','use Action Orders']],coverageOnly:true});
      renderPublicSources();if(status)status.textContent=`Public scan complete · ${lastPublicSources.filter(x=>!x.coverageOnly).length} returned evidence layers · ${lastPublicSources.filter(x=>x.coverageOnly).length} explicit coverage gap${lastPublicSources.filter(x=>x.coverageOnly).length===1?'':'s'}.`;logEvent('public','Public evidence scan completed',`${loc.label} · ${lastPublicSources.length} source/coverage cards`,true)
    }catch(e){if(status)status.textContent=e.message||'Public evidence scan failed.'}finally{if(btn)btn.disabled=false}
  }

  function loadScript(src,test){return new Promise((resolve,reject)=>{if(test?.())return resolve();const s=document.createElement('script');s.src=src;s.async=true;s.onload=resolve;s.onerror=()=>reject(new Error('Could not load document extraction library.'));document.head.appendChild(s)})}
  async function ocrImage(input,onProgress){await loadScript('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js',()=>window.Tesseract);const out=await window.Tesseract.recognize(input,'eng',{logger:m=>{if(m.status==='recognizing text'&&Number.isFinite(m.progress))onProgress?.(Math.round(m.progress*100))}});return out?.data?.text||''}
  async function extractPdf(file,onProgress){const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.mjs';const data=new Uint8Array(await file.arrayBuffer()),pdf=await pdfjs.getDocument({data}).promise,max=Math.min(pdf.numPages,30);let text='';for(let i=1;i<=max;i++){const page=await pdf.getPage(i),content=await page.getTextContent();text+=`\n--- PAGE ${i} ---\n`+content.items.map(x=>x.str).join(' ');onProgress?.(Math.round(i/max*65))}if(text.replace(/\W/g,'').length<100){const ocrPages=Math.min(pdf.numPages,3);let ocr='';for(let i=1;i<=ocrPages;i++){const page=await pdf.getPage(i),viewport=page.getViewport({scale:1.6}),canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:ctx,viewport}).promise;ocr+=`\n--- OCR PAGE ${i} ---\n`+await ocrImage(canvas,p=>onProgress?.(65+Math.round(((i-1)+p/100)/ocrPages*35)));}text=ocr}return{text:text.slice(0,120000),pages:pdf.numPages,scanned:text.includes('--- OCR PAGE')}}
  async function extractDocument(){const btn=$('[data-doc-extract]'),bar=$('[data-doc-progress]');if(!docFile)return;if(btn)btn.disabled=true;docText='';set('[data-doc-mode]','PROCESSING');set('[data-doc-preview]','Reading the document…');if(bar)bar.style.width='3%';try{let result;if(docFile.type==='application/pdf'){result=await extractPdf(docFile,p=>{if(bar)bar.style.width=`${p}%`});set('[data-doc-mode]',result.scanned?'PDF + OCR':'PDF TEXT');set('[data-doc-meta]',`${result.pages} page${result.pages===1?'':'s'} · ${result.scanned?'scanned fallback used':'embedded text extracted'}`);docText=result.text}else{set('[data-doc-mode]','IMAGE OCR');docText=(await ocrImage(docFile,p=>{if(bar)bar.style.width=`${p}%`})).slice(0,120000);set('[data-doc-meta]',`${docFile.type||'image'} · browser OCR`)}if(bar)bar.style.width='100%';set('[data-doc-preview]',docText.trim()||'No readable text was extracted.');$('[data-doc-send]').disabled=!docText.trim();logEvent('document','Document text extracted',`${docFile.name} · ${docText.length.toLocaleString()} characters`,true)}catch(e){set('[data-doc-mode]','ERROR');set('[data-doc-preview]',e.message||'Document extraction failed.');if(bar)bar.style.width='0%'}finally{if(btn)btn.disabled=false}}
  function sendDocumentToEvidence(){if(!docText.trim())return;const text=$('#ei-evidence-text');if(!text)return;$('#ei-evidence-name').value=docFile?.name||'Extracted project document';$('#ei-evidence-type').value=docFile?.type?.startsWith('image/')?'inspection':'other';$('#ei-evidence-type').dispatchEvent(new Event('change',{bubbles:true}));$('#ei-evidence-strength').value='document';text.value=docText;text.scrollIntoView({behavior:'smooth',block:'center'});set('[data-evidence-status]','Document text loaded from Document Intelligence. Review the text and source strength, then choose Parse + add evidence.');logEvent('document','Extracted document loaded into Evidence Inbox',docFile?.name||'document',false)}
  function bindDocuments(){const input=$('[data-doc-file]'),drop=$('[data-doc-drop]');const choose=f=>{docFile=f||null;docText='';set('[data-doc-name]',docFile?docFile.name:'No document loaded');set('[data-doc-meta]',docFile?`${(docFile.size/1024/1024).toFixed(2)} MB · ${docFile.type||'unknown type'}`:'PDF text + image OCR beta');set('[data-doc-mode]',docFile?'READY':'WAITING');$('[data-doc-extract]').disabled=!docFile;$('[data-doc-send]').disabled=true;set('[data-doc-preview]','Extracted text will appear here.');const b=$('[data-doc-progress]');if(b)b.style.width='0%'};$('[data-doc-pick]')?.addEventListener('click',()=>input?.click());input?.addEventListener('change',()=>choose(input.files?.[0]));drop?.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag')});drop?.addEventListener('dragleave',()=>drop.classList.remove('drag'));drop?.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag');choose(e.dataTransfer?.files?.[0])});drop?.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input?.click()}});$('[data-doc-extract]')?.addEventListener('click',extractDocument);$('[data-doc-send]')?.addEventListener('click',sendDocumentToEvidence)}

  function gateMap(){const out={};$$('.gate-row').forEach(row=>{const title=row.querySelector('.gate-main h3')?.textContent?.trim()||'Gate';const state=row.querySelector('.gate-state')?.textContent?.trim()||'OPEN';out[title]=state});return out}
  function captureState(){return{at:new Date().toISOString(),fragility:numText('[data-precision-frag]')??numText('[data-r-fragility]'),evidence:numText('[data-precision-evidence]')??numText('[data-evidence-score]'),bottleneck:($('[data-precision-bottleneck]')?.textContent||$('[data-r-bottleneck]')?.textContent||'—').trim(),gatePosture:($('[data-gate-posture]')?.textContent||'—').trim(),conflicts:numText('[data-conflict-count]')??0,utilityUnknown:numText('[data-r-utility]'),gates:gateMap()}}
  function baselineStore(){return loadJSON(BASELINE_KEY,{})}
  function baselineFor(){return baselineStore()[projectKey()]||null}
  function setBaseline(){const all=baselineStore(),state=captureState();all[projectKey()]=state;saveJSON(BASELINE_KEY,all);renderImpact();logEvent('baseline','Project baseline set',`Fragility ${state.fragility??'—'} · evidence ${state.evidence??'—'} · ${state.gatePosture}`,true)}
  function clearBaseline(){const all=baselineStore();delete all[projectKey()];saveJSON(BASELINE_KEY,all);renderImpact();logEvent('baseline','Project baseline cleared','Change Impact reset for this project.',false)}
  function delta(now,base){if(now==null||base==null)return null;return now-base}
  function sign(n){return n==null?'—':`${n>0?'+':''}${Math.round(n)}`}
  function renderImpact(){const b=baselineFor(),n=captureState(),zone=$('[data-impact-changes]');if(!zone)return;zone.innerHTML='';if(!b){set('[data-impact-posture]','NO BASELINE');set('[data-impact-copy]','Set a baseline after a meaningful project run. Future changes will be evaluated against it instead of disappearing into a new score.');set('[data-impact-frag]','—');set('[data-impact-evidence]','—');set('[data-impact-gates]','—');set('[data-impact-conflicts]','—');set('[data-baseline-meta]','No saved baseline for this project.');return}const fd=delta(n.fragility,b.fragility),ed=delta(n.evidence,b.evidence),cd=delta(n.conflicts,b.conflicts),gateNames=new Set([...Object.keys(b.gates||{}),...Object.keys(n.gates||{})]),gateChanges=[...gateNames].filter(k=>(b.gates||{})[k]!== (n.gates||{})[k]);set('[data-impact-frag]',sign(fd));set('[data-impact-evidence]',sign(ed));set('[data-impact-gates]',String(gateChanges.length));set('[data-impact-conflicts]',sign(cd));set('[data-baseline-meta]',`Baseline ${nowLabel(b.at)} · ${b.gatePosture}`);const worse=(fd??0)>4||(cd??0)>0||gateChanges.some(k=>/BLOCKED/.test((n.gates||{})[k]||'')),better=(fd??0)<-4||(ed??0)>8||gateChanges.some(k=>/CLEARED/.test((n.gates||{})[k]||''));set('[data-impact-posture]',worse?'RISK INCREASED':better?'PROJECT STRENGTHENED':'MIXED / STABLE');set('[data-impact-copy]',worse?'At least one material project-control signal worsened versus baseline. Read the changed gates before committing more capital.':better?'The current project record is stronger than baseline on one or more material controls. Confirm that the improvement came from better evidence or a real project change—not just a softer assumption.':'No single directional conclusion dominates the changes versus baseline.');const entries=[['Fragility',`${b.fragility??'—'} → ${n.fragility??'—'}`,fd==null?'No comparable score.':`${sign(fd)} points versus baseline.`],['Evidence depth',`${b.evidence??'—'} → ${n.evidence??'—'}`,ed==null?'No comparable score.':`${sign(ed)} points versus baseline.`],['Bottleneck',`${b.bottleneck} → ${n.bottleneck}`,b.bottleneck===n.bottleneck?'Dominant bottleneck unchanged.':'Dominant bottleneck changed.'],['Gate posture',`${b.gatePosture} → ${n.gatePosture}`,b.gatePosture===n.gatePosture?'Overall gate posture unchanged.':'Overall release posture changed.']];gateChanges.slice(0,4).forEach(k=>entries.push([k,`${(b.gates||{})[k]||'—'} → ${(n.gates||{})[k]||'—'}`,'Gate state changed.']));entries.forEach(([label,value,copy])=>{const el=document.createElement('article');el.className=`impact-card ${value.includes('→')&&!value.split('→').map(x=>x.trim()).every(x=>x===value.split('→')[0].trim())?'changed':''}`;el.innerHTML='<span></span><strong></strong><p></p>';el.querySelector('span').textContent=label;el.querySelector('strong').textContent=value;el.querySelector('p').textContent=copy;zone.appendChild(el)})}

  function renderTimeline(){const all=loadJSON(TIMELINE_KEY,{}),rows=all[projectKey()]||[],z=$('[data-timeline-list]');if(!z)return;z.innerHTML='';if(!rows.length){z.innerHTML='<div class="timeline-empty">No events yet. Public scans, document extraction, baselines and material project changes will appear here.</div>';return}rows.forEach(r=>{const el=document.createElement('article');el.className=`timeline-item ${r.major?'major':''}`;el.innerHTML='<header><span></span><time></time></header><strong></strong><p></p>';el.querySelector('header span').textContent=r.type||'PROJECT';el.querySelector('time').textContent=nowLabel(r.at);el.querySelector('strong').textContent=r.title;el.querySelector('p').textContent=r.detail||'';z.appendChild(el)})}
  function clearTimeline(){const all=loadJSON(TIMELINE_KEY,{});delete all[projectKey()];saveJSON(TIMELINE_KEY,all);renderTimeline()}

  function currentDecision(){const posture=($('[data-gate-posture]')?.textContent||'HOLD FOR EVIDENCE').trim(),evidence=($('[data-evidence-grade]')?.textContent||`${numText('[data-evidence-score]')??'—'}`).trim(),frag=($('[data-precision-frag]')?.textContent||$('[data-r-fragility]')?.textContent||'—').trim(),bot=($('[data-precision-bottleneck]')?.textContent||$('[data-r-bottleneck]')?.textContent||'—').trim(),conflicts=numText('[data-conflict-count]')??0,address=$('#pj-address')?.value||'Unresolved project',use=$('#pj-use')?.value||'other',gates=$$('.gate-row').map(r=>({title:r.querySelector('.gate-main h3')?.textContent?.trim()||'Gate',state:r.querySelector('.gate-state')?.textContent?.trim()||'OPEN',close:r.querySelector('.gate-close b')?.textContent?.trim()||'',owner:r.querySelector('.gate-owner b')?.textContent?.trim()||''})),conditions=gates.filter(g=>!/^CLEARED$/i.test(g.state)).slice(0,7);let decision='PROCEED WITH CONDITIONS';if(/HOLD|RESOLVE/i.test(posture)||conflicts>0)decision='HOLD';else if(/READY/i.test(posture)&&conditions.length===0)decision='PROCEED';return{posture,decision,evidence,frag,bot,conflicts,address,use,gates,conditions}}
  function renderDecision(){const d=currentDecision();set('[data-decision-posture]',d.decision);set('[data-decision-copy]',`${d.posture}. ${d.conditions.length?`${d.conditions.length} named condition${d.conditions.length===1?'':'s'} still control advancement.`:'No currently open gate is shown in the Gatekeeper.'}`);set('[data-decision-stamp]',d.decision.replace(/ /g,'\n'));set('[data-decision-evidence]',d.evidence);set('[data-decision-frag]',d.frag);set('[data-decision-bot]',d.bot);set('[data-decision-conflicts]',String(d.conflicts));const z=$('[data-decision-conditions]');if(!z)return;z.innerHTML='';(d.conditions.length?d.conditions:[{title:'No open gate shown',state:'CLEARED',owner:'Project team',close:'Keep evidence current.'}]).forEach((g,i)=>{const el=document.createElement('div');el.className='decision-condition';el.innerHTML='<i></i><strong></strong><span></span>';el.querySelector('i').textContent=String(i+1).padStart(2,'0');el.querySelector('strong').textContent=`${g.title} — ${g.close||g.owner}`;el.querySelector('span').textContent=g.state;z.appendChild(el)})}
  function briefText(d){return `EXPENSEINTEL PROJECT DECISION BRIEF\n${d.address}\nProposed use: ${d.use}\n\nSCREEN: ${d.decision}\nGatekeeper posture: ${d.posture}\nEvidence: ${d.evidence}\nFragility: ${d.frag}\nDominant bottleneck: ${d.bot}\nDirect conflicts: ${d.conflicts}\n\nCONDITIONS\n${d.conditions.length?d.conditions.map((g,i)=>`${i+1}. ${g.title} [${g.state}] — ${g.close||g.owner}`).join('\n'):'No open gate shown.'}\n\nScreening output only. Verify legal, engineering, code, utility, environmental, financial and transaction facts with the responsible professionals and authorities.`}
  function printBrief(){const d=currentDecision(),conditions=d.conditions.length?d.conditions.map((g,i)=>`<li><b>${esc(g.title)}</b><span>${esc(g.state)}</span><p>${esc(g.close||g.owner)}</p></li>`).join(''):'<li><b>No open gate shown</b><span>CLEARED</span><p>Keep evidence current.</p></li>',w=window.open('','_blank','noopener,noreferrer,width=900,height=1100');if(!w)return;w.document.write(`<!doctype html><html><head><title>ExpenseIntel Decision Brief</title><style>body{font-family:Arial,sans-serif;margin:0;color:#111;background:#f3f0e8}.sheet{max-width:820px;margin:28px auto;background:#fff;border:1px solid #111}.head{background:#111;color:#fff;padding:28px}.head small{letter-spacing:.12em;font-weight:700}.head h1{font-family:Georgia,serif;font-size:40px;margin:10px 0}.decision{font:800 24px monospace;color:#b8ff3f}.grid{display:grid;grid-template-columns:repeat(4,1fr);border-bottom:1px solid #111}.grid div{padding:14px;border-right:1px solid #ddd}.grid span{display:block;font:700 10px monospace;color:#666}.grid b{display:block;margin-top:6px}.body{padding:24px}h2{font-family:Georgia,serif}ol{padding:0;list-style:none}li{border-top:1px solid #ddd;padding:12px 0}li span{float:right;font:700 10px monospace}li p{font-size:12px;color:#555;margin:5px 0}.foot{border-top:1px solid #111;padding:15px 24px;font-size:10px;color:#666}@media print{body{background:#fff}.sheet{margin:0;max-width:none;border:0}}</style></head><body><div class="sheet"><div class="head"><small>EXPENSEINTEL / PROJECT DECISION BRIEF</small><h1>${esc(d.address)}</h1><div class="decision">${esc(d.decision)}</div><p>${esc(d.posture)} · proposed use ${esc(d.use)}</p></div><div class="grid"><div><span>EVIDENCE</span><b>${esc(d.evidence)}</b></div><div><span>FRAGILITY</span><b>${esc(d.frag)}</b></div><div><span>BOTTLENECK</span><b>${esc(d.bot)}</b></div><div><span>CONFLICTS</span><b>${d.conflicts}</b></div></div><div class="body"><h2>Conditions to advance</h2><ol>${conditions}</ol></div><div class="foot">Generated ${esc(new Date().toLocaleString())}. Screening output only; not legal, engineering, permitting, appraisal, environmental, insurance or investment advice.</div></div><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`);w.document.close();logEvent('brief','Decision brief generated',`${d.decision} · ${d.conditions.length} open conditions`,true)}
  async function copyBrief(){const d=currentDecision(),text=briefText(d);try{await navigator.clipboard.writeText(text);set('[data-decision-copy]','Brief copied to clipboard.');setTimeout(renderDecision,1800)}catch(_e){set('[data-decision-copy]','Clipboard unavailable. Open the printable brief instead.')}}

  async function cloudStatus(){try{const d=await fetchJSON('/api/cloud-status');if(d.configured){$('[data-cloud-dot]')?.classList.add('ready');set('[data-cloud-title]','Cloud backend configured');set('[data-cloud-copy]','A publishable backend is configured. Account sync still requires the ExpenseIntel project schema and auth flow to be enabled.')}else{set('[data-cloud-title]','Cloud backend not provisioned');set('[data-cloud-copy]','Browser-local mode is active. A dedicated ExpenseIntel Supabase project is required before real accounts can be enabled safely.')}}catch(_e){set('[data-cloud-title]','Cloud status unavailable');set('[data-cloud-copy]','Browser-local mode remains active.')}}

  let lastObserved='';function observeMaterialState(){const target=$('[data-project-results]')||document.body;const run=()=>{renderImpact();renderDecision();const s=captureState(),digest=JSON.stringify([s.fragility,s.evidence,s.bottleneck,s.gatePosture,s.conflicts,s.utilityUnknown,s.gates]);if(lastObserved&&digest!==lastObserved&&$('[data-project-results]')?.classList.contains('show'))logEvent('change','Project state changed',`${s.gatePosture} · fragility ${s.fragility??'—'} · evidence ${s.evidence??'—'} · ${s.bottleneck}`,false);lastObserved=digest};new MutationObserver(()=>setTimeout(run,120)).observe(target,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class']});run()}
  function bind(){
    injectUI();renderPublicSources();bindDocuments();renderTimeline();renderImpact();renderDecision();cloudStatus();
    $('[data-public-pull]')?.addEventListener('click',pullPublicEvidence);$('[data-set-baseline]')?.addEventListener('click',setBaseline);$('[data-clear-baseline]')?.addEventListener('click',clearBaseline);$('[data-clear-timeline]')?.addEventListener('click',clearTimeline);$('[data-print-brief]')?.addEventListener('click',printBrief);$('[data-copy-brief]')?.addEventListener('click',copyBrief);
    $('#pj-address')?.addEventListener('change',()=>{renderTimeline();renderImpact();renderDecision()});$('#pj-use')?.addEventListener('change',()=>{renderTimeline();renderImpact();renderDecision()});
    const vault=$('[data-evidence-vault]');if(vault)new MutationObserver(()=>{logEvent('evidence','Evidence record changed',($('[data-evidence-vault-count]')?.textContent||'Evidence vault updated'),false);renderDecision();renderImpact()}).observe(vault,{childList:true});observeMaterialState();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();
