const dns=require('dns').promises;
const net=require('net');
const {fetchBls,fetchTreasury,fetchFuelPrices}=require('./public-intel');
const {resolveFuelVehicle}=require('./vehicle-intel');
const {fetchRecalls,fetchComplaints,fetchRatings}=require('./nhtsa-safety');
const {fetchMortgageRates,fetchHousePriceContext,stateFromLocation}=require('./housing-intel');

const MAX_HTML=700000;
const MAKE_NAMES=['Acura','Alfa Romeo','Audi','BMW','Buick','Cadillac','Chevrolet','Chevy','Chrysler','Dodge','Ford','Genesis','GMC','Honda','Hyundai','Infiniti','Jaguar','Jeep','Kia','Land Rover','Lexus','Lincoln','Lucid','Mazda','Mercedes-Benz','Mercedes','Mini','Mitsubishi','Nissan','Polestar','Porsche','Ram','Rivian','Subaru','Tesla','Toyota','Volkswagen','Volvo'];
const GROUPS={vehicle:['new_vehicles','used_vehicles','gasoline','vehicle_repair'],home:['household','electricity','utility_gas','household_insurance'],property:['shelter','electricity','utility_gas','household_insurance'],equipment:['all_items','electricity'],'business-project':['all_items','electricity','utility_gas'],personal:['all_items','household'],other:['all_items']};
function cleanText(v,max=4000){return String(v||'').replace(/\0/g,'').replace(/\s+/g,' ').trim().slice(0,max)}
function finite(v){const n=Number(String(v??'').replace(/[$,%\s]/g,'').replace(/,/g,''));return Number.isFinite(n)?n:null}
function moneyFromText(text){const vals=[...String(text||'').matchAll(/\$\s?([0-9]{1,3}(?:,[0-9]{3})+(?:\.\d{1,2})?|[0-9]{3,}(?:\.\d{1,2})?)/g)].map(m=>finite(m[1])).filter(n=>n>0);return vals.length?vals[0]:null}
function stripHtml(s){return String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;|&#34;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/\s+/g,' ').trim()}
function meta(html,key,attr='name'){const rx=new RegExp(`<meta[^>]+${attr}=["']${key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}["'][^>]+content=["']([^"']+)["'][^>]*>`,`i`),m=html.match(rx);if(m)return m[1];const rx2=new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+${attr}=["']${key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}["'][^>]*>`,`i`);return html.match(rx2)?.[1]||''}
function titleFrom(html){return stripHtml(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||'')}
function walkJson(v,out,depth=0){if(depth>7||v==null)return;if(Array.isArray(v)){for(const x of v)walkJson(x,out,depth+1);return}if(typeof v!=='object')return;const type=Array.isArray(v['@type'])?v['@type'].join(' '):String(v['@type']||'');if(type)out.types.push(type);if(v.name&&!out.name)out.name=cleanText(v.name,300);if(v.description&&!out.description)out.description=cleanText(v.description,1200);const offer=v.offers||v.Offers;if(offer){const o=Array.isArray(offer)?offer[0]:offer;if(o&&typeof o==='object'){const p=finite(o.price??o.lowPrice??o.highPrice);if(p!=null&&!out.price)out.price=p;out.currency=out.currency||String(o.priceCurrency||'')}}const direct=finite(v.price);if(direct!=null&&!out.price)out.price=direct;for(const x of Object.values(v))walkJson(x,out,depth+1)}
function parseJsonLd(html){const out={types:[],name:'',description:'',price:null,currency:''};for(const m of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{walkJson(JSON.parse(m[1]),out)}catch(_e){}}return out}
function isPrivateIp(ip){if(!net.isIP(ip))return true;if(net.isIPv4(ip)){const p=ip.split('.').map(Number);return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===100&&p[1]>=64&&p[1]<=127)||(p[0]>=224)}const n=ip.toLowerCase();return n==='::1'||n==='::'||n.startsWith('fc')||n.startsWith('fd')||n.startsWith('fe80:')||n.startsWith('::ffff:127.')||n.startsWith('::ffff:10.')||n.startsWith('::ffff:192.168.')}
async function validatePublicUrl(raw){let u;try{u=new URL(raw)}catch(_e){throw new Error('That link is not a valid URL.')}if(!['http:','https:'].includes(u.protocol))throw new Error('Only public http/https links can be checked.');if(u.username||u.password)throw new Error('Links containing credentials are not supported.');if(u.port&&!['80','443'].includes(u.port))throw new Error('Non-standard URL ports are not supported.');const host=u.hostname.toLowerCase();if(host==='localhost'||host.endsWith('.local')||host.endsWith('.internal')||(net.isIP(host)&&isPrivateIp(host)))throw new Error('Private-network links are not supported.');const addrs=await dns.lookup(host,{all:true,verbatim:true});if(!addrs.length||addrs.some(x=>isPrivateIp(x.address)))throw new Error('This link does not resolve to a public internet address.');return u}
async function fetchPublicPage(raw,signal){let current=await validatePublicUrl(raw);for(let hop=0;hop<5;hop++){const r=await fetch(current.toString(),{redirect:'manual',signal,headers:{'User-Agent':'Mozilla/5.0 (compatible; ExpenseIntelCheck/1.0; +https://www.expenseintel.com)','Accept':'text/html,application/xhtml+xml'}});if(r.status>=300&&r.status<400){const loc=r.headers.get('location');if(!loc)throw new Error('The linked page redirected without a destination.');current=await validatePublicUrl(new URL(loc,current).toString());continue}return{response:r,finalUrl:current}}throw new Error('The linked page redirected too many times.')}
async function inspectUrl(raw){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),6500);try{const {response:r,finalUrl}=await fetchPublicPage(raw,controller.signal);if(!r.ok)throw new Error(`The linked page returned ${r.status}.`);const type=String(r.headers.get('content-type')||'');if(!type.includes('text/html')&&!type.includes('application/xhtml+xml'))throw new Error('The link is not an HTML product/listing page.');const reader=r.body?.getReader();let chunks=[],size=0;if(reader){while(size<MAX_HTML){const {done,value}=await reader.read();if(done)break;chunks.push(value);size+=value.length}try{reader.cancel()}catch(_e){}}const html=chunks.length?Buffer.concat(chunks.map(x=>Buffer.from(x))).toString('utf8'):await r.text();const ld=parseJsonLd(html),ogTitle=meta(html,'og:title','property'),ogDesc=meta(html,'og:description','property'),desc=meta(html,'description','name'),productPrice=finite(meta(html,'product:price:amount','property')||meta(html,'og:price:amount','property'));const title=cleanText(ld.name||ogTitle||titleFrom(html),320),description=cleanText(ld.description||ogDesc||desc,1600),price=ld.price||productPrice||moneyFromText(`${title} ${description}`);return{ok:true,url:finalUrl.toString(),host:finalUrl.hostname.replace(/^www\./,''),title,description,price,currency:ld.currency||'USD',schemaTypes:[...new Set(ld.types)].slice(0,12),source:'Public webpage metadata',note:'ExpenseIntel reads publicly returned page metadata. Some retailers and marketplaces block automated retrieval; if so, paste the listing text instead.'}}finally{clearTimeout(timer)}}
function classify(text,url=''){const t=`${text} ${url}`.toLowerCase();if(/zillow|redfin|realtor\.com|homes\.com|condo|townhome|house for sale|home for sale|real estate|property listing|mortgage|apartment/.test(t))return'property';if(/\b(car|truck|suv|sedan|coupe|vehicle|pickup|hatchback|crossover|vin)\b/.test(t)||MAKE_NAMES.some(m=>new RegExp(`\\b${m.replace(/[- ]/g,'[- ]?')}\\b`,'i').test(text)))return'vehicle';if(/hvac|roof|plumb|electrician|solar|furnace|air conditioner|heat pump|renovat|remodel|contractor|home repair|windows|siding/.test(t))return'home';if(/forklift|excavator|cnc|generator|compressor|lathe|skid steer|machine|industrial equipment|commercial equipment/.test(t))return'equipment';if(/warehouse|restaurant|facility|buildout|build-out|lease|site|permit|utility capacity|construction project|development project/.test(t))return'business-project';return'personal'}
function inferVehicle(text){const s=String(text||'');const year=s.match(/\b((?:19|20)\d{2})\b/)?.[1]||'';let make='';for(const m of MAKE_NAMES){if(new RegExp(`\\b${m.replace(/[- ]/g,'[- ]?')}\\b`,'i').test(s)){make=m==='Chevy'?'Chevrolet':m;break}}let model='';if(year&&make){const esc=make.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const after=s.match(new RegExp(`${year}\\s+${esc}\\s+([A-Za-z0-9][A-Za-z0-9 -]{1,32})`,'i'))?.[1]||s.match(new RegExp(`${esc}\\s+([A-Za-z0-9][A-Za-z0-9 -]{1,32})`,'i'))?.[1]||'';model=after.split(/\s(?:for|in|with|at|from|priced|price|sale|asking|listed|awd|4wd|rwd|fwd|crew|supercrew|xlt|lt|limited|premium|sport|hybrid|electric)\b/i)[0].trim();model=model.replace(/[|,:;].*$/,'').replace(/\s+-\s+.*$/,'').trim().split(/\s+/).slice(0,4).join(' ')}return{year,make,model}}
function verdict({price,category,evidence,vehicle,housing}){let score=50,signals=[],unknown=[];if(price){score+=4;signals.push('Price captured from the decision.')}else unknown.push('Exact purchase/quote price');const sourceCount=evidence?.sourceCount||0;score+=Math.min(18,sourceCount*4);if(category==='vehicle'){if(vehicle?.fuel?.ok){score+=9;signals.push('Official EPA/DOE operating-cost data connected.')}else unknown.push('Exact EPA configuration');if(vehicle?.safety?.ok){score+=9;signals.push('NHTSA safety/recall evidence connected.')}else unknown.push('Model-specific safety evidence');unknown.push('Verified transaction-price benchmark');unknown.push('Personalized insurance/depreciation');}else if(category==='property'){if(housing?.mortgage?.ok){score+=7;signals.push('Freddie Mac mortgage context connected.')}if(housing?.hpi?.ok){score+=7;signals.push('FHFA local house-price trend connected.')}unknown.push('Property-specific appraisal / comps');unknown.push('Property-specific insurance and taxes unless separately verified');}else{unknown.push('Transaction-level comparable price database');if(category==='home')unknown.push('Local scope-matched contractor quotes');}score=Math.max(0,Math.min(92,score));let label='NEEDS MORE EVIDENCE',tone='neutral';if(score>=78){label='STRONG CONTEXT';tone='good'}else if(score>=62){label='USEFUL, NOT COMPLETE';tone='mid'}return{score,label,tone,signals,unknown}}
async function gather({text='',url='',category='',price=null,location=''}={}){let page=null;if(url){try{page=await inspectUrl(url)}catch(e){page={ok:false,error:String(e.message||e)}}}const combined=cleanText([text,page?.title,page?.description].filter(Boolean).join(' '),5000);const detected=category&&category!=='auto'?category:classify(combined,url);const amount=finite(price)||page?.price||moneyFromText(combined);const state=stateFromLocation(location),blsKeys=GROUPS[detected]||GROUPS.other;const [bls,treasury,fuel,mortgage,hpi]=await Promise.all([fetchBls(blsKeys),fetchTreasury(),detected==='vehicle'?fetchFuelPrices():Promise.resolve(null),detected==='property'?fetchMortgageRates():Promise.resolve(null),detected==='property'&&location?fetchHousePriceContext(location,state):Promise.resolve(null)]);const evidenceSignals=[];for(const s of bls.signals||[])evidenceSignals.push({label:s.label,value:s.value,unit:'index',period:s.period,yoy:s.yoy,source:s.source,grade:'A'});if(treasury.ok)evidenceSignals.push({label:'U.S. Treasury 10-year',value:treasury.tenYear,unit:'%',period:treasury.date,source:treasury.source,grade:'A'});if(fuel?.ok)evidenceSignals.push({label:'Regular gasoline',value:fuel.regular,unit:'$/gal',period:'current federal assumption',source:fuel.source,grade:'A'});if(mortgage?.ok&&mortgage.thirtyYear!=null)evidenceSignals.push({label:'30-year fixed mortgage',value:mortgage.thirtyYear,unit:'%',period:mortgage.date,source:mortgage.source,grade:'A'});if(hpi?.ok){const h=hpi.metro||hpi.state;if(h?.oneYearChange!=null)evidenceSignals.push({label:`${h.name} house prices`,value:h.oneYearChange,unit:'% YoY',period:'latest FHFA quarterly HPI',source:hpi.source,grade:'A'})}let vehicle=null;if(detected==='vehicle'){const v=inferVehicle(combined);if(v.year&&v.make&&v.model){const [f,r,c,ratings]=await Promise.all([resolveFuelVehicle(v),fetchRecalls(v),fetchComplaints({...v,limit:20}),fetchRatings(v)]);vehicle={identity:v,fuel:f,safety:{ok:!!(r.ok||c.ok||ratings.ok),recalls:r.ok?r:null,complaints:c.ok?c:null,ratings:ratings.ok?ratings:null}}}else vehicle={identity:v,fuel:null,safety:null}}const evidence={signals:evidenceSignals,sourceCount:new Set(evidenceSignals.map(x=>x.source).filter(Boolean)).size};const housing=detected==='property'?{mortgage,hpi}:null;const result=verdict({price:amount,category:detected,evidence,vehicle,housing});return{ok:true,input:{text:cleanText(text,1600),url,location,category:detected},page,detectedCategory:detected,price:amount,evidence,vehicle,housing,check:result,actions:actionsFor(detected,{amount,location,combined})}}
function actionsFor(category,{amount,location,combined}){const p=new URLSearchParams({q:combined.slice(0,500),category,amount:amount||'',location:location||'',horizon:'5'}),a=[];if(category==='vehicle'||category==='property'||category==='equipment'||category==='personal')a.push({label:'Build TrueCost',href:`/truecost/?${p}`});if(category==='home')a.push({label:'X-Ray the quote',href:'/xray/'});if(category==='property'||category==='business-project')a.push({label:'Open Project Intelligence',href:`/project/?${p}`});a.push({label:'Test timing',href:`/timing/?${p}`});a.push({label:'Save / watch',href:'/watch/'});return a}
module.exports={inspectUrl,classify,inferVehicle,gather};