'use strict';
const {finite,clamp}=require('./http');
const CONTRACTOR_MODEL_VERSION='EI-CON-2026.09.1';
const SCOPE_RISK={service:.02,fitout:.03,renovation:.035,groundup:.05,civil:.06};
const UNKNOWN_RISK={low:.01,medium:.03,high:.06};
function hazardRate(rating){const s=String(rating||'').toLowerCase();if(s.includes('very high'))return .03;if(s.includes('relatively high')||s==='high')return .02;if(s.includes('moderate'))return .01;return 0}
function normalize(input={}){const scope=['service','fitout','renovation','groundup','civil'].includes(input.scope)?input.scope:'renovation',unknowns=['low','medium','high'].includes(input.unknowns)?input.unknowns:'medium';return{scope,sqft:Math.max(300,finite(input.sqft,25000)),laborHours:Math.max(0,finite(input.laborHours,0)),laborRate:Math.max(0,finite(input.laborRate,0)),laborPremium:clamp(finite(input.laborPremium,0),0,200)/100,materials:Math.max(0,finite(input.materials,0)),equipDays:Math.max(0,finite(input.equipDays,0)),equipRate:Math.max(0,finite(input.equipRate,0)),miles:Math.max(0,finite(input.miles,0)),trips:Math.max(0,finite(input.trips,0)),mileRate:Math.max(0,finite(input.mileRate,0)),tons:Math.max(0,finite(input.tons,0)),tonRate:Math.max(0,finite(input.tonRate,0)),permits:Math.max(0,finite(input.permits,0)),service:Math.max(0,finite(input.service,0)),months:Math.max(1,finite(input.months,1)),overhead:Math.max(0,finite(input.overhead,0)),unknowns,contingencyPct:clamp(finite(input.contingency,5),0,40)/100,margin:clamp(finite(input.margin,18),1,60)/100,verified:{wage:!!input.verified?.wage,permit:!!input.verified?.permit,utility:!!input.verified?.utility,site:!!input.verified?.site,disposal:!!input.verified?.disposal,schedule:!!input.verified?.schedule}}}
function readiness(i,locationCase){const verified=Object.values(i.verified).filter(Boolean).length,publicEvidence=finite(locationCase?.evidence?.score,0),score=Math.round(Math.min(100,35+verified*7.5+publicEvidence*.2));return{score,label:score>=85?'Bid-review ready':score>=70?'Developing':score>=55?'Open diligence':'Early case'}}
function calculateContractorDecision(input,locationCase){const i=normalize(input),labor=i.laborHours*i.laborRate*(1+i.laborPremium),equipment=i.equipDays*i.equipRate,mobilization=i.miles*i.trips*i.mileRate,disposal=i.tons*i.tonRate,schedule=i.months*i.overhead,direct=labor+equipment+i.materials+mobilization+disposal+i.permits+i.service+schedule,hr=hazardRate(locationCase?.risk?.composite?.rating),locationPct=Math.min(.15,(SCOPE_RISK[i.scope]||.03)+(UNKNOWN_RISK[i.unknowns]||.03)+hr),contingency=direct*i.contingencyPct,reserve=direct*locationPct,floor=direct+contingency+reserve,target=floor/(1-i.margin),marginDollars=target-floor,ready=readiness(i,locationCase),sensitivity=[['Labor +10%',labor*.10],['Materials +10%',i.materials*.10],['One extra month',i.overhead],['Mobilization +50%',mobilization*.50],['Utility/service allowance +25%',i.service*.25],['Disposal +25%',disposal*.25]].map(([label,delta])=>({label,delta})).sort((a,b)=>b.delta-a.delta);return{modelVersion:CONTRACTOR_MODEL_VERSION,inputs:i,costs:{labor,equipment,materials:i.materials,mobilization,disposal,permits:i.permits,service:i.service,schedule,direct,contingency,reserve,floor,target,marginDollars,bidPerSqft:i.sqft?target/i.sqft:null},locationReservePct:locationPct,hazardReservePct:hr,readiness:ready,sensitivity,locationCaseVersion:locationCase?.modelVersion||null,warning:'Pre-bid decision support only. Not a contractor estimate, proposal, engineering opinion or quote.'}}
module.exports={CONTRACTOR_MODEL_VERSION,calculateContractorDecision};
