'use strict';
const {finite,clamp}=require('./http');
const HOME_MODEL_VERSION='EI-HOME-2026.09.1';

function payment(loan,ratePct,years){const months=Math.max(1,Math.round(years*12)),r=ratePct/100/12;if(loan<=0)return 0;if(r===0)return loan/months;return loan*r/(1-Math.pow(1+r,-months))}
function balance(loan,ratePct,years,monthsPaid){const months=Math.max(1,Math.round(years*12)),k=Math.min(months,Math.max(0,monthsPaid)),r=ratePct/100/12,p=payment(loan,ratePct,years);if(r===0)return Math.max(0,loan-p*k);return Math.max(0,loan*Math.pow(1+r,k)-p*((Math.pow(1+r,k)-1)/r))}
function fiveYearRent(monthly,growthPct){let total=0,rent=Math.max(0,monthly),g=growthPct/100;for(let y=0;y<5;y++){total+=rent*12;rent*=1+g}return total}

function normalize(input={},locationCase={}){
  const price=Math.max(1,finite(input.price,0)),sqft=Math.max(300,finite(input.sqft,2500)),downPct=clamp(finite(input.downPct,20),0,100),rate=clamp(finite(input.rate,6.5),0,30),term=clamp(finite(input.term,30),1,40);
  const fallbackTax=locationCase?.categories?.tax||0,fallbackInsurance=locationCase?.categories?.insurance||0;
  const tax=finite(input.tax,0)>0?finite(input.tax,0):fallbackTax,insurance=finite(input.insurance,0)>0?finite(input.insurance,0):fallbackInsurance;
  return{price,sqft,downPct,rate,term,tax,insurance,taxSource:finite(input.tax,0)>0?'user supplied':'ExpenseIntel modeled fallback',insuranceSource:finite(input.insurance,0)>0?'user supplied':'ExpenseIntel modeled fallback',hoa:Math.max(0,finite(input.hoa,0)),maintPct:clamp(finite(input.maintPct,1),0,10)/100,closingPct:clamp(finite(input.closingPct,2.5),0,15)/100,app:clamp(finite(input.app,3),-20,30)/100,salePct:clamp(finite(input.salePct,6),0,15)/100,budget:Math.max(0,finite(input.budget,0)),rent:Math.max(0,finite(input.rent,0)),rentGrowth:clamp(finite(input.rentGrowth,3),-10,20),locationAnnual:(locationCase?.categories?.electric||0)+(locationCase?.categories?.gas||0)+(locationCase?.categories?.water||0)+(locationCase?.categories?.other||0)};
}
function ownershipNet(i,appRate){const downCash=i.price*i.downPct/100,loan=i.price-downCash,pi=payment(loan,i.rate,i.term),maintAnnual=i.price*i.maintPct,monthly=pi+i.tax/12+i.insurance/12+i.hoa+maintAnnual/12+i.locationAnnual/12,closingCash=i.price*i.closingPct,bal5=balance(loan,i.rate,i.term,60),value5=i.price*Math.pow(1+appRate,5),saleCosts=value5*i.salePct,proceeds=Math.max(0,value5-saleCosts-bal5),cash5=downCash+closingCash+monthly*60,net=cash5-proceeds;return{downCash,loan,pi,maintAnnual,monthly,closingCash,bal5,value5,saleCosts,proceeds,cash5,net,principal:loan-bal5}}
function maxPriceForBudget(i){if(!i.budget)return null;const taxRatio=i.tax/i.price,insRatio=i.insurance/i.price;const monthlyAt=p=>payment(p*(1-i.downPct/100),i.rate,i.term)+(p*taxRatio)/12+(p*insRatio)/12+i.hoa+(p*i.maintPct)/12+i.locationAnnual/12;let lo=0,hi=Math.max(i.price*5,3000000);for(let j=0;j<70;j++){const mid=(lo+hi)/2;if(monthlyAt(mid)<=i.budget)lo=mid;else hi=mid}return lo}
function breakEvenApp(i,rentFive){if(!i.rent)return null;const f=a=>ownershipNet(i,a).net-rentFive;let lo=-.15,hi=.25;if(f(lo)<=0)return{kind:'below',value:-.15,label:'< -15% / yr'};if(f(hi)>0)return{kind:'above',value:.25,label:'> 25% / yr'};for(let j=0;j<70;j++){const mid=(lo+hi)/2;if(f(mid)>0)lo=mid;else hi=mid}const value=(lo+hi)/2;return{kind:'within',value,label:`${(value*100).toFixed(1)}% / yr`}}
function calculateHomeDecision(input,locationCase){const i=normalize(input,locationCase),o=ownershipNet(i,i.app),rentFive=fiveYearRent(i.rent,i.rentGrowth),maxPrice=maxPriceForBudget(i),breakEven=breakEvenApp(i,rentFive),stress=o.pi+(i.tax*1.10)/12+(i.insurance*1.25)/12+i.hoa+(o.maintAnnual*1.25)/12+(i.locationAnnual*1.15)/12,budgetGap=i.budget?i.budget-o.monthly:null,rentDifference=i.rent?o.net-rentFive:null;return{modelVersion:HOME_MODEL_VERSION,inputs:i,ownership:o,rentFive,maxPrice,breakEven,stress,budgetGap,rentDifference,locationCaseVersion:locationCase?.modelVersion||null,warning:'Decision support only. Confirm financing, taxes, insurance, HOA and property condition independently.'}}
module.exports={HOME_MODEL_VERSION,payment,balance,fiveYearRent,calculateHomeDecision};
