const FREDDIE='https://www.freddiemac.com/pmms';
const FHFA_STATE='https://www.fhfa.gov/hpi-state/json';
const FHFA_CITY='https://www.fhfa.gov/hpi-city/json';
const STATE_NAMES={AL:'Alabama',AK:'Alaska',AZ:'Arizona',AR:'Arkansas',CA:'California',CO:'Colorado',CT:'Connecticut',DE:'Delaware',DC:'District of Columbia',FL:'Florida',GA:'Georgia',HI:'Hawaii',ID:'Idaho',IL:'Illinois',IN:'Indiana',IA:'Iowa',KS:'Kansas',KY:'Kentucky',LA:'Louisiana',ME:'Maine',MD:'Maryland',MA:'Massachusetts',MI:'Michigan',MN:'Minnesota',MS:'Mississippi',MO:'Missouri',MT:'Montana',NE:'Nebraska',NV:'Nevada',NH:'New Hampshire',NJ:'New Jersey',NM:'New Mexico',NY:'New York',NC:'North Carolina',ND:'North Dakota',OH:'Ohio',OK:'Oklahoma',OR:'Oregon',PA:'Pennsylvania',RI:'Rhode Island',SC:'South Carolina',SD:'South Dakota',TN:'Tennessee',TX:'Texas',UT:'Utah',VT:'Vermont',VA:'Virginia',WA:'Washington',WV:'West Virginia',WI:'Wisconsin',WY:'Wyoming'};
function timeout(ms=6500){const c=new AbortController();const timer=setTimeout(()=>c.abort(),ms);return{signal:c.signal,done:()=>clearTimeout(timer)}}
async function fetchText(url){const t=timeout();try{const r=await fetch(url,{signal:t.signal,headers:{'User-Agent':'Mozilla/5.0 ExpenseIntel/1.0'}});if(!r.ok)throw new Error(`${new URL(url).hostname} ${r.status}`);return await r.text()}finally{t.done()}}
async function fetchJson(url){const t=timeout();try{const r=await fetch(url,{signal:t.signal,headers:{Accept:'application/json','User-Agent':'ExpenseIntel/1.0 (+https://www.expenseintel.com)'}});if(!r.ok)throw new Error(`${new URL(url).hostname} ${r.status}`);return await r.json()}finally{t.done()}}
function strip(s){return String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&#039;|&apos;/gi,"'").replace(/\s+/g,' ').trim()}
function finite(v){const n=Number(String(v??'').replace(/[,%]/g,''));return Number.isFinite(n)?n:null}
function norm(v){return String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'')}
function stateFromLocation(s){const m=String(s||'').toUpperCase().match(/(?:,|\s)([A-Z]{2})(?:\s+\d{5}(?:-\d{4})?)?(?:\s|$|,)/);return m?.[1]||''}
function cityFromLocation(s){const parts=String(s||'').split(',').map(x=>x.trim()).filter(Boolean);if(parts.length>=2){const last=parts[parts.length-1],prev=parts[parts.length-2];if(/^[A-Za-z .'-]+$/.test(prev)&&/\b[A-Z]{2}\b/i.test(last))return prev}return parts[0]||''}
async function fetchMortgageRates(){try{const text=strip(await fetchText(FREDDIE)),r30=text.match(/30[- ]year\s+Fixed[- ]Rate\s+Mortgage\s+([0-9.]+)%/i)||text.match(/30[- ]Yr\s+FRM\s+([0-9.]+)%/i),r15=text.match(/15[- ]year\s+Fixed[- ]Rate\s+Mortgage\s+([0-9.]+)%/i)||text.match(/15[- ]Yr\s+FRM\s+([0-9.]+)%/i),date=(text.match(/(?:averages|rates)\s+as of\s+([A-Za-z]+\s+\d{1,2},\s+\d{4})/i)||text.match(/as of\s+(\d{2}\/\d{2}\/\d{4})/i))?.[1]||'';const thirty=finite(r30?.[1]),fifteen=finite(r15?.[1]);if(thirty==null&&fifteen==null)throw new Error('Mortgage rates not found');return{ok:true,date,thirtyYear:thirty,fifteenYear:fifteen,source:'Freddie Mac Primary Mortgage Market Survey',sourceUrl:FREDDIE,grade:'A',retrievedAt:new Date().toISOString(),note:'National weekly averages based on mortgage applications submitted through Freddie Mac Loan Product Advisor; not a personalized rate quote.'}}catch(e){return{ok:false,error:String(e?.message||e)}}}
async function fetchHousePriceContext(location,stateInput=''){const state=(stateInput||stateFromLocation(location)).toUpperCase(),stateName=STATE_NAMES[state],city=cityFromLocation(location);try{const [states,cities]=await Promise.all([fetchJson(FHFA_STATE),fetchJson(FHFA_CITY)]),s=Array.isArray(states)?states.find(x=>x.name===stateName):null;let metro=null;if(Array.isArray(cities)&&city){const nc=norm(city);const candidates=cities.filter(x=>!state||String(x.name||'').toUpperCase().includes(`, ${state}`)).map(x=>({x,score:norm(String(x.name||'').split(',')[0]).startsWith(nc)?100:norm(x.name).includes(nc)?85:nc.includes(norm(String(x.name||'').split('-')[0]))?70:0})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);metro=candidates[0]?.x||null}return{ok:!!(s||metro),state:stateName&&s?{name:s.name,rank:finite(s.current_rank),quarterChange:finite(s.sa_1period),oneYearChange:finite(s.sa_1y),fiveYearChange:finite(s.sa_5y),since1991:finite(s.sa_since91)}:null,metro:metro?{name:metro.name,rank:finite(metro.current_rank),quarterChange:finite(metro.nsa_1period),oneYearChange:finite(metro.nsa_1y),fiveYearChange:finite(metro.nsa_5y),since1991:finite(metro.nsa_since91)}:null,source:'Federal Housing Finance Agency House Price Index',sourceUrl:'https://www.fhfa.gov/data/hpi/datasets',grade:'A',retrievedAt:new Date().toISOString(),note:'HPI measures changes in house values; it is not a current listing-price or appraisal estimate.'}}catch(e){return{ok:false,error:String(e?.message||e)}}}
module.exports={fetchMortgageRates,fetchHousePriceContext,stateFromLocation,cityFromLocation};