function finite(v){const n=Number(v);return Number.isFinite(n)?n:null}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function percentilePosition(price,p){if(!price||!p)return null;const pts=[[10,p['10']],[25,p['25']],[50,p['50']],[75,p['75']],[90,p['90']]].filter(x=>finite(x[1])!=null);if(!pts.length)return null;if(price<=pts[0][1])return pts[0][0];for(let i=1;i<pts.length;i++){const [a,av]=pts[i-1],[b,bv]=pts[i];if(price<=bv){const span=bv-av;return Math.round(a+(b-a)*(span?((price-av)/span):0))}}return 95}
function locationParts(location){const s=String(location||'').trim();const zip=s.match(/\b(\d{5})\b/)?.[1]||'';const cs=s.match(/^\s*([^,]+),\s*([A-Za-z]{2})\b/);return{zip,city:cs?.[1]?.trim()||'',state:cs?.[2]?.toUpperCase()||''}}
function statsOf(d,field='price'){const st=d?.stats?.[field]||{},p=st.percentiles||{};return{count:finite(st.count)??finite(d?.num_found)??0,median:finite(st.median),mean:finite(st.mean),min:finite(st.min),max:finite(st.max),p10:finite(p['10']),p25:finite(p['25']),p75:finite(p['75']),p90:finite(p['90'])}}
function normalizeListing(x){return{id:x.id||x.listing_id||'',price:finite(x.price),msrp:finite(x.msrp),miles:finite(x.miles),year:x.build?.year||x.year||'',make:x.build?.make||x.make||'',model:x.build?.model||x.model||'',trim:x.build?.trim||x.trim||'',dealer:x.dealer?.name||x.seller_name||'',city:x.dealer?.city||x.city||'',state:x.dealer?.state||x.state||'',dom:finite(x.dom_active||x.dom),url:x.vdp_url||x.source_url||x.website_url||''}}
async function request(endpoint,params,key){const q=new URLSearchParams({api_key:key,...params}),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),7000);try{const r=await fetch(`https://api.marketcheck.com${endpoint}?${q}`,{signal:controller.signal,headers:{Accept:'application/json','User-Agent':'ExpenseIntel/1.0 (+https://www.expenseintel.com)'}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error||`MarketCheck ${r.status}`);return{ok:true,data:d}}catch(e){return{ok:false,error:String(e?.message||e)}}finally{clearTimeout(timer)}}
function baseParams({year,make,model,trim,vin},includeTrim=true){const p={start:'0',rows:'8',stats:'price,miles,dom_active',dedup:'true'};if(vin){p.vins=vin;p.match=includeTrim?'year,make,model,trim':'year,make,model'}else{p.year=String(year);p.make=String(make);p.model=String(model);if(includeTrim&&trim)p.trim=String(trim)}return p}
function locationTiers(location){const l=locationParts(location),out=[];if(l.zip){out.push({scope:'local',label:'75-mile',params:{zip:l.zip,radius:'75'}});out.push({scope:'regional',label:'200-mile',params:{zip:l.zip,radius:'200'}})}else if(l.city&&l.state){out.push({scope:'local',label:`${l.city}, ${l.state}`,params:{city:l.city,state:l.state}});out.push({scope:'state',label:l.state,params:{state:l.state}})}else if(l.state)out.push({scope:'state',label:l.state,params:{state:l.state}});out.push({scope:'national',label:'U.S.',params:{}});return out}
function blend(a,b,key){const av=finite(a?.[key]),bv=finite(b?.[key]);if(av==null)return bv;if(bv==null)return av;return av*.48+bv*.52}
function confidence({active,recent,scope,includeTrim,vin,miles}){const ac=active?.count||0,rc=recent?.count||0,total=ac+rc;let s=22;if(vin)s+=14;else if(includeTrim)s+=12;else s+=4;s+=scope==='local'?18:scope==='regional'?14:scope==='state'?9:2;s+=Math.min(22,total>=60?22:total>=30?18:total>=15?13:total>=8?7:2);if(ac>=8&&rc>=8&&active.median&&recent.median){const gap=Math.abs(active.median-recent.median)/((active.median+recent.median)/2);s+=gap<=.05?16:gap<=.10?10:gap<=.18?3:-8}if(rc>=10)s+=5;if(miles!=null&&active?.milesMedian!=null){const gap=Math.abs(Number(miles)-active.milesMedian);if(gap>30000)s-=12;else if(gap>15000)s-=6}return clamp(Math.round(s),0,95)}
async function fetchTier(key,input,tier,includeTrim){const common={...baseParams(input,includeTrim),...tier.params};const [a,r]=await Promise.all([request('/v2/search/car/active',common,key),request('/v2/search/car/recents',{...common,sold:'true'},key)]);const active=a.ok?statsOf(a.data):{count:0},recent=r.ok?statsOf(r.data):{count:0};if(a.ok){const ms=statsOf(a.data,'miles');active.milesMedian=ms.median;active.listings=(a.data.listings||[]).slice(0,8).map(normalizeListing)}if(r.ok){const ms=statsOf(r.data,'miles');recent.milesMedian=ms.median}return{active,recent,errors:[a.ok?'':a.error,r.ok?'':r.error].filter(Boolean)}}
async function fetchVehicleComparables({year,make,model,vin='',price=null,location='',trim='',miles=null}={}){const key=process.env.MARKETCHECK_API_KEY;if(!key)return{ok:false,available:false,configured:false,error:'Licensed automotive comparable data is not configured.'};if(!year||!make||!model)return{ok:false,available:false,configured:true,error:'Exact year, make and model are required for comparable pricing.'};const tiers=locationTiers(location),precision=[true,...(trim||vin?[false]:[])];let best=null;for(const includeTrim of precision){for(const tier of tiers){const res=await fetchTier(key,{year,make,model,trim,vin},tier,includeTrim),combined=(res.active.count||0)+(res.recent.count||0),score=confidence({active:res.active,recent:res.recent,scope:tier.scope,includeTrim,vin,miles});const candidate={...res,tier,includeTrim,score,combined};if(!best||candidate.score>best.score||(candidate.score===best.score&&candidate.combined>best.combined))best=candidate;if(score>=68&&combined>=12&&(res.active.count>=5||res.recent.count>=5)){best=candidate;break}}if(best?.score>=68&&best.combined>=12)break}
 if(!best)return{ok:false,available:false,configured:true,error:'No comparable vehicle data returned.'};const {active,recent,tier,includeTrim,score,combined}=best,median=blend(active,recent,'median'),p25=blend(active,recent,'p25'),p75=blend(active,recent,'p75'),p10=blend(active,recent,'p10'),p90=blend(active,recent,'p90'),listingPrice=finite(price),delta=listingPrice&&median?listingPrice-median:null,deltaPct=delta!=null&&median?delta/median:null,verdictEligible=score>=68&&combined>=12&&median!=null;const p={10:p10,25:p25,50:median,75:p75,90:p90};return{ok:verdictEligible,available:median!=null,configured:true,verdictEligible,confidenceScore:score,confidenceLabel:score>=82?'HIGH':score>=68?'GOOD':score>=55?'DIRECTIONAL':'LOW',matchScope:tier.label,matchPrecision:includeTrim?(vin?'VIN-matched attributes':'exact trim'):'year / make / model',source:'MarketCheck active + recent sold-listing market data',sourceUrl:'https://www.marketcheck.com/apis/',numFound:combined,activeCount:active.count||0,recentSoldCount:recent.count||0,activeMedian:active.median,recentSoldMedian:recent.median,median,mean:blend(active,recent,'mean'),min:finite(active.min)??finite(recent.min),max:finite(active.max)??finite(recent.max),p10,p25,p75,p90,listingPrice,deltaToMedian:delta,deltaToMedianPct:deltaPct,approxPercentile:verdictEligible?percentilePosition(listingPrice,p):null,medianMiles:active.milesMedian??recent.milesMedian,listings:active.listings||[],note:verdictEligible?'ExpenseIntel only publishes a price-position verdict when match precision, geography and sample size clear its reliability threshold. Active listings and recently sold/expired dealer listings are advertised prices, not guaranteed transaction prices.':'Comparable data exists, but ExpenseIntel is withholding a fair/overpriced verdict because the match or sample did not clear the reliability threshold.'}}
module.exports={fetchVehicleComparables};