const BASE='https://api.nhtsa.gov';
function timeout(ms=6500){const c=new AbortController();const timer=setTimeout(()=>c.abort(),ms);return{signal:c.signal,done:()=>clearTimeout(timer)}}
async function get(url){const t=timeout();try{const r=await fetch(url,{signal:t.signal,headers:{Accept:'application/json','User-Agent':'ExpenseIntel/1.0 (+https://www.expenseintel.com)'}});if(!r.ok)throw new Error(`NHTSA ${r.status}`);return await r.json()}finally{t.done()}}
function finite(v){const n=Number(v);return Number.isFinite(n)?n:null}
function norm(v){return String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'')}
function words(v){return String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().split(/\s+/).filter(Boolean)}
function score(a,b){const A=norm(a),B=norm(b);if(!A||!B)return 0;if(A===B)return 100;if(B.startsWith(A)||A.startsWith(B))return 94;if(B.includes(A)||A.includes(B))return 88;const wa=new Set(words(a)),wb=new Set(words(b)),n=[...wa].filter(x=>wb.has(x)).length;return n?55+35*n/Math.max(wa.size,wb.size):0}
async function productModels(year,make,issueType){try{const d=await get(`${BASE}/products/vehicle/models?modelYear=${encodeURIComponent(year)}&make=${encodeURIComponent(make)}&issueType=${encodeURIComponent(issueType)}`),rows=d?.results||d?.Results||[];return rows.map(x=>String(x.model||x.Model||x.modelName||x.ModelName||'')).filter(Boolean)}catch(_e){return[]}}
async function modelFamily(year,make,model,issueType){const available=await productModels(year,make,issueType),matched=available.map(x=>({x,s:score(model,x)})).filter(x=>x.s>=55).sort((a,b)=>b.s-a.s||a.x.length-b.x.length).slice(0,8).map(x=>x.x);return[model,...matched].filter((v,i,a)=>v&&a.indexOf(v)===i)}
async function collect(kind,year,make,models){const calls=models.slice(0,8).map(async model=>{try{let u;if(kind==='recall')u=`${BASE}/recalls/recallsByVehicle?make=${encodeURIComponent(make)}&model=${encodeURIComponent(model)}&modelYear=${encodeURIComponent(year)}`;else u=`${BASE}/complaints/complaintsByVehicle?make=${encodeURIComponent(make)}&model=${encodeURIComponent(model)}&modelYear=${encodeURIComponent(year)}`;const d=await get(u);return{model,rows:d?.results||d?.Results||[]}}catch(_e){return{model,rows:[]}}});return Promise.all(calls)}
async function fetchRecalls({year,make,model}={}){if(!year||!make||!model)return{ok:false,error:'Year, make and model are required',recalls:[]};try{const models=await modelFamily(year,make,model,'r'),groups=await collect('recall',year,make,models),map=new Map();for(const g of groups)for(const x of g.rows){const campaign=x.NHTSACampaignNumber||x.nhtsaCampaignNumber||'',component=x.Component||x.component||'',key=campaign||`${x.Manufacturer||''}|${component}|${x.ReportReceivedDate||''}`;if(!map.has(key))map.set(key,{campaignNumber:campaign,manufacturer:x.Manufacturer||x.manufacturer||'',component,summary:x.Summary||x.summary||'',consequence:x.Consequence||x.consequence||'',remedy:x.Remedy||x.remedy||'',reportReceivedDate:x.ReportReceivedDate||x.reportReceivedDate||'',parkIt:String(x.parkIt||x.ParkIt||'').toUpperCase()==='TRUE',parkOutside:String(x.parkOutSide||x.ParkOutSide||'').toUpperCase()==='TRUE',matchedModels:[g.model]});else map.get(key).matchedModels.push(g.model)}const recalls=[...map.values()].map(x=>({...x,matchedModels:[...new Set(x.matchedModels)]}));return{ok:true,count:recalls.length,matchedModels:models,recalls,source:'NHTSA Safety Recalls',sourceUrl:'https://www.nhtsa.gov/recalls',grade:'A',note:'Records are aggregated across closely matched model-family variants and deduplicated by campaign. A model-level recall does not show whether a particular VIN still needs repair.'}}catch(e){return{ok:false,error:String(e?.message||e),recalls:[]}}}
async function fetchComplaints({year,make,model,limit=60}={}){if(!year||!make||!model)return{ok:false,error:'Year, make and model are required',complaints:[]};try{const models=await modelFamily(year,make,model,'c'),groups=await collect('complaint',year,make,models),map=new Map();for(const g of groups)for(const x of g.rows){const odi=String(x.odiNumber||x.ODINumber||'');const key=odi||`${x.dateComplaintFiled||''}|${x.summary||''}`;if(!map.has(key))map.set(key,{odiNumber:odi,dateComplaintFiled:x.dateComplaintFiled||x.DateComplaintFiled||'',crash:!!(x.crash||x.Crash),fire:!!(x.fire||x.Fire),injuries:finite(x.numberOfInjuries||x.NumberOfInjuries)||0,deaths:finite(x.numberOfDeaths||x.NumberOfDeaths)||0,components:x.components||x.Components||'',summary:x.summary||x.Summary||'',matchedModels:[g.model]});else map.get(key).matchedModels.push(g.model)}const all=[...map.values()].map(x=>({...x,matchedModels:[...new Set(x.matchedModels)]})).sort((a,b)=>new Date(b.dateComplaintFiled)-new Date(a.dateComplaintFiled));return{ok:true,count:all.length,matchedModels:models,complaints:all.slice(0,Math.max(1,Math.min(100,limit))),source:'NHTSA Consumer Complaints',sourceUrl:'https://www.nhtsa.gov/report-a-safety-problem',grade:'A',note:'Complaint counts are unnormalized reports aggregated across closely matched model-family variants; they are not a defect probability or reliability score.'}}catch(e){return{ok:false,error:String(e?.message||e),complaints:[]}}}
async function fetchRatings({year,make,model}={}){if(!year||!make||!model)return{ok:false,error:'Year, make and model are required',variants:[]};try{const attempts=[model];const issueModels=await productModels(year,make,'c');for(const m of issueModels.map(x=>({x,s:score(model,x)})).filter(x=>x.s>=80).sort((a,b)=>b.s-a.s).slice(0,4).map(x=>x.x))if(!attempts.includes(m))attempts.push(m);let variants=[];for(const m of attempts){try{const d=await get(`${BASE}/SafetyRatings/modelyear/${encodeURIComponent(year)}/make/${encodeURIComponent(make)}/model/${encodeURIComponent(m)}?format=json`),r=d?.Results||d?.results||[];if(r.length){variants=r;break}}catch(_e){}}if(!variants.length)return{ok:true,count:0,variants:[],source:'NHTSA 5-Star Safety Ratings',sourceUrl:'https://www.nhtsa.gov/ratings',grade:'A',note:'No NHTSA NCAP variant rating was returned for this model/year.'};const details=(await Promise.all(variants.slice(0,10).map(async v=>{const id=v.VehicleId||v.vehicleId;if(!id)return null;try{const d=await get(`${BASE}/SafetyRatings/VehicleId/${encodeURIComponent(id)}?format=json`),r=(d?.Results||d?.results||[])[0];if(!r)return null;return{vehicleId:id,description:v.VehicleDescription||v.vehicleDescription||'',overall:r.OverallRating||'',frontCrash:r.OverallFrontCrashRating||'',sideCrash:r.OverallSideCrashRating||'',rollover:r.RolloverRating||'',rolloverPossibility:finite(r.RolloverPossibility),sidePole:r.SidePoleCrashRating||''}}catch(_e){return null}}))).filter(Boolean);return{ok:true,count:details.length,variants:details,source:'NHTSA 5-Star Safety Ratings',sourceUrl:'https://www.nhtsa.gov/ratings',grade:'A'}}catch(e){return{ok:false,error:String(e?.message||e),variants:[]}}}
module.exports={fetchRecalls,fetchComplaints,fetchRatings};