const {gather}=require('../lib/check-intel');
const {fetchPpi}=require('../lib/ppi-intel');
function send(res,status,payload,cache=false){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cache-Control',cache?'public, s-maxage=1800, stale-while-revalidate=7200':'no-store');res.end(JSON.stringify(payload))}
function refreshLabel(check){if(!check)return;check.score=Math.min(92,Math.max(0,Number(check.score)||0));check.label=check.score>=78?'STRONG CONTEXT':check.score>=62?'USEFUL, NOT COMPLETE':'NEEDS MORE EVIDENCE';check.tone=check.score>=78?'good':check.score>=62?'mid':'neutral'}
function categoryHint(category,url,text){if(category&&category!=='auto')return category;const s=`${url} ${text}`.toLowerCase();if(/(?:autotrader|cars\.com|cargurus|carmax|carvana|edmunds|truecar|kbb)|\/(?:cars?|trucks?|vehicles?|autos?)(?:\/|\?|$)/.test(s))return'vehicle';if(/(?:zillow|redfin|realtor\.com|homes\.com)|\/(?:homes?|properties?|real-estate)(?:\/|\?|$)/.test(s))return'property';return'auto'}
function stateFromLocation(s){return String(s||'').toUpperCase().match(/(?:,|\s)([A-Z]{2})(?:\s+\d{5}(?:-\d{4})?)?(?:\s|$|,)/)?.[1]||''}
async function fetchStateEnergy(req,state,category){if(!state||!['home','property','equipment','business-project'].includes(category))return null;const use=category==='home'||category==='property'?'residential':category==='equipment'||category==='business-project'?'industrial':'other';try{const proto=String(req.headers['x-forwarded-proto']||'https').split(',')[0],host=req.headers.host;if(!host)return null;const r=await fetch(`${proto}://${host}/api/energy?state=${encodeURIComponent(state)}&use=${encodeURIComponent(use)}`,{headers:{Accept:'application/json'}}),d=await r.json().catch(()=>null);return r.ok&&d?.ok?d:null}catch(_e){return null}}
function ppiRank(signal,query,category){const q=String(query||'').toLowerCase(),k=signal.key||'',label=String(signal.label||'').toLowerCase();let score=0;const hit=(rx,keys,points=100)=>{if(rx.test(q)&&keys.includes(k))score+=points};hit(/hvac|air condition|heat pump|ac unit|cooling/,['hvac'],160);hit(/hvac|air condition|heat pump|ac unit|cooling/,['heating','wiring','electrical_machinery'],90);hit(/furnace|boiler|heating/,['heating','hvac','plumbing']);hit(/roof|shingle|siding/,['roofing','lumber','softwood_lumber']);hit(/plumb|pipe|fixture|water heater/,['plumbing','heating']);hit(/electric|panel|switchgear|wiring/,['wiring','electrical_machinery']);hit(/paint/,['paint']);hit(/concrete|foundation|slab/,['concrete','cement','sand_gravel']);hit(/lumber|wood|framing/,['lumber','softwood_lumber','plywood']);hit(/steel|structural|metal/,['steel','structural_metal']);hit(/warehouse/,['warehouse_building','construction','steel','concrete']);hit(/industrial|factory|manufactur/,['industrial_building','general_machinery','electrical_machinery','steel']);hit(/machine|cnc|forklift|equipment|generator|compressor/,['general_machinery','electrical_machinery','machinery_repair','equipment_rental']);hit(/insurance/,['property_insurance']);hit(/property management|hoa/,['residential_property_mgmt','nonres_property_mgmt']);if(category==='vehicle'&&k==='vehicle_repair_service')score+=80;if(category==='property'&&['property_insurance','residential_property_mgmt'].includes(k))score+=55;if(category==='home'&&k==='construction')score+=15;if(category==='business-project'&&k==='construction')score+=25;if(category==='equipment'&&['general_machinery','electrical_machinery'].includes(k))score+=30;if(q.includes(label))score+=120;return score}
function evidenceRank(s,query,category){const q=String(query||'').toLowerCase(),l=String(s.label||'').toLowerCase(),src=String(s.source||'').toLowerCase();let n=0;if(category==='vehicle'){if(/used/.test(q)&&/used cars/.test(l))n+=150;if(!/used/.test(q)&&/new vehicles/.test(l))n+=130;if(/gasoline|fuel/.test(l))n+=110;if(/maintenance|repair/.test(l))n+=100;if(/treasury/.test(l))n+=/finance|loan|apr/.test(q)?75:25}
 if(category==='property'){if(/house prices/.test(l))n+=150;if(/30-year fixed mortgage/.test(l))n+=145;if(/property and casualty insurance/.test(l))n+=120;if(/shelter/.test(l))n+=95;if(/electricity|natural gas/.test(l))n+=70;if(/treasury/.test(l))n+=45;if(/construction/.test(l))n+=35}
 if(category==='home'){if(/air conditioning|heating equipment|wiring devices|plumbing fixtures|roofing|lumber|concrete/.test(l))n+=130;if(/construction/.test(l))n+=95;if(/electricity|natural gas/.test(l))n+=65;if(/household furnishings/.test(l))n+=45;if(/insurance/.test(l))n+=15;if(/treasury/.test(l))n+=20}
 if(category==='equipment'){if(/machinery|equipment|rental|repair/.test(l))n+=135;if(/electricity|natural gas/.test(l))n+=75;if(/treasury/.test(l))n+=55}
 if(category==='business-project'){if(/construction|warehouse|industrial|steel|structural|concrete|architectural|machinery/.test(l))n+=130;if(/electricity|natural gas/.test(l))n+=90;if(/property management|rent/.test(l))n+=85;if(/treasury/.test(l))n+=55}
 if(q&&q.split(/\W+/).filter(x=>x.length>3).some(x=>l.includes(x)))n+=45;if(src.includes('producer price'))n+=10;return n}
module.exports=async function handler(req,res){
  if(!['GET','POST'].includes(req.method))return send(res,405,{ok:false,error:'Method not allowed'});
  let body=req.method==='GET'?(req.query||{}):req.body;if(typeof body==='string'){try{body=JSON.parse(body)}catch(_e){body={}}}body=body||{};
  const text=String(body.text||'').slice(0,5000),url=String(body.url||'').slice(0,1600),category=String(body.category||'auto').slice(0,40),location=String(body.location||'').slice(0,180),price=body.price;
  if(!text.trim()&&!url.trim())return send(res,400,{ok:false,error:'Paste a link, quote/listing text, or describe what you are considering.'});
  try{
    const out=await gather({text,url,category:categoryHint(category,url,text),price,location}),query=[text,out.page?.title,out.page?.description].filter(Boolean).join(' '),state=stateFromLocation(location);
    const [ppi,energy]=await Promise.all([['home','property','equipment','business-project','vehicle'].includes(out.detectedCategory)?fetchPpi(out.detectedCategory):Promise.resolve(null),fetchStateEnergy(req,state,out.detectedCategory)]);
    if(ppi?.ok&&ppi.signals?.length){const seen=new Set((out.evidence.signals||[]).map(x=>x.label));const add=ppi.signals.filter(x=>!seen.has(x.label)).map((x,i)=>({x,i,score:ppiRank(x,query,out.detectedCategory)})).sort((a,b)=>b.score-a.score||a.i-b.i).slice(0,4).map(({x})=>({label:x.label,value:x.yoy,unit:'% YoY',period:x.period,source:x.source,grade:'A',latestMonth:x.latestMonth}));out.evidence.signals.push(...add);out.evidence.producerPriceContext={period:ppi.period,note:ppi.note,signalCount:add.length};if(add.length){out.check.score+=4;out.check.signals.push('BLS producer-cost pressure connected.')}}
    if(energy){if(energy.electricity?.centsKwh!=null)out.evidence.signals.push({label:`${state} electricity`,value:energy.electricity.centsKwh,unit:'¢/kWh',period:energy.electricity.period||'',source:energy.electricity.source||'U.S. EIA',grade:'A'});if(energy.gas?.dollarsMcf!=null)out.evidence.signals.push({label:`${state} natural gas`,value:energy.gas.dollarsMcf,unit:'$/Mcf',period:energy.gas.period||'',source:energy.gas.source||'U.S. EIA',grade:'A'});out.evidence.stateEnergy={state,source:'U.S. EIA'};out.check.score+=2;out.check.signals.push('State energy-cost evidence connected.')}
    if(out.detectedCategory==='vehicle'&&(out.vehicle?.fuel?.options?.length||0)>1&&!out.check.unknown.includes('Exact vehicle configuration / trim'))out.check.unknown.unshift('Exact vehicle configuration / trim');
    out.evidence.sourceCount=new Set(out.evidence.signals.map(x=>x.source).filter(Boolean)).size;out.evidence.signals=out.evidence.signals.map((s,i)=>({s,i,rank:evidenceRank(s,query,out.detectedCategory)})).sort((a,b)=>b.rank-a.rank||a.i-b.i).map(x=>x.s);refreshLabel(out.check);
    return send(res,200,out,req.method==='GET'&&!url)
  }catch(e){return send(res,502,{ok:false,error:String(e?.message||e||'ExpenseIntel Check could not complete.')})}
};