const {fetchBls,fetchTreasury,fetchFuelPrices}=require('../lib/public-intel');
function send(res,status,payload,cache=true){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cache-Control',cache?'public, s-maxage=14400, stale-while-revalidate=43200':'no-store');res.end(JSON.stringify(payload))}
const GROUPS={vehicle:['new_vehicles','used_vehicles','gasoline','vehicle_repair'],home:['household','electricity','utility_gas','household_insurance','shelter'],property:['shelter','electricity','utility_gas','household_insurance'],equipment:['all_items','electricity'], 'business-project':['all_items','electricity','utility_gas'],personal:['all_items','household'],other:['all_items']};
function stateFromLocation(s){const m=String(s||'').toUpperCase().match(/(?:,|\s)([A-Z]{2})(?:\s|$|,)/);return m?.[1]||''}
async function stateEnergy(req,state,category){if(!state)return null;const use=category==='vehicle'?'other':category==='property'?'residential':category==='home'?'residential':category==='equipment'?'industrial':category==='business-project'?'industrial':'other';try{const proto=String(req.headers['x-forwarded-proto']||'https').split(',')[0],host=req.headers.host;if(!host)return null;const r=await fetch(`${proto}://${host}/api/energy?state=${encodeURIComponent(state)}&use=${encodeURIComponent(use)}`,{headers:{Accept:'application/json'}});const d=await r.json().catch(()=>null);return r.ok&&d?.ok?d:null}catch(_e){return null}}
module.exports=async function handler(req,res){
 if(req.method!=='GET')return send(res,405,{ok:false,error:'Method not allowed'},false);
 const category=String(req.query?.category||'other').toLowerCase(),q=String(req.query?.q||'').slice(0,600),location=String(req.query?.location||'').slice(0,120),state=stateFromLocation(location),keys=GROUPS[category]||GROUPS.other;
 const [bls,treasury,fuel,stateEnergyResult]=await Promise.all([fetchBls(keys),fetchTreasury(),category==='vehicle'?fetchFuelPrices():Promise.resolve(null),stateEnergy(req,state,category)]);
 const signals=(bls.signals||[]).map(s=>({type:'price_index',label:s.label,value:s.value,period:s.period,mom:s.mom,threeMonth:s.threeMonth,yoy:s.yoy,source:s.source,sourceUrl:s.sourceUrl,grade:s.grade}));
 if(treasury.ok){signals.push({type:'rate',label:'U.S. Treasury 2-year',value:treasury.twoYear,unit:'%',period:treasury.date,source:treasury.source,sourceUrl:treasury.sourceUrl,grade:'A'},{type:'rate',label:'U.S. Treasury 10-year',value:treasury.tenYear,unit:'%',period:treasury.date,source:treasury.source,sourceUrl:treasury.sourceUrl,grade:'A'})}
 if(fuel?.ok){for(const [key,label] of [['regular','Regular gasoline'],['premium','Premium gasoline'],['diesel','Diesel'],['electric','Electricity']])if(fuel[key]!=null)signals.push({type:'fuel_price',label,value:fuel[key],unit:key==='electric'?'$/kWh':'$/gal',period:'current FuelEconomy.gov assumption',source:fuel.source,sourceUrl:fuel.sourceUrl,grade:'A'})}
 if(stateEnergyResult?.electricity?.centsKwh!=null)signals.push({type:'state_energy',label:`${state} electricity`,value:stateEnergyResult.electricity.centsKwh,unit:'¢/kWh',period:stateEnergyResult.electricity.period||'',source:stateEnergyResult.electricity.source||'U.S. EIA',grade:'A'});
 const coverage={bls:!!bls.ok,treasury:!!treasury.ok,fuelPrices:!!fuel?.ok,stateEnergy:!!stateEnergyResult};
 const known=Object.values(coverage).filter(Boolean).length,total=category==='vehicle'?4:3,score=Math.round(known/total*100);
 return send(res,200,{ok:true,decision:{q,category,location,state},signals,coverage,coverageScore:Math.min(100,score),sourceCount:new Set(signals.map(s=>s.source).filter(Boolean)).size,methodology:{meaning:'Connected context supplies observed external evidence around a spending decision. It is not itself a buy/sell recommendation, fair-price verdict, or forecast.',rule:'Observed trends remain separate from user assumptions and modeled outputs.'}});
};