const {fetchBls,fetchTreasury,fetchFuelPrices}=require('../lib/public-intel');
const {fetchMortgageRates,fetchHousePriceContext}=require('../lib/housing-intel');
const {fetchPpi}=require('../lib/ppi-intel');
function send(res,status,payload,cache=true){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cache-Control',cache?'public, s-maxage=14400, stale-while-revalidate=43200':'no-store');res.end(JSON.stringify(payload))}
const GROUPS={vehicle:['new_vehicles','used_vehicles','gasoline','vehicle_repair'],home:['household','electricity','utility_gas','household_insurance','shelter'],property:['shelter','electricity','utility_gas','household_insurance'],equipment:['all_items','electricity'],'business-project':['all_items','electricity','utility_gas'],personal:['all_items','household'],other:['all_items']};
function stateFromLocation(s){const m=String(s||'').toUpperCase().match(/(?:,|\s)([A-Z]{2})(?:\s+\d{5}(?:-\d{4})?)?(?:\s|$|,)/);return m?.[1]||''}
async function stateEnergy(req,state,category){if(!state)return null;const use=category==='vehicle'?'other':category==='property'||category==='home'?'residential':category==='equipment'||category==='business-project'?'industrial':'other';try{const proto=String(req.headers['x-forwarded-proto']||'https').split(',')[0],host=req.headers.host;if(!host)return null;const r=await fetch(`${proto}://${host}/api/energy?state=${encodeURIComponent(state)}&use=${encodeURIComponent(use)}`,{headers:{Accept:'application/json'}});const d=await r.json().catch(()=>null);return r.ok&&d?.ok?d:null}catch(_e){return null}}
module.exports=async function handler(req,res){
 if(req.method!=='GET')return send(res,405,{ok:false,error:'Method not allowed'},false);
 const category=String(req.query?.category||'other').toLowerCase(),q=String(req.query?.q||'').slice(0,600),location=String(req.query?.location||'').slice(0,160),state=stateFromLocation(location),keys=GROUPS[category]||GROUPS.other,isHousing=category==='home'||category==='property',ppiUseful=['home','property','equipment','business-project'].includes(category);
 const [bls,treasury,fuel,stateEnergyResult,mortgage,hpi,ppi]=await Promise.all([fetchBls(keys),fetchTreasury(),category==='vehicle'?fetchFuelPrices():Promise.resolve(null),stateEnergy(req,state,category),isHousing?fetchMortgageRates():Promise.resolve(null),isHousing&&location?fetchHousePriceContext(location,state):Promise.resolve(null),ppiUseful?fetchPpi(category):Promise.resolve(null)]);
 const signals=(bls.signals||[]).map(s=>({type:'price_index',label:s.label,value:s.value,period:s.period,mom:s.mom,threeMonth:s.threeMonth,yoy:s.yoy,source:s.source,sourceUrl:s.sourceUrl,grade:s.grade}));
 if(treasury.ok){signals.push({type:'rate',label:'U.S. Treasury 2-year',value:treasury.twoYear,unit:'%',period:treasury.date,source:treasury.source,sourceUrl:treasury.sourceUrl,grade:'A'},{type:'rate',label:'U.S. Treasury 10-year',value:treasury.tenYear,unit:'%',period:treasury.date,source:treasury.source,sourceUrl:treasury.sourceUrl,grade:'A'})}
 if(fuel?.ok){for(const [key,label] of [['regular','Regular gasoline'],['premium','Premium gasoline'],['diesel','Diesel'],['electric','Electricity']])if(fuel[key]!=null)signals.push({type:'fuel_price',label,value:fuel[key],unit:key==='electric'?'$/kWh':'$/gal',period:'current FuelEconomy.gov assumption',source:fuel.source,sourceUrl:fuel.sourceUrl,grade:'A'})}
 if(stateEnergyResult?.electricity?.centsKwh!=null)signals.push({type:'state_energy',label:`${state} electricity`,value:stateEnergyResult.electricity.centsKwh,unit:'¢/kWh',period:stateEnergyResult.electricity.period||'',source:stateEnergyResult.electricity.source||'U.S. EIA',grade:'A'});
 if(stateEnergyResult?.gas?.dollarsMcf!=null)signals.push({type:'state_gas',label:`${state} natural gas`,value:stateEnergyResult.gas.dollarsMcf,unit:'$/Mcf',period:stateEnergyResult.gas.period||'',source:stateEnergyResult.gas.source||'U.S. EIA',grade:'A'});
 if(mortgage?.ok){if(mortgage.thirtyYear!=null)signals.push({type:'rate',label:'30-year fixed mortgage',value:mortgage.thirtyYear,unit:'%',period:mortgage.date||'latest weekly survey',source:mortgage.source,sourceUrl:mortgage.sourceUrl,grade:'A'});if(mortgage.fifteenYear!=null)signals.push({type:'rate',label:'15-year fixed mortgage',value:mortgage.fifteenYear,unit:'%',period:mortgage.date||'latest weekly survey',source:mortgage.source,sourceUrl:mortgage.sourceUrl,grade:'A'})}
 if(hpi?.ok){if(hpi.metro?.oneYearChange!=null)signals.push({type:'percent_change',label:`${hpi.metro.name} house prices`,value:hpi.metro.oneYearChange,unit:'% YoY',period:'latest FHFA quarterly HPI',source:hpi.source,sourceUrl:hpi.sourceUrl,grade:'A',quarterChange:hpi.metro.quarterChange,fiveYearChange:hpi.metro.fiveYearChange});else if(hpi.state?.oneYearChange!=null)signals.push({type:'percent_change',label:`${hpi.state.name} house prices`,value:hpi.state.oneYearChange,unit:'% YoY',period:'latest FHFA quarterly HPI',source:hpi.source,sourceUrl:hpi.sourceUrl,grade:'A',quarterChange:hpi.state.quarterChange,fiveYearChange:hpi.state.fiveYearChange})}
 if(ppi?.ok){for(const s of (ppi.signals||[]).slice(0,8))signals.push({type:'producer_pressure',label:s.label,value:s.latestMonth,unit:'% latest month',period:s.period,yoy:s.yoy,source:s.source,sourceUrl:s.sourceUrl,grade:s.grade})}
 const coverage={bls:!!bls.ok,treasury:!!treasury.ok,fuelPrices:!!fuel?.ok,stateEnergy:!!stateEnergyResult,mortgageRates:!!mortgage?.ok,housePriceIndex:!!hpi?.ok,producerPrices:!!ppi?.ok};
 const expected=category==='vehicle'?['bls','treasury','fuelPrices']:isHousing?['bls','treasury',...(state?['stateEnergy']:[]),'mortgageRates',...(location?['housePriceIndex']:[]),'producerPrices']:['equipment','business-project'].includes(category)?['bls','treasury',...(state?['stateEnergy']:[]),'producerPrices']:['bls','treasury',...(state?['stateEnergy']:[])],known=expected.filter(k=>coverage[k]).length,score=expected.length?Math.round(known/expected.length*100):0;
 return send(res,200,{ok:true,decision:{q,category,location,state},signals,coverage,coverageScore:Math.min(100,score),sourceCount:new Set(signals.map(s=>s.source).filter(Boolean)).size,methodology:{meaning:'Connected context supplies observed external evidence around a spending decision. It is not itself a buy/sell recommendation, fair-price verdict, appraisal, or forecast.',rule:'Observed trends remain separate from user assumptions and modeled outputs. Mortgage rates are national Freddie Mac survey averages; FHFA HPI measures price change rather than current property value; BLS PPI measures producer price pressure rather than a local retail or contractor price.'}});
};