const SERIES=[
  {id:'MORTGAGE30US',cadence:'weekly'},
  {id:'GS10',cadence:'monthly'},
  {id:'CPIAUCSL',cadence:'monthly'},
  {id:'CUUR0000SETA02',cadence:'monthly'},
  {id:'CUUR0000SETA01',cadence:'monthly'},
  {id:'GASREGW',cadence:'weekly'},
  {id:'FEDFUNDS',cadence:'monthly'},
  {id:'PPIACO',cadence:'monthly'}
];
function send(res,status,payload){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','public, s-maxage=900, stale-while-revalidate=3600');res.end(JSON.stringify(payload))}
function parse(text){const lines=String(text||'').trim().split(/\r?\n/);for(let i=lines.length-1;i>0;i--){const row=lines[i].split(','),value=Number(row[row.length-1]),date=row[0];if(Number.isFinite(value)&&date&&row[row.length-1]!=='.')return{date,value,ageDays:Math.max(0,Math.round((Date.now()-new Date(date).getTime())/86400000))}}return null}
function freshness(ageDays,cadence){const weekly=cadence==='weekly';if(ageDays<=(weekly?14:45))return'current';if(ageDays<=(weekly?35:100))return'aging';return'stale'}
async function probe(series){const c=new AbortController(),timer=setTimeout(()=>c.abort(),4500);const started=Date.now();try{const r=await fetch(`https://fred.stlouisfed.org/graph/fredgraph.csv?id=${series.id}`,{signal:c.signal,headers:{'User-Agent':'ExpenseIntel/EvidenceHealth (+https://www.expenseintel.com)'}});if(!r.ok)throw new Error(String(r.status));const latest=parse(await r.text());if(!latest)throw new Error('empty');return{...series,ok:true,latencyMs:Date.now()-started,...latest,freshness:freshness(latest.ageDays,series.cadence)}}catch(e){return{...series,ok:false,latencyMs:Date.now()-started,error:String(e?.message||e)}}finally{clearTimeout(timer)}}
module.exports=async function handler(req,res){if(req.method!=='GET')return send(res,405,{ok:false,error:'Method not allowed'});const checks=await Promise.all(SERIES.map(probe));const healthy=checks.filter(x=>x.ok),failed=checks.filter(x=>!x.ok),aging=healthy.filter(x=>x.freshness==='aging'),stale=healthy.filter(x=>x.freshness==='stale'),slow=healthy.filter(x=>x.latencyMs>3000);const coveragePct=Math.round((healthy.length/SERIES.length)*100);const status=failed.length===0&&aging.length===0&&stale.length===0?'strong':coveragePct>=75&&stale.length===0?'degraded':'weak';return send(res,200,{ok:true,status,checkedAt:new Date().toISOString(),coveragePct,healthy:healthy.length,requested:SERIES.length,failed:failed.length,aging:aging.length,stale:stale.length,slow:slow.length,checks,guardrails:['Feed availability never upgrades modeled values to transaction comparables.','Aging or stale observations suppress strong evidence quality.','Freshness thresholds reflect source cadence instead of one global age threshold.','Observed date and retrieval time remain separate.','User-entered facts supersede model defaults when explicitly supplied.']})};