'use strict';
const {validateCaseInput,estimateCase,MODEL_VERSION}=require('../lib/model-core');
const {payment,balance,calculateHomeDecision,HOME_MODEL_VERSION}=require('../lib/home-core');
const {calculateContractorDecision,CONTRACTOR_MODEL_VERSION}=require('../lib/contractor-core');

module.exports=async function handler(req,res){
  if(req.method!=='GET'){res.statusCode=405;return res.end(JSON.stringify({ok:false,error:'Method not allowed'}))}
  res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');
  const host=req.headers['x-forwarded-host']||req.headers.host,proto=req.headers['x-forwarded-proto']||'https',base=`${proto}://${host}`;
  const scripts=['/app.js','/find/find.js','/analyze/analyze.js','/simulate/simulate.js','/watch/watch.js','/matrix/matrix.js','/passport.js','/shock.js','/contractor/contractor.js','/home/home.js'];
  const pages=['/','/find/','/analyze/','/simulate/','/watch/','/screen/','/matrix/','/data/','/pricing/','/developers/','/contractor/','/home/'];
  const scriptChecks=[];for(const path of scripts){try{const r=await fetch(base+path);const source=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status}`);new Function(source);scriptChecks.push({path,ok:true,bytes:source.length})}catch(e){scriptChecks.push({path,ok:false,error:e.message})}}
  const pageChecks=[];for(const path of pages){try{const r=await fetch(base+path,{redirect:'manual'});pageChecks.push({path,ok:r.status>=200&&r.status<400,status:r.status})}catch(e){pageChecks.push({path,ok:false,error:e.message})}}
  const modelChecks=[];
  try{const valid=validateCaseInput({address:'32 Chestnut St, Westborough, MA 01581',use:'residential',sqft:2500});if(!valid.ok)throw new Error('valid input rejected');modelChecks.push({name:'input_validation_accepts_valid_case',ok:true})}catch(e){modelChecks.push({name:'input_validation_accepts_valid_case',ok:false,error:e.message})}
  try{const invalid=validateCaseInput({address:'x',use:'office',sqft:20});if(invalid.ok)throw new Error('invalid input accepted');modelChecks.push({name:'input_validation_rejects_invalid_case',ok:true})}catch(e){modelChecks.push({name:'input_validation_rejects_invalid_case',ok:false,error:e.message})}
  let fixture=null;
  try{fixture=estimateCase({address:'Test',use:'office',sqft:10000,location:{verified:true,label:'Test, IL',provider:'test',components:{state:'IL'}},energy:{electricity:{centsKwh:10,source:'test',grade:'A'},gas:{dollarsMcf:8,source:'test',grade:'A'},intensity:{kwhSqft:10,gasCfSqft:20,source:'test',grade:'B'}},risk:{available:true,composite:{rating:'Very Low'},source:'test'}});if(!(fixture.total>0&&fixture.range.low<fixture.range.high&&fixture.modelVersion===MODEL_VERSION&&fixture.evidence.score<90))throw new Error('model invariants failed');modelChecks.push({name:'location_model_invariants',ok:true,version:MODEL_VERSION,evidenceScore:fixture.evidence.score})}catch(e){modelChecks.push({name:'location_model_invariants',ok:false,error:e.message})}
  try{const p=payment(400000,6.5,30),b=balance(400000,6.5,30,60);if(Math.abs(p-2528.27)>1||!(b>350000&&b<390000))throw new Error(`unexpected amortization ${p.toFixed(2)} / ${b.toFixed(2)}`);modelChecks.push({name:'mortgage_amortization_invariants',ok:true,version:HOME_MODEL_VERSION})}catch(e){modelChecks.push({name:'mortgage_amortization_invariants',ok:false,error:e.message})}
  try{const loc=fixture||estimateCase({address:'Test',use:'residential',sqft:2500,location:{verified:true,label:'Test, IL',provider:'test',components:{state:'IL'}}});const home=calculateHomeDecision({price:550000,sqft:2500,downPct:20,rate:6.5,term:30,tax:8000,insurance:2500,maintPct:1,closingPct:2.5,app:3,salePct:6,rent:3200,rentGrowth:3},loc);if(!(home.ownership.monthly>0&&home.ownership.cash5>home.ownership.monthly*50&&Number.isFinite(home.stress)))throw new Error('home decision invariants failed');modelChecks.push({name:'home_decision_invariants',ok:true,version:HOME_MODEL_VERSION})}catch(e){modelChecks.push({name:'home_decision_invariants',ok:false,error:e.message})}
  try{const loc=fixture||{};const con=calculateContractorDecision({scope:'renovation',sqft:25000,laborHours:3000,laborRate:70,materials:250000,equipDays:20,equipRate:1200,miles:40,trips:12,mileRate:2.2,tons:20,tonRate:130,permits:7000,service:20000,months:5,overhead:10000,unknowns:'medium',contingency:5,margin:18,verified:{wage:true}},loc);if(!(con.costs.target>con.costs.floor&&con.costs.floor>con.costs.direct&&con.locationReservePct>0&&con.locationReservePct<=.15))throw new Error('contractor decision invariants failed');modelChecks.push({name:'contractor_decision_invariants',ok:true,version:CONTRACTOR_MODEL_VERSION})}catch(e){modelChecks.push({name:'contractor_decision_invariants',ok:false,error:e.message})}
  const apiChecks=[];
  const liveAddress='32 Chestnut St, Westborough, MA 01581';
  const liveTests=[
    {name:'home_decision_endpoint',path:'/api/home-decision',body:{address:liveAddress,sqft:2500,price:550000,downPct:20,rate:6.5,term:30,tax:8000,insurance:2500,maintPct:1,closingPct:2.5,app:3,salePct:6,budget:5000,rent:3200,rentGrowth:3},assert:d=>d?.ok&&d?.decision?.ownership?.monthly>0},
    {name:'contractor_decision_endpoint',path:'/api/contractor-decision',body:{address:liveAddress,scope:'renovation',sqft:25000,laborHours:3000,laborRate:70,materials:250000,equipDays:20,equipRate:1200,miles:40,trips:12,mileRate:2.2,tons:20,tonRate:130,permits:7000,service:20000,months:5,overhead:10000,unknowns:'medium',contingency:5,margin:18,verified:{wage:true}},assert:d=>d?.ok&&d?.decision?.costs?.target>d?.decision?.costs?.floor}
  ];
  await Promise.all(liveTests.map(async t=>{try{const r=await fetch(base+t.path,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(t.body)}),d=await r.json().catch(()=>({}));if(!r.ok||!t.assert(d))throw new Error(d.error||`HTTP ${r.status}`);apiChecks.push({name:t.name,ok:true,status:r.status})}catch(e){apiChecks.push({name:t.name,ok:false,error:e.message})}}));
  const ok=scriptChecks.every(x=>x.ok)&&pageChecks.every(x=>x.ok)&&modelChecks.every(x=>x.ok)&&apiChecks.every(x=>x.ok);res.statusCode=ok?200:500;res.end(JSON.stringify({ok,checkedAt:new Date().toISOString(),modelVersion:MODEL_VERSION,specializedModels:{home:HOME_MODEL_VERSION,contractor:CONTRACTOR_MODEL_VERSION},modelChecks,apiChecks,scripts:scriptChecks,pages:pageChecks}))
};