const ELECTRIC_URL='https://www.eia.gov/electricity/monthly/epm_table_grapher.php?t=table_5_06_b';
const MARKETS=[
  ['Boston','MA','Northeast'],['Buffalo','NY','Northeast'],['Pittsburgh','PA','Northeast'],['Newark','NJ','Northeast'],['Chicago','IL','Midwest'],['Indianapolis','IN','Midwest'],['Columbus','OH','Midwest'],['Detroit','MI','Midwest'],['Milwaukee','WI','Midwest'],['Minneapolis','MN','Midwest'],['St. Louis','MO','Midwest'],['Louisville','KY','South'],['Nashville','TN','South'],['Charlotte','NC','South'],['Atlanta','GA','South'],['Dallas','TX','South'],['Houston','TX','South'],['Oklahoma City','OK','South'],['Denver','CO','West'],['Phoenix','AZ','West'],['Salt Lake City','UT','West'],['Reno','NV','West'],['Portland','OR','West'],['Spokane','WA','West']
];
const STATE_NAMES={AL:'Alabama',AK:'Alaska',AZ:'Arizona',AR:'Arkansas',CA:'California',CO:'Colorado',CT:'Connecticut',DE:'Delaware',DC:'District of Columbia',FL:'Florida',GA:'Georgia',HI:'Hawaii',ID:'Idaho',IL:'Illinois',IN:'Indiana',IA:'Iowa',KS:'Kansas',KY:'Kentucky',LA:'Louisiana',ME:'Maine',MD:'Maryland',MA:'Massachusetts',MI:'Michigan',MN:'Minnesota',MS:'Mississippi',MO:'Missouri',MT:'Montana',NE:'Nebraska',NV:'Nevada',NH:'New Hampshire',NJ:'New Jersey',NM:'New Mexico',NY:'New York',NC:'North Carolina',ND:'North Dakota',OH:'Ohio',OK:'Oklahoma',OR:'Oregon',PA:'Pennsylvania',RI:'Rhode Island',SC:'South Carolina',SD:'South Dakota',TN:'Tennessee',TX:'Texas',UT:'Utah',VT:'Vermont',VA:'Virginia',WA:'Washington',WV:'West Virginia',WI:'Wisconsin',WY:'Wyoming'};
const INTENSITY={restaurant:43.8,retail:13.2,office:13.6,warehouse:5.5,industrial:18.0,multifamily:8.5,residential:7.2,other:12.6};
function send(res,status,payload,cache=true){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cache-Control',cache?'public, s-maxage=21600, stale-while-revalidate=86400':'no-store');res.end(JSON.stringify(payload))}
function strip(s){return String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim()}
function cells(row){return(row?.match(/<t[dh]\b[\s\S]*?<\/t[dh]>/gi)||[]).map(strip).filter(Boolean)}
function numeric(v){const n=Number(String(v||'').replace(/[$,%]/g,''));return Number.isFinite(n)?n:null}
function sectorFor(use){if(use==='residential'||use==='multifamily')return'residential';if(use==='industrial')return'industrial';return'commercial'}
function parseTable(html,sector){const rows=html.match(/<tr\b[\s\S]*?<\/tr>/gi)||[];const idx=sector==='residential'?0:sector==='commercial'?2:4;const out={};for(const row of rows){const text=strip(row);for(const [abbr,name] of Object.entries(STATE_NAMES)){if(text.startsWith(name+' ')||text===name){const nums=cells(row).slice(1).map(numeric);const current=nums[idx],prior=nums[idx+1];if(current!=null)out[abbr]={centsKwh:current,priorCentsKwh:prior,yoy:prior?current/prior-1:null};break}}}return out}
module.exports=async function handler(req,res){if(req.method!=='GET')return send(res,405,{ok:false,error:'Method not allowed'},false);const use=String(req.query?.use||'industrial').toLowerCase();const sector=sectorFor(use),kwhSqft=INTENSITY[use]||INTENSITY.other;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),7000);try{const r=await fetch(ELECTRIC_URL,{signal:controller.signal,headers:{'User-Agent':'ExpenseIntel/1.0 (+https://expenseintel.com)'}});if(!r.ok)throw new Error('upstream');const html=await r.text();const rates=parseTable(html,sector);const markets=MARKETS.map(([city,state,region])=>{const e=rates[state]||null;return{city,state,region,electricity:e?{...e,source:'U.S. EIA · Electric Power Monthly Table 5.6.B',period:'2026 YTD through June',grade:'A'}:null}}).filter(x=>x.electricity);return send(res,200,{ok:true,use,sector,intensity:{kwhSqft,source:use==='industrial'?'ExpenseIntel industrial bridge · MECS layer pending':'EIA/CBECS benchmark layer'},markets,methodology:{scope:'Representative U.S. market scan using state electricity price signals. It is not parcel-level site selection.',warning:'Taxes, exact utility tariffs, incentives, labor, water and property-specific costs are not automatically ranked in this market scan.'}})}catch(error){return send(res,error?.name==='AbortError'?504:502,{ok:false,error:'Market scan data is temporarily unavailable.'},false)}finally{clearTimeout(timer)}};