const MASSGIS_URL='https://services1.arcgis.com/hGdibHYSPO59RG1h/ArcGIS/rest/services/Massachusetts_Property_Tax_Parcels/FeatureServer/0/query';
const ACS_BASE='https://api.census.gov/data/2024/acs/acs5';
const RENTCAST_URL='https://api.rentcast.io/v1/properties';
const ATTOM_URL='https://api.gateway.attomdata.com/propertyapi/v1.0.0/property/detail';
const OVERPASS_URL='https://overpass-api.de/api/interpreter';

function clean(v,max=220){return String(v||'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max)}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function send(res,status,payload){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cache-Control','public, s-maxage=86400, stale-while-revalidate=604800');res.end(JSON.stringify(payload))}
async function fetchJson(url,opts={},timeoutMs=4800){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(url,{...opts,signal:c.signal});if(!r.ok)throw new Error(`${new URL(url).hostname} ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
function latestMapValue(obj,key='total'){if(!obj||typeof obj!=='object')return null;const years=Object.keys(obj).sort((a,b)=>Number(b)-Number(a));for(const y of years){const row=obj[y];const v=num(row?.[key]);if(v!=null)return {year:Number(y)||null,value:v}}return null}
function parseDate8(v){const s=clean(v,8);return /^\d{8}$/.test(s)?`${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}`:null}
function mapUse(text=''){const s=String(text).toLowerCase();if(/single|residential|dwelling|condo|townhouse/.test(s))return'residential';if(/multi|apartment/.test(s))return'multifamily';if(/restaurant|food/.test(s))return'restaurant';if(/retail|store/.test(s))return'retail';if(/office/.test(s))return'office';if(/warehouse/.test(s))return'warehouse';if(/industrial|manufactur/.test(s))return'industrial';return''}

async function massgis(q){if(q.state!=='MA'||q.lat==null||q.lon==null)return null;const u=new URL(MASSGIS_URL);u.searchParams.set('geometry',`${q.lon},${q.lat}`);u.searchParams.set('geometryType','esriGeometryPoint');u.searchParams.set('inSR','4326');u.searchParams.set('spatialRel','esriSpatialRelIntersects');u.searchParams.set('outFields','MAP_PAR_ID,PROP_ID,TOTAL_VAL,FY,LOT_SIZE,LOT_UNITS,LS_DATE,LS_PRICE,USE_CODE,SITE_ADDR,CITY,ZIP,ZONING,YEAR_BUILT,BLD_AREA,UNITS,RES_AREA,STYLE,NUM_ROOMS,STORIES,USE_DESC,LAST_EDIT');u.searchParams.set('returnGeometry','false');u.searchParams.set('resultRecordCount','8');u.searchParams.set('f','json');const d=await fetchJson(u,{},5200);const fs=(d.features||[]).map(x=>x.attributes||{});if(!fs.length)return null;fs.sort((a,b)=>(num(b.RES_AREA)||num(b.BLD_AREA)||0)-(num(a.RES_AREA)||num(a.BLD_AREA)||0));const a=fs[0],lot=num(a.LOT_SIZE),lotSqft=lot==null?null:String(a.LOT_UNITS||'').toUpperCase().startsWith('A')?lot*43560:lot;return{sourceKey:'massgis',sourceLabel:'MassGIS + local assessor',quality:96,parcelId:clean(a.PROP_ID||a.MAP_PAR_ID,80),facts:{squareFootage:num(a.RES_AREA)||num(a.BLD_AREA),lotSize:lotSqft,yearBuilt:num(a.YEAR_BUILT),stories:num(a.STORIES),roomCount:num(a.NUM_ROOMS),units:num(a.UNITS),propertyType:clean(a.USE_DESC,120),style:clean(a.STYLE,80),zoning:clean(a.ZONING,40),assessedValue:num(a.TOTAL_VAL),assessmentYear:num(a.FY),lastSalePrice:num(a.LS_PRICE),lastSaleDate:parseDate8(a.LS_DATE),siteAddress:clean(a.SITE_ADDR,180)},suggestedUse:mapUse(a.USE_DESC),meta:{recordCount:fs.length,lastEdit:num(a.LAST_EDIT),note:'State-hosted standardized assessor parcel record. Owner fields are intentionally not retrieved.'}}}

async function rentcast(q){const key=process.env.RENTCAST_API_KEY;if(!key)return null;const u=new URL(RENTCAST_URL);u.searchParams.set('address',q.address);u.searchParams.set('limit','1');const d=await fetchJson(u,{headers:{Accept:'application/json','X-Api-Key':key}},5200);const p=Array.isArray(d)?d[0]:d?.properties?.[0];if(!p)return null;const ta=latestMapValue(p.taxAssessments,'value'),tx=latestMapValue(p.propertyTaxes,'total');return{sourceKey:'rentcast',sourceLabel:'RentCast public-record normalization',quality:90,parcelId:clean(p.assessorID,80),facts:{squareFootage:num(p.squareFootage),bedrooms:num(p.bedrooms),bathrooms:num(p.bathrooms),lotSize:num(p.lotSize),yearBuilt:num(p.yearBuilt),propertyType:clean(p.propertyType,80),zoning:clean(p.zoning,40),lastSalePrice:num(p.lastSalePrice),lastSaleDate:p.lastSaleDate?String(p.lastSaleDate).slice(0,10):null,hoaMonthly:num(p.hoa?.fee),stories:num(p.features?.floorCount),roomCount:num(p.features?.roomCount),units:num(p.features?.unitCount),style:clean(p.features?.architectureType,80),heatingType:clean(p.features?.heatingType,80),coolingType:clean(p.features?.coolingType,80),roofType:clean(p.features?.roofType,80),exteriorType:clean(p.features?.exteriorType,80),foundationType:clean(p.features?.foundationType,80),garageSpaces:num(p.features?.garageSpaces),pool:p.features?.pool===true?true:p.features?.pool===false?false:null,assessedValue:ta?.value??null,assessmentYear:ta?.year??null,propertyTaxAnnual:tx?.value??null,propertyTaxYear:tx?.year??null},suggestedUse:mapUse(p.propertyType),meta:{note:'Normalized county/public-record property data. Owner and mailing information are intentionally discarded.'}}}

async function attom(q){const key=process.env.ATTOM_API_KEY;if(!key)return null;const street=clean(q.street||q.address.split(',')[0],120),line2=[q.city,q.state,q.zip].filter(Boolean).join(' ');if(!street||!line2)return null;const u=new URL(ATTOM_URL);u.searchParams.set('address1',street);u.searchParams.set('address2',line2);const d=await fetchJson(u,{headers:{Accept:'application/json',apikey:key}},5200);const p=d?.property?.[0];if(!p)return null;const f={squareFootage:num(p.building?.size?.universalsize||p.building?.size?.livingSize),bedrooms:num(p.building?.rooms?.beds),bathrooms:num(p.building?.rooms?.bathstotal),lotSize:num(p.lot?.lotsize2),yearBuilt:num(p.summary?.yearbuilt),stories:num(p.building?.summary?.levels),roomCount:num(p.building?.rooms?.roomsTotal),units:num(p.building?.summary?.unitsCount),propertyType:clean(p.summary?.proptype||p.summary?.propertyType,100),style:clean(p.building?.summary?.bldgType,80),heatingType:clean(p.utilities?.heatingtype,80),coolingType:clean(p.utilities?.coolingtype,80),assessedValue:num(p.assessment?.assessed?.assdttlvalue),assessmentYear:num(p.assessment?.tax?.taxyear),propertyTaxAnnual:num(p.assessment?.tax?.taxamt),lastSalePrice:num(p.sale?.amount?.saleamt),lastSaleDate:p.sale?.salesearchdate?String(p.sale.salesearchdate).slice(0,10):null};return{sourceKey:'attom',sourceLabel:'ATTOM property detail',quality:92,parcelId:clean(p.identifier?.apn,80),facts:f,suggestedUse:mapUse(f.propertyType),meta:{note:'Licensed property detail. Owner and mortgage fields are intentionally not retained.'}}}

async function acs(q){const geoid=clean(q.tract,20);if(!/^\d{11}$/.test(geoid))return null;const state=geoid.slice(0,2),county=geoid.slice(2,5),tract=geoid.slice(5);const u=new URL(ACS_BASE);u.searchParams.set('get','NAME,B25035_001E,B25077_001E,B25064_001E,B19013_001E,B25002_001E,B25002_003E,B25003_001E,B25003_002E');u.searchParams.set('for',`tract:${tract}`);u.searchParams.append('in',`state:${state}`);u.searchParams.append('in',`county:${county}`);const d=await fetchJson(u,{},4200);if(!Array.isArray(d)||d.length<2)return null;const h=d[0],r=d[1],o=Object.fromEntries(h.map((k,i)=>[k,r[i]])),housing=num(o.B25002_001E),vacant=num(o.B25002_003E),occupied=num(o.B25003_001E),owner=num(o.B25003_002E);return{sourceKey:'census_acs_2024',sourceLabel:'U.S. Census ACS 2024 5-year',quality:88,geoid,context:{name:clean(o.NAME,180),medianYearBuilt:num(o.B25035_001E),medianHomeValue:num(o.B25077_001E),medianGrossRent:num(o.B25064_001E),medianHouseholdIncome:num(o.B19013_001E),housingUnits:housing,vacancyRate:housing&&vacant!=null?vacant/housing:null,ownerOccupancyRate:occupied&&owner!=null?owner/occupied:null}}}

function polygonAreaM2(geom=[]){if(geom.length<3)return null;const lat0=geom.reduce((s,p)=>s+Number(p.lat||0),0)/geom.length*Math.PI/180,pts=geom.map(p=>({x:Number(p.lon)*111320*Math.cos(lat0),y:Number(p.lat)*110540}));let a=0;for(let i=0,j=pts.length-1;i<pts.length;j=i++)a+=(pts[j].x*pts[i].y)-(pts[i].x*pts[j].y);return Math.abs(a)/2}
async function osmFootprint(q){if(q.lat==null||q.lon==null)return null;const query=`[out:json][timeout:3];way(around:35,${q.lat},${q.lon})["building"];out tags geom;`;const u=new URL(OVERPASS_URL);u.searchParams.set('data',query);try{const d=await fetchJson(u,{headers:{'User-Agent':'ExpenseIntel/1.0 (https://expenseintel.com)'}},3600);let best=null;for(const e of d.elements||[]){const area=polygonAreaM2(e.geometry);if(!area)continue;const levels=num(e.tags?.['building:levels']);const footprint=area*10.7639;const rec={footprintSquareFootage:Math.round(footprint),mappedLevels:levels,estimatedGrossFloorArea:levels?Math.round(footprint*levels):null,buildingTag:clean(e.tags?.building,50)};if(!best||rec.footprintSquareFootage<best.footprintSquareFootage*4)best=rec}return best?{sourceKey:'openstreetmap',sourceLabel:'OpenStreetMap building geometry',quality:55,facts:best,meta:{note:'Map geometry is a footprint signal, not assessor living area. It is never silently substituted for verified living square footage.'}}:null}catch(_e){return null}}

const IMPORTANT=['squareFootage','bedrooms','bathrooms','lotSize','yearBuilt','stories','roomCount','units','propertyType','style','zoning','heatingType','coolingType','roofType','exteriorType','foundationType','garageSpaces','pool','hoaMonthly','assessedValue','assessmentYear','propertyTaxAnnual','propertyTaxYear','lastSalePrice','lastSaleDate','footprintSquareFootage','mappedLevels','estimatedGrossFloorArea'];
function merge(records){const facts={},fieldSources={},conflicts=[];const sorted=[...records].sort((a,b)=>b.quality-a.quality);for(const field of IMPORTANT){const vals=sorted.map(r=>({r,v:r.facts?.[field]})).filter(x=>x.v!==null&&x.v!==undefined&&x.v!=='');if(!vals.length)continue;facts[field]=vals[0].v;fieldSources[field]={sourceKey:vals[0].r.sourceKey,sourceLabel:vals[0].r.sourceLabel,quality:vals[0].r.quality};if(vals.length>1){const a=vals[0].v,b=vals[1].v;let clash=false;if(field==='squareFootage'||field==='lotSize'||field==='assessedValue'){const x=num(a),y=num(b);clash=x&&y?Math.abs(x-y)/Math.max(x,y)>.15:false}else if(field==='yearBuilt')clash=Math.abs((num(a)||0)-(num(b)||0))>3;else if(field==='bedrooms'||field==='bathrooms')clash=Math.abs((num(a)||0)-(num(b)||0))>1;if(clash)conflicts.push({field,chosen:a,alternate:b,chosenSource:vals[0].r.sourceLabel,alternateSource:vals[1].r.sourceLabel})}}
  const autoFillSafe={squareFootage:!!facts.squareFootage&&!conflicts.some(c=>c.field==='squareFootage'),bedrooms:facts.bedrooms!=null&&!conflicts.some(c=>c.field==='bedrooms'),bathrooms:facts.bathrooms!=null&&!conflicts.some(c=>c.field==='bathrooms'),yearBuilt:!!facts.yearBuilt&&!conflicts.some(c=>c.field==='yearBuilt')};
  const core=['squareFootage','yearBuilt','lotSize','propertyType','assessedValue','lastSalePrice','bedrooms','bathrooms','stories','roomCount'],present=core.filter(k=>facts[k]!=null&&facts[k]!=='').length,coverage=Math.round(present/core.length*100);return{facts,fieldSources,conflicts,autoFillSafe,coverage}}

module.exports=async function handler(req,res){if(req.method!=='GET')return send(res,405,{ok:false,error:'Method not allowed'});const q={address:clean(req.query?.address,220),street:clean(req.query?.street,140),city:clean(req.query?.city,90),state:clean(req.query?.state,2).toUpperCase(),zip:clean(req.query?.zip,10),tract:clean(req.query?.tract,20),lat:num(req.query?.lat),lon:num(req.query?.lon)};if(!q.address)return send(res,400,{ok:false,error:'A verified property address is required.'});const tasks=[massgis(q),rentcast(q),attom(q),acs(q),osmFootprint(q)],settled=await Promise.allSettled(tasks),values=settled.filter(x=>x.status==='fulfilled'&&x.value).map(x=>x.value),propertyRecords=values.filter(x=>x.facts),context=values.find(x=>x.context)||null,merged=merge(propertyRecords),suggestedUse=propertyRecords.sort((a,b)=>b.quality-a.quality).map(x=>x.suggestedUse).find(Boolean)||'';return send(res,200,{ok:true,address:q.address,propertyFound:Object.keys(merged.facts).length>0,facts:merged.facts,fieldSources:merged.fieldSources,conflicts:merged.conflicts,autoFillSafe:merged.autoFillSafe,coverage:merged.coverage,suggestedUse,context:context?.context||null,sources:values.map(x=>({key:x.sourceKey,label:x.sourceLabel,quality:x.quality,meta:x.meta||null})),connectors:{massgis:q.state==='MA',rentcast:!!process.env.RENTCAST_API_KEY,attom:!!process.env.ATTOM_API_KEY,census:!!q.tract,openstreetmap:q.lat!=null&&q.lon!=null},note:Object.keys(merged.facts).length?'Property facts are merged field-by-field with provenance. Conflicts are exposed instead of averaged away.':'No property-specific record was returned by the currently connected sources. Neighborhood context may still be available.'})}
